### ISSUE TITLE
Discuss what our plan for next phase of development will entail

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#103]
## Overview
There are different methodologies for determining site requirements.  If we pick which type we want to use we can keep the team engaged.

## Options
- In person [Design sprint](https://www.gv.com/sprint/)
- online survey of members
- Website User Behavior Modeling #128
- Other: ____________(please add other options to this document, or to comments).

## Action Item
Please add your notes to this document.

**Comment by ExperimentsInHonesty** [comment]
Also, at what point does leadership add what they need on the site for current activities, like outreach to new project partners (e.g., ACLU, etc).

**Comment by switchzer0** [comment]
Firstly, I know there's a lot of background information I'm missing because I just showed for the first time a week ago, so please consider my comments with my myopia in mind.

My actual thoughts: I think step 1 is a design sprint, step 2 is behavior-modeling/data-collection. I think there's value in going into this process with a perspective as opposed to a blank slate. Experienced members of H4LA should have an idea already of where skilled people and ideas come from, and the site could be designed with minimizing friction for those elements in mind without empirical data collection—we need a starting point that incorporates pre-existing information.

I believe data collection is most valuable when it supports a decision we want to make. We should have the decision options laid out before we figure out what data we want to collect to support the decision.
