### ISSUE TITLE
Fix the Logo for Heart - Project List Page

### ISSUE THREAD

**Issue by tarang100** [hackforla/website#1050]
### Overview
We need to fix the project picture visible for Heart on the HfLA Projects webpage. The project picture is visible on the project webpage for Heart but it is not visible on the HfLA projects webpage. Sharing screenshots below, for reference

![image](https://user-images.githubusercontent.com/75314672/107878243-392a8f00-6ef7-11eb-87c9-f797049ea229.png)

![image](https://user-images.githubusercontent.com/75314672/107878252-4b0c3200-6ef7-11eb-9a81-f6ea29f792d3.png)

### Action Items

- [x] Identify the cause of error
- [x] Rectify the error and ensure that the project picture is visible on the HfLA projects webpage
- [x] Create a pull request
- [x] Ask someone in the Development team to review the pull request
- [x] Commit changes and close issue

### Resources/Instructions
[HfLA Projects Webpage](https://www.hackforla.org/#projects)
[Project Webpage for Heart](https://www.hackforla.org/projects/heart)

**Comment by drubgrubby** [comment]
The image was accidentally deleted in a previous PR (and I didn't notice when I merged it). The attached PR replaces the image.  There shouldn't be any other impact from the mistake that caused this, so rather than trying to roll back the commit that caused the problem it seemed easier to simply re-add the image.
