### ISSUE TITLE
Implement redirects on gh-pages site

### ISSUE THREAD

**Issue by thekaveman** [hackforla/website#106]
We have a few [redirects currently active](https://github.com/hackforla/website/blob/master/static/_redirects) on the Netlify site. We need to support these in the new gh-pages site as well.

**Comment by thekaveman** [comment]
[This blog post](https://superdevresources.com/redirects-jekyll-github-pages/) has a fairly good run-down of the options, TLDR;

1. Use the (GitHub approved) [JekyllRedirectFrom](https://github.com/jekyll/jekyll-redirect-from) plugin
2. Create a Layout that does client-side redirect via `<meta>` tag and javascript fallback.

Personally I've used Option 2 before and it's relatively straightforward. Option 1 seems pretty easy too, but adds another Plugin that we have to deal with/learn/etc. I'm going to submit a PR for Option 2 and let the team review/approve/reject.

**Comment by ajb176** [comment]
You must be a member of the HFLA website team in order to create pull requests. Please see our page on how to join us as a member at HFLA: https://www.hackforla.org/getting-started.  If you have been though onboarding, and feel this message was sent in error, please message us in the #hfla-site team Slack channel with the link to this PR.
