### ISSUE TITLE
Potential malicious link

### ISSUE THREAD

**Issue by Rankazze** [hackforla/website#109]
Under Projects
  CurbMap Project Description
      Links:  Site link pushes to potential malicious path

**Comment by ExperimentsInHonesty** [comment]
Please paste the url of the page you found the link on, and the malicious link it posts too and a screen shot

**Comment by Rankazze** [comment]
Page I found link on:  https://www.hackforla.org/#projects
Malicious link on: https://curbmap.com/
![image](https://user-images.githubusercontent.com/50686892/58071673-46fc8600-7b52-11e9-8c27-5fa8c72ab3e1.png)
![Screenshot_2019-05-20 Hack for LA](https://user-images.githubusercontent.com/50686892/58071911-efaae580-7b52-11e9-9d19-74573b583be9.png)

**Comment by ExperimentsInHonesty** [comment]
Closed with PR #123

**Comment by ajb176** [comment]
You must be a member of the HFLA website team in order to create pull requests. Please see our page on how to join us as a member at HFLA: https://www.hackforla.org/getting-started.  If you have been though onboarding, and feel this message was sent in error, please message us in the #hfla-site team Slack channel with the link to this PR.
