### ISSUE TITLE
Performance: Refactor JS files to exclude babel

### ISSUE THREAD

**Issue by abregorivas** [hackforla/website#112]
Light house test shows that we could improve our performance by not using babel CDN.
Need the following:
- Refactor the following two files to only use vanilla javascript. No Babel
   "api-actionnetwork.js",  "api-calendar.js"
- Update the head.html _include file to remove the Babel CDN script tag.
- Move issue #117 from icebox once this issue is completed

**Comment by abregorivas** [comment]
Pull request for  issue#125 moved babel file to body vs having in head. Improved performance.

**Comment by ajb176** [comment]
You must be a member of the HFLA website team in order to create pull requests. Please see our page on how to join us as a member at HFLA: https://www.hackforla.org/getting-started.  If you have been though onboarding, and feel this message was sent in error, please message us in the #hfla-site team Slack channel with the link to this PR.
