### ISSUE TITLE
Standardize Credits Page Header

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1122]
### Overview
We need to standardize the Credits page header so that it will be more consistent with the rest of the website, and because a link to this page will soon be in the footer.

### Action Items
UI Design
- [x] Review the standard header layout in the Style Guide & Design System file on Figma
- [x] Apply the standards to the Credits page header on Figma
- [x] Discuss with @daniellex0 how to guide the changes in CSS for devs

Front-End Dev
- [x] Implement the new standard design of the Credits page header based on the [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1074%3A0) (in pink rectangle)
   - [x] Reference the [Sitemap Page](https://www.hackforla.org/sitemap) header code, but try to use both a reusable `.header-container` class and another page-specific class (contact @daniellex0 / daniellenedivi on slack for clarification)

### Resources/Instructions
[Credits page](https://www.hackforla.org/credits)
[Credits Page on Figma
](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1074%3A0) (final design in pink rectangle)

<img width="500" alt="Screen Shot 2021-03-06 at 7 47 21 PM" src="https://user-images.githubusercontent.com/67400366/110228288-ce94bf80-7eb4-11eb-894e-c8d546491e14.png">

**Comment by ashleylin1** [comment]
Status: Finished Figma on Credit Page for and discussed with Danielle
Blockers: None
Availability: after 4pm on Weekdays

**Comment by daniellex0** [comment]
Looks great @ashleylin1 , thank you! Moving this now to development.

**Comment by erikaBell** [comment]
Hey @sena-ji , could you give us an update on your status for this issue, progress blockers, ETA and availability.

Thanks (-:

**Comment by sena-ji** [comment]
After working on this issue, I think we should take a week or something to clean up some of the .scss files. The sitemap page had header styling and image properties that did not correlate with the header styling that was done to the credits page. I think if we remove the separate header styling class from individual pages and apply the same standard one to every page, it would be easier. 

I took out image styling classes because it interfered with the container alignment. So I made a temporary width size of 350px. Will discuss with dev team to see what size is appropriate. Below 230px, the image starts to get blurry. I think because of the image size, the text alignment is not 1:1 with the sitemap page. Will discuss with dev team on how to further move on with this as well.

Commented out the parts I removed. Added @media features to work for mobile.

**Comment by sena-ji** [comment]
![image](https://user-images.githubusercontent.com/42919318/115457605-a13c7080-a1d9-11eb-8805-027dc4adeb74.png)
![image](https://user-images.githubusercontent.com/42919318/115457633-a7cae800-a1d9-11eb-8637-df0f9730fd34.png)
Here are the photos!
