### ISSUE TITLE
Turn the About Page sponsor icons into links

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1167]
### Overview
We need to add links to our About page sponsors to give them proper credit 

### Action Items
- [ ] Add a link to each sponsor on the [About page](https://www.hackforla.org/about) sponsors section- these should be exactly the same links as in the [Home page](https://www.hackforla.org/) sponsors section

### Resources/Instructions
[About Us page](https://www.hackforla.org/about) (scroll to bottom for Sponsors)
[Home page](https://www.hackforla.org/) (scroll to bottom for Sponsors) 

<img width="400" alt="Screen Shot 2021-03-06 at 10 00 43 PM" src="https://user-images.githubusercontent.com/67400366/110230764-fd686100-7ec7-11eb-9cce-459665730fe3.png">

**Comment by efrenmarin45** [comment]
Completed adding the links to the sponsors as well as including alternate text for accessibility. I did see that a lot of the images do not have alt text, maybe we can look into adding them. 

Also. below the sponsors there are news articles where the logo's do not lead to the article only the hyperlink. 

![Screen Shot 2021-03-08 at 12 58 27 PM](https://user-images.githubusercontent.com/51544521/110381202-fc414c00-800d-11eb-83dd-fe286353ad74.png)

So if you hover over, for example, CNN it will not take them to the news article because it has no link. Maybe we can add a link to the articles? Other than that, this is done.

**Comment by daniellex0** [comment]
@efrenmarin45 That's a good idea about linking the CNN/LA Times etc logos to the articles as well, I can make an issue for that.

Also maybe mention the missing alt text at today's meeting? That should probably be an issue as well..
