### ISSUE TITLE
Slack auto invite email response should be changed

### ISSUE THREAD

**Issue by abregorivas** [hackforla/website#118]
## Overview
Currently the response from the auto invite shows that it comes from Viky but it should come from Nina.

## Action Item
We need to find out how configure slack to set which slack owner email is used to send the welcome response email.

**Comment by thekaveman** [comment]
(Or can we make it come from team@hackforla.org?)

For me this is a larger issue related to the comments I left in #110 and the original issue #102 - ideally we should get control of the Heroku app so we can make this and other changes as needed.

**Comment by brandonjturner** [comment]
The response from the auto invite will always say it is from the Primary Owner of the slack. We can create a slack account with team@hackforla.org and assign that as the primary owner so that is the email that shows up on the auto invite email. Only Viky's account can set a new primary owner so we will need to reach out to her for her password or ask her to set the primary owner to the team@hackforla.org account.

**Comment by ExperimentsInHonesty** [comment]
@thekaveman believes that any of the owners can make this change, not just the primary owner (Vyki).  To be verified by Bonnie by looking at Nina's view on Tuesday 6/11.

**Comment by brandonjturner** [comment]
Only the Primary Owner can transfer ownership of a workspace or org.

https://get.slack.help/hc/en-us/articles/204401633-Transfer-primary-ownership

**Comment by thekaveman** [comment]
I think this has been solved, right @matikin9? You transferred ownership and updated the auto-invite email address.

**Comment by matikin9** [comment]
@thekaveman yup, confirmed resolved.  Closing out this issue.
