### ISSUE TITLE
Events Page has buggy scroll on mobile

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1184]
### Overview
The drop downs in the events page has a weird behaviour on mobile(NOT mobile view on desktop). Where scrolling the page fires the resize event which in turn causes the drop downs to auto close while scrolling and trying to read it. The issue is more obvious in firefox browser compared to chrome

### Action Items
- [ ] Prevent drop downs from auto closing when being resized

### Resources/Instructions
- https://stackoverflow.com/questions/17328742/mobile-chrome-fires-resize-event-on-scroll#:~:text=Browsers%20in%20mobile%20devices%20often,client%2C%20firing%20the%20resize%20event.
 - https://gist.github.com/jonnymaceachern/9e2cea7e117f8142a00d

**Comment by drubgrubby** [comment]
@akibrhast -> That's really interesting, that the accordion closes as you scroll on my phone.  It's kind of cool, but not in a good way.  The about page also uses a resize event listener, but because it also has other things it checks for it doesn't seem to be an issue. Let me know when you figure this out.
