### ISSUE TITLE
Update homepage header - all meetings are remote

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1202]
### Overview
We need to update the homepage header to notify visitors that all of our meetings are remote 

### Action Items
- [x] Review design for the header on ['Home Page (WIP)' file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205) on Figma **(section on left, in blue rectangle)**
   - [x] For help with Figma functionality / a quick tutorial, reach out to @daniellex0 on this issue (or on slack)
- [x] Edit the header text to match the new version on Figma
- [x] Edit the margins between the text to match the new version on Figma
- [x] Add pink line under 'remote' to match the new version on Figma
   - [x] Research how to add the pink line (regular text styling underline most likely won't have the same look)
- [x] Adjust the placement of the header splash image (move higher up) to match the new version on Figma (the goal is to make sure the 'Getting Started' button shows up fully on the screen when users visit the site- without needing to scroll down)
- [x] Project filters on homepage: Remove all of the location filter options except for 'Remote' (see explanation on Figma)

### Resources/Instructions
[Homepage](https://www.hackforla.org/#)
New header design on [Figma 'Home Page (WIP)' file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205)  (section on left, in blue rectangle)

<details>
<summary> New header designs (click arrow)
</summary>
<br>

Before (current header):

<img width="500" alt="Screen Shot 2021-03-13 at 3 47 41 PM" src="https://user-images.githubusercontent.com/67400366/111054802-6e59cc80-8424-11eb-93cb-37ec09853015.png">

<br>
<br>

After (new header):

<img width="500" alt="Screen Shot 2021-03-13 at 5 48 02 PM" src="https://user-images.githubusercontent.com/67400366/111054804-73b71700-8424-11eb-813d-6d10845bdb4e.png"></details>

So that you know what to look for in Figma- this is what the header update section in the blue rectangle looks like in the [Figma homepage file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205):

<img width="550" alt="Screen Shot 2021-03-13 at 6 02 05 PM" src="https://user-images.githubusercontent.com/67400366/111055012-4c614980-8426-11eb-9aab-22132c06ec19.png">

**Comment by Lol-Whut** [comment]
Progress: Getting acquainted with the issue
Blockers: Nothing so far, just timing
Availability: Evenings
ETA: Middle/end of the week
Pictures: N/A

**Comment by Lol-Whut** [comment]
Progress: 
- removed "margin-bottom: 0" specification from h1 tag to add space below the header as per Figma
- changed h1 font-weight to bold as per Figma
- edited text to update wording
- added second p tag to create spacing between pieces of text
- added a span tag around word "remote" with class "underlined"; gave this class a border-bottom property with styling to match underline on Figma. (Note, this is currently a class in the _hero.css file, but we could in theory try to move it to a css file with a wider scope if we wanted to use the new "underlined" class elsewhere?

Blockers:
- I'd love some input on how to remove the non-remote locations from the "Locations" drop-down menu, as it seems like there are two potential methods. The crux of the matter: the locations are generated from the cumulation of each project's markdown file, and I'm not sure if we want to preserve the projects' non-Covid-era locations in those files. I can either go into each individual project file and remove/replace any non-Remote locations, or I can edit the JavaScript that generates the drop-down filter menu so that only the "Remote" location shows up on screen. I think it makes sense to change the markdown files rather than mess with logic since it sounds like some HfLA projects will remain remote permanently post Covid; still, figured I'd check before getting trigger happy on a ton of files!

Availability: Most evenings, pretty flexible this week!
ETA: Can finish this today or tomorrow, depending on input; I don't think this task will take too long after that.
Pictures:
![image](https://user-images.githubusercontent.com/40847248/113513627-3da31980-9530-11eb-8261-7df23ce72d6c.png)

**Comment by Lol-Whut** [comment]
Will comment out non-remote locations in the .md files so they will be preserved but not show up

**Comment by daniellex0** [comment]
@Lol-Whut That works, thanks Lara!

**Comment by ExperimentsInHonesty** [comment]
@Lol-Whut @daniellex0 @akibrhast @jbubar There is potentially an effect if you comment out the locations, which is that on the [events page](https://www.hackforla.org/events/) the projects on the lower part of the page are either hard coded or possibly being delivered  via that that location information.  So the commenting out the currently unused locations solution is not one I would recommend.

**Comment by erikaBell** [comment]
Just reviewed Lara's pull request, the changes she made does not break the events page 'our locations'. 

<details>
<summary>Events Pg</summary>


![image](https://user-images.githubusercontent.com/67438372/113916925-6b3ccc80-9795-11eb-80c9-5c12e48630fd.png)


</details>
