### ISSUE TITLE
Wins: adding the badges

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1203]
### Dependency
#981 Wins bag UX design testing

### Overview
@daniellex0 redesigned the way the wins cards should look when '...see more' is pressed. It includes badges!

### Action Items
- [ ] Get a look at the [figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1284%3A102) and the picture of the figma below, to get an idea of what you will be adding (the badges), and compare it to the site right now
<details>
    <summary>what it should look like when '...see more' is pressed</summary>

![Screen Shot 2021-03-14 at 3 31 12 AM](https://user-images.githubusercontent.com/53061723/111065820-ed78f000-8478-11eb-9895-00a5928f77a9.png)

</details>

- [ ] look at /wins/wins.html and get an idea of what happens when '...see more' is pressed
- [ ] rework the wins overly ('.wins-card-info') to include the badges
- [ ] rework the mobileSeeMore function to add the badges in mobile (if this is too much, we can break this out into another issue)

### Resources/Instructions
- [figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1284%3A102)
- I got started on this long ago... #1006 (it might be more confusing than its worth. The wins page has changes quite a bit since then)
- the big mother issue #162

**Comment by akibrhast** [comment]
@jbubar @daniellex0 
This new design would have issues. Currently there is no badge length limit. As such, given the form we have this entire paragraph below can become a valid badge. Which would mess up the UI.. lol 😄 ! As shown in this figma image

<details>
<summary>Figma Image</summary>

![image](https://user-images.githubusercontent.com/32349001/111338767-937d5380-864d-11eb-906a-fef3511a13c6.png)

</details>

Some badge are taking 2 lines, some are taking up a single line because of their length. What happens when a badge is the length of an entire paragraph..... ? What happens to the two line badges on the smaller devices? Do they become three lines, four lines? Doesn't that break up the current flow of the UI?

My recommendation is 
1. Figuring out a viable length limit to the section `What do you want to celebrate`.
2. Apply the length limit to all the options in the section `What do you want to celebrate`.
3. Remove the `other` user input section from the form IF we aren't planning to actually display them.

<details>
<summary>3. `Other` not being displayed</summary>

![image](https://user-images.githubusercontent.com/32349001/111340732-45694f80-864f-11eb-9f14-a22031cc1dc6.png)

</details>

<details>
<summary>Paragraph that could be a badge</summary>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet ex vel ex semper dictum. Donec in lacus turpis. Quisque sed viverra ipsum. Nam interdum consequat dolor, vel aliquam velit iaculis nec. Aliquam placerat neque eu risus bibendum lobortis. Proin blandit ligula sem, quis rutrum nibh blandit in. Donec et lacus dui. Aenean mi tortor, cursus ac aliquam nec, imperdiet sit amet enim. Vivamus quis lectus et risus venenatis tempus. Nam vel orci a orci faucibus scelerisque id eu eros.

Etiam a tristique turpis, vitae aliquet justo. Aenean in nisl eget sapien vestibulum rutrum at sollicitudin neque. Aliquam arcu lacus, elementum eu ex in, convallis congue eros. Nam quis pharetra dolor, id dictum lectus. Nam dolor diam, rhoncus quis iaculis et, consectetur id diam. Cras ultricies efficitur finibus. Nulla mi tellus, iaculis nec dictum nec, commodo id mauris. Duis aliquam fringilla justo, non congue sapien pharetra vel.

Suspendisse mollis a sapien ac porta. Mauris vitae tellus porta, tempus justo ut, lacinia lectus. Duis convallis urna ut viverra placerat. Morbi mollis nibh nec sem tempus faucibus. Vestibulum tincidunt mauris sit amet orci ultricies, sit amet malesuada dui efficitur. In egestas erat a justo posuere, et imperdiet enim lobortis. Suspendisse sit amet nibh condimentum, ullamcorper dui in, ornare dui. Quisque fringilla vitae turpis molestie faucibus. Nullam sed varius tellus. Vestibulum quis neque ut mauris interdum mollis id sit amet justo. Cras sodales mi dictum scelerisque ullamcorper.

Quisque quis maximus ipsum, nec vulputate nisl. Nulla auctor enim non ullamcorper pretium. Donec tincidunt eget dolor eget imperdiet. Nunc commodo, ex a mollis lobortis, ante est malesuada lectus, at placerat lacus ligula eget risus. Nam sapien purus, rhoncus vel nibh in, tristique rutrum purus. Morbi non nisi lorem. Vestibulum laoreet odio enim, vel molestie velit condimentum eget. Nunc id nulla venenatis, congue turpis in, convallis est. Sed ac nunc at lectus vestibulum mollis a nec ipsum. Donec eget mollis tellus, non mollis massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam accumsan, mi id volutpat egestas, nibh sem semper massa, quis facilisis enim enim id purus. Suspendisse pellentesque vel dui nec ornare.

Suspendisse elementum nisi non est dictum finibus non nec nisl. Nulla condimentum porta auctor. Donec sollicitudin orci eget sem vestibulum, quis volutpat odio blandit. Sed convallis ante ac nisl pellentesque, vitae posuere magna ultrices. Morbi pulvinar egestas eros, rutrum pellentesque orci tristique eget. Integer massa neque, malesuada faucibus lorem quis, ultricies ornare odio. Duis condimentum tincidunt leo a efficitur. Ut nunc lorem, posuere et facilisis eu, vulputate ut dolor. Pellentesque facilisis leo diam. Nulla facilisi.

Generated 5 paragraphs, 424 words, 2806 bytes of Lorem Ipsum

</details>

**Comment by daniellex0** [comment]
**Progress:** The results are in, and people definitely prefer the icons over the circle badges:

<img width="500" alt="Screen Shot 2021-03-21 at 2 48 57 AM" src="https://user-images.githubusercontent.com/67400366/111900489-10168600-89f0-11eb-8c1f-6026881e7430.png">

Some of the reasons they gave:

"More consistent with overlay, cleaner look. (Circles draw too much attention and compete with the text for focus)"

"The circle icons seem a bit distracting with the circular profile pictures. I think this view makes them seem more unified with the card element."

"Bigger icons, lighter feeling on first impact"

"I like the variation among the shapes compared to the circles. If there was color involved, my opinion may change."

"better visibility"

**Next Steps:** Consult with Bonnie about whether this is ready for development, or if there should be any more adjustments or a/b testing

**Comment by daniellex0** [comment]
@akibrhast Sorry I missed this comment- editing this because I misunderstood your point. So the main concern is what would happen if someone wrote a really long response for the "other" option? I'm not sure how likely that is, I would think they would write that in the actual paragraph field where they explain the overview of their wins. But yes, we could remove "other" if Bonnie doesn't feel strongly about including it. And if it's possible to add length limits, that's definitely a good option.

As for how it would look in mobile- the badges will be in one column, and the text would wrap to as many lines as needed

**Comment by akibrhast** [comment]
@jbubar Any chance you could please edit the google forms and remove the `others` section if @ExperimentsInHonesty approves.

If bonnie does not approve of removing that section, please discuss with @daniellex0 about potential character limit values. I am going to take a stab it and say that 50 characters should be good for the upper limit

**Comment by qiqicodes** [comment]
@jbubar will open a new issue with the following actions.

Desired Actions:
spreadsheet: add wording to the form that communicates that "other" wins that's left off
spreadsheet: when they check the form, if didn't get asked, put it in the bottom of the review
spreadsheet: limit the characters on input
