### ISSUE TITLE
Add a new field to project files called Display

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#123]
## Overview

We need an easy way to make project cards display or not display temporarily on the site for various reasons

## Action required
@thekaveman , reviews my proposal and if he agrees we make the change specified in the recommendation or an alternate recommendation per Kegan's review.

## Recommendation
Add a new field to project .md files called Display, with the value of true or false.
add logic into the _includes/current-projects.html file which would check to see if the project's .md file had a display value of true before displaying.

## Timelyness
I want to temporarily remove two projects from the site:
- Light the way (because we need to find out the project's status and change out the image)
- Curbmap (because it has a malicious link warning on its site link)

**Comment by thekaveman** [comment]
Seems like a reasonable approach to get something going until we figure out the categorization and other things we've talked about for Projects.

From an implementation point of view, it might be easier to add a new field `hide: true` to the couple of cards you want to hide, instead of having to add `display: true` to *all* of the cards. The logic just has to invert in the include.

**Comment by ExperimentsInHonesty** [comment]
Closed by pull request #124
