### ISSUE TITLE
Finalize new nav bar order

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1256]
### Overview
We need to redesign the top nav bar in order to improve the site's ease of navigation, make all pages accessible from the homepage, and have a structure in which to add new pages such as the [Join](https://www.hackforla.org/join-us) and [About](https://www.hackforla.org/about) pages once they are ready

### Action Items
- [x] Redesign top-nav bar to meet above stated needs

### Resources/Instructions
[About page](https://www.hackforla.org/about)
[Join page](https://www.hackforla.org/join-us)

**Current nav bar:**

<img width="400" alt="Screen Shot 2021-03-18 at 12 13 06 AM" src="https://user-images.githubusercontent.com/67400366/111586926-c3784400-877e-11eb-8ce9-77abae577582.png">

**Comment by akibrhast** [comment]
@ExperimentsInHonesty What is the plan in regards to the new navbar order?

**Comment by akibrhast** [comment]
Based on the following [Figma ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=6187%3A40167)Design Specification and conversations with @ExperimentsInHonesty and @daniellex0 

The new navbar order is going to be as follows

![image](https://user-images.githubusercontent.com/32349001/113735056-de790c80-96c9-11eb-8fae-63a82f9879db.png)

- [ ] Remove `Press` and replace with  [ `About Us` or `About` ]
- [x] Remove `Connect` and replace with [ `Join Us` or `Join` ]

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 I had said to Akib that when we were originally discussing making it Join, it sounded a little membership like, whereas Join Us sounded more friendly and open.  I am fine with About being a single word menu item however I am not sure about the Join Us and would like to have it tested to find out what people think would be behind that link.  Or if the whole UX team thinks I am making this into too big a deal, I am ok for it to get changed to join.  Just saying it needs some thought.

**Comment by kristine-eudey** [comment]
**Progress:** We are currently finalizing both the [homepage redesign](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14637%3A94968) and the [expanded footer redesign](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3417%3A3), which should both inform the site hierarchy as shown to users by top nav. 

In moving forward with this issue and considering a change to the top nav, I have identified a larger issue which needs to be considered: as we add new pages to the site that do not fit into the current top nav, the current solution seems to be adding additional sections to the top nav which link to individual pages. I think we instead need to reconsider how the top nav functions since this is not a scalable strategy as the # of pages increase, and (maybe even more importantly) doesn't provide users with a clear understanding of the content the site offers and give a quick/comprehensive view of how to navigate it when they come to the page. I believe we are at a point where it's important to reconsider how we're using the top nav and if it currently reflects the site's main content categories and hierarchy of information. 

**Blockers:** None, though continued work on the homepage and footer will provide helpful context to move this forward. 
**Availability:** At least 5 hours per week
**ETA:** TBD. First step is an audit of current sitemap (as description of current information architecture) and then the creation of an alternate possible sitemap based on the categories ideated in this new [footer design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14814%3A95261), which takes a different approach to the site's IA focused on increasing user-friendliness and scalability. I can have this step completed by Sunday 9/5/21

**Comment by kristine-eudey** [comment]
Design is ready for discussion and review. [Figma - New Nav Bar](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14120%3A92883)

In order to make our entire site accessible through the top level navigation and create an effective hierarchy of information, I organized the pages into logical buckets (mirroring those in the new footer design). 

The goal of this new structure is to make the site easier and more intuitive for users to navigate (both via browsing and searching), alongside making the site more easily scalable as we add new pages.

**Comment by kristine-eudey** [comment]
Design portion of this issue will be finished by Tuesday, 10/26.

**Comment by kristine-eudey** [comment]
New top-nav design is completed, approved, and can be found here: [Figma - Top Nav Redesign](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17368%3A107075)

**Comment by ExperimentsInHonesty** [comment]
Thanks!  looks amazing
