### ISSUE TITLE
Remove pink rectangle behind the mobile hamburger menu 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1258]
### Overview
We need to remove the pink rectangle that shows up behind the mobile hamburger menu when it is clicked, because it is supposed to stay white. It is unclear when or why this turned pink.

### Action Items
- [x] Determine what is causing the mobile hamburger menu background to turn pink
- [x] Remove the pink rectangle behind the mobile hamburger menu (should stay white when clicked)

### Resources/Instructions

Pink rectangle behind the mobile hamburger menu (top right) should be removed:

<img width="250" alt="Screen Shot 2021-03-18 at 12 31 24 AM" src="https://user-images.githubusercontent.com/67400366/111589088-a42ee600-8781-11eb-8c19-e5934f41ab76.png">       <img width="250" alt="Screen Shot 2021-03-18 at 12 31 33 AM" src="https://user-images.githubusercontent.com/67400366/111589106-a98c3080-8781-11eb-8241-38deb6dd8bb6.png">

**Comment by sena-ji** [comment]
In order to reproduce bug consistently, the outer edges of the burger icon must be pressed instead of directly on the burger icon. There is a background that is spilling on top of this icon shown in the photo. When I unchecked that, it worked and removed the color.
![image](https://user-images.githubusercontent.com/42919318/112900604-95590500-9098-11eb-9b54-07b5e220327c.png)

The color is coming from _calendar.scss:
![image](https://user-images.githubusercontent.com/42919318/112901549-c2f27e00-9099-11eb-8dfc-6e4312c34aaa.png)

Will discuss on how to move on with this issue with developers to see if the background color is important for any other feature before removing it.
