### ISSUE TITLE
Adjust styling of Wins page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1336]
### Overview
We need to adjust the styling of the Wins page to make it more consistent with the rest of the site

### Action Items
- [x] In mobile only: make the heading ('let's celebrate together!') 32px (instead of 38px) - use rem units
- [x] In mobile only: make the "Team(s)" and "Role(s)" sections the same font size- 15px - use rem units (currently one is 12px and one is 16px)
   - [x] Try to also add a little margin between all of these lines (person's name, Teams, Roles) to give it some breathing room- maybe something like 3px?
   - [x] Remove the margin-top from the volunteers' names on the wins cards
- [x] Change desktop .wins-page-contain>ul.filter-list width to 40% (instead of 46%) so that filters are less wide
- [x] Try to make only this header button ("Share your wins") use the properties of class ".btn-md-narrow" (smaller size) only in mobile - without affecting the mobile version of any other buttons on the site that use the same button classes (this might require adding the properties to mobile media query in .btn--wins)
- [x] Please add @daniellex0 as a reviewer when finished 

### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/)

**Comment by erikaBell** [comment]
@daniellex0 , I've done the above styling. My photo below shows that a new problem arrives, with the "...see more" text. Would you like me to try to adjust that? I was looking at it, and it's set up in a way that makes it a bit tricky to work with, but since the rest of the styles were pretty easy, I don't mind trying to mess with it for a bit. 

Also feel free to lmk if any of the styles I've currently added need more adjustment, i.e. the spacing between teams/roles. 

<details>
<summary>New Styles Added - Wins Page</summary>

<img width="320" alt="Screen Shot 2021-04-09 at 1 05 10 PM" src="https://user-images.githubusercontent.com/67438372/114234924-492d8080-9934-11eb-8779-d78960e17301.png">
</details>

<details>
<summary>New Styles - Example 2</summary>

<img width="331" alt="Screen Shot 2021-04-09 at 1 10 34 PM" src="https://user-images.githubusercontent.com/67438372/114235432-07510a00-9935-11eb-842a-c02a6af8390b.png">

</details>

**Comment by daniellex0** [comment]
Ohhh yikes, thanks for pointing this out @erikaBell .. 

@jbubar has a lot of experience with dealing with the "See more" on this page so he might have some ideas..? Josh I know you have spent more time than you would like on "see more" so sorry to do this to you lol, but I thought you might have a quick fix in mind... if not, yeah Erika this might require some noodling around with CSS..

**Comment by erikaBell** [comment]
@daniellex0 Oops sorry, should have stated I ended up working on it cus the challenge seemed fun, lol. So I ended up getting it together. I'll just double check my work and then make a pull request (-:

**Comment by daniellex0** [comment]
Ah ok great! Never mind @jbubar you are saved lol
