### ISSUE TITLE
Developer's need a guide path on how to handle good first issue.

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1338]
### Issue Incomplete
Needs + size of issue,  then this issue can be moved to prioritized backlog.

### Overview
Create a wiki page that guides new developer on how to handle a new good first issue. Good First Issue are all usually updates/edits to the projects collection. Ensure that the instruction specifies which template to follow for a project being edited.

### Action Items
- [ ] Create a wiki page that guides new developer on how to self assign new good first issue. Good First Issue are all usually updates/edits to the projects collection. Ensure that the instruction specifies which template to follow for a project being edited.
- [ ] Add a link to the wiki page detailing these information somewhere in the contributing.md file

### Resources/Instructions
[How to contribute file](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[WIKI](https://github.com/hackforla/website/wiki)
[Good First Issue WIKI page](https://github.com/hackforla/website/wiki/Good-First-Issue) WIP and not linked anywhere]

**Comment by Sihemgourou** [comment]
Discussed during All Team => @ExperimentsInHonesty to edit this issue and create another one

- [ ] Add how to take on a good first issue
- [ ] Reference all the changes to make : put check your changes locally as its own step
- [ ] Remove branche from fork
- [ ] how to stash/unstash and delete stash
- [ ] other issues about the contributing file :  #1893 , #1750

**Comment by JessicaLucindaCheng** [comment]
Closing this issue because instructions for handling good first issue is already part of the CONTRIBUTING.md 2.1 through 2.7.e: [Part 2: How the Website team works with GitHub issues](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) 

Also, any improvements or additions can be made as part of the wiki audit: https://github.com/hackforla/website/issues/2676
