### ISSUE TITLE
Technologies dropdown bug

### ISSUE THREAD

**Issue by erikaBell** [hackforla/website#1353]
### Overview
Checkmarks disappear during refresh, only on technologies dropdown—specifically after first two list items. 

### Action Items

- [ ] make sure checkmarks don't disappear on refresh

### Resources/Instructions
page: current-projects.html
<details>
<summary>Technologies Checkbox Issues</summary>

<img width="939" alt="Screen Shot 2021-04-04 at 1 03 55 PM" src="https://user-images.githubusercontent.com/67438372/113520194-4c94c680-9546-11eb-9a90-c80b131c499f.png">
<img width="845" alt="Screen Shot 2021-04-04 at 1 03 46 PM" src="https://user-images.githubusercontent.com/67438372/113520195-4dc5f380-9546-11eb-8818-b14d5f8800be.png">

</details>

**Comment by erikaBell** [comment]
Issues are caused by "/" and filter-items containing more than two words (i.e. "React Testing Library", "Microsoft SQL Server") — potentially space, " ", related?


### I have made the following changes to filter-items under "Technologies"

- React Testing Library **==>** React Testing

- Microsoft SQL Server **==>** Microsoft SQL

- Azure App Service **==>** Azure App
-  Google Docs (Doc, Sheet, Slide, Forms) **==>** Google Docs

### I need to make the following changes to filter-items under "Looking" & "Technologies"
- Auth0 / OIDC / OAuth2 **==>** ???
- SEO/Marketing **==>**  ???
- UI/UX **==>** ???

I am wondering if my current name changes are o-k and am unsure on how I should change the three-items found in the second header.

**Comment by erikaBell** [comment]
@ExperimentsInHonesty I just saw [issue #1346](https://github.com/hackforla/website/issues/1346) and am wondering if this one, related to filter-item naming _limitations_, should be figured out first?  

Read comment above.

**Comment by akibrhast** [comment]
@erikaBell Currently this is the consolidated list of technologies https://github.com/hackforla/engineering/issues/7 .
Based of that, I am assuming that we are not going to be changing any of those names. If @ExperimentsInHonesty Could please confirm this... ?

---
The reason the above error is occuring is due to improper and unexpected handling/parsing of the URL parameter both during setting the URL parameter and during retrieving the URL parameter.

``` javascript
// When a filter with three space separated words are selected the url parameter gets set to 
technologies='Azure+App%20Service' 
// However when a filter with two space separated words are selected the url parameter gets set to
technologies='Code+Climate'
```

The above is an unexpected and improper behaviour. Because sometimes a space is being encoded as a `+` and other times the space is being encoded `%20` .
- [ ] We need to ensure that a space is always encoded as a `+` and never as `%20`

---

These are the functions related to the url set/get and parse: 
1. https://github.com/hackforla/website/blob/df4a8a4654dc061a0db119bc3f2870dcb4642674/assets/js/project-filter.js#L55
2. https://github.com/hackforla/website/blob/df4a8a4654dc061a0db119bc3f2870dcb4642674/assets/js/project-filter.js#L41
3. https://github.com/hackforla/website/blob/df4a8a4654dc061a0db119bc3f2870dcb4642674/assets/js/project-filter.js#L226

**Comment by erikaBell** [comment]
@akibrhast curious as to what the reason for choosing `+` over `%20` is?
And assuming we keep the names as they are, which is preferred for `/` ==> `%2F` or `_` or ..

**Comment by akibrhast** [comment]
@erikaBell https://github.com/hackforla/website/issues/1030

Also in regards to your second question use `_` because it's more readable
