### ISSUE TITLE
Dedicated Projects page

### ISSUE THREAD

**Issue by thekaveman** [hackforla/website#14]
The current project listing design and implementation worked well for the smaller number of projects that we started with.

We have a bit of a "good" problem now, in that both DTLA and Westside are going strong (and with the forthcoming South LA night, and maybe others in the future -- LA *is* quite large), so new project teams are spinning up left and right.

https://hackforla.org should be the preeminent showcase of our projects to the broader community.

Finding a project to join that interests you *and* matches your skill-set (existing or desired) should be easy.

Getting your new project listed should also be *relatively* straightforward. We'll probably need some [governance](https://github.com/hackforla/governance) to figure out when a project gets listed, and if/when/how it comes off.

**Comment by gawaragcha** [comment]
Hey y'all,
  My name is Chris McKee. Sorry if I do this incorrectly. I'm not clear on all the formatting I see on this page. 

Here are a few thoughts on the dedicated projects page, which I like, and which I discussed with Bonnie June 17th at the Hack For LA meeting in Santa Monica:

1. I am happy to collect more information about each project and write them up for the pages. 

2. I will also be using this process to create material for your newsletter with Anthony.

3. Bonnie will soon send me questions/bullet points for each project which could be used to shape these interviews/descriptions. 

4. Project pages should ideally include photos of the principals working on them to build rapport and community with other volunteer collaborators.

5. Please consider for the newsletter and website bios about principals, including information about their day-jobs and previous accomplishments. I think this helps build community by attracting talent who want to meet them, and it creates a starting point for conversations.

6. I'm open to producing a short video if the subject and principals involved will be evergreen. Feel free to make suggestions. You can see some samples of my work on my website (made with Wix - I don't know HTML): www.ragcha.com

7. I encourage you to keep the projects navigation simple. "Past Projects" with a "Mission Accomplished" approach is compelling. Differentiating between fledgling projects and mature projects may be confusing for people visiting the site for the first time. I think it can be done; I just urge caution. I've worked in companies and organizations where things were overly complicated because project managers were too focused on how their teams understood them, rather than users. 

Another thing to keep in mind with all of these issues is that since Hack for LA is a volunteer organization at this point, it's very easy for the site to become out of date. People come and go, and they are busy with their day jobs and families. I think it's helpful to imagine stuff going on there to stay the same for up to three years, and thoroughly vet anyone who says they're going to stay on maintaining and updating the site. I expect you've already had experiences with people declaring their best intentions and then failing to deliver consistently or over a long period of time.

To this end, as an example, when doing project descriptions and principal bios, I think it might be good to limit what goes up to people and projects that have been around for a reasonable period of time: 6 months? a year? You know how long people stick around better than I.

I think maybe users don't need to know about all the projects from visiting the site - just get some good perspectives on the types of work Hack for LA is doing. Perhaps the newsletter would be more appropriate for information about fledgling and potential projects or recently added principals accomplishing good work - particularly if projects need help. 

Cheers

**Comment by switchzer0** [comment]
I support a distinct projects page. One feedback theme we're seeing on the hackforla.org/survey is that people find the overall page very informative but overwhelming. 58% of respondents want to find project information; safe to say it's a very important element to visitors, worthy of its own page.

I really like the point by @gawaragcha No. 7 about simple distinctions between current and "mission accomplished" case studies, and considering who the audience is for the website and making sure content is in a relevant voice.

> 7. I encourage you to keep the projects navigation simple. "Past Projects" with a "Mission Accomplished" approach is compelling. Differentiating between fledgling projects and mature projects may be confusing for people visiting the site for the first time. I think it can be done; I just urge caution. I've worked in companies and organizations where things were overly complicated because project managers were too focused on how their teams understood them, rather than users.

I do think getting talent for fledgling projects is important to enable their success, so that's a reason to make sure new projects are prominently featured, in addition to reliably ongoing ones. Not sure if getting talent is a big pain point though judging by the large number of 1st timers showing up at the meetings each week.
