### ISSUE TITLE
Add Communities of Practice page header illustration to Credits page 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1506]
### Overview
We need to add the vector illustration from the [Communities of Practice page](https://www.hackforla.org/communities-of-practice) header to the [Credits](https://www.hackforla.org/credits/) page so that we are following the image use requirements

### Action Items
- [x] View the image credit information in the comment below (scroll down) 
- [x] Add the credit information to the Credits page

### Resources/Instructions
- [Credits page](https://www.hackforla.org/credits/)
- [credit.md template](https://github.com/hackforla/website/wiki/Template-of-a-credit.md-file-(for-Credits-page))

**Comment by daniellex0** [comment]
Name: Teamwork

Used in: Communities of Practice

Artist: freepik

Provider: Freepik

(original image link: https://www.freepik.com/premium-vector/teamwork-concept-landing-page_5168259.htm#page=1&query=team%20work&position=0)

**Comment by qiqicodes** [comment]
@paulsvh Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by paulsvh** [comment]
@qiqicodes Of course, I've hit a couple of snags, see below:

Progress: Created a new .yml called 'teamwork.yml' for the teamwork image, used the other image yml files in _data/internal/credits as a template. To the best of my knowledge, this new 'teamwork.yml' is correct.

Blockers: 

- After creating this new 'teamwork.yml' I'm not seeing it added to the UL in "credits-list unstyled-list" where I would imagine it would be.
- The credit.md template is blank, I created the teamwork.yml based on the other yml files in the credits folder
- I'm not seeing the new card for teamwork added to the credits list at all, so it's not just the an issue with the image
- On the cards that I can see on the credits page, if I go to that specific card's .yml file in _data/internal/credits and make a change, I don't see that change updated on the website through my jekyll server.
- Due to the above, I think I'm fundamentally misunderstanding where the credits cards in the credits UL are pulling data from.

**Comment by qiqicodes** [comment]
@paulsvh look at [this issue](https://github.com/hackforla/website/issues/1558#issue-893064148
)'s alt text for inspiration. 

### Resources/Instructions
https://cliquestudios.com/alt-text/
[How to write effective alt tag for images](https://medium.com/nyc-design/how-to-write-effective-alt-tags-for-images-9f888f36992f)
[WebAIM](https://webaim.org/techniques/alttext/)
