### ISSUE TITLE
Fix CSS on Toolkit page

### ISSUE THREAD

**Issue by Lol-Whut** [hackforla/website#1510]
### Overview
There's a CSS bug on the toolkit page and it doesn't look right. Stuck in mobile view -- check out toolkit-flex-container as possible culprit?

### Action Items
- [ ] compare the page and the Figma
- [ ] find bug (it's stuck in mobile view for some reason)
- [ ] fix bug :)

### Resources/Instructions
Page: https://www.hackforla.org/toolkit/
Figma (see pink rectangle): https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967

**Comment by qiqicodes** [comment]
@sanchece Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:
Availability:
ETA:

**Comment by daniellex0** [comment]
Hey @sanchece sorry we didn't make this clear when this was assigned, but this issue is urgent because it is live on the site and looks wrong, so we are assigning this to @qiqicodes to finish quickly. 

Feel free to let her know if you've already started working on this and/or grab another issue. Thank you and sorry for not making this more clear from the beginning!
