### ISSUE TITLE
Adjust layout of Wins page cards with badges

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1551]
### Overview
We need to adjust the layout of the cards on the version of the Wins page with badges (not live yet) to make it more consistent with the original Figma design.

### Action Items
- [ ] Access the "wins-feature-1" (not gh-pages) branch to view the code for the Wins page version with badges
- [ ] Try to adjust the layout of the Wins card with badges so that there is always the same (small) amount of space between the quote paragraph and the badges, no matter how many rows of badges are on one of the side-by-side cards (see screenshot below for reference)
- [ ] Please assign @daniellex0 as a reviewer on your PR 

### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/) (currently without the badges- need to access the "wins-feature-1" branch to see them)
[Figma Designs of Wins page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in blue rectangle)

How it **should** look when two side-by-side cards have a different number of rows of badges (correct- the same amount of space between quote paragraph and badges):

<img width="769" alt="Screen Shot 2021-05-16 at 7 49 48 AM" src="https://user-images.githubusercontent.com/67400366/118401997-cd9ead80-b61c-11eb-8cb0-529260d772ba.png">

How it look right now when two side-by-side cards have a different number of rows of badges (wrong - too much space in one between the quote paragraph and badges):

<img width="750" alt="Screen Shot 2021-05-16 at 8 02 18 AM" src="https://user-images.githubusercontent.com/67400366/118402051-15253980-b61d-11eb-9f6f-190a88454087.png">

**Comment by jbubar** [comment]
Guide for git 
https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch

**Comment by erikaBell** [comment]
**UPDATE:**

*As far as I can tell* this is happening from extra spacing being added to the bottom of short descriptions because we have a height requirement on `.wins-card-text` of `{ height: 88px }`.

We have this height requirement for good reasons. Changing `height` to `max-height` sustains issues. 

Because the win text and badge divs are children of `.project-card wins-card` (their parent div), I cannot position the badge icons, relative to the wins text. 

Placing the badge icons in other various divs, in an effort to make it a child of the text, also creates a number of issues. 

Everything I just wrote might sound like non-sense to read (-:|>*
Ultimately, I tried several methods of solving the issue but am still stumped on how to fix it. Help would be appreciated.

**Comment by daniellex0** [comment]
@erikaBell No worries, this is not required for MVP to make the Wins page badges go live, so someone can try to sort it out after it goes live!

**Comment by jbubar** [comment]
@erikaBell I was running into this same issue yesterday when I was working on my wins issue (#1549). I think we might have to rethink how we shrink or hide the text...  I will be working on this in the next few days. lets brainstorm

**Comment by Abel-Zambrano** [comment]
IMPORTANT!! 
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)

**Comment by erikaBell** [comment]
**UPDATE:**

Progress - found a simple CSS solution for the spacing issue between wins-text and wins-badges
Blockers - see more & see less functionality
