### ISSUE TITLE
Prototype the Projects page

### ISSUE THREAD

**Issue by thekaveman** [hackforla/website#156]
### Overview

We want to start prototyping a dedicated Projects page. This task will eventually roll up into #14.

###  Dependency
#254 filtering and When we are ready to do this page, we will also have to redesign the homepage #492 , because the projects, which are taking up all the space will be gone.

### Action Items

1. Create a new page under `/projects`
2. Render the current list of projects as cards (similar to how the homepage currently does)
3. Implement filtering based on project attributes (status, language, location, etc.)
4. Resolve drop shadow artifact on prototype

**Comment by McRawly** [comment]
![image](https://user-images.githubusercontent.com/18178289/67352480-f9bb8080-f504-11e9-9ee8-7bc25642a64c.png)
Is this the latest design idea?  I'm thinking of assigning this task to Matt. Hopefully I'm not superceding Brandon's work.

**Comment by sarL3y** [comment]
v1 of the Projects Page wireframe with sort functionality for your consideration:

[Projects Page Prototype v1 (Desktop).pdf](https://github.com/hackforla/website/files/3761362/Projects.Page.Prototype.v1.Desktop.pdf)

![Projects Page Prototype v1 (Desktop)](https://user-images.githubusercontent.com/39248174/67376902-baf3ed80-f539-11e9-9581-151a1353167e.png)

**Comment by StephenVNelson** [comment]
I have created the basic design and rudimentary filtering functionality. I would like to talk with one of the reviewers for some feedback.

**Comment by StephenVNelson** [comment]
So I have fully functioning filtering and the basic design. 
1. There is one issue where the top margin of the footer is making a white space at the bottom of the page. I'm open to suggestions as far as how we handle that because changing the footer CSS would change everything on every page.  (see screenshot below) 
2. When @harishlingam and I talked last week I let him know that currently none of the projects have any information about what programming languages they're using on their projects. So I need that information before I can add the LANGUAGES filter on the prototype.
3. @harishlingam Also said he will get a UX/Design person to look at what I have thus far. I am attaching a screenshot of the whole page so you guys can reference it. (see below)
3. I know we just edited the Not Today project image, but it's still different from all the others because it's a square instead of a rectangle and that's a little annoying, yeah?
4. Do I just submit a pull request now? If you guys accept the pull request will it be added to the main branch of the project? Since we have a few more details that need to be done on the all projects page I'm not sure we want to do a pull request yet? Can we merge my changes into a different branch so that it won't be live quite yet? LMK
![FireShot Capture 007 - Hack for LA - localhost](https://user-images.githubusercontent.com/20952309/70005642-307eb080-151f-11ea-9dda-24f38ddb1112.png)

**Comment by StephenVNelson** [comment]
Here is the preview of the projects page as a part of the full website. 
![image](https://user-images.githubusercontent.com/20952309/71612482-81e98200-2b55-11ea-805a-6bc4fad0143b.png)

**Comment by StephenVNelson** [comment]
Just did a pull request #243 that is ready for review

**Comment by ExperimentsInHonesty** [comment]
@StephenVNelson Please revert the sort controls to the prior version (white).  Also, please have the default position of the selectors say Location and Status

**Comment by ExperimentsInHonesty** [comment]
Dependence on #254 and When we are ready to do this page, we will also have to redesign the homepage #492 , because the projects, which are taking up all the space will be gone.

**Comment by alexandrastubbs** [comment]
@yuikomajima to provide image for this page. @ExperimentsInHonesty to provide a blurb for the page.

**Comment by yuikomajima** [comment]
Image added to this page: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=532%3A1455
