### ISSUE TITLE
Prototype a Project Home Page

### ISSUE THREAD

**Issue by thekaveman** [hackforla/website#157]
### Overview

We want to start prototyping a dedicated page for each Project. These are already being rendered by Jekyll, but we need to add more details. This task will eventually roll up into #14.

### Action Items

1. Edit the existing Project layout under `_layouts/project.html`
2. Fill out details, assets, etc.
3. Render links as cards.

**Comment by sarL3y** [comment]
Here's a v1 for the Project-specific page. I'll take a stab at the Projects Page in the other issue next.

Edit: Found a better wireframe tool. 

[Project-Specific Page Prototype v1 (Desktop).pdf](https://github.com/hackforla/website/files/3760791/Project-Specific.Page.Prototype.v1.Desktop.pdf)

![Project-Specific Page Prototype v1 (Desktop)](https://user-images.githubusercontent.com/39248174/67368782-c260ca00-f52c-11e9-803d-71bd68c2f645.png)

**Comment by KianBadie** [comment]
First iteration of project page made around Oct 21st

![Screenshot from 2019-10-21 20-21-38](https://user-images.githubusercontent.com/18221058/69472560-a84f1d00-0d60-11ea-9abb-eb3a1cdd2e8d.png)

**Comment by KianBadie** [comment]
Second iteration of project page based off of wire frame made by @sarL3y 

![Screenshot from 2019-11-18 19-21-00](https://user-images.githubusercontent.com/18221058/69472583-dc2a4280-0d60-11ea-913f-a5e346633126.png)

**Comment by ysjiang18** [comment]
![Project Page Wireframe Revision](https://user-images.githubusercontent.com/38798303/69501853-d9912f80-0ebd-11ea-9be8-3644592ad62c.png)
I made some minor changes, the overall page looks great.

**Comment by KianBadie** [comment]
Here is a current work in progress of the prototype for the project page 
![Screenshot from 2019-12-08 17-35-54](https://user-images.githubusercontent.com/18221058/70400755-4f7ab800-19e1-11ea-9e43-84313a4fe656.png)
![Screenshot from 2019-12-08 17-36-05](https://user-images.githubusercontent.com/18221058/70400756-51447b80-19e1-11ea-836c-091f34af442b.png)

**Comment by KianBadie** [comment]
Current state of the page:
![Screenshot from 2019-12-22 08-37-03](https://user-images.githubusercontent.com/18221058/71324716-4d136600-2497-11ea-9145-ac78a0038d84.png)

Accepting any kind of feedback. The place I have most in mind right now is the banner, and how to make it look nice.

**Comment by ExperimentsInHonesty** [comment]
potentially adding link to see a demo, not jus a site.

**Comment by ExperimentsInHonesty** [comment]
I think the challenge with the banner is that we are trying to make something work for the banner that is only designed to work for the cards.  Why don't we just request a different image from the projects for the project specific page.  it allows them to come up with something that is more narrative.

**Comment by ExperimentsInHonesty** [comment]
![Screen Shot 2019-12-28 at 10 59 13 PM](https://user-images.githubusercontent.com/37763229/71553521-b75f6580-29c5-11ea-892e-0f0391069dc7.png)
This screenshot was taken from the hellogov.org website.  What about using it as a placeholder for a second image, that is not the card image

**Comment by KianBadie** [comment]
I like that idea @ExperimentsInHonesty, and I think that would also be a great image for the banner. I think in order for that to be implemented, we would have to create a banner property on the project cards. Because currently, the project page is a layout that jekyll is using, so I wouldn't be able to hard-code this in for this specific page, but would have to check for a variable that is part of the project yaml.

**Comment by ExperimentsInHonesty** [comment]
@KianBadie in order to add a second image to the project's md file, we need to decide what to rename the current image field and a host of other questions.  I am going to open an issue for this discussion and I will get back to you with his answer.

**Comment by KianBadie** [comment]
@ExperimentsInHonesty Sounds good!

**Comment by KianBadie** [comment]
From a Zoom meeting with Bonnie on 1/6:
[Necessary context for the "Getting Started" feature](https://github.com/hackforla/website/issues/237)

- The main [Hack for LA Getting Started readme](https://github.com/hackforla/getting-started) will be on each project page under the "Getting Started" section.  
- Adding another field to each project md file called "resources" that is similar to the existing "links" field (which currently holds every link associated with the project). Resources will now contain every single link/resource associated with the project, meaning there will be overlap in displayed information. While the original "links" field are prioritized links. Meaning that these are the links that show towards the top of the project page in the "Links" section. These links on top are most likely seen first and are a shorter lists than the resources section. 
- Wikis/readmes of the project should show in the "Getting Started" section and the resources section. Meaning there will be overlap in displayed information. 
- In the "Getting Started Section", if the project already has a wiki/readme, it would show next to the hfla readme. If not, show a call for action to encourage users to help make a wiki/readme for the project. 
- Reemphasizing the importance of having the "looking for field" filled for each project, so that it can be displayed on each project page. As of right now, if it is not filled out, nothing relating to that field will display on the page. 
- Need better project banners. 
- Need a tools section displaying the tools used in the project.
- Have wiki/readme show on main projects page as "Start Guide" link. However, the wording will be different on the project home page.
- Resource Icons should be in color

**Comment by KianBadie** [comment]
From Zoom meeting on 1/11: 
The discussion in #237 is also related to this

- It seemed that the page had better feedback when it was going in this direction: 
![Screenshot from 2020-01-17 17-36-37](https://user-images.githubusercontent.com/18221058/72656446-132b6780-3950-11ea-9247-a2638d5d68eb.png)
- Changing green background to a blue that matches the end of the gradient on the project banner. 
- Changing the project title to just be white text
- Increasing the size of the project banner

I will aim to have this implemented by our next zoom meeting 1/29

**Comment by ExperimentsInHonesty** [comment]
@KianBadie will do a Mobile optimization proposal
@ExperimentsInHonesty is going to provide a image naming schema and how to provide links at top vs all resource links
### dependancies 
are need github api integration for languages and contributors.

**Comment by KianBadie** [comment]
Posting current progress in case any UI/UX people would like to do anything with the page. I am not a UI/UX person at all, so please feel free to let me know anything as it can help tremendously! (Sorry @ExperimentsInHonesty , I know I was supposed to post this 1 week ago so UI/UX people could potentially work on this). Let me know if better pictures are needed.

### With Readme provided by project:
![Peek 2020-02-03 13-17](https://user-images.githubusercontent.com/18221058/73691893-1af54680-4688-11ea-94dc-c842f1640139.gif)
![Screenshot from 2020-02-03 13-25-39](https://user-images.githubusercontent.com/18221058/73692223-c8685a00-4688-11ea-9d6d-5f2edc24038a.png)

### Without Readme provided by project (no hero image is currently implemented so it uses a generic one which is from the homepage):
![Peek 2020-02-03 13-22](https://user-images.githubusercontent.com/18221058/73691978-4710c780-4688-11ea-8fb7-b18b69bd918d.gif)
![Screenshot from 2020-02-03 13-25-14](https://user-images.githubusercontent.com/18221058/73692210-c1d9e280-4688-11ea-9a10-4ed0a5a0ee87.png)

**Comment by KianBadie** [comment]
And in terms of mobile optimization, I am not sure how a proposal for things like this usually look. But I can try to make implement it on my branch and then provide pictures. I was just going to use the media queries used by css to aplly different style rules when screen sizes are smaller than 480px, which is already a varable defined in the sass.

**Comment by KianBadie** [comment]
### Lastly, some topics/points that have come up during my development that I wanted to post here for record keeping/possible discussion:

1. We mentioned in a previous meeting having a field for "prioritized links" that will display at the top section of the project home page/the projects page. Is this still a feature we want? If so, how will we determine what prioritized links are? This also leads into the question of how will projects be displayed on the projects page? Will they be the same?
2. Right now, the comma separated list for the "looking for" section does not completely work because there are commas that separate roles themselves and commas that separate additional information within the same role. So it is difficult to parse and figure out when a new role is actually being described. Are we going to manually fix this ourselves in the md cards? If so how?
3. For some of the icons (the link icon specifically), I got them from ioicons, a MIT licensed icon library. I downloaded the ones I needed and stuck the license in the file.
4. The icons used in the resources section could use some touching up. The way they are currently implemented, they might look fine, but the github logo is actually slightly cut off on the right side and the slack logo is off center. These things get blown up when they are the size they currently are in the resources section.
5. For the hero image, the dimensions were based off of the hero image on the homepage (which is exactly 1500x719. Which is 19px wider than what we are requesting. Apologies on my part, I should have double checked rather than going based off of an approximation). However, both the home page and project home page hero images are not wide enough to fill the width of the display (at least on my monitor, and I think probably most). I implemented some css rules to make the image fit the width of the display on the project home page to fix this (inspired by a similar fix on the website home page). My apologies if there could have been an easier way to implement this with a more thorough investigation rather than having a fix like this.  
6. It would be nice to have a confirmed project.md skeleton, and to have all cards updated to that if there are going to be changes. Right now, I have a sample skeleton based off the Record Clearance project

title: 
description: 
image:
alt: 
image-hero: 
alt-hero: 
links:
- name: 
url:

partner: 
looking: 
location: 
status: 

### If more issues/topics come up I will be sure to raise them so they can be fixed immediately rather than dumped like this. My apologies for the load of text.

**Comment by ExperimentsInHonesty** [comment]
the links will look like:

```yaml
- name: link text here
  url: https://www.example.com
  show_at_top: true
```

**Comment by thekaveman** [comment]
Answer 2.

> Right now, the comma separated list for the "looking for" section does not completely work because there are commas that separate roles themselves and commas that separate additional information within the same role. So it is difficult to parse and figure out when a new role is actually being described. Are we going to manually fix this ourselves in the md cards? If so how?

Last night we discussed the idea of turning this section into a proper YAML list instead of a comma-separated string, which removes the parsing problem.

So instead of:

```yaml
looking: One skill, another skill, a compound skill (part 1, part1)
```

We have:

```yaml
looking:
  - One skill
  - another skill
  - a compound skill (part 1, part 2)
```

**Comment by ExperimentsInHonesty** [comment]
@thekaveman 
@KianBadie asked the following:

Dialog on 1.

> We mentioned in a previous meeting having a field for "prioritized links" that will display at the top section of the project home page/the projects page. Is this still a feature we want? If so, how will we determine what prioritized links are? This also leads into the question of how will projects be displayed on the projects page? Will they be the same?

And we decided at the meeting to do the following:
- name: link text here
  url: https://www.example.com
  show_at_top: true

But then Kian and I were talking wed and we realized that it might be easier to leave out the 
show_at_top: true
and just put if its going to show on the pages, into the include that builds the page.  So the logic is something like if x (e.g., github, slack, test site, launch site) link exists, show it at top.

The pros of that method are:
less risk that we didn't put true on something that as an org we want to be live on all project homepages
The con is that all the way that we refer to links in each project page, have to be identical, and currently they are not.  But this is also sort of a pro, because we really need a common way to refer to things like 
     test site
vs staging server
vs beta site

Thoughts?

**Comment by thekaveman** [comment]
> ... and just put if its going to show on the pages, into the include that builds the page. So the logic is something like if x (e.g., github, slack, test site, launch site) link exists, show it at top.

I'm not sure I follow what you mean here. Assuming the links are still represented as a YAML list, are you suggesting the template/include would e.g. check if the current link (inside a loop) is the GitHub link, and if so render it? This seems more complicated and error prone to test for URL patterns vs. being explicit with a property on the link data itself.

Alternatively are you suggesting that certain important links like GitHub, Slack, etc. would be pulled out into their own top-level YAML properties, apart from the resources/links list? This seems like it would work fine and accomplish both goals.

**Comment by ExperimentsInHonesty** [comment]
@thekaveman 

I was suggesting that our org decides we always want to display specific important links in the top part of the project homepages (github, test site, launch site)
![Screen Shot 2020-02-05 at 12 56 56 PM](https://user-images.githubusercontent.com/37763229/73882494-085d4780-4817-11ea-8ae6-8be09bef55df.png)
See this link for the whole mockup https://github.com/hackforla/website/issues/157#issuecomment-557929588

And then a month from now, we decide that we want to link to the the project's slack channel as well (just an example), we add that to the _/includes/project-homepage.html as something to render at that top part of the project home page, if the name exists in the list of **names** of links (not the url itself):

```yaml
links:
  - name: Github
    url: 'https://github.com/helloGov/'
  - name: Site
    url: 'https://hellogov.squarespace.com/'
```

**Comment by ExperimentsInHonesty** [comment]
Answer 6. I created a wiki page that has a link to the template we are currently using.  We will update when we change the standard.

**Comment by thekaveman** [comment]
@ExperimentsInHonesty 

> And then a month from now, we decide that we want to link to the the project's slack channel as well (just an example), we add that to the _/includes/project-homepage.html as something to render at that top part of the project home page, if the name exists in the list of names of links (not the url itself)

Thanks for the explanation, I understand now. I'm often wary of making logic choices like this based on string matching, since it is so easy to introduce casing/spelling errors. On the other hand, it removes the need to update each project.md when a new "required" link comes online. On the other other hand, it also somewhat removes the distributed content editing nature of updates and requires a dev to come in and edit a template. Trade-offs!

**Comment by ExperimentsInHonesty** [comment]
Answer 1. Created new issue #297 to change the project.md file format, and add logic to the project homepage include to render specific links at top.
Answer 2. Issue is created to implement our decision on how to reform the looking for in project.md #291 
Answer 3. We decided we should provide details about where icons on the site came from in the wiki resources section.  Issue to assemble that info and display it #292, and its dependency #293 
Answer 4. We created an issue to have someone improve the social icons #296
Answer 5. We decided we should try to make a gradient around the image so that it doesn't distort the image when the screen size changes. #295 
Answer 6. I created a [wiki page](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file) that has a link to the template we are currently using. We will update when we change the standard.

**Comment by ExperimentsInHonesty** [comment]
Currently waiting details about how to render the contributors and Languages of projects.

**Comment by KianBadie** [comment]
Added logic to display prioritized links at the top:
![Screenshot from 2020-02-10 18-49-11](https://user-images.githubusercontent.com/18221058/74207867-13104600-4c36-11ea-83e2-9a44dfd7b8c8.png)
![Screenshot from 2020-02-10 18-49-23](https://user-images.githubusercontent.com/18221058/74207870-14da0980-4c36-11ea-851d-7bb846f65556.png)
The actual logic itself is not pretty. I had simpler/prettier logic, but formatting issues arose specifically with adding commas. For now, the logic for this functionality looks like this:
```
                            {% assign counter = 0 %}
                            {% for item in page.links %}
                                {% if item.name == 'Github' or item.name == 'Test Site' or item.name == 'Launch Site' %}
                                    {% assign counter = counter | plus:1 %}
                                {% endif %}
                            {% endfor %}
                            {% for item in page.links %}
                                {% if item.name == 'Github' or item.name == 'Test Site' or item.name == 'Launch Site' %}
                                    {% if counter > 1 %}
                                        <a href='{{ item.url }}'> {{ item.name }}</a>,
                                        {% assign counter = counter | minus:1 %}
                                    {% elsif counter <= 1 %}
                                        <a href='{{ item.url }}'> {{ item.name }}</a>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
```

**Comment by KianBadie** [comment]
@ExperimentsInHonesty @harishlingam 
In regards to last nights discussion with wanting icons with color before deciding what resource cards would look like, I mocked up what the page/resource card options would look like with icons with color if you were still interested at looking at them. I threw a facebook icon in there for more examples:

**1. (Original)**
![Screenshot from 2020-02-11 18-21-59](https://user-images.githubusercontent.com/18221058/74297978-52ee3080-4cfd-11ea-9a49-5fe828bb3711.png)
**2.**
![Screenshot from 2020-02-11 18-25-51](https://user-images.githubusercontent.com/18221058/74297993-5a153e80-4cfd-11ea-831d-95b3ea8d6d7c.png)
**3.**
![Screenshot from 2020-02-11 18-31-20](https://user-images.githubusercontent.com/18221058/74298002-5f728900-4cfd-11ea-99fc-97c21f320ae9.png)

**Comment by ashlingam** [comment]
@ysjiang18 We are taking a second look at the Project Home Page to improve its UI. Our question at the moment: how best can we display the contributors on the project? For instance, if a project has 20 contributors, do we show all of them on page-load, or a select portion? If a select portion, how can one view the remaining contributors if they so choose?

**Comment by KianBadie** [comment]
Here are some screenshots for testing that are more in context

### Regular
**Gif:** ![Peek 2020-02-17 16-23_vanilla](https://user-images.githubusercontent.com/18221058/74693957-eebae900-51a2-11ea-8f38-1600f3385adb.gif)
**Screenshot:** ![Screenshot from 2020-02-17 16-24-03](https://user-images.githubusercontent.com/18221058/74693987-0a25f400-51a3-11ea-93da-fe3db0a3acac.png)
### Border Top
**Gif:** ![Peek 2020-02-17 16-26_bordertop](https://user-images.githubusercontent.com/18221058/74693971-f8dce780-51a2-11ea-867d-0a667e73ce58.gif)
**Screenshot:** 
![Screenshot from 2020-02-17 16-26-29](https://user-images.githubusercontent.com/18221058/74693990-114d0200-51a3-11ea-85a7-1b8428ccfd6d.png)
### Pink
**Gif:** ![Peek 2020-02-17 16-29_pink](https://user-images.githubusercontent.com/18221058/74693980-fed2c880-51a2-11ea-9b7b-cc9f2583f0fa.gif)
**Screenshot:**  ![Screenshot from 2020-02-17 16-29-57](https://user-images.githubusercontent.com/18221058/74693994-1447f280-51a3-11ea-83da-750d7cf71e89.png)

**Comment by thekaveman** [comment]
Not sure if this has come up in the discussion, but the information is available via GitHub API: https://developer.github.com/v3/repos/#list-contributors

**Comment by KianBadie** [comment]
@ExperimentsInHonesty @harishlingam 
Just added a first iteration of the Project Team card based off of mock data added to _data/github.json and record-clearance-projectt.md files. (Order of contributors/leadership is arbitrary).

### Gif
![Peek 2020-02-19 17-45](https://user-images.githubusercontent.com/18221058/74893609-9ff78580-5341-11ea-9a3c-4c820af72838.gif)
### Stills
![Screenshot from 2020-02-19 17-46-17](https://user-images.githubusercontent.com/18221058/74893119-6a9e6800-5340-11ea-95b5-b126260cd1ca.png)
![Screenshot from 2020-02-19 17-51-47](https://user-images.githubusercontent.com/18221058/74893155-899cfa00-5340-11ea-9973-159658af4f63.png)

The leadership card is built with mock data of what the expected github api calls will give us after it is parsed. The sources for all the images in the team seciton are the urls to the github profile pictures, so they were easy to obtain. Leadership section was hard coded into the project.md file (which from my understanding, is the way we plan to do it.) That will allow us to specify what role they play in the project as well as provide any links to forms of contact.

**Comment by ashlingam** [comment]
@KianBadie @ExperimentsInHonesty @ysjiang18 Thanks for putting this together Kian. It's really helpful to see this iteration of the Project Home Page with dummy data added in.  A couple requests: (1) Can you increase the margins between each project resource box as we did on last call? (2) Now seeing the photos added in, I propose we split test the resource boxes Monday evening with: (a) red color tabs (b) gray line (c) light gray color tabs.

**Comment by ashlingam** [comment]
@ysjiang18 (Just copying my earlier message here): Basically, we are looking for a wireframe that iterates on the mockup we already have, specifically, improving the way contributors are shown beyond a certain number (drop down?carousel? etc.). Following that, how can we improve the look of the Getting Started carrot, which when clicked displays the content box immediately below?

**Comment by ashlingam** [comment]
@KianBadie My proposed UI edits to the current version:

- [x] Beneath “Open roles”, make bullets flush left
- [x] “Getting Started” centered horizontally with content box. Increase line space above “Getting Started” by 100%.
- [x] Getting Started carrot: Remove bolding. Reduce size by 100%. Increase space between “Getting Started” text and carrot by 100%.
- [ ] (If possible) Light grey horizontal line between Project Overview box and Getting Started content box, such that the two boxes look "hinged" when the user has clicked the carrot.
- [x] Left edge of first project leadership, contributors, and project resources to be aligned
- [x] Increased spacing between Getting Started, Readme, and project resource boxes
- [x] Light gray divider line in between logo and “GitHub”, “Slack” and “Readme” within resource boxes
- [x] Light gray boxes around contributor pictures
- [x] Red hyperlink to project leader names (but not to field title "Name")
- [x] “Project Resources” to “Resources” at bottom
- [x] Match font size of "GitHub, Slack, Readme" in resource boxes to font size of "Status, Partner, Location" under Project Overview
- [x] Edit paragraph text within call-out boxes to left-justify

**Comment by ExperimentsInHonesty** [comment]
@KianBadie is currently working on the left right scroll problem identified by Joel, on this [issue comment ](https://github.com/hackforla/website/issues/351#issuecomment-596337260)
ETA : Friday March 12th

**Comment by KianBadie** [comment]
***Sorry for the lack of documentation. Here is an update***
## Current state of project home page on desktop (my local branch):
### A project with all the data we need (linked github repo, readme/wiki, defined project leadership, etc)
![current_state311data](https://user-images.githubusercontent.com/18221058/76672331-12324300-6559-11ea-9a6c-43f87e1abe70.gif)
#### Mobile iPhone 6/7/8
![current_state311data_mobile](https://user-images.githubusercontent.com/18221058/76672660-95549880-655b-11ea-80a2-e17f27726cc4.gif)


### A project missing a lot of the data we need (linked github repo, readme/wiki, defined project leadership, etc)
![current_state_workforla](https://user-images.githubusercontent.com/18221058/76672338-2118f580-6559-11ea-907d-8473968fcd7a.gif)
#### Mobile iPhone 6/7/8
![current_state_workforla_mobile](https://user-images.githubusercontent.com/18221058/76672666-ab625900-655b-11ea-91b1-b850ea14a679.gif)

Using these 2 example to show the 2 "opposite" ends of the spectrum of what the pages can look like. I currently have a pull request open to have the project home page be up to date with my local branch. I think the main differences on that pull request might be mobile styling rules. To see what the mobile styling updates look like, I have provided many examples in the pull request #363, using screens that are small, medium, and large. 

## How to view the page on your desktop
The pages are actually currently integrated into the main site. Just type https://www.hackforla.org/projects/[INSERT_PROJECT_NAME]. The only caveat is that you need to type the [PROJECT_NAME] according to the file name on the website repo. For example, the "ArtWatcher" project url would be "https://www.hackforla.org/projects/adopt-civic-art". I am going to try to keep this comment readable, so I am going to avoid posting many screenshots and refer to the project page urls that are available now (however, they are not completely up to date to the gifs/pictures I have posted above. Those are currently on an open pull request).

## Other
There are some things I wanted to talk about relating to the page. 
- Some leaders for the leadership cards do not have slack or github links. So when a user clicks on the picture/name, it just opens a new tab of the project home page (rather than slack/github links).
- I currently have 3 separate pull request relating to the project home page #366 #364 #363. #366 Makes the project home page accessible from the current projects page. #364 makes the hack for la logo a clickable link to the current projects page. #363 adds the mobile friendly rules that I think @joelparkerhenderson mentioned. 

Other than that I can't think of any other updates. My apologies for the information dump. If I think of more things I will edit this comment and add it.

**Comment by ExperimentsInHonesty** [comment]
Prototype complete!!!!
