### ISSUE TITLE
Change Alt Text for Partnership Icon on Credit page

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1576]
### Overview
Alt text for Partnership Icon on Credit Page needs update.

### Action Items
- [ ] Change the alt attribute value to 'Partnership Icon'

```diff
- alt: 'Image of Partnership'
+ alt: 'Partnership Icon'
```

### Resources/Instructions
https://github.com/hackforla/website/blob/90a20d1e088b0a05a286af101f82135ad4774e39/_data/internal/credits/partnership.yml#L10

**Comment by benrempel** [comment]
I fixed this locally, should I push now?

As far as I can tell, partnership.yml isn't referenced anywhere in the site. This same partnership icon is used in the "join us" page, but directly references the .svg file, with its own alt text. Is that an issue? Still getting a sense of the architecture.

https://github.com/hackforla/website/blob/3054d9ff1540fccec4630a3aa5b5b76d4b36d9b3/pages/join-us.html#L70

**Comment by jbubar** [comment]
@benrempel Great question! yes go ahead and create a pr. 

partnership.yml is part of a collection that gets referenced in the credits page with some fancy liquid jekyll syntaxy stuff
https://github.com/hackforla/website/blob/115f01be3684952b6e5c7d39918289d0678255c9/pages/credits.html#L22

and for the second question. I think they are supposed to be different, because they are on different pages. 

but lets ask qiqi.

@qiqicodes want to weight in on this?

**Comment by benrempel** [comment]
ah got it! I was trying to figure out where partership.yml was used in the site. Now I get what's going on- I think you're right and there's no issue here
