### ISSUE TITLE
Change Alt Text for Redo Icon on Credit page

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1581]
### Overview
Alt text for Redo Icon on Credit Page needs update.

### Action Items
- [x] Change the alt attribute value to 'Redo Icon'

```diff
- alt: 'Image of Redo'
+ alt: 'Redo Icon'
```

### Resources/Instructions
https://github.com/hackforla/website/blob/90a20d1e088b0a05a286af101f82135ad4774e39/_data/internal/credits/redo.yml#L10

**Comment by averdin2** [comment]
@celinevalentine I saw that you closed this issue even though the pull request #1937 that links to this issue has not yet been merged. I just want to let you know that you do not need to close the issue. When the pull request is merged it will close the issue. I am reopening this issue since the pull request has not yet been merged.
