### ISSUE TITLE
Add sidebar to wiki

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1622]
### Overview
We need a custom sidebar for the wiki so that we can navigate and find articles easily

### Action Items
- [x] create the custom sidebar (see option below the regular sidebar in the [wiki](https://github.com/hackforla/website/wiki)) following the new categories outlined in the [wiki file audit](https://docs.google.com/spreadsheets/d/1ZfLAUfpxjblvfobdewQ0SkQ9I2HqheD56c5ogrcYdiA/edit#gid=2115689612) (check 2nd and 3rd tabs)
- [x] add each of the articles into the sidebar
   - [x] Style with "see more" and "see less" Github functionality to hide the subcategories.
- [x] Feel free to ask @daniellex0 and/or @ruqpyL2 any questions that might come up here
- [x] ensure that it is user friendly

### Resources/Instructions
[wiki file audit](https://docs.google.com/spreadsheets/d/1ZfLAUfpxjblvfobdewQ0SkQ9I2HqheD56c5ogrcYdiA/edit#gid=2115689612) (check 2nd and 3rd tabs)
[wiki](https://github.com/hackforla/website/wiki)) following the new categories outlined in the [wiki file audit](https://docs.google.com/spreadsheets/d/1ZfLAUfpxjblvfobdewQ0SkQ9I2HqheD56c5ogrcYdiA/edit#gid=2115689612) (che

**Comment by Aveline-art** [comment]
@daniellex0 Is this the sidebar that you were referring to: [sidebar for expunge project](https://github.com/hackforla/expunge-assist/wiki)

**Comment by daniellex0** [comment]
@Aveline-art Yes exactly 👍 

I need to update @ruqpyL2 's [spreadsheet](https://docs.google.com/spreadsheets/d/1ZfLAUfpxjblvfobdewQ0SkQ9I2HqheD56c5ogrcYdiA/edit#gid=534478216) with Bonnie's edits and then we can start moving forward with this

**Comment by Aveline-art** [comment]
@daniellex0 Just want to make sure this issue does not die. Can anyone be assigned to it at the moment? Is the work on this in progress?

**Comment by daniellex0** [comment]
Thank you for checking on this @Aveline-art ! I will meet with @ruqpyL2 to work on this, but in the meantime I wanted to just make double triple sure devs are ok with the new categories. I already shared the doc in a dev meeting in the past but I'm not sure many people looked at it beyond a passing glance, especially the 2nd/3rd tabs with the new categories. What do you think would be the best way to get several devs to check this out? Should it be brought up again at the Tue dev meeting?

https://docs.google.com/spreadsheets/d/1ZfLAUfpxjblvfobdewQ0SkQ9I2HqheD56c5ogrcYdiA/edit#gid=534478216

**Comment by Aveline-art** [comment]
Got it! I will move it to the dev meeting discussion items and it will most likely be picked up Tuesday. The document is a little cryptic, though, so I am unsure if the team can comment on it. Can you or @ruqpyL2 post some discussion questions relating to your possible concerns? I do not think the team have experience exploring our wiki very often, so it is hard to form an opinion on the categories.

**Comment by daniellex0** [comment]
@Aveline-art just double checking, did you notice the second and third tabs? Those describe each wiki article and which category it can fit into

**Comment by Aveline-art** [comment]
Thank you for letting me know! I have taken a look at it, and just to be sure, do you have any specific concerns that you would like the devs to address or would you like us to make general comments and observations?

**Comment by daniellex0** [comment]
@Aveline-art  I think it would mostly be helpful to know if they agree with the categories/the way the different articles are organized into the categories. And if they have any suggestions for changes/improvements. Because we don't want anyone upset or annoyed when these changes are made! :)

**Comment by marcobarrera** [comment]
On behalf of the dev team, we are very impressed with the work yall have done. Thank you @daniellex0 @ruqpyL2 We spoke about the categories and we have some suggestions: 
1. We would like site architecture and code templates split into separate categories rather than one.
2. We want a new category titled How To. The articles that fall under these would be the 4 How To Wikis. 
3. Ensure file name style consistency.

We also would like to ask why do some files fall under multiple categories, for example Onboarding/Roles.
Since we now have PMs, is this a task that should be spearheaded by the PMs instead of the UI team? @sayalikotkar @Sihemgourou

**Comment by daniellex0** [comment]
@marcobarrera Thank you so much for all reviewing it and for the feedback! This feedback all sounds great (as long as Bonnie approves too). 

As soon as this gets the go-ahead, @ruqpyL2 and I agreed this could be a good dev issue if anyone wants to take on implementing this.

**Comment by GLRJr** [comment]
Decision is: Join Us will move to the home page and the About Us link will get a summary paragraph that references that there is more history and roadmap information available.

**Comment by daniellex0** [comment]
Progress: Confirming some questions with devs about new wiki

Blockers: Busy schedules

Next Steps: Implementing new wiki this week, meeting with Candace to discuss next steps

ETA: 1 week

**Comment by csseu** [comment]
OK, I put up a [sidebar](https://github.com/hackforla/website/wiki) with the categories and expansions.

![image](https://user-images.githubusercontent.com/23020878/122718622-033d4480-d222-11eb-8fdc-caac00734c2d.png)

**TIL:**
+ You can make branches on wiki repos, but nobody can see the branch without cloning it to their machine
  + You could then try to render it using gollum
  + But the github wiki engine has subtly but sufficiently branched from gollum so that the link structure needed for local machine does! **not!** work! on! github!
+ It also seems like you can't make a PR for a branch on a wiki 

**Rather than make reviewers deal with that mess, I pushed to master directly. Sorry, I hate it too.**
- I checked that all the sidebar links are valid
- But please lmk if I broke anything in the articles
- I also made some general content updates for formatting, typos, etc.
- And rewrote the Home page.

**Other notes:**
- Being a part of the HfLA team (NEW article) - added to Onboarding.
- The former "Tech tips/Github" category turned mostly into How-To. "Security-updates" was left over, but isn't really a how to, just a FYI, so I put it in Onboarding.
- Moved "Tools" into Marketing-and-Analytics and renamed "Analytics Tools"
- Pulled Roles out of Onboarding since we had a lot of Onboaring articles.

**Next steps:**
- Let me know if you have feedback // if we can eventually close the issue.
- PMs may want to update: Project terminology, all Marketing and Analytics articles
- "How to Git GUI was marked for merge into another doc, this should probably be revisited in view of the CONTRIBUTING reord.
- Will move styling out of Site Architecture once we have that documentation prepped
- Will probably add a Edit Wiki how-to with wiki structure tips so that the next person won't have as terrible a time)

**Comment by csseu** [comment]
@daniellex0 and I looked at alternate styling of the sidebar. There are competing requests: 1) to have larger text than the default (approx h2 size) for at least the categories, and 2) have the expansion arrows.

header tags are not compatible with the `<summary>` tag; the arrows do not align with the text (current appearance). Some will find this OK and others not.

I looked into injecting custom css; this appears to have been restricted out of the github wiki engine.
I tried writing inline css with `style="font-size:16px;"` and the like at various tags. This also appears to be overridden by the engine.

**Comment by sayalikotkar** [comment]
@ruqpyL2 @daniellex0 The PMs got together & reviewed it, we want o know if the below format works for everyone. It works for us 

[Home](Home)

<details>
<summary>Onboarding Links</summary>

<br>

+ [Joining the HfLA Team](Joining-the-HackforLA.org-Website-Team)
+ [Introduction to the Project](Introduction-to-the-Project)
+ [Being Part of the HfLA Dev Team](Being-a-Part-of-the-Hack-For-LA-Team)
+ [Contributing to the Website Repository](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
+ [Project Terminology](Project-Terminology)
+ [On Github Security Updates](Github-security-updates)

</details>

<details>
<summary>Site Architecture Links</summary>

<br>

+ [Hack for LA Site Architecture](Hack-for-LA's-Site-Architecture)
+ [Standardized Components](Standardized-Components)
+ [Project File Layout Guide](Guide-to-the-Project-Layout-File)

</details>

**Comment by csseu** [comment]
Sure, works for me.

**Comment by Aveline-art** [comment]
Something to consider:

As some of the categories expand, having subcategories would help isolate relevant/irrelevant articles. For example, it might be hard to locate something about pull requests in the How To: section. I don't have suggestions on splitting the How To section for now, but if this feature is preferable, I can gather suggestions during the next development meeting.

**Comment by csseu** [comment]
That's a good idea. I trust your judgment, so if a split doesn't seem that
obvious to you right now, it could probably wait a few months (especially
if you think you'll be writing more articles).

**Comment by daniellex0** [comment]
Looks like this issue is completed, closing- thank you so much for all of your great work on this @ruqpyL2 ! 🥇
