### ISSUE TITLE
Come Up With User Stories For Roles/Jobs Page

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1685]
### Overview
We need to generate user stories to reach a consensus about the functionality of the civic tech job.

### Action Items
- [ ] Create User Stories for the jobs page
- [ ] Use the existing job boards for reference to potential user stories

### Resources/Instructions
Existing Job Boards:
- https://github.com/hackforla/engineering/projects/2
- https://github.com/hackforla/UI-UX/projects/3
- https://github.com/hackforla/UI-UX/projects
- Other Job Boards in their respective communitize of practice project boards

Figma Design
- https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=5326%3A26395

Techonologies
- https://github.com/hackforla/website/issues/1602#issuecomment-854326393

**Comment by paulsvh** [comment]
-As a volunteer job-seeker, I want to be able to find and learn about open roles on the Hack 4 LA team so that I can potentially pursue one of these roles. (e.g. the roles are presented/described in a list accessible to volunteers)

-As a project manager, I want to be able to create, update, and remove job postings for roles available within the Hack 4 LA team. (e.g. project managers get full CRUD ability on job postings that will be listed on the posting page)

**Comment by arghmatey** [comment]
As a project manager, I want to receive a notification in my project's main Slack channel when a volunteer is interested in one of my job postings.

As a volunteer, I want the ability to filter new job opportunities based on my role, preferable technologies, program area I'm interested in, personal experience level, specific project name, and availability for meeting times.

**Comment by wendywilhelm10** [comment]
As a full-stack developer and volunteer, I want to be able to find open positions in the different projects offered by Hack 4 LA.  I would like to use this platform to increase my skills in the technologies I have been learning so that I can eventually find a job using these skills.

**Comment by grhhhh** [comment]
- As a project manager, I want my volunteer role to be easy to search for so that candidates can find it without difficulty.

_These specifically reference functionalities represented on the Figma design_:
- As a project manager, I want my project meeting times to be displayed on the role description so that candidates know our meeting schedule.

- As a project manager, I want my volunteer role to be shareable via socials (linked in, twitter, fb) so that volunteers can share them with friends and colleagues.

**Comment by akibrhast** [comment]
- As a project manager I would like to have the ability to start creating a new open role and save it in an unfinished state, without making the role live
- As a project manager I would like to have the ability to create new open roles based on an existing template.
- As a project manager I would like to have a dashboard to view all the people and their resume/background that applied to a role I created to such that I can onboard those that are qualified for the role.
- As a project manager I would like to have the ability to create roles and schedule them to be posted at specific date/time.

**Comment by jbubar** [comment]
- as a future contributor, I would like to see the open roles, in order to decide if I have the skills to contribute to a project
- as a veteran contributor, I would like to see what the projects are up to, so that I can get a quick commit in on a project

**Comment by Aveline-art** [comment]
1. As a volunteer, I want to be able to search for projects that explores my areas of interest.
2. As a volunteer, I want to clearly know how to submit my intention to apply for a project.

@akibrhast Can we get some PMs to document their own user stories, if not already?

**Comment by akibrhast** [comment]
@sharadgaurav7 I am going to unassign myself from this one for the moment and close this issue. I am  linking you to this just in case the information here is useful for us . The user stories and the information on this issue can be transferred to the new civictechjobs repository - https://github.com/hackforla/CivicTechJobs/issues
