### ISSUE TITLE
#About Meetings

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1724]
Please write here the questions for the development meeting : 

- [x] New team members do not know that doing PR reviews is part of their contribution to H4LA
- [x] How to get this information out there?
- [x] Proposal: Have one meeting a month dedicating to teaching members how to do PR reviews
- [x] Desired outcome: Teach members how to do PR reviews and get the information out there.

What are everyone's thoughts?

**Comment by akibrhast** [comment]
Spend time on Developer meeting both on sunday and tuesday and do at least one pull request review with the crowd, and sell the wiki link that ava wrote https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests

**Comment by Aveline-art** [comment]
Backend meeting June 17, 2021 Notes
- Sorting through new labels. There are size labels and roles labels, but also a lot of misc. labels. When are they supposed to be used? How are we going to relay the intent behind these labels to our team?

Add-ons:
- How do we feel about people working on a new issue when one issue is under a pull request review? Is this desirable? Should there be a maximum number of issues a contributor can take on at once? Also, it seems that part of the reason why people want to take on multiple issues is that there is a lot of energy. Should we have a process that speeds up merging so that this energy is not lost?
- What are some good weekly reminders to give out? Let us make a list so that we can make it a part of our meeting opening!

**Comment by akibrhast** [comment]
I believe we should ask all the developers to connect their github account and their slack account together. That way the new PR notification feature created by @arghmatey that is running on the hfla-site-pr will be able automatically be able to notify said people on their PRs that has been stalled for a long time.

**Comment by akibrhast** [comment]
Things to discuss with @Sihemgourou :

- Possible emailing solution for wins submission
- Changing labels for the auto issue created by wins submission
- Issue template for the wins submission
- This PR - https://github.com/hackforla/website/pull/1732
- Adding descriptions to the newly created labels
- Discussion permission levels - https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization

**Comment by Aveline-art** [comment]
Backend meeting July 1, 2021 Notes:

- Consider using ~~GitHub Explorer~~ GitHub GraphQL endpoint to perform API requests for GitHub actions rather than depend on multiple disjointed RESTAPI calls,.

**Comment by akibrhast** [comment]
>  Btw in the future please add screenshots of how the changes look on the website to your PR, because **_other designers won't be able to review the branch on their machine_** :)

The above comment was made by @daniellex0 in this review, https://github.com/hackforla/website/pull/1819#pullrequestreview-693372676 .

This a one of the primary barriers that needs to be resolved to motivate communication between designers and developers .

The backend team should involve it's members in researching possible solutions such that designers can review changes made in pull request from a visual perspective without needing to muddle in the git stuff and forking and what not..

**Comment by Aveline-art** [comment]
Closing this in favor of a better way to organize ideas for meetings #1891 . Format is based on #1734 .

@abuna1985 I believe you are heading the meeting next Tuesday? If so, you can feel free to use [this](https://github.com/hackforla/website/issues/1891#issuecomment-873684556) to organize (it is also helpful if you have an emergency and we need to pick up on the agenda)
