### ISSUE TITLE
Contributing.md: feature branch

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#1750]
### Overview
The [contributing guide ](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)is an important documentation on situating new members to the team. Currently, it is lacking critical information about reviewing or creating non-default-branch (for example, the [wins-feature-1 branch](https://github.com/hackforla/website/tree/wins-feature-1)\).

### Action Items
- [x] Add feature branch information to the [contributing guide ](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
  - [x] As with above, place it at a place that is intuitive.
  - [x] Add a link to [GitHub's documentation on resolving merge conflicts
](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

### Resources/Instructions
[Code base for wins-feature-1 branch](https://github.com/hackforla/website/tree/wins-feature-1)
[How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
[Resolving a merge conflict on GitHub](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

**Comment by Aveline-art** [comment]
@jbubar I feel the issue might sound confusing. Can you review this and let me know if it looks okay?

**Comment by jbubar** [comment]
@Aveline-art This is a great issue! I think we should call it a feature branch, because that is what they seem to call it in the industry [a cool article about gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

Could I jump in there and edit it a little?

I changed the overview a little. I switched non-default-branch to feature branch, and called gh-pages production. 

I also think that we can add something about "feature branch" label which I put at the end.

Sorry I did not have more time to do a better job on this. Let me know what you think

If noone hops on this... I can knock out the first few action items next week

_______________________________________________________________

### Overview
The [wiki guide on doing pull requests](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests) and [contributing guide ](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) are missing information about how to work off of and review a feature branch like [wins-feature-1 branch](https://github.com/hackforla/website/tree/wins-feature-1)\).

Sometimes, when we are doing a big refactor, we will be working off of a feature branch, not our production branch which is gh-pages. This way we can break up a large issue into a bunch of smaller ones, but not have it go live on our site. 


### Action Items
- [ ] Add information to the pull request wiki guide about [setting up a non-default-branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)(specifically step 1 and 2)
  - [ ] Add information about viewing changes for feature branches
  - [ ] Add information about updating the a feature branch
  - [ ] Make sure the information is placed in the appropriate place in the wiki guide
  - [ ] Also, make sure the information is in an intuitive order so that end users (the dev team) can easily navigate the guide
  - [ ] Recommended: if not done so already, do a practice pull request review on a non-default branch to understand the process ([for instance](https://github.com/hackforla/website/pull/1670)) 
- [ ] Add feature branch information to the [contributing guide ](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
  - [ ] As with above, place it at a place that is intuitive.
  - [ ] Add a link to [GitHub's documentation on resolving merge conflicts
](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

### Resources/Instructions
[How to Review Pull Requests](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests)
[Code base for wins-feature-1 branch](https://github.com/hackforla/website/tree/wins-feature-1)
[How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
[Sample pull request involving non-default branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
[Resolving a merge conflict on GitHub](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

Possible wording to add in the documentation: 
Sometimes you might see a label "feature branch" on your issue. If so you are going to have to do a couple of additional steps.

**Comment by Aveline-art** [comment]
Of course! Edit it however you'd like! I am sure you know how to word this a lot better than I do, since I am very weak with Git! Thank you for giving your expertise @jbubar !

**Comment by Sihemgourou** [comment]
This issue is part of the edits that we need to make https://github.com/hackforla/website/issues/1338. Please add it in the main issue as reference

**Comment by kathrynsilvaconway** [comment]
ETA: End of day on 6/08/2022
Availability: 6-10 hours.

**Comment by tamara-snyder** [comment]
Figure out what [this comment](https://github.com/hackforla/website/issues/1750#issuecomment-881850027) is about

**Comment by jbubar** [comment]
@tamara-snyder I am happy to explain, but it is most likely no longer relevant

**Comment by plang-psm** [comment]
i. Availability: 8hrs
ii. ETA: 9/20/22
