### ISSUE TITLE
Development workflow diagram

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#178]
### Overview
Update SDLC (Sample Software Development Lifecycle) diagram to incorporate Glossary hyperlinks and branding.

### Dependency
#602 

### Action Items
- [x] Add branding to diagram
- [x] Replace boxes with diamond's and indicate yes/no decision points
- [ ] Test process on new feature #602. 
- [ ] Create web page with embedded diagram and hyperlinks to Glossary of Terms page
- [ ] Choose an example feature and translate across definitions

### Resources/Instructions
Development workflow diagram: https://drive.google.com/file/d/1xEkFX4x6iDNCl_wxxoG0FOybGyaAGTa_/view?usp=sharing

Development workflow folder: https://drive.google.com/file/d/1xEkFX4x6iDNCl_wxxoG0FOybGyaAGTa_/view?usp=sharing

**Comment by ashlingam** [comment]
1. Progress - Diagram has been revised to reflect appropriate decision flow shapes: https://drive.google.com/file/d/1EUmsEpy4LcOHb4VLl_dfE3gUFSpc_CaL/view?usp=sharing. To determine whether dedicated new web page is an appropriate next step at present point in time.
2. Blocks - None
3. Availability - Sunday, Friday, Saturday
4. ETA - TBD

**Comment by ExperimentsInHonesty** [comment]
Updated SDLC: https://drive.google.com/file/d/1emxhYv9N6KuCVrG-gnqkqHdGnjhm_Qvb/view?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
**Term: Epic**
> 2020 Project Home Page Launch
 - Definition: An epic is a large body of work that can be broken down into a number of smaller stories, sometimes called issues.
 - Link: https://www.atlassian.com/agile/project-management/epics

**Term: Feature**
> Project Filtering
 - Definition: A product feature is a characteristic of your product that describe its appearance, components, and capabilities. Put another way, it is a slice of business functionality that has a corresponding benefit or set of benefits for that product's end user.
 - Link: https://www.aha.io/roadmapping/guide/requirements-management/what-are-product-features

**Term: User Story**
> As a _New Member_, I want to find projects that need a _UX Designer_ so that _I can develop a portfolio of work_.
 - Definition: A user story is a tool used in Agile software development to capture a description of a software feature from an end-user perspective. It describes the type of user, what they want and why and helps to create a simplified description of a requirement.
 - Link: https://www.atlassian.com/agile/project-management/user-stories

**Term: Customer Research**
 - Definition: Customer research is the process of identifying customer segments, needs, and behaviors. Customer research may be carried out as part of market research, user research, or design research.
 - Link: https://www.interaction-design.org/literature/topics/customer-research

**Term: Data Requirements**
> _Categories of Roles for Project Filtering:_
> Business Analyst
> PM
> Content
> UI/UX
> Development
> Ops
> Data
> QA
> SEO/Marketing
 - Definition: Data requirements, in the context of software development, ensure that the data produced and consumed satisfy organizational objectives, are understood by all relevant stakeholders, and meet the needs of the team that create and use the data.
 - Link: https://www.healthit.gov/playbook/pddq-framework/data-operations/data-requirements-definition/

**Term: Acceptance Criteria**
> _Given_ I am on the Project Page and I am searching for projects that use Node.js and need a Front-End Developer,
_When_ I checkmark "Node.js" in the Technologies filter and "Development" in the Roles filter and select apply,
_Then_ the page shows me all projects that meet the criteria I've chosen.
 - Definition: Acceptance criteria refers to a set of predefined requirements that must be met in order to mark a user story complete. Acceptance criteria are also sometimes called the “definition of done.” They determine the scope and requirements that must be executed by developers to consider a user story finished.
 - Link: https://www.productplan.com/glossary/acceptance-criteria/
 - Link: https://rubygarage.org/blog/clear-acceptance-criteria-and-why-its-important

**Term: Product Backlog**
 - Definition: A product backlog is a list of new features, changes to existing features, bug fixes, infrastructure changes, or other activities that a team may deliver to achieve a specific outcome. The product backlog is the single authoritative source for things that a team works on.
 - Link: https://www.agilealliance.org/glossary/backlog/

**Term: Wireframe**
 - Definition: A wireframe is a static, low-fidelity representation of different layouts that form a product. Wireframes communicate structure, content, and functionality of a product, feature, or enhancement.
 - Link: https://theblog.adobe.com/everything-you-need-to-know-about-wireframes-and-prototypes/

**Term: QA**
 - Definition: Software QA is the process of ensuring software quality. It often includes tasks like functional testing and source code quality and performance testing.
 - Link: https://www.mindfulqa.com/qa-sdlc/

**Term: Usability Standards**
 - Definition: Usability falls under the broader discipline of user experience and refers to the ease of access and/or use of a product or website. These standards include compliance with ADA standards, which refer to the Americans with Disabilities Act Standards for Accessible Design. These standards state that all electronic and information technology, including websites, must be accessible to people with disabilities.
 - Link: https://www.interaction-design.org/literature/topics/usability
 - Link: https://www.usability.gov/what-and-why/accessibility.html

**Term: Product Analytics**
 - Definition: Product analytics refers to capturing and analyzing quantitative data through embedded tools that record how users interact with a product.
 - Link: https://mixpanel.com/topics/what-is-product-analytics/

**Term: Product Roadmap**
 - Definition: A product roadmap is a shared source of truth that outlines the vision, direction, priorities, and progress of a product over time. It is a plan of action that aligns the team around short- and long-term goals for a product and how they will be achieved.
 - Link: https://www.atlassian.com/agile/product-management/product-roadmaps

**Term: Launch**
 - Definition: A software launch can be staged into a soft launch before its final release. In a soft launch, a small release is made to a limited group of individuals for beta testing.
 - Link: https://en.wikipedia.org/wiki/Soft_launch

**Term: Product Management**
 - Definition: Product management concerns defining the why, when, and what of a product. A product manager is responsible for setting a product's vision and strategy. A product manager leads cross-functional teams from a product's conception to launch. 
 - Link: https://www.hotjar.com/blog/product-management/

**Term: Project Management**
- Definition: Project management is the application of knowledge, skills, tools, and techniques to project activities to meet defined project requirements.
- Link: https://www.pmi.org/about/learn-about-pmi/what-is-project-management

**Term: Development**
 - Definition: Software development refers to the process of conceiving, specifying, designing, programming, documenting, testing, and bug-fixing to create and maintain applications, frameworks, or other software components.
 - Link: https://en.wikipedia.org/wiki/Software_development

**Term: User Interface/User Experience**
 - Definition: User interface (UI) is the series of screens, pages, and visual elements, including buttons, icons, typeface, graphics, and images, that enable a person to interact with a product or service. User experience (UX), on the other hand, is the internal experience a person has as they interact with a product or service.
 - Link: https://www.usertesting.com/blog/ui-vs-ux

**Comment by ashlingam** [comment]
1. Progress - Definitions and links associated with key terms, as found on SDLC diagram, along with those terms that provide relevant context. Definitions to be undergo final round of editing and outstanding terms added.
2. Blocks - None
3. Availability - Through 6/3, then exit project.
4. ETA - 6/3

**Comment by ExperimentsInHonesty** [comment]
@Rankazze are you reading a book about the items in the glossary above.  Can we talk about it?

**Comment by alexandrastubbs** [comment]
This has been added to agenda for PM TB.

**Comment by alexandrastubbs** [comment]
Bonnie & Alex have discussed and decided to test the [mocked up version](https://drive.google.com/file/d/1emxhYv9N6KuCVrG-gnqkqHdGnjhm_Qvb/view) of the SDLC in practice. We will then identify which pieces need to be removed and/or adapted based on the site team operating model. 

Issue #602 is ready to be used to test the development model.

**Comment by ExperimentsInHonesty** [comment]
Will not be worked on here.  Have created a new issue on Product Management repo
