### ISSUE TITLE
Update Project Description pages

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1794]
### Overview
We need to remove the "Getting Started" page card from the Project Description pages, and instead move the "Getting Started" resource card to the end of the Resources page card, because the Getting Started card is currently redundant and unnecessary. PM's agreed about this at their Community of Practice meeting.

### Action Items
- [ ] Remove 'Getting Started' page card from the project description pages
- [ ] Add the 'Getting Started' resource card to the end of the Resources page card section
   - [ ] The 'Getting Started' resource card should always automatically be there on project description pages
- [ ] Make sure that the markdown that automatically adds these resource cards doesn't get negatively affected by these changes

### Resources/Instructions
[Example of a project description page](https://www.hackforla.org/projects/100-automations)

<img width="976" alt="Screen Shot 2021-06-20 at 1 04 13 AM" src="https://user-images.githubusercontent.com/67400366/122666904-dc6d0880-d164-11eb-944e-9e61ca3cd6ce.png">

**Comment by aalieu** [comment]
Hi @daniellex0, 

I was able to move the 'Getting Started' card from the 'Getting Started' section into the 'Resources' section for the project description page. There are a few problems though that I was hoping you could address. 

The first one is that in both the 'Getting Started' and 'Resources' section, the code is grabbing the 'Wiki', 'Readme', and 'Overview' cards if they're available which leads to repeating cards in both sections. Is this something we want to keep or should we keep it to one specific section only? 

![image](https://user-images.githubusercontent.com/28831668/124373474-51513f80-dc47-11eb-9eb5-b9e2ea7fefef.png)

The second one is that for the projects that don't have 'Wiki', 'Readme', or 'Overview' – Undebate(https://www.hackforla.org/projects/undebate) is an example – after moving the 'Getting Started' card to the 'Resources' section, the 'Getting Started' section is completely bare. 

![image](https://user-images.githubusercontent.com/28831668/124373536-ddfbfd80-dc47-11eb-9865-54e75f0c6c86.png)

Lastly, in the code, there's a section where if there is no 'Getting Started' card for the project page, it will add a button that links you to another page to help make a 'Getting Started' guide. There are a few bugs in the code though where it doesn't always work as intended and will create a button even if there is a 'Getting Started' card already. I was wondering if I should get rid of the button since all it takes is one line of code to add it to all project description pages in the 'Resources' section. 

![image](https://user-images.githubusercontent.com/28831668/124373695-6202b500-dc49-11eb-9a64-37ca174b3457.png)

Let me know if you need any clarifications on any of the problems!

**Comment by aalieu** [comment]
Hey @akibrhast @jbubar,

I was wondering if one of you could answer a question for me!

Am I allowed to edit a .md project file? In my case, some project pages have two 'Getting Started' cards in the 'Resources' section because some projects have a 'Getting Started' value under the links key (or object or whatever the right terminology it is here). The Open Community Survey project is the example project I'm going to use here but I've attached an image of what's in the .md file and what's happening on the page after my code changes. 

![image](https://user-images.githubusercontent.com/28831668/124373839-ad699300-dc4a-11eb-8711-eea69b1d191d.png)

![image](https://user-images.githubusercontent.com/28831668/124373841-b5293780-dc4a-11eb-8a03-b235c44b57d8.png)

So the real question is: 

Am I allowed to remove the 'Getting Started' value from the project .md files that have it in there? I promise it will only be a few projects that I will be editing because the majority of them don't have the 'Getting Started' value in there.

**Comment by daniellex0** [comment]
@aalieu 

1. Keep this in one section only please (Resources)!. That redundancy is why we're getting rid of the Getting Started section

2. Yup, that's why we're actually completely getting rid of the Getting Started section- it shouldn't be on the page at all anymore. Sorry if that wasn't clear! 

3.  Yes please get rid of this button and anything remaining from this Getting Started section on this page. Thank you! (Please just make sure removing it doesn't negatively affect anything else on this page)

**Comment by aalieu** [comment]
@daniellex0 

Got it! Thanks for the clarification – I definitely misunderstood some of the requirements.
