### ISSUE TITLE
Remove additional space from wins-card-mobile.svg within WIns About page (mobile only)

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#1908]
### Overview
Remove the additional 31px of additional space from the `/assets/images/about/wins-card-mobile.svg`. We are currently using this `<svg>` within `pages/about/about-card-accomplishments.html`.

<details>
  <summary>Current About Page (mobile view)</summary>
  <img src="https://user-images.githubusercontent.com/21162229/124348909-81460780-dba1-11eb-8c5b-44a5669cd58d.jpg" />
</details>

<details>
  <summary>About Page (mobile view) figma design</summary>
  <img src="https://user-images.githubusercontent.com/21162229/124348974-bc483b00-dba1-11eb-9b67-e2bc98bb6131.jpg" />
</details>

<details>
  <summary>Current wins-card-mobile.svg</summary>
  <img src="https://user-images.githubusercontent.com/21162229/125109126-cb465600-e097-11eb-8d4f-49a1d0d5ccf6.jpg" />
</details>

### Action Items
- [x] Research removing additional space from a `<svg>`.
- [x] update the `/assets/images/about/wins-card-mobile.svg` to remove the 31px of additonal space
- [x] verify the svg matches the figma design

### Resources/Instructions
- [/assets/images/about/wins-card-mobile.svg](https://github.com/hackforla/website/blob/gh-pages/assets/images/about/wins-card-mobile.svg)
- [My previous research from pull request 1870](https://github.com/hackforla/website/pull/1870#issuecomment-875169026)
- [SVG tutorial - review so you know what is going on in the svg](https://flaviocopes.com/svg/)
- [MDN - svg `viewBox` attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox)
- [CSS Tricks - Using SVG](https://css-tricks.com/using-svg/)
- [remove padding from svg](https://stackoverflow.com/questions/14299571/removing-padding-from-svg)
- findings on comment down below

**Comment by anonymousanemone** [comment]
Here are my findings laid out. Please read! (And please help)
![image](https://user-images.githubusercontent.com/86015625/125218083-02269280-e277-11eb-9d32-7018b8890f85.png)

**Comment by jbubar** [comment]
@anonymousanemone this was so entertaining to read! you might be the next xkcd.

Ok this is super janky but... going off your negative padding idea...
you can do something like
```css
.wins-card-mobile img{
    margin-left: -20px;
    width: calc(100% + 10px);
}
```

But I think it is mostly because you just need a new img.. that img has a lot of extra space around the card. maybe get an svg of the wins card without the box shadow and add the box shadow on using css?

Its up to you.. but thanks for giving us an opportunity to give our 2 cents

**Comment by Aveline-art** [comment]
Fully agree with @jbubar. That image was great.

Jumping off of the new image idea, I have looked into [the history ](https://github.com/hackforla/website/pull/811) of [that page ](https://github.com/hackforla/website/issues/614). (Fun fact: I had to recreate the original folder in my own version of the directory to see the history since the original about-us folder was renamed to about). It seems that the original image was there since creation, and the creator of the page had a preference for SVGs. If you decide to recreate the image [here ](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Tools_for_SVG)is a list of tools for creating SVGs. Or you can lift the Figma design and use a png file.

In any case, good job for sticking at this for so long.

Edit: Went on a bit of a rabbit-hole, and found this [StackOverFlow ](https://stackoverflow.com/questions/17883655/svg-shadow-cut-off)that might help?

**Comment by anonymousanemone** [comment]
Progress: Submitted pull request, but received request for changes
Blockers: Unable to work on issue recently, needs help with how to build a tablet css class.
Availability: Unable to work on issue this entire week
ETA: Around the end of next next week

**Comment by anonymousanemone** [comment]
I've centered the image for "below tablet" which is when the screen is under 768px, but should I also center the image for when it is "bigger than tablet" but less than desktop? Here's how it looks:
Below tablet: 
![image](https://user-images.githubusercontent.com/86015625/127528782-aa628e6b-46b5-4723-8e98-7b5f97757064.png)
Over tablet: 
![image](https://user-images.githubusercontent.com/86015625/127528797-b1bd8138-1052-42ba-984c-a5a62786e90f.png)

**Comment by anonymousanemone** [comment]
Progress: Made hopefully last commit
Blockers: Waiting on review
Availability: 5 hrs
ETA: Should be done
Pictures: in pr
