### ISSUE TITLE
Wins Page Responiveness - Mobile to Desktop

### ISSUE THREAD

**Issue by Abel-Zambrano** [hackforla/website#1985]
### Overview
"see more” is unresponsive when going from mobile to desktop view (must be clicked in mobile) and turns to "see less" when opened in mobile and changing to desktop screen

### Action Items
- [ ] Fix onclick event listener for "see more"
- [ ] Fix "see less" to only be shown after "see more" has been clicked.

### Resources/Instructions
[Wins Page](http://localhost:4000/wins/)

IMPORTANT!!
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)

**Comment by Sihemgourou** [comment]
Hey @Abel-Zambrano your issue is not on the project board, do you want to put it there ?

**Comment by Abel-Zambrano** [comment]
Hey @Sihemgourou I just added this issue to the project board. Thank you for reminding me.

**Comment by ExperimentsInHonesty** [comment]
@Abel-Zambrano 
- [ ] Please fix the link  - you have linked to resources in the body of the top part, but it goes to a local host url, which doesn't work from here.  
- [ ] Please fix the Overview - it is not a user story (we need to do X for Y reason)
- [ ] Please add animated gif to demonstrate what you are saying, because its not clear.

**Comment by Abel-Zambrano** [comment]
Hey @jbubar 

I know you have been working on this feature recently, any chance you fixed this issue already? I don't see the bugs anymore.

**Comment by jbubar** [comment]
Yes. I believe I did. This was fixed by #1954
