### ISSUE TITLE
Discussion to merge `wins-feature-1` branch

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#2138]
### Overview 
We need to determine whether we merge the `wins-feature-1` branch so that we can stop using feature branch instructions. The wins page is ready to merge now, but we should have a consensus to move forward with merging `wins-feature-1` branch.

### Action Items
- [ ] Discuss `benefits` of merging `wins-feature-1` branch
- [ ] Discuss `setbacks` for merging `wins-feature-1` branch
- [ ] Discuss the topic during a Front-End or Back-end meeting for further feedback
- [ ] Come to a consensus within the dev team about whether to merge the `wins-feature-1` branch

### Resources
#2135

**Comment by macho-catt** [comment]
- First bullet point for reasons not to merge can be fixed by this PR: #2144

**Comment by adam-abundis** [comment]
From @jbubar 5 days ago:

# Reason to merge:
- the wins-feature-1 wins page is better in its current state then the current production
- everything on the wins-feature-1 page works and looks good
- only need minor touch ups
- will create a lot of new issue opportunities
- people do not have to use the feature branch anymore

# Reason to wait to merge:
- ~~the inert.js.map file error is annoying~~ resolved by #2144 
    - ~~we need it for accessibility~~
    - ~~the error does not break anything~~
- the tablet expanded view is funky

**Comment by adam-abundis** [comment]
@hackforla/website-merge It seems like the big 3 remaining tasks are:
1.  Refactor CSS Styling for Wins page(visual touch-ups)
2. fix some JavaScript logic for modals, see more/see less functionality
3. Move from google form to internal form at https://hackforla.org/share-your-wins (which is live, but broken)

Task 3 (wins form) is going to take some time, but the page is still functional with a Google form for now. We can complete tasks 1 (improve styling) and 2 (JS logic) after we merge the `wins-feature-branch`. I think it is time we show what improvements we have made to the Wins page and because we don't really need a feature branch for the Wins page as of right now.

My vote would be for merging. Please let me know if you agree team @hackforla/website
