### ISSUE TITLE
Wins submission issue formatting

### ISSUE THREAD

**Issue by sobe-an** [hackforla/website#2160]
### Overview
All automatically generated issues need to have the complete set of required labels so that we have consistency across all issues

### Action Items
- [x] The automated issues with the title "Review Needed - New Wins Form Submission" need to have the following labels automatically added"
   - [x] role: product
   - [x] p-Feature: Wins Page
   - [x] good first issue
- [x] remove the following label
  - [x] Role: Administrative
- [x] identify if any automations other than this one use Role: Administrative and bring this up to PMs so that they can identify proper role.
   - [x] if no other automations use it, remove the role label.  No one wants to signup to do administrative tasks, so they will never get done if we call them that.

### Resources/Instructions
Ex: Submission issue https://github.com/hackforla/website/issues/2142

**Comment by macho-catt** [comment]
@sobe-an @ExperimentsInHonesty 
This is implemented as part of my moving the wins to the admin drive.
#2336 is an example where the labels are updated. I kept the "new-win-submission" label. Do we want this removed as well?

Currently there are no other automations that use the "Role: Administrative" label, but there is one issue that uses it: #2264

Also picking this issue up because currently the code for the wins API is limited to leads.
Thanks

**Comment by macho-catt** [comment]
Completed, closing the issue
