### ISSUE TITLE
Update Donate Permalinks

### ISSUE THREAD

**Issue by mgodoy2023** [hackforla/website#2203]
### Overview
We need to update the link for the 'Donate' button on the website. Currently it redirects to the Code for America donate page but it needs to redirect to the [Hack for LA Donate page](https://www.hackforla.org/donate). Afterwards, the [redirection](https://github.com/hackforla/website/blob/gh-pages/redirections/donate.md) link for Code for America needs to be updated to avoid conflicting permalinks.

### Action Items

- [x] Update the permalink  in the [donate.html](https://github.com/hackforla/website/blob/gh-pages/redirections/donate.md) file from '/donate' to '/donate/'
- [x] Update the [donate.md](https://github.com/hackforla/website/blob/gh-pages/redirections/donate.md) file so it does not conflict with the updated permalink
    - [x] Change the title from 'Donate' to 'CodeForAmerica'
    - [x] Change the permalink from '/donate/' to '/codeforamerica/'
    - [x] Change name of the md file from 'donate.md' to 'codeforamerica.md'
- [x] Ensure in your local environment that the new links work and point to the correct urls.

### Resources/Instructions
[donate.html](https://github.com/hackforla/website/blob/gh-pages/redirections/donate.md)
[donate.md ](https://github.com/hackforla/website/blob/gh-pages/redirections/donate.md)
[Jekyll Permalinks](https://jekyllrb.com/docs/permalinks/)

**Comment by ExperimentsInHonesty** [comment]
Special note for @Aveline-art  and @abuna1985 and @mgodoy2023  More details behind this issue:
If we delete the redirect anyone who types hackforla.org/donate/ (the url with a end slash) ends up at the 404 page, but then they could just click the donate button on the page.  See https://www.hackforla.org/getting-started/ as example.  This of course brings up the question, if we should have redirects for all our pages in case someone uses an end slash or if we can figure out another way to solve that.

Issue will be rewritten by @mgodoy2023 to remove redirect and edit the donate-button html file
https://github.com/hackforla/website/blob/gh-pages/_includes/donate-button.html

**Comment by Aveline-art** [comment]
@ExperimentsInHonesty From just testing the [events page](https://www.hackforla.org/events/), we can fix this by adding end '/' to the permalinks.

Compare permalink front matter for the [events page ](https://github.com/hackforla/website/blob/gh-pages/pages/events.html)vs the [getting started page](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html).

The donate page is a little trickier, since '/donate' leads to our in-house donate page, and '/donate/ leads to a redirect. The simplest fix is to rename the redirect to something else (hackforla.org/coa-donate?). Then we can have '/donate/' lead to the in-house donate page.

P.S. We also need to find out where the current redirect is being used so we can replace that with our new redirect link.
P.P.S. We can also open issues to scroll through all of our pages that lack the end '/' and add the slash.

**Comment by macho-catt** [comment]
@abuna1985 @ExperimentsInHonesty @Aveline-art I suggest that for this particular issue, we can rewrite it to update the permalink for the [donate page](https://github.com/hackforla/website/blob/gh-pages/pages/donate.html) to become '/donate/' instead (as Ava) suggested. Then, change the permalink in this [file](https://github.com/hackforla/website/blob/gh-pages/redirections/donate.md) to '/codeforamerica/' for the time being. This way we keep the redirection to that url (without deleting the md file) and we can decide if we want to revise that in the future.

After the issue is rewritten we can add the label 'ready for milestone.'
