### ISSUE TITLE
Wiki needed to prevent duplicate style classes

### ISSUE THREAD

**Issue by averdin2** [hackforla/website#2210]
### Overview
As outlined in issue #1901, there are places in the codebase where the same style classes are copied and pasted in multiple different files. In order to prevent this in the future, we need to have some documentation in the wiki that documents how to proceed when duplicate styles are encountered in the code and what we can do to fix them.

### Action Items
- [x] Come up with a procedure for dealing with duplicate style classes in the codebase.
- [x] Find a suitable place within the wiki for this documentation.
- [x] Write a section in the wiki detailing your procedures.

### Resources/Instructions
See issue #1901 for some more information.

**Comment by abdiaz2018** [comment]
Availability: 6 hours
ETA: saturday night

**Comment by plang-psm** [comment]
i. Availability: 6hrs
ii. ETA: 10/16/22

**Comment by plang-psm** [comment]
Blocker: I believe this may have already been completed. Found in the Wiki as [Styling with Reusable Components](https://github.com/hackforla/website/wiki/Standardized-Components).

**Comment by plang-psm** [comment]
See link below for the procedure created in the Wiki. @hackforla/website-merge 

https://github.com/hackforla/website/wiki/How-to-deal-with-duplicate-style-classes

**Comment by arpitapandya** [comment]
Removing inactive label as @plang-psm provided an update for the issue and reached out that he might not be 100% active for about 2 weeks/more due to a dental problem.
I am unable to review this week.

**Comment by blulady** [comment]
@plang-psm I am so sorry it took me so long to get to reviewing this issue.
You did an **OUTSTANDING** job creating this page. Your Wiki page is through, clear and direct. 
However I don't see any explicit instructions on what to do when a developer comes across a duplicate style class. Maybe just one more section that explains what happens when you come across a duplicate style class. If you find it helpful maybe dig around to find a class that has been duplicated and walk through the steps you would take to eliminate the duplication. If you do find an error please give merge team a heads up so we can create an issue out of it so someone can use your Awesome guide to eliminate it.
Thank you!!!

**Comment by plang-psm** [comment]
Hi @blulady , thank you for the review! My apologies for not being more direct, but the first two sections below the overview are supposed to be the steps a developer should follow when coming across a duplicate style. It covers checking to see if the component has already been made and simply needs implementation, or if it has not, then the developer should move onto how to create a reusable component. That section covers how to add the file, naming conventions, and the styles generally used. I had no luck finding a duplicated style so I used the button and page card components because they cover most of the styles we'd generally use on a style (base, size, color, and page-specific). I'll go back and edit some items to highlight the process a bit better.

**Comment by plang-psm** [comment]
@blulady I went ahead and changed a few things, including the format to make the instructions much more clear. Please let me know if this clarifies the instruction concern. https://github.com/hackforla/website/wiki/How-to-deal-with-duplicate-style-classes

**Comment by plang-psm** [comment]
Progress: Finished edit the document
Blockers: None
Availability: 2hrs
ETA: Completed -- awaiting review
Pictures (optional): N/A

**Comment by plang-psm** [comment]
The Wiki page has been redone and pending review. https://github.com/hackforla/website/wiki/How-to-deal-with-duplicate-style-classes

**Comment by jdingeman** [comment]
Reviewed dev's wiki page - requested a few grammar/spelling changes and issue will be ready to close without PR.

**Comment by plang-psm** [comment]
The grammar/spelling changes have been made and this issue is ready to be closed.
