### ISSUE TITLE
Fix typo for Undebate under Accomplishments: from engagment to engagement

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2347]
### Prerequisite
Please make sure you have read the **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue

### Overview
We need to keep code quality standards high on this project so that we can model best practices for new developers and team pride.  

### Action Items
- [x] Correct the spelling mistake in the Accomplishments section of the About page by changing "engagment" to "engagement" in line 36:
From
```
    Hack for LA has provided labor to this important tool which continues to increase engagment at local elections 
```
To
```
    Hack for LA has provided labor to this important tool which continues to increase engagement at local elections 
```
- [x] Ensure that the [corresponding webpage](https://www.hackforla.org/about/#accomplishments) reflects the spelling fix

#### File and Code links you will need to review this issue
- Directory to find the page in once you have it in your IDE: ```gh-pages/_data/internal/accomplishments.yml```

- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/f015a891265d56372f87e1adb1e1b6088dcfac06/_data/internal/accomplishments.yml#L36

#### Backround information about the Jekyll framework (optional reading)
[Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
[Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

**Comment by Brymmobaggins** [comment]
kindly assign this issue to me

**Comment by adam-abundis** [comment]
@Brymmobaggins Thank you for showing interest in this issue. We don't actually "assign" issues. In order to claim issues, you can join a volunteer onboarding meeting and can be added to the Hack for LA organization/website repo. Feel free to check out our Getting Started page (https://www.hackforla.org/getting-started) and our guide to contributing (https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) to see how our team works. Let me know if you have any other questions.
