### ISSUE TITLE
Adding additional font sizes and weights to HfLA Design System - Feasibility/Desirability Assessment 

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2361]
### Overview
As designers, we need to have more flexibility in terms of font sizing and weight within the HfLA Design System. 

### Action Items

- [x] Review current Design System font size/weight options and guidance around usage.
- [x] Assess which are currently being used, where, and with what frequency on the site. 
- [x] Determine if and where additional font size and/or weight options would be beneficial for the site, considering the impacts on accessibility, informational hierarchy, and visual design. 
- [x] Suggest, based on your research, potential new additions to our Design System font options.
- [x] Create 2-3 Figma mockups to share with the team showing the potential implementation of these new font sizes on several pages of the site, so we can see an example and have a visual reference to discuss. 

### Resources/Instructions
[Figma - HfLA Design Sysytem ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
[Font Weight Audit](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18792%3A126489)

**Comment by Stephen-Parent** [comment]
Progress: Reviewing existing font weights
Blockers: 
Availability: 6 hrs
ETA: Dec 18
Pictures:

**Comment by Stephen-Parent** [comment]
Progress: Reviewed font usage and found the main problems are too many font styles and some consistency issues. Consider removing Title 5 because it sees limited use. Title 6 is redundant/unused. Title 7 should be removed because it shares the settings of the button style. Paragraph 4 should also be removed because it too sees little to no use.
Blockers:
Availability:
ETA:
Pictures: For now, to view the full audit that I did, see the Communities of Practice page in the Figma file.

![image](https://user-images.githubusercontent.com/94029486/146472659-77d532d1-a1e1-4b59-8055-b0a3a62870ca.png)

**Comment by IsaacDesigns** [comment]
@Stephen-Parent These are very helpful findings. I will make an issue to revise the Font Styles in Figma screens and style guide based on your recommendations. I'm moving this audit to the Design System page.

**Comment by ExperimentsInHonesty** [comment]
@IsaacDesigns I am adding this to our agenda doc for our next meeting

**Comment by ExperimentsInHonesty** [comment]
Isaac you can close this issue, once you revised issue https://github.com/hackforla/website/issues/2601 to addresses the Light Regular Medium Bold found on this comment https://github.com/hackforla/website/issues/1797#issuecomment-1001077278

**Comment by ExperimentsInHonesty** [comment]
#2601 has been updated as requested.  This issue is good to be marked as done.
