### ISSUE TITLE
Update HelloGov Slack link

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2444]
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to ensure that links on the website resolve properly and are up to date.

### Action Items
- [x] Change the GitHub link for HelloGov so it resolves to the correct url
    - **Line 33** under `_projects/hellogov.md`

From:
```
url: 'https://hackforla.slack.com/archives/CMER3R1RD'
```
To:
```
url: 'https://hackforla.slack.com/messages/CDA23KHKP'
```
- [x] Ensure that clicking the Slack link from the [projects page](https://www.hackforla.org/projects/) and [HelloGov page](https://www.hackforla.org/projects/hellogov) both resolve to the new address

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/hellogov.md`
- [Projects page](https://www.hackforla.org/projects/)
- [HelloGov page](https://www.hackforla.org/projects/hellogov)
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/8b2585f5cd0ac7c5ff568b7d790832f9935a5a01/_projects/hellogov.md#L33

**Comment by lindseyindev** [comment]
Availability for this week: 5 hours
My estimated ETA for completing this issue: by Sunday 12/12

**Comment by ExperimentsInHonesty** [comment]
@lindseydotdev Hi!  So I noticed you said you had 5 hours available this week, and thought you would be done by Sunday (today), can you provide an update with what happened.  

If you get stuck, the team meetings time are the time to discuss things.  Here is where you would place your issue so that it can be reviewed during the meeting:
**Development team meeting discussion items 🤔** 
https://github.com/hackforla/website/projects/7#column-14434559

**Comment by lindseyindev** [comment]
@ExperimentsInHonesty pull request submitted waiting for review! Sorry for the delay I have been adjusting to a new dev environment and that was my only blocker
