### ISSUE TITLE
Implement the new design for the top navigation bar

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2455]
### Dependency
- [x] https://github.com/hackforla/website/issues/3023
- [x] https://github.com/hackforla/website/issues/3026 

### Overview
We need to implement the [new figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14120%3A92883) for our main navigation bar so it's more user friendly.

<details>
  <summary>Click here to see current HfLA navigation bar</summary>

![tempsnip](https://user-images.githubusercontent.com/48004150/140571688-65864028-e3af-4f1e-9db8-ee106e1c7fc3.png)

</details>

<details>
  <summary>Click here to see the proposed navigation bar (Figma design)</summary>

![work](https://user-images.githubusercontent.com/48004150/140572004-9722e771-4f9e-4a2c-855f-56d5883c1bff.PNG)

</details>

### Note: Feature Branch
The pull request created from this issue should be pushed into a feature branch called "feature-homepage-launch." Please note this [wiki article](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) on how to work off of a feature branch.

### Action Items
- [x] Read the wiki article: [DR:-Capitalization-of-menu-items-in-nav-bar-and-header](https://github.com/hackforla/website/wiki/DR:-Capitalization-of-menu-items-in-nav-bar-and-header)
- [x] Create data files (if they don't exist yet) with the column title (Our Work, join Us, Get in Touch, etc) and the list of links that go in each column
    - [x] The data can be stored under `_data/navigation`
    - [x] The main navigation bar should dynamically get the data using liquid instead of being statically rendered
- [x] Modify the existing navigation bar based on the new Figma design
- [x] Remove the current red hover-over text transformation from the top-level menu items
- [x] Implement a new dropdown for each top-level menu items
    - [x] Hover-over of menu items should reveal the dropdown menus, with top nav text remaining unchanged
    - [x] Ensure that the dropdown from the navigation bar has 93% opacity
    - [x] Ensure to implement the hover state according to the figma design
- [x] Check all the links in the top navigation work and go to the correct webpage or section on a webpage
- [x] Create a PR that is merging into the feature branch called "feature-homepage-launch". See [How to work off of a feature branch wiki article](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) for detailed instructions.

<details>
  <summary>New hover-over menu items</summary>

![menu](https://user-images.githubusercontent.com/48004150/140572951-6cb80a92-e4bb-4a0a-a489-53cf9f53fee6.PNG)

</details>

<details>
  <summary>Remove red hover-over text for top level menu items</summary>

![hover](https://user-images.githubusercontent.com/48004150/140573019-93e7236b-f87a-43e8-900a-45d4c47eee4f.PNG)

</details>

<details>
  <summary>Dropdown has 93% opacity</summary>

![dropdown](https://user-images.githubusercontent.com/48004150/140573048-01220f21-bce0-4657-9964-ce6074f081c8.PNG)

</details>

### Resources/Instructions
[Feature branch wiki article](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
[Figma - New navigation bar design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14120%3A92883)
[Navigation data directory](https://github.com/hackforla/website/tree/gh-pages/_data/navigation)
Click below to see main nav bar
https://github.com/hackforla/website/blob/66f89317e84517f4bbbd29911bb21aeddb8bb2d3/_includes/main-nav.html#L1-L14

Related issues:
- https://github.com/hackforla/website/issues/3023
- https://github.com/hackforla/website/issues/3026
- https://github.com/hackforla/website/issues/2802

**Comment by kristine-eudey** [comment]
@macho-catt I just updated the order of menu items in the "Join Us" section of the top nav to match the order they appear on the Join Us page.

**Comment by IsaacDesigns** [comment]
@ExperimentsInHonesty is the new menu still relevant? You had told me that we don't have a Get IN Touch page on Wednesdays meeting. The menu items are also not consistent with the new sitemap and Home page design.

**Comment by answebdev** [comment]
ETA: 3/23/2022 (end of day)
Availability: 6 hours

**Comment by answebdev** [comment]
**Progress Report**

- Progress: Have redesigned the navbar according to the figma design (i.e., navbar items Our Work, Join Us, Get in Touch, etc. with dropdown items) and got most of the basic styling done (though still need to finish some styling)
- Blockers: I got the redesigned navbar dropdown working, but all of the dropdown items are in one separate `.yml`. file, and they should be in separate files. I am currently stuck on getting this to work (i.e., they are in now in separate files but my blocker is getting everything to work)
- Availability: 6 hours
- ETA: 3/30/2022

**Comment by answebdev** [comment]
- Progress: Worked on and finished CSS according to Figma design; need to work on CSS for smaller screen sizes
- Blockers: Though I mostly worked on the CSS since the last Progress Report, I still need to work on getting the dropdown items into in separate `.yml` files and getting this to work (as of now, the dropdown items _are_ in separate `.yml` files, but my blocker is getting everything to work)
- Availability: 6 hours
- ETA: 4/6/2022

**Comment by JessicaLucindaCheng** [comment]
@answebdev Do you need help with your blocker?

**Comment by answebdev** [comment]
@JessicaLucindaCheng Yes, I think I do. Basically, I have the navbar redesign finished and working according to the Figma designs (see below). But what I'm stuck on is getting the dropdown items into separate `.yml` files like we previously talked about. As of now, all of the navbar items and their dropdown items are in one file (`main.yml`), and it works, as you can see below. But when I tried creating separate `.yml` files for each of the navbar item's dropdown items, I can't get it to work right. I've tried using collections as you first suggested, and tried looking at the other example files, and trying a bunch of other things, but I still can't get the dropdown to work right when I try putting the items in separate files.

The anchor tags also need to be sorted out. I was planning on writing a comment when I finished about creating an issue to deal with the anchor tags, as discussed in a previous meeting with Bonnie, but since I'm stuck on this, I haven't gotten to that yet.

<details>
  <summary>Click here to see navbar redesign</summary>

![navbar_redesign](https://user-images.githubusercontent.com/36783010/162077720-0ed00cb7-3d47-4c4e-a737-a28078548677.gif)

</details>

Right now, this is where I'm stuck on, and this is what the navbar looks like when putting the navbar items and their dropdowns in separate `.yml` files:

<details>
  <summary>Click here to see current blocker state</summary>

![navbar_stuck](https://user-images.githubusercontent.com/36783010/162079728-d4409905-3b22-4bce-94c0-5736d4525f5c.gif)

</details>

**Comment by JessicaLucindaCheng** [comment]
@answebdev Don't worry about writing issues for the anchors because I am writing them already. I will provide you with what the anchor links should be so you can still add them to your code (but since the anchors aren't implemented on the webpages it just won't jump to the specified sections).

I'll get back to you on your blocker about the separate yml files for the menu and let you know about the anchor links most likely by tomorrow.

**Comment by answebdev** [comment]
@JessicaLucindaCheng Okay, I'll wait for the anchor tags so that they can at least be in the code. Okay, let me know. Thank you!

**Comment by JessicaLucindaCheng** [comment]
@answebdev Can you push your code to your topic branch on your remote forked repo? This way I can see your code and try to help you better.

Also, here are the links for the anchors. The links won't jump to the sections yet because that hasn't been implemented on the pages but they should go to the webpage for now. You'll need to modify them for your purposes since I don't think the menus will use the full url.
- https://www.hackforla.org/#get-in-touch → This is for the Contact Us submenu item
- https://www.hackforla.org/join#advise
- https://www.hackforla.org/join#volunteer
- https://www.hackforla.org/join#partner
- https://www.hackforla.org/toolkit#guides
- https://www.hackforla.org/toolkit#external-resources

**Comment by answebdev** [comment]
@JessicaLucindaCheng Thank you. I've pushed the code to my topic branch on my forked repo. Here is the link to my topic branch: https://github.com/answebdev/website/tree/navbar-redesign

What about the anchor link for "Submit Your Pitch" for the Join Us submenu? Would it be "/#submit-your-pitch"?

**Comment by JessicaLucindaCheng** [comment]
@answebdev Submit your pitch is the current way it opens for the Submit your pitch button now.

I'll try to take a look at your code before tomorrow's meeting and comment in this issue. However, feel free to bring it up in the meeting if we have time for discussion.

Edit: I didn't get a chance to look at your code yet but I will later today.

**Comment by JessicaLucindaCheng** [comment]
Updated ETA for trying to figure out blocker: Tue, April 12, 2022

Edit: Sorry, going to delay this by a day. New date is Wed, April 14, 2022

**Comment by answebdev** [comment]
**Progress Report**

- Progress: Have finished everything (except for the blocker), and have added the anchor links to the `.yml` files as per Jessica's previous comment.
- Blockers: I got the redesigned navbar dropdown working, but all of the dropdown items are in one separate `.yml`. file, and they should be in separate files. I am currently stuck on getting this to work (i.e., they are in now in separate files but my blocker is getting everything to work). Currently getting help from Jessica (I have pushed my code to my topic branch on my remote forked repo), who is helping out by looking at my blocker, and will continue as soon as I hear back.
- Availability: 6 hours
- ETA: 4/20/2022

**Comment by JessicaLucindaCheng** [comment]
@answebdev I took a look at your code and have a few notes.
- It looks like you created your topic branch off of gh-pages and not "feature-homepage-launch". You should base your topic branch off of "feature-homepage-launch" because that is what your pr will be merged into. See the Details section above for instructions.
- For your blocker,
  - The files you have in navsub directory should look more like https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/ui-ux.yml in terms of structure, specifically
    - For the submenu links, look at 
      https://github.com/hackforla/website/blob/a8a0a36c3a0f50d94e1af5b8f16867d302a9d2a9/_data/internal/communities/ui-ux.yml#L28-L32
    - For the main menu item names you have in main.yml, can probably be incorporated into the files in the navsub directory. Then you won't need to use main.yml.
    - I used this to help with figuring out how to show the submenus in a certain order: https://stackoverflow.com/a/9126294
      - You will need to have another field in each of the submenu files in order to use this method.
      - Also, I don't know if this is the most efficient way to implement this. Thus, if you find a better way to do this, feel free to do that.
- FYI: This may or may not be helpful but I think it's something good to know: [Whitespace control in Liquid](https://shopify.github.io/liquid/basics/whitespace/)

**Comment by JessicaLucindaCheng** [comment]
@answebdev Could you please change the following 2 menu items to have the following capitalization?
- `Submit your Pitch`
- `Get in Touch`

This decision came from https://github.com/hackforla/website/issues/2481#issuecomment-1100764836

**Comment by answebdev** [comment]
> @answebdev Could you please change the following 2 menu items to have the following capitalization?
> 
> * `Submit your Pitch`
> * `Get in Touch`
> 
> This decision came from [#2481 (comment)](https://github.com/hackforla/website/issues/2481#issuecomment-1100764836)

Okay, got it.

**Comment by answebdev** [comment]
**Progress Report**

- Progress: Got feedback/help back from Jessica and started addressing some of the feedback: Had previously created my topic branch off of "gh-pages", instead of "feature-homepage-launch", so I have now created my topic branch of of "feature-homepage-launch" and worked on my getting my code into this new topic branch; addressed capitalization as mentioned in a comment; updated the files in my navsub directory so that they are consistent with the other `.yml` files in the codebase in terms of structure.
- Blockers: None yet, as I have just started working on this after receiving feedback
- Availability: 6 hours
- ETA: 4/27/2022

**Comment by answebdev** [comment]
**Progress Report**

- Progress: Got feedback/help back from Jessica and started addressing some of the feedback.
- Blockers: I have been having Docker issues since last week, and have not been able to work on this issue, since I was working on my Docker issue. Got Docker issue resolved, but currently have another issue.
- Availability: 6 hours
- ETA: 5/4/2022 (depending on Docker issues)

**Comment by JessicaLucindaCheng** [comment]
@answebdev Please give a progress report in a comment in this issue that includes Progress, Blockers, Availability, and ETA. See more detailed information in [section 2.5 Reporting progress on your issue in CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#25-reporting-progress-on-your-issue).  If you are taking a leave of absence or a vacation, please also let us know in your progress report.

Also, do you need help with your blocker?

**Comment by answebdev** [comment]
Progress: Started addressing some of the feedback, e.g., adding the anchor links - all that's left is getting it to work with the nav items in separate `.yml` files as opposed to having all the navbar items in one `.yml` file.
Blockers: I was mostly trying get my Docker issue fixed, so I was not able to work on this navbar issue. As of now, my Docker is working, though I'm not sure how I got it to work; it still randomly takes some time before it works, but it eventually works.
Availability: 6 hours.
ETA: 5/11/2022 (depending on Docker issues).

@JessicaLucindaCheng My Docker seems to be working now, though I'm not sure how I got it going, so I wasn't able to post anything about how to fix the issue. It still sometimes takes time to get working, but after a lot of quitting and restarts, it seems to eventually work.

**Comment by answebdev** [comment]
Progress: Redesign is done and working, but I need to get the nav items in separate `.yml` files as opposed to having all the navbar items in one `.yml` file. This is what I've been working on, but have been stuck on getting this to work.
Blockers: Getting the dropdown navbar items to work in separate `.yml` files. Have reached out for help and am currently waiting for feedback.
Availability: 6 hours.
ETA: 5/18/2022 (depending on when I get feedback back)

**Comment by JessicaLucindaCheng** [comment]
@answebdev Sorry for the delay in getting back to you about your blocker. Good job so far on your work on the navigation bar. Here are my suggestions:
- The yml files in `_data/navigation/navsub` have a position, menu, and submenu field. For example for our-work.yml,
  ```
  position: 1
  menu: Our Work
  submenu:
  - name: About Us
    url: /about
  - name: Program Areas
    url: /program-areas
  - name: Projects
    url: /projects
  - name: Our Wins
    url: /wins
  - name: Press
    url: /about#news
  ```
  - The position will help order the menu items
  - The menu will be the main menu item
  - The submenu will contain the submenu items
  - Having the menu and submenu items together will make it easier to iterate through main menu items and their respective submenu items
- For _includes/main-nav.html, the pseudocode logic for iterating through the menu and submenu  items: 
  ```
  for order in (1..4) <!-- This is a for loop that iterates through the numbers 1 through 4, inclusive -->
    for loop iterating through yml files in _data/navigation/navsub
      if the "position" field in the yml file is equal to "order"
        then
          display the main menu item
          for loop iterating through the submenu items in a yml file
            display each submenu item
  ```
  If what I wrote is confusing, I can go over this with you during meeting time; just let me know.
- Also, make sure the urls for the following submenu items are as follows:
  - url for `Press` is `/about#news`  
  - url for `Volunteer with Us` is `/join#volunteer`
  - url for `Partner with Us` is `/join#partner`
  - url for `Advise Us` is `/join#advise`
  - url for `Guides` is `/toolkit#guides`
  - url for `External Resources` is `/toolkit#external-resources`

**Comment by answebdev** [comment]
Progress: Updated `.yml` files for submenu navbar items (added "position", "menu", and "submenu" fields) to make it easier to iterate through main menu items; updated URLs for submenu items to the correct URLs
Blockers: Not yet, as I just started addressing what was in the feedback
Availability: 6 hours.
ETA: 5/25/2022

**Comment by answebdev** [comment]
Progress: Didn't have much of a chance to work on this since my last progress report due to working on tasks for job applications and focusing on other tasks (PR reviews and issue creation)
Blockers: Not yet, as I just started addressing what was in the feedback
Availability: 6 hours.
ETA: 6/1/2022

**Comment by answebdev** [comment]
This message is to say that I'm going to be taking a week off starting today...I need to get a lot of things done for work.

**Comment by answebdev** [comment]
Progress: Took a week off to get things done for work, so I did not work on this issue.
Blockers: Not yet, as I just started addressing what was in the feedback
Availability: 6 hours.
ETA: 6/15/2022

**Comment by answebdev** [comment]
Progress: Did not have time to work on this issue this past week due to having a lot to do for work.
Blockers: Not yet, as I just started addressing what was in the feedback
Availability: 6 hours.
ETA: 6/22/2022

**Comment by answebdev** [comment]
I will be leaving the HfLA team, so I am moving this issue from ‘In progress’ to the ‘Prioritized Backlog’ on the Project Board. The following are notes for the next developer:

Out of the 10 Action Item tasks above, 8 of them have been completed. The following Action Items need to be completed (see Action Items section above in the issue):

 - [ ] The main navigation bar should dynamically get the data using liquid instead of being statically rendered
 - [ ] Create a PR that is merging into the feature branch called "feature-homepage-launch".

The completed tasks are currently in the `navbar-redesign-branch` branch. The main navigation items (Our Work, Join Us, Get in Touch, Toolkit) are in `_data/navigation/main.yml`. For the dropdown navigation items, as per the comments above, there is a separate file created for each of the main navigation items. Each of the separate files contain the dropdown items for each main navigation item. These files are inside the folder `_data/navigation/navsub`. The `navsub` folder contains four `.yml` files, each containing the dropdown items for each of the main navigation items: `get-in-touch.yml`, `join-us.yml`, `our-work.yml`, and `toolkit.yml`.

Everything in this issue has been completed except for one thing. Currently, when you hover over the navbar where the main navigation items should be, you can see the dropdown appear as it should. However, neither the main navigation items nor the dropdown items can be seen (see image below). Previously, when all of the navigation items where all in one `.yml` file, everything worked as it should. But after creating separate `.yml` files for each set of dropdown items (as noted above), the items do not show. This is the current state of this issue. This is all that needs to be done. Once this is addressed and both the main navigation items and the dropdown items can be seen, the issue will be finished, and then all that needs to be done is to create a PR that is merging into the feature branch called "feature-homepage-launch".

To continue working on where this issue has left off, go to `_includes/main-nav.html`. This is the file I was last working in. I believe this is what needs to be coded correctly to get everything working.

<details>
  <summary>Current State of Dropdown Menu</summary>

![issue](https://user-images.githubusercontent.com/36783010/175163683-b617d7d6-552f-4c85-b9b6-825d7688e86b.jpg)

</details>

**Comment by ExperimentsInHonesty** [comment]
@phuonguvan we need to discuss this issue because it shows a header that is not consistent with the designs in red on the Figma page for the homepage launch https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9477%3A88938 - Please find all the issues related to the header and footer, and the related Figma pages and add all of that to our agenda so that we can discuss at our next meeting

**Comment by ExperimentsInHonesty** [comment]
This issue might need a redesign.

**Comment by ExperimentsInHonesty** [comment]
- [ ]  A note will need to be added to the top of this issue before it's put back into the prioritized backlog.
```
There is one design note regarding the menu from the [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?type=design&node-id=14120-92883&mode=design&t=71lJxEmeOpmjHX3O-0) design.  The figma design for the menu does not list the sections under Join Us in the order that they appear on the [Join us page](https://www.hackforla.org/join).  When the next developer works on this issue, they should list the items under Join Us in the following order with the following capitalization:
1. Advise Us
2. Volunteer with Us
3. Partner with Us
4. Submit Your Pitch
5. Donate
```

**Comment by ExperimentsInHonesty** [comment]
@hackforla/devops-merge The developer who worked on this never made a commit. The code changes are located in a branch on his fork of the repo
https://github.com/answebdev/website/tree/navbar-redesign-branch.  Do we think a developer can pick up where he left off, or do we need to uncheck everything and have someone start again?

**Comment by ExperimentsInHonesty** [comment]
After discussion with the Merge team we decided to hide all the information about the prior commits and let the new developer start from scratch because 
- the version that this developer has done is not on a branch on the github.com/hackforla/website repo but rather on his own repo https://github.com/answebdev/website/tree/navbar-redesign-branch and we can't catch it up. 
- the code has not been reviewed, there are concerns about using it as a reference for code quality.
- we don't have the explicit permission of a pr, which would allow us to use the original developer's code while providing credit.

**Comment by danajeon** [comment]
i. **Availability:** Mon-Fri 4-7PM EST
ii. **ETA:** 5/3 EOD

**Comment by danajeon** [comment]
I'll be busy for the remainder of this week and next week and won't be able to finish this issue by 5/3 EOD, I've unassigned myself from this issue.

**Comment by ramitaarora** [comment]
i. Availability: Weekdays 9am-12pm
ii. ETA: May 10

**Comment by ramitaarora** [comment]
Progress: I have completed changing the links for the new menu and the new hover look with the underline. I am in the middle of creating the dropdown menu.
Blockers: I am having trouble creating dynamic dropdowns according to the menu items. I need to incorporate a for loop in the code but am unsure of the syntax.
Availability: Weekdays 9am-12pm.
ETA: May 17 latest
Pictures (optional): 

<img width="583" alt="Screenshot 2024-05-10 at 9 08 06 AM" src="https://github.com/hackforla/website/assets/104021517/98684f0a-edda-4154-a2a6-3600586380d2">

**Comment by ramitaarora** [comment]
I am blocked: I have an issue where the toolkit anchor tags are not working, but it seems the "/toolkit/" link itself is not working. When I navigate to "/toolkit/" or "/toolkit", it redirects to "/toolkit/?". I have tried changing the slashes but it has not seemed to work yet.

**Comment by Thinking-Panda** [comment]
@ramitaarora This behavior is probably happening because of the event handlers in `toolkit.js`

**Comment by ExperimentsInHonesty** [comment]
@ramitaarora I moved this issue back to the in progress column since it seems like you got your answer.  If you need more support, please move this issue back to the questions column and add the `ready for merge team` label.

**Comment by t-will-gillis** [comment]
PR #6854 fixes this issue, closing as completed
