### ISSUE TITLE
Update the images on the credits page so they're all the same width

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2456]
### Overview
We need to ensure that the images on the credits page have the same width so the page looks uniform and professional. 

### Action Items
- [x] Adjust the css of the div class that contains the image (.icon-left) so the width is uniform across all images
    - [x] Maintain a proper aspect ratio for the height
    - [x] Adjust the image size as necessary for smaller viewport screens (responsiveness)

<details>
<summary>All individual images should be the same width</summary>

![tempsnip](https://user-images.githubusercontent.com/48004150/140589837-9791fff3-5fba-4ae0-b759-ae3ab24e5bc5.png)

</details>

### Resources/Instructions
[Credits html file](https://github.com/hackforla/website/blob/gh-pages/pages/credits.html)
[CSS file](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_credit-items.scss)
[Credits page](https://www.hackforla.org/credits/)

**Comment by JimGeist** [comment]
1. Progress:  I found that there is a maxwidth attribute tag. The maxwidth downsizes larger images but it does not upscale smaller images. Adding in a wdith tag for the image in the inspector console fixed the image sizes. However, not all the images will have the same 'icon' size width because some of the image files have negative space on either side of the image.
1. Blockers: No difficulties, but I need to hold on this (2456) issue because some rework is needed for [Tooltip with long text cuts off when hovering over wins icons](https://github.com/hackforla/website/issues/2408).
1. Availability: "How much time will you have this week to work on this issue?"
1. ETA: I hope this issue (2456) and 2408 are resolved by Wednesday, Dec. 29, 2021.
1. Pictures: No pictures at this time.

**Comment by JimGeist** [comment]
1. Progress: I found that there is a maxwidth attribute tag. The maxwidth downsizes larger images but it does not upscale smaller images. Adding in a wdith tag for the image in the inspector console fixed the image sizes. However, not all the images will have the same 'icon' size width because some of the image files have negative space on either side of the image.
1. Blockers: None - rework for Tooltip with long text cuts off when [hovering over wins icons](https://github.com/hackforla/website/issues/2408) was completed today.
1. Availability: ~1 - 2 hours
1. ETA: I hope this issue (2456) and 2408 are resolved by Wednesday, Dec. 29, 2021.
1. Pictures: No pictures at this time.
