### ISSUE TITLE
Update Project Profile: [name of project]

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#2473]
### Overview
We need to cleanup the current way for projects to do updates via new issues so that it can be easier for all involved

### Action Items
- [ ] Gather all the information about the various methods
- [ ] Review the template provided by Danielle and Sihem below

### Resources/Instructions
[Current template](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D)
Suggestion:  https://github.com/hackforla/website/issues/2473#issuecomment-965895271

**Comment by ExperimentsInHonesty** [comment]
Suggestion for  project update template
---
Update Project Profile: [name of project] 

---

[ DELETE BEFORE SUBMITTING: Please fill this out and add comments with any up-to-date information about your project below, so that developers on the Hack for LA website team can update your project information. After you submit this new issue, post a link to it on #hfla-site slack channel with this message: "Please place this on the Hack for LA project board with the labels Good First Issue and Front-End"]

### Overview
We need to update the information about the project [INSERT PROJECT NAME] so that it is up-to-date on the Hack for LA website

### Project card
[ Insert url of your project card here before sending - all of their project cards can be found in this folder: https://github.com/hackforla/website/tree/gh-pages/_projects ]

### Action Items

**Devs** (from HfLA website team)
- [ ] Update the project.md file linked above using the information and comments here and posted below (scroll down)
   - [ ] Reference the [project.md file template](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file) for guidance
   - [ ] Every section that is checked off should be left as-is. Any section that is unchecked should have up-to-date information you can add to the project.md file in comments below (scroll further down)

**PMs**
- [ ] Please check off everything that is up-to-date or missing on purpose on your project page (to find your project page, click on your project card on the [homepage](https://www.hackforla.org/)). If any of this information is not correct or missing, please provide the updated information by adding comments on this issue, following the guidelines below:
  - [ ] Title [of project]
  - [ ] description [of project]
  - [ ] image 
    <details>
     <summary>Check Template</summary>

     image:  insert image (png or jpg) here
     alt: 'description of the card image'
     _Card image should be 600px wide x 400px high_
     </details>
   - [ ] image-hero

     <details>
     <summary>Check Template</summary>

     image: insert image (png) here
 
     _Card image should be 1500 px wide x800 px high_
     </details>
  - [ ] Current Project Team** 
      <details>
     <summary>Check Template</summary>

     name: First Last
     role: _Product Manager or other_
     slack: 'https://hackforla.slack.com/team/xxxxxx'
     github: 'https://github.com/githubusername'   
     </details>

  - [ ] links
     - [ ] Github
     - [ ] Slack
     - [ ] Test Site
     - [ ] Demo Site
     - [ ] Site
     - [ ] Overview [find your project's one-sheet [here](https://github.com/hackforla/product-management/tree/master/project-one-sheets) ]
     - [ ] Wiki
     - [ ] Readme
  - [ ] looking [roles project is looking to fill]
     <details>
     <summary>Check Template</summary>

     category: 
     skill: 
     </details>

  - [ ] technologies 
   - [ ] partner 
   - [ ] tools
   - [ ] status (Put false if the page should not be visible)

_**Current Project Team:_   
The following details should be provided in a comment below about any project member who has been actively contributing on your team for at least 1 month, and who is not already listed under "Current Project Team":
- name: First Last
- role: 
- slack: 'https://hackforla.slack.com/team/xxxxxx' **(see Slack note below)
- github: 'https://github.com/githubusername'

_**Slack:_ 
To create a Slack link for each person, search for their slack profile, click on their name; this should give you a popup window with the user's picture, name, and a link to "View full profile". Click on "View full profile". That pane gives you the options message, call, and more. Click on "more" and you should be shown "Copy member ID" followed by the actual id. This is the id you need to use in the slack url, e.g. https://app.slack.com/team/<member_id_here

### Resources

[Template of a Project.md file](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

**Comment by ExperimentsInHonesty** [comment]
Product needs to cleanup this issue so its clearer what to do next.

**Comment by ExperimentsInHonesty** [comment]
I am closing this issue. The details have been recorded in the wiki https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Not-Implemented
