### ISSUE TITLE
Create a copy of the project page with only two filters: technology and language

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2502]
### Dependency
- ~#2488~

### Overview
We need a copy of the project page with only the technology and language filter to ensure that the page filters properly

### Action Items
- [x] Create a new page based off of the current [project page](https://www.hackforla.org/projects/)
    - [x] The new page's permalink should be set to `/projects-check/`
    - [x] The page should only be reachable via permalink
- [x] For the newly created page, update the dropdown filters so there are only two: technologies filter and language filters
    - [x] The technologies filter should filter based on a specific technology
    - [x] The languages filter should filter based on a specific language
    - [x] You may use the ideas of the current existing code: [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- [ ] Ensure the new page works, and it should not affect any existing pages on the website

### Resources/Instructions
- [projects page](https://www.hackforla.org/projects/)
- [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)

**Comment by maybleMyers** [comment]
Progress: stuck
Blockers: having a hard time understanding assets/js/current-projects.js. I have never used the jekyll/liquid before.
Availability: 10 hours/week
ETA: not sure

**Comment by SAUMILDHANKAR** [comment]
@Benji-Montgomery Just wanted to follow up regarding your blocker. Please let us know if you have made progress or need help. Thanks.

**Comment by SAUMILDHANKAR** [comment]
@Benji-Montgomery Just wanted to share some of the resources on Jekyll/liquid you might find helpful: 
- https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture
- https://jekyllrb.com/docs/liquid/
- https://jekyllrb.com/docs/step-by-step/01-setup/
- https://shopify.github.io/liquid/tags/control-flow/

You can also post your blocker on our slack channel or add help wanted label on this issue if you need help on something specific. Thank you.

**Comment by JessicaLucindaCheng** [comment]
@jnmrles
- [ ] At the time you self-assign an issue, make sure to write in a comment the following:
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"
- [x] Also, please move this to the In Progress column. Edit: I moved this to In Progress because I think this got missed during our checks since it wasn't in the In Progress column.

**Comment by Sparky-code** [comment]
@macho-catt 
Checking in to see if you are still working on this issue or if your availability has changed. Please add your ETA and availability. Thanks!

**Comment by ExperimentsInHonesty** [comment]
@jnmrles We have not heard from you since you self assigned this issue.  We are putting it back into the prioritized backlog

**Comment by Wny-Duong** [comment]
Availability: (07/14-07/17): 4 hours, (07/18-07/22): 6 hours
ETA: 07/22, Friday.

**Comment by Wny-Duong** [comment]
Progress: Created projects-check.html file and page with current-projects-check.html and current-projects-check.js files based off of dependencies of the original projects pages. The createFilter function was also reworked to return only a technologies and languages filter based off of the original combined technologies filter, which are visible and can be "used."

Blockers: The languages filter does not work properly (doesn't get a count of the project languages and doesn't filter by the language) and I'm still trying to figure out why and how to fix that. But that should be the only obstacle remaining. 

Availability: 6 hours (7/25 - 7/29)

ETA: 7/29/22

Pictures:
![image](https://user-images.githubusercontent.com/32424251/180584717-b5c10ed6-302a-4f81-990a-97d1ae35df0f.png)

**Comment by ExperimentsInHonesty** [comment]
@Wny-Duong don't forget to remove the 2week inactive label when you do your update.  Thanks!

**Comment by Wny-Duong** [comment]
Progress: Progress has been much slower than I'd like it to be because of personal issues. However, this issue is very close to finished. The Languages and Technologies filter now both work properly. They can be used to filter project cards on the projects-check page and they maintain the frequency of the filter tags in the filter bar themselves, as seen in the images below.

The long delay in delivery has also been a result of needing to read through and trace back the code to deal with the problem of url parameters only working when language parameters treated as technologies parameters. This was fixed by editing the projectCardComponent() function to create a data-languages property to allow for filtering by that data-languages parameter through the url. Languages were previously combined with technologies in the data-technologies property of the project-card class in projectCardComponent().

Blockers: None! Just checking to make sure these changes don't impact other pages on the website.

Availability: 4 hours (8/5 - 8/7)

ETA: 8/7/22

Pictures:
![image](https://user-images.githubusercontent.com/32424251/183222211-a2c53f37-cf2e-4a15-9b3a-1956170ecaba.png)
![image](https://user-images.githubusercontent.com/32424251/183222225-6ec98a28-377e-435d-8840-81ed38bc445f.png)
![image](https://user-images.githubusercontent.com/32424251/183222236-90c1f3ea-3248-4dea-bd0a-92e5bdeee18e.png)
