### ISSUE TITLE
Implement the new design for the footer: mobile

### ISSUE THREAD

**Issue by R-Tomas-Gonzalez** [hackforla/website#2554]
~### Dependency~
-  ~#2393~

### Overview
We need to update the mobile view of the footer on the website to reflect the new design in Figma.

### Details
We are changing the way the mobile footer looks. We will be adding sections to the footer that include: "Our Work", "Get in Touch", "Join Us", and "Toolkit.

<details>
<summary>Current Mobile Footer</summary>
<img width="373" alt="Screen Shot 2021-12-06 at 10 46 42 PM" src="https://user-images.githubusercontent.com/63771558/144968068-3b17ce96-7826-443d-90f2-12313cc04c93.png">
</details>

<details>
<summary>Desired Mobile Footer</summary>
<img width="204" alt="Screen Shot 2021-12-06 at 10 36 11 PM" src="https://user-images.githubusercontent.com/63771558/144967079-9f36a559-6998-4032-b8e4-aa16cd00e1b2.png">
</details>

Note, the figma design in the desired mobile footer shows the last link on the bottom as "Privacy Policy". However, the current link on the website is "Join Us". The last link should remain as "Join Us".

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch` and the pull request created from this issue should be pushed into that feature branch. Please read and follow the steps in the [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) wiki article.
- [x] Navigate to footer.html  -> [/_includes/footer.html](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-filter.scss)
- [x] Create new section under the Donate button, and above the link section
- [x] Include four sections of Our Work, Join Us, Get in Touch, Toolkit
- [x] Under each section add desired links according to figma design
- [x] If scss is necessary, add to the _footer.scss file -> [/_sass/components/_footer.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_footer.scss)

### Resources/Instructions
#2393 - issue for updating the footer design for desktop view
Figma - [Mobile Footer Design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3417%3A3)

Issue Creator - Tomas Gonzalez
Designer of Feature - Stephen Parent

**Comment by ExperimentsInHonesty** [comment]
@R-Tomas-Gonzalez I added the feature branch label to this issue.

**Comment by ExperimentsInHonesty** [comment]
@R-Tomas-Gonzalez

-  it looks like there is already an issue for the design team to make a new footer, that is closed with the submission of the new footer design. #2511  I don't think Issac knew that Adam has already created issue #2393

- If you think that resolves the dependency, close the redundant issue with a note, and remove the dependency and link to the issue where the work can be found #2511

**Comment by JimGeist** [comment]
I hope for a quick turnaround on this and am shooting for Thursday, December 23. I will know more once I start looking at the files.

**Comment by R-Tomas-Gonzalez** [comment]
> I hope for a quick turnaround on this and am shooting for Thursday, December 23. I will know more once I start looking at the files.

Jim. Hold off on working on this for now... Will contact you via slack. Thanks.

**Comment by ExperimentsInHonesty** [comment]
I hid the [comment](https://github.com/hackforla/website/issues/2554#issuecomment-992033003) after updating the dependency.  It was confusion on my part.  This issue is ready to work

**Comment by Wny-Duong** [comment]
Availability:  (05/20-05/22): 6 hours, (05/25-05/29): 10 hours
ETA: Sunday, 5/29.

**Comment by JessicaLucindaCheng** [comment]
@Wny-Duong Here are the anchor links. These anchors may not all work since they may not all have been implemented yet. To check you can click on the links and see if they go to an anchor.
- [ ] Press is www.hackforla.org/about#news
- [ ] Volunteer with Us is www.hackforla.org/join#volunteer
- [ ] Partner with Us is www.hackforla.org/join#partner
- [ ] Advise Us is www.hackforla.org/join#advise
- [ ] Guides is www.hackforla.org/toolkit#guides
- [ ] External Resources is www.hackforla.org/toolkit#external-resources
- [ ] Contact Us is www.hackforla.org/#get-in-touch

**Comment by Wny-Duong** [comment]
Update
1. Progress: Mobile footer is roughly implemented with working links and placeholder links where anchors haven't been added yet. The current work done matches the Desired Mobile Footer layout for most mobile screen resolutions except for very small ones (less than 360px in width) as this causes the social media icons to become formatted strangely. There's also some inconsistencies with how much spacing exists between website content and footer because of a change I made to the main-footer styling in _footer.scss to prevent it from covering content at the very bottom.
- Demonstration of issue with small mobile resolutions
![Demonstration of issue with small mobile resolutions](https://user-images.githubusercontent.com/32424251/170813432-7795de16-13a6-4c09-961a-a09e33c058df.png)
- Demonstration of issue with spacing between website content and footer. The white blank space can be bigger or smaller depending on which the mobile resolution I'm testing with.
![image](https://user-images.githubusercontent.com/32424251/170813524-e8bffe78-f83a-4dc0-bc6a-9819ffffc975.png)

3. Blockers: None. Some slight tweaking needed with padding and margin values in _footer.scss should fix the issues mentioned in progress and I expect there won't be any serious issues.
4. Availability: 5/28 - 5/29 (4 hours)
5. ETA: Sunday, 5/29

**Comment by JessicaLucindaCheng** [comment]
This issue has been completed with the merging of pull request #3183. However, there is an issue with the linking between this issue and that pr. (I even tried linking it manually but I was unable to.)

Thus, I'm closing this issue as completed.
