### ISSUE TITLE
Audit the existing HfLA website UX research on drive

### ISSUE THREAD

**Issue by sacamp** [hackforla/website#2561]
### Overview
We need to document the resources from the previous UX research projects in order to create templates to use again in subsequent rounds of research and avoid repeating research projects.

### Action Items
 
- [x] Add each document from the Wiki to the resources below
- [x] Create HfLA website UX research audit spreadsheet (add it to the resouces below)
  - [x] Make a tab to annotate all the resources from wiki
  - [x] Make a tab for research plan. Include:
      - [x] research project type or project name
      - [x] if a research plan exists for the project
      - [x] whether any data been collected for this project
      - [x] methods used on the project
      - [x] remaining work to be done on the project
      - [x] if the project completed
        - [x] if completed, any existing artifacts (personas, user journeys, scenarios, etc)
- [x] Create templates/protocols based on existing research plans of completed research
- [x] create list of partially completed projects so that new issues can be generated from them
- [x] release dependency on #2529 

### Resources/Instructions
- [HfLA UX research drive](https://drive.google.com/drive/folders/14ZChVwBKzURRPSey7NAZGDbMwA4BzwRo)
- [HfLA Website Research Audit](https://docs.google.com/spreadsheets/d/1ZdUOlFx0DrM6jUfjcIwGw42Fpgba_pQVlaKPL-DBy38/edit#gid=0)
#### All the links even remotely related to this topic, pulled from the wiki
https://docs.google.com/document/d/147dkULzPX5i8hJCzXoMGoJnDEPkKhk9VhpcFMRe5VJE/edit#heading=h.qsbacjbyy36h
https://drive.google.com/drive/u/0/folders/1WchXF8whHAySPWy6p-gIJA_77mCoOS2K?ths=true
https://github.com/hackforla/website/projects/6
https://github.com/hackforla/website/wiki/A-Quick-Overview-of-FullStory
https://github.com/hackforla/website/wiki/Analytics-tools
https://github.com/hackforla/website/wiki/Success-Metrics
https://github.com/hackforla/website/wiki/Digital-Marketing-Overview

**Comment by ghost** [comment]
Availability for this week: 6 hours every week
My estimated ETA for completing this issue: next two weeks

- [x] Weekly, please also provide an update on the issue
```Got the assignment today. Will start working on it tomorrow. 
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by ghost** [comment]
Progress: Creating an Excel Sheet of all the existing UX research on a website redesign 
Blockers: Large amount of data to parse through in order to distill relevant information. Not a blocker really but more of a challenge. 
Availability: 6-7 hours
ETA: By Jan 6
Pictures: "Add any pictures of the visual changes made to the site so far."

**Comment by ExperimentsInHonesty** [comment]
@ShrutiMukherjee please put a link to the spreadsheet you are creating in the top of this issue under resources.

**Comment by ghost** [comment]
Resources: https://docs.google.com/spreadsheets/d/1ZdUOlFx0DrM6jUfjcIwGw42Fpgba_pQVlaKPL-DBy38/edit#gid=0
Progress: Creating an Excel Sheet of all the existing UX research on a website redesign
Blockers: Large amount of data to parse through in order to distill relevant information. Not a blocker really but more of a challenge.
Availability: 6-7 hours
ETA: By Jan 12

**Comment by sacamp** [comment]
Hi @ShrutiMukherjee, please remember to add an update about your progress on this issue. Thanks!

**Comment by ghost** [comment]
Hi Simone, 
My grandfather is unwell back home in India and is in the hospital. I have not been doing well emotionally and needed to take some time off to be with my family virtually. Have kept sometime before the meeting today to update the audit google sheet and the issue here. Thanks for the reminder.

**Comment by ghost** [comment]
Resources: https://docs.google.com/spreadsheets/d/1ZdUOlFx0DrM6jUfjcIwGw42Fpgba_pQVlaKPL-DBy38/edit#gid=0
Progress: Created an Excel Sheet of all the existing UX research on a website redesign
Blockers: None
Availability: 6-7 hours
ETA: Finished

**Comment by sacamp** [comment]
issue has been completed and the spreadsheet can be found on the user research wiki page.
