### ISSUE TITLE
Determine best image size for project homepage hero image

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#260]
### Overview
There needs to be a hero image that is unique for each of the project pages, and project leads need to know what those dimensions are. The dimensions of all hero images is to be: 1500 x 700 px.

### Action Items

- [x] Team discuss Charlotte's suggestions
- [x] Annotate this issue with additional questions
- [x] Send questions to Charlotte
- [ ] Review feedback
- [ ] Make decision on path to take
- [ ] Update project issues with size of image we are requiring

### Resources
[Hack for LA website](https://www.hackforla.org/)
[Current Project Homepage Wireframe](https://github.com/hackforla/website/issues/157#issuecomment-545255117)
[Hero image guidelines ](https://wphero.io/wp-content/uploads/2017/02/WP-Hero-WordPress-Image-Size-Cheatsheet.png)

## @charlottesauce 's suggestions
There are a few things to consider.
I think the biggest is considering responsive layouts. Sorry if you’ve already considered this and are purely asking for dimensions so that you can extrapolate to mobile!
There are probably a number of ways to deal with this. Here are the ones I can think of. Stars for my current faves:
1. We can ask for a 4000px (or at least 2880px) image that is fine to be cropped in random ways (food oasis’s beets pic is a good example), then resize to optimize loading times. 
Middle path of #2: we ain’t trying to sell cars, so slightly blurry is fine. Some dimension like 1800 x 700 would be fine. 
2. No custom hero image! I think this would be the simplest. You can probably put in a nice gradient that fits with the theme of the whole page OR do a generic “project” hero which can also make the project name stand out. Way less work to maintain.-------------------------------------------------------------------------------IDEA: You can also still add the preview project image on the site like this: [http://christinatruong.com/projects/](http://christinatruong.com/projects/) (She doesn’t have a header for her hero, but if you have a custom “projects” hero, then I think adding one would be great). You can also have the floating small image to remind people to check out the GitHub or some other CTAs!) Then you maintain project continuity from the previous click.

**Comment by ExperimentsInHonesty** [comment]
Notes from team meeting:
1. Project Homepage definitely needs a hero image because projects want to feel that its custom to their project.
2. We have changed the page to use a gradient similar to the hackforla.org homepage
3. The current hero image on the  hackforla homepage is 1500x719. 
4.  Charlotte is suggesting 1800 x 700 for the project page.  

Q for @charlottesauce : What is the benefit of 1800 x 700 over the 1500 x 700 ish on the homepage.  Is 1800 x 700 a more standard image size?

**Comment by charlottesauce** [comment]
@ExperimentsInHonesty -- posted this in slack in response to stephen's find in the slack channel. Posting it here for posterity so it doesn't disappear into the ether. 

(below found by stephen)
> "The minimum resolution on most computer screens is 1024 x 768 pixels, so we recommend a hero image of around 1600 x 500 pixels so you can maintain a 16:9 ratio as a good rule of thumb. 
> https://www.bangdigital.com.au/2018/02/photography-web-design-hero-image-best-practices/ (edited) 

---------my response below---------

Hi all! As I’m sure you’ve discovered, hero image dimensions aren’t an exact science. :)

A 16:9 ratio is fine (I’m guessing the 1600x500 is a typo which should say 1600x900, unless I’m missing something)—just depends on how much you want peeking over the fold that’s not a hero image.  

Eyeballing a 16x9 image, it pretty much fills the whole screen, which I don’t think is the style you guys are going for? (Though I understand it’s up in the air.) 

I personally like more content above the fold, which is why I went with my 1800x700: a number swiped from a big name site’s hero that I thought maintained a decent quality image on my retina screen + external monitor.

That being said--two factors to consider re: hero height:
1. How will you make the text over the hero legible? If you have a darker gradient over it like the HFLA site, then you probably don’t want the image too short (in other words, maybe 1800x700 is too thin)
2. How much do you want “under” the fold?

**Comment by charlottesauce** [comment]
Sorry, I realize I didn't directly answer you question.

> Q for @charlottesauce : What is the benefit of 1800 x 700 over the 1500 x 700 ish on the homepage. Is 1800 x 700 a more standard image size?

 In short: 

1800x700 is somewhat arbitrarily chosen based on another site I think looked fine.

The (arbitrary) benefit of 1800x700 it is that it allows for a nicer image quality on retina screens, and more space for content beneath.

I think 1500x700 also works (and looks) totally fine.
