### ISSUE TITLE
Edit Wiki to request review ETA and availability

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2667]
### Overview
As developers, we want the PR review process to be more efficient, so we will add instructions in Wiki for the PR reviewers to add their review ETA and availability.

### Action Items
- [x] Review the Wiki article [How to review a pull request](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)
- [x] Analyze which section would be the best place to add instructions for instance: Introduction, Step 0, Step 1 or any other
- [x] Add the instructions to request the reviewers to add their review ETA and availability at the time of picking up a PR for review.
- [x] Make edits directly to the Wiki article [How to review a pull request](https://github.com/hackforla/website/wiki/How-to-review-pull-requests), once done @ mention the technical leads and merge team members to review it.

### Resources/Instructions
- Wiki article where instructions are to be added: [How to review a pull request](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)
- Sample comment to be added by a reviewer
```
Review ETA: 6 PM 3/4/22
Availability: 5-8 PM Monday
```

**Comment by jnmrles** [comment]
Review ETA:  EOD 02/24
Availability: 12-9PM CEST Wed-Sat

**Comment by SAUMILDHANKAR** [comment]
@answebdev I have edited the action item on how to make changes to our Wiki article. Please let me know if you have questions. Thank you.

**Comment by answebdev** [comment]
@SAUMILDHANKAR Thank you for letting me know. I'll let you know if I have any questions.

**Comment by answebdev** [comment]
ETA: 2/27/2022 (end of day)
Availability: 3 hours

**Comment by answebdev** [comment]
@SAUMILDHANKAR @JessicaLucindaCheng I have made the edits in the above action items and added the instructions to request the reviewers to add their review ETA and availability at the time of picking up a PR for review. I added these instructions at the end of [Step -1](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#Step-1), before starting with the actual review in Step 0, which seems to make the most sense (but if you'd like me to move it elsewhere, please let me know). Here is a screenshot of what I have added for reference:

<img width="944" alt="wiki-edit" src="https://user-images.githubusercontent.com/36783010/155862774-3d23f428-d633-4edc-bf00-d1dd8657270f.png">

Please let me know if there is anything you'd like me to change.

Also, do I need to make a pull request for this, or no, since I made the edits directly to the Wiki article?

Thank you.

**Comment by SAUMILDHANKAR** [comment]
Review ETA: End of Day 2/27/22
Availability: Sunday 6-8 PM

**Comment by SAUMILDHANKAR** [comment]
@answebdev Thank you for making the changes to the wiki page. Changes look good to me, and their position is good as well. There is no need for a PR. I am approving it and closing the issue. Feel free to pick up a medium issue next. Thanks a lot. Awesome work!!
