### ISSUE TITLE
Create Project Home Page hero image for HackforLA website

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#272]
### Overview
Create Project Home Page hero image

### Action Items
Create Project Home Page hero image. Possibilities include:
- Collage image composed of snippets from the many mockups we have created to date.
- A singular horizontal banner image that effectively communicates our project.

### Resources/Instructions
see issue #244

**Comment by charlottesauce** [comment]
I brainstormed a few options for hero images. Below are three iterations, in order of my personal preference. Let me know what you think. Happy to tweak/make changes!

### **Version 1**
The current site with a hammer and a blue bg (color can be easily changed). The first img is my proposed "project card" to match with the hero for continuity.

![hfla-site project card](https://user-images.githubusercontent.com/45779646/73327052-4ea81a80-4209-11ea-814b-91efabc593f1.png)

![hfla-site hero](https://user-images.githubusercontent.com/45779646/73327046-494ad000-4209-11ea-959b-16a8311aaf08.png)



### **Version 2 proposal**
an image I take at a meeting with y'all in action.

![hfla-site hero proposal v2](https://user-images.githubusercontent.com/45779646/73326488-2ddec580-4207-11ea-8ef3-ef1db121391c.jpg)

### **Version 3 proposal**
A bunch of wireframes (to be filled in) with the current website for a grounding ref.

![hfla-site hero proposal v3](https://user-images.githubusercontent.com/45779646/73327039-418b2b80-4209-11ea-8bce-d0601f154bd2.png)

**Comment by ExperimentsInHonesty** [comment]
I really like the hammer image and the reference to the homepage hero image.

**Comment by ashlingam** [comment]
Nice work @charlottesauce -- of the three, I like concept 1 the most! I think the color scheme works.

**Comment by charlottesauce** [comment]
Thanks @ExperimentsInHonesty and @harishlingam ! :)

I went ahead and cleaned up the combo of concept 1 so that the project card mimics the hero a bit more faithfully. It's here for you. 

I'm concerned about how gradient on gradient (when you add text to the hero?) will look and have attached no gradient versions below just in case. 

Let me know what else I need to do to help close this issue, e.g.— Is there a better place where these should live? 2x versions for retina screens? Naming conventions, etc? Am I asking too many questions? :D

### Hero image (1500x700)
![hfla-site-hero](https://user-images.githubusercontent.com/45779646/73503670-c1d49c80-4381-11ea-97b9-d4afb7c15fbd.png)

### Project Card Image (600x400)
![hfla-site-project-card](https://user-images.githubusercontent.com/45779646/73503671-c26d3300-4381-11ea-86f4-85d57ee49a27.png)

### No gradient versions:
![hfla-site-hero-no-gradient](https://user-images.githubusercontent.com/45779646/73503880-53dca500-4382-11ea-9aae-a06ddedc7627.png)
![hfla-site-project-card-no-gradient](https://user-images.githubusercontent.com/45779646/73503879-53440e80-4382-11ea-8c7b-a44784bb27d0.png)
