### ISSUE TITLE
Communities of Practice information updates: Ops

### ISSUE THREAD

**Issue by JasonEb** [hackforla/website#2743]
### Overview
We need to add information on the COP page so it is up to date.

### Action Items
- [x] Please make the following changes (Note: Find and add the complete links for GitHub handle and Slack IDs in the Ops.yml file):
```
Remove person(s) and info from CoP file?

NO

If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:

Name:

Add person(s) and info to CoP file?

YES

If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Jason Ebueng
Title: CoLead
GitHub Handle: JasonEb
Slack Member ID: U02CA3CAK7Z

Name: Nicole Dubin
Title: CoLead
GitHub Handle: Neecolaa
Slack Member ID: U02LL2XK486
```
- [x] Make sure the changes are reflected in your repo

### Resources/Instructions
- Webpage where changes should be reflected: [Hackforla COP page](https://www.hackforla.org/communities-of-practice)
- File where changes need to be made: [Ops yml file](https://github.com/hackforla/website/blob/b602137a825371cb5ff28917f892f43b030d7c44/_data/internal/communities/ops.yml)

**Comment by lindseyindev** [comment]
Availability: 3 hours
ETA: Midnight 2/24

**Comment by SAUMILDHANKAR** [comment]
@lindseyindev Since you have already worked on small and medium issues, so request you to please pick up medium or large issues next as that is the recommended order of progression in our website team and provides more learning opportunity. Please let us know if you have any questions or challenges while picking up a medium or large complexity issue. Thank you.
