### ISSUE TITLE
Fix variable name in citizen-engagement.js

### ISSUE THREAD

**Issue by tamara-snyder** [hackforla/website#2887]
### Dependency
- [x] #2480

### Overview
We need to fix a typo in a variable name so that we can reuse it reliably.

### Details
As developers, it is important to write our JavaScript variable names carefully so that we don't mistakenly declare new variables that pollute the global namespace. In this issue, we will fix a variable name typo in `assets/js/citizen-engagement.js` in order to prevent a global variable from being declared later in the file.

### Action Items
- [x] In line 4 of `assets/js/citizen-engagement.js`, change `let currentDropown;` to `let currentDropdown;`
- [x] Check that the [Citizen Engagement page](https://www.hackforla.org/citizen-engagement) still functions as expected
- [x] Create a pull request for this issue according to the instructions found in the pull request section of [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-3-pull-requests)

### Resources/Instructions
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- The file you'll be editing: [assets/js/citizen-engagement.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/citizen-engagement.js)
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-3-pull-requests)
- Although the code in `citizen-engagement.js` is technically fine, here's a [brief explanation](https://hackernoon.com/understanding-javascript-scope-1d4a74adcdf5#:~:text=Undeclared%20variables,-JavaScript%20won%27t&text=This%20means%20that%20at%20any,a%20global%20variable%20for%20you.) as to why declaring variables without `let`, `const`, or `var` isn't best practice.

**Comment by JessicaLucindaCheng** [comment]
@tamara-snyder Great job on writing this issue! I just wanted to provide some feedback:

- [x] I would recommend including any links in the Action Items in the Resources/Instructions section too.
- [x] Since this issue is dependent on another issue, please add an action item to release this issue in issue #2480. See the last Action Item in this issue as an example:  https://github.com/hackforla/website/issues/2061
- [x] Also, I know our documentation doesn't include the points yet but please add a points label. Just search "pt" when looking for the label and you will see all the points labels. 1 point is equivalent to 6 hours of work. (The labels have a more detailed definition of the hours.)

**Comment by tamara-snyder** [comment]
@JessicaLucindaCheng Thanks for the feedback! I made the changes mentioned in your comment — please let me know if anything else needs to be fixed.
