### ISSUE TITLE
Update blank issue form with dependency

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2904]
### Dependency
- [x] https://github.com/hackforla/website/issues/2954

### Overview
We want to make the title, description, and format of the Blank Issue form clear that it is for issues with dependencies so that it will be easier and quicker to pick an issue template and write an issue. For this issue, we will update the title and description, and move the dependency section to the top of the form.

### Details
The screenshots below were taken by viewing the form on GitHub. (See the last Action Item for detailed instructions on how to do this.)
<details>
  <summary>Click here to see a screenshot of the current form</summary>
  
  ![current-form](https://user-images.githubusercontent.com/31293603/200982884-319437ce-29d5-4b91-80c8-11304980b942.png)
</details>

<details>
  <summary>Click here to see a screenshot of the desired updated form</summary>
  
  ![desired form](https://user-images.githubusercontent.com/31293603/200982482-ad64b08d-8a87-47c3-aa35-fe6ff69f3c2d.png)
</details>

### Action Items
In `.github/ISSUE_TEMPLATE/blank-issue-form.yml` on your local computer/IDE, 
- [x] Move
  ```
    - type: dropdown
      id: dependency
      attributes:
        label: Is there a dependency?
        options:
          - "Yes"
          - "No"
      validations:
        required: true
    - type: textarea
      id: dependency-explanation
      attributes:
        label: If Yes, please explain
  ```
  to right below `body:`
  ```
  name: 'Blank Issue '
  description: 'Standard HackforLA issue template '
  
  body:
  ```
- [x] Change
  ```
  name: 'Blank Issue '
  description: 'Standard HackforLA issue template'
  ```
  to
  ```
  name: 'Blank Issue Form with Dependency'
  description: 'Standard HackforLA issue form with dependency'
  ```
- [x] To check the form works correctly
  - [x] Push the changes to your remote forked repo's topic branch on GitHub
  - [x] In your remote forked repo on GitHub, 
    - [x] You are going to temporarily change the default branch from `gh-pages` to your topic branch. (See the link in the Resources/Instructions section for more documentation on how to do this.)
    - [x] Then, check you have issues enabled in your forked repo by
      - [x] Going to the `Settings` tab and then select `General` in the left menu.
      - [x] On the right side of your screen, scroll until you see the `Issues` checkbox under the `Features` section. Make sure the checkbox is checked.
          <details>
            <summary>Click here to see what it looks like when issues are enabled in a repo</summary>
            <img width="617" alt="" src="https://user-images.githubusercontent.com/31293603/200694955-c9c4dba3-b0d0-4259-9989-07079f166da8.png">
           </details>
      - [x] You should now see the Issues tab in your forked repo
    - [x] Now, open an issue within your repo to test out the form you just edited by 
      - [x] Going to the `Issues` tab and clicking the `New issue` button.
      - [x] Then select `Getting Started` button for `Blank Issue Form with Dependency`
      - [x] You should now be able to test out the form and make sure everything functions as expected.
- [x] Once you're done, in your remote forked repo on GitHub, remember to change your default branch back to `gh-pages`.
- [x] Do items in [comment below](https://github.com/hackforla/website/issues/2904#issuecomment-1328329813) to finish the issue
 
### Resources/Instructions
- Blank Issue Form: https://github.com/hackforla/website/issues/new?assignees=&labels=&template=blank-issue-form.yml
- Raw view of .github/ISSUE_TEMPLATE/blank-issue-form.yml: https://raw.githubusercontent.com/hackforla/website/gh-pages/.github/ISSUE_TEMPLATE/blank-issue-form.yml
- Blob view of .github/ISSUE_TEMPLATE/blank-issue-form.yml: https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/blank-issue-form.yml
- [GitHub's documentation on how to change the default branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch#changing-the-default-branch)

**Comment by Adastros** [comment]
Availability this week (PST): 9 - 11:30 PM Thursday, 10 AM - 10 PM Sunday
ETA: End of day Sunday 13NOV22

**Comment by ExperimentsInHonesty** [comment]
The form created can be see here: https://github.com/hackforla/website/issues/new?assignees=&labels=&template=blank-issue-form.yml

**Comment by ExperimentsInHonesty** [comment]
If we have two versions of the form.  One with Dependency and one without, why does it ask you on the dependency one if you have a dependency?

![image](https://user-images.githubusercontent.com/37763229/204128346-d3b55845-ea2a-43b6-ad48-a1df0c33afe3.png)

[with dependency](https://github.com/hackforla/website/issues/new?assignees=&labels=&template=blank-issue-form.yml)
[without dependency](https://github.com/hackforla/website/issues/new?assignees=&labels=&template=blank-issue-form-with-no-dependency.yml)

**Comment by ExperimentsInHonesty** [comment]
## Change the following section items

### "Is there a dependency?"
1. Please remove the YES/NO question
### "If Yes, please explain"
1. Change the title of text area from `If Yes, please explain` to `Add Dependencies (ideally by issue #)`
1. Inside the text area add the default text
`- [ ]`

**Comment by Adastros** [comment]
Availability this week (PST): 9 - 11 PM 29NOV22 , 30NOV22
ETA: 11PM 30NOV22

**Comment by ExperimentsInHonesty** [comment]
@Adastros I moved this to the in progress column.  Please do that in future when you self assign

**Comment by Adastros** [comment]
Won't be able to finish tonight. Currently asking a dev lead a question I had while working on this issue.

**Comment by Adastros** [comment]
Hi @ExperimentsInHonesty, I was working on the issue and wanted to get your thoughts on updating the issue template so that it more closely matches the structure of issue #2775 and #3132. Shout out to @JessicaLucindaCheng for helping me out. Below are some images to visualize the changes. 

The images with the proposed changes moves the text area title `Add Dependencies (ideally by issue #)` to the description under the title and uses `Dependency` as the title instead. The main goal is to structure it similar to issue #2775 and #3132 while making the issue form itself more uniform. It also makes it a bit more convenient having it structured that way so that the user doesn't have to re-edit the issue after submitting it to rename the Dependency section of the issue. 

## Issue form with previous feedback implemented
<details>
<summary>Before submitting issue</summary>

![Image](https://user-images.githubusercontent.com/48114590/205832051-4321b0ad-5607-4622-ae8b-a7d29e445373.png)

</details>

<details>
<summary>After submitting issue</summary>

![Image](https://user-images.githubusercontent.com/48114590/205833165-6384c532-19f3-4d64-9448-773d09feeea3.png)

</details>

## Issue form with proposed changes
<details>
<summary>Before submitting issue</summary>

![Image](https://user-images.githubusercontent.com/48114590/205834510-ede6a278-1dc6-4f1d-b971-fea9c4e3c30e.png)

</details>

<details>
<summary>After submitting issue</summary>

![Image](https://user-images.githubusercontent.com/48114590/205834750-df34ec39-18d1-4f38-b86f-176faa5a1c82.png)

</details>

**Comment by ExperimentsInHonesty** [comment]
The proposed changes are better.  do those

**Comment by Adastros** [comment]
Availability (PST): 9 - 11 PM 10JAN23
ETA: 11PM 10JAN23

**Comment by ExperimentsInHonesty** [comment]
good job!
