### ISSUE TITLE
Fix misspelled words on home-unite-us.md file

### ISSUE THREAD

**Issue by answebdev** [hackforla/website#2912]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [x] For the file `_projects/home-unite-us.md`,  on line 4, change the spelling from "non-profits" to "nonprofits" and the spelling from "scaleable" to "scalable", so

  ```
  description: We're working with community non-profits who have a Host Home initiative to develop a workflow 
  management tool to make the process scaleable
  ```
  becomes
  ```
  description: We're working with community nonprofits who have a Host Home initiative to develop a workflow 
  management tool to make the process scalable
  ```
- [x] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website pages with the issue:
- https://www.hackforla.org/projects
- https://www.hackforla.org/projects/home-unite-us

File on GitHub: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md
Line of code:
https://github.com/hackforla/website/blob/08b2f7096e54feb7b88466b92d90bbb19357ef01/_projects/home-unite-us.md?plain=1#L4

**Comment by Wny-Duong** [comment]
Availability for this week: 8 hours
My estimated ETA for completing this issue: Monday, April 18th

**Comment by Wny-Duong** [comment]
Leaving a note in case the pull request made does not seem to match action items. There is no change from scaleable to scalable because the description that was recorded in the issue has changed since the issue was first posted.

from: `description: We're working with community non-profits who have a Host Home initiative to develop a workflow 
management tool to make the process scaleable`
to: `description: The Home Unite Us project is developing a workflow management tool for community non-profits to automate and scale their existing Host Home initiatives,`
