### ISSUE TITLE
Add SoGoSurvey credit reference to the credit page for the Design Systems team 

### ISSUE THREAD

**Issue by JeannyRen** [hackforla/website#2936]
### Overview

The Design Systems team will have access to SoGoSurvey's Plus plan for free. In order for them to have this access they need a SoGoSurvey credit reference on the credits webpage.

### Action Items

- [x] Add SoGoSurvey credit code (see in resources) to the credit webpage
  - [x] Mention the Design Systems team as part of the credit

**Merge Team**
- [ ] Once merged, inform the Design System's PM or one of the UXR Leads. They need to provide a print screen in order to access the Plus plan. 

### Resources/Instructions

Please use this provided code for the credit (without modification): 
``` 
<a style="text-decoration: none;" href="https://www.sogosurvey.com/" target="_blank">Online Surveys powered by SoGoSurvey<br /><img style="border: none;" src="https://www.sogosurvey.com/static/ONLINE-SURVEY-IMAGES/ONLINE-SURVEYS-COMMON/logoM.png" alt="Provided by SoGoSurvey" /></a> 
```

[Figma, Credits page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1074%3A0)

**Comment by JeannyRen** [comment]
@ExperimentsInHonesty I created the issue for the SoGoSurvey credit reference for the Credit Page, but I cannot add labels to this issue.

**Comment by allthatyazz** [comment]
@JeannyRen We will address this in our meeting today.

**Comment by JessicaLucindaCheng** [comment]
@JeannyRen 

- > @ExperimentsInHonesty I created the issue for the SoGoSurvey credit reference for the Credit Page, but I cannot add labels to this issue.

Sorry, you weren't able to add the labels. I went ahead and added the labels for you.

I will bring up this issue with Bonnie at our Dev/PM meeting on Saturday. However, I have some questions: 

- As an action item in the issue, you wrote "Mention the Design Systems team". Did you mean to mention the Design Systems team as part of the credit, such as "used by the Design Systems Team"?

- The current code snippet provided displays the credit differently than how we currently have the rest of the credits on the [Credits page](https://www.hackforla.org/credits/).
  - Does the credit to SoGoSurvey have to be displayed exactly the way it was provided?
  - Did SoGoSurvey provide guidelines for how to provide credit to them in order to use their service for free? If so, can you link to those guidelines?

**Comment by JeannyRen** [comment]
Hi @JessicaLucindaCheng,

Thank you for picking up this issue so quickly. With reference to your questions, the communication regarding the credit reference for SoGoSurvey has taken place through e-mail solely. (Bonnie knows about it.)

- As an action item in the issue, you wrote "Mention the Design Systems team". Did you mean to mention the Design Systems team as part of the credit, such as "used by the Design Systems Team"?
  - Yes.
- The current code snippet provided displays the credit differently than how we currently have the rest of the credits on the [Credits page](https://www.hackforla.org/credits/).
  - Does the credit to SoGoSurvey have to be displayed exactly the way it was provided?
    - YES. 
- Did SoGoSurvey provide guidelines for how to provide credit to them in order to use their service for free? If so, can you link to those guidelines? 
    - Yes, they do. Please see the code shared in this issue. This was communicated through email. The platform agreed with a their credit reference being placed on our credit webpage. 

EDIT: I cross-checked with the platform, the provided code should be used without any modification.

**Comment by ExperimentsInHonesty** [comment]
@JeannyRen This is getting put into the icebox with a dependency until we get a website designer on the project.  Sorry for the hassle, but we don't anyone to work on it.  If your team can loan us a designer, please have them respond  to our [pms message in  slack ](https://hackforla.slack.com/archives/C017ESHSMNG/p1646948582263239)

**Comment by JeannyRen** [comment]
Thank you @ExperimentsInHonesty, @allthatyazz can we spare one designer of our team for this task (incorporating the SoGoSurvey credit on the HfLA credit page)? Please, see the comment above by Bonnie :-). Thank you.

**Comment by allthatyazz** [comment]
@JeannyRen I will reach out to our designers to find out.

**Comment by Providence-o** [comment]
@hangjoyce hi, I've assigned this issue to you. When you're able to start working on it please move it from the 'prioritized backlog' to the 'in progress' column using the drop down on the right pane above.
![image](https://user-images.githubusercontent.com/97491889/158453390-5a4327cf-3351-4b94-8dc4-eea06f8933d5.png)

**Comment by hangjoyce** [comment]
Got it. Thanks

**Comment by ExperimentsInHonesty** [comment]
@JeannyRen just letting you know that we got a designer on this because we have to rework the page to create a new section for this type of credit.  We will get back to you to let you know the status in a week.   We don't yet have an ETA for deployment.

**Comment by ExperimentsInHonesty** [comment]
@JeannyRen we have the designer you sent us working on this.  

- This issue will get finished in design, and then we will open a new issue for development and let you know the issue number in your issue https://github.com/hackforla/design-systems/issues/350

**Comment by JeannyRen** [comment]
Thank you for keeping me updated!

**Comment by Providence-o** [comment]
@hangjoyce Thank you for the work on the credits page.  Let's see if we can't get the vendor to agree to what we have provided before we have you do a different version.

@jeannyren Can go back to them and see if you can't get them to agree to the below layout.   See details below:

We will not be able to use the HTML as specified because it does not fit with our compliance requirements for WCAG.   Specifically, it has alt text which is redundant to the copy being provided, which not recommended by current guidance.  And the image is purely decorative, which also calls for empty alt tags. 

Additionally, we would prefer to provide the information in the format we have specified below (that matches our design system), so that people can see exactly how the resource is being used.  The "By" line would grow as more Hack for LA teams use it.

Here is what we recommend as being appropriate to their intention, while keeping with our Page Design.
![image](https://user-images.githubusercontent.com/97491889/159786181-66206938-fc2a-4a46-9d9d-c01586936b55.png)


---
Accessibility standards
Title III of the Americans with Disabilities Act (ADA) requires that all websites be accessible to people with disabilities. The World Wide Web (W3C) Consortium's Web Content Accessibility Guidelines (WCAG) 2.0 Level AA function as the current legal standard for website accessibility.

Get acquainted with accessibility: https://www.ada.gov/pcatoolkit/chap5toolkit.htm

[When to have an empty alt tag](https://accessibleweb.com/question-answer/when-should-i-use-a-null-or-empty-alt-tag/#:~:text=Alt%20tags%20are%20used%20to,be%20announced%20to%20the%20user.)

**Comment by JeannyRen** [comment]
@hangjoyce Thank you so much for your help!!!!!! You have helped a lot with speeding up this process. It is much appreciated. I will remove the update label for you. You can ignore the github-bot.

**Comment by JeannyRen** [comment]
Update @Providence-o :

Thank you for the update. I have gotten back to them. Thank you also for providing the reasoning behind the design decisions. That was very useful. Let's see what happens :-)

**Comment by JeannyRen** [comment]
@Providence-o, @ExperimentsInHonesty, @allthatyazz. The SoGoSurvey platform team has approved the credit reference as is. So we can proceed :-)

**Comment by phuonguvan** [comment]
@JeannyRen Great! We'll hand this to the development team and keep you informed.

**Comment by JessicaLucindaCheng** [comment]
@phuonguvan 

- Is there a link to the Figma design for the SoGoSurvey credit?
- Also, from https://github.com/hackforla/website/issues/2936#issuecomment-1076770029,  I noticed the following from the image. 

<details>

  <summary>Click here to see image I am referring to</summary>
  
  ![image](https://user-images.githubusercontent.com/97491889/159786181-66206938-fc2a-4a46-9d9d-c01586936b55.png)

</details>

  * The header `Iconograpfy & Imagery` has a typo. `Iconograpfy` should be `Iconography`.
  * Also, in the credit itself (on the bottom), is the red text `Design System's Team` and `SoGoSurvey` supposed to be links?
    * If yes, should they be underlined like the other links on the page?

**Comment by hangjoyce** [comment]
@JessicaLucindaCheng Hi Jessica, I was the designer of this issue. Thank you for pointing out the typo and the link, I fixed it. You can find the design in Hack for LA Website Figma file > Issac's Page > Credit Page. The new design (both web and mobile ver) is in the blue box on the Credit Page. Please let me know if you had problem finding it.

**Comment by JeannyRen** [comment]
@cunninghamej Hereby the process with regards to the access to the SoGoSurvey Plus program. Once the reference is online I can contact the SoGoSurvey team and include the necessary details :-)

**Comment by JessicaLucindaCheng** [comment]
Link to the development issue for adding SoGoSurvey to the Credits page: #3022

**Comment by ExperimentsInHonesty** [comment]
@phuonguvan We need to make a new issue for copying The finished design
 from [Figma, Credits page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1074%3A0)

to the [Figma, Current Pages](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0)

See [Figma Housekeeping, Current pages](https://github.com/hackforla/website/wiki/Figma-Housekeeping#current-pages) for details

Once the new issue is made, go ahead and link it in a comment below and then move this issue into Done column.

**Comment by ExperimentsInHonesty** [comment]
- Created ER https://github.com/hackforla/website/issues/4283
