### ISSUE TITLE
Add h tags to Getting Started page (Steps 1-3)

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2952]
### Overview
As a developer, I need to replace p tags with h tags on the headings of [Getting Started page](https://www.hackforla.org/getting-started) (Steps 1-3) so it becomes WCAG compliant

### Action Items
- [x] Review [Getting Started html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html) file
- [x] In line 51, change the p tag to an appropriate h tag: https://github.com/hackforla/website/blob/dadd71fd3db10520b3c69acdce198418863301a3/pages/getting-started.html#L51
- [x] In line 91, change the p tag to an appropriate h tag:
https://github.com/hackforla/website/blob/dadd71fd3db10520b3c69acdce198418863301a3/pages/getting-started.html#L91
- [x] In line 127, change the p tag to an appropriate h tag: https://github.com/hackforla/website/blob/96f02c4a8446f615741c881d823b94619738a708/pages/getting-started.html#L127
- [x] Ensure h tags (h1, h2, h3 etc.) reflect the correct hierarchy of the page for screen readers
- [x] Make sure the [Getting started page](https://www.hackforla.org/getting-started) still looks the same.

### Resources/Instructions
- [Getting Started page](https://www.hackforla.org/getting-started)
- [Getting Started html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html) file
- [Headings in Page Structure Tutorial](https://www.w3.org/WAI/tutorials/page-structure/headings/)
- [WCAG guidelines](https://www.w3.org/WAI/standards-guidelines/wcag/)
- Related issue #2953

**Comment by JessicaLucindaCheng** [comment]
@Jaretzbalba This issue was in the New Issue Approval column, so it is not ready to be worked on. Please only work on issues from the Prioritized Backlog column.

**How to find issues to work on:**
1) In the "Onboarding info/links" column on the far left of the Project Board, scroll down the column until you see the cards that say "Sort by Front-end Issues" and "Sort by Back-end Issues".
<img width="973" alt="Filter-cards" src="https://user-images.githubusercontent.com/31293603/159599628-3961821f-50ad-4f82-9f81-de924ff083e7.png">

2) Then, you can filter by role and complexity by clicking on the links in those cards. (I saw you already completed a Small issue, so you should work on a Medium complexity issue. To search for a Medium complexity, front-end issue, click on the "Medium" link on the "Sort by Front-end Issues" card.

3) After applying the filters, pick the top issue from the "Prioritized Backlog" column to work on because that issue has been prioritized with the highest priority compared to the other Medium, front-end issues.


For this issue, I will be un-assigning you and moving this back into New Issue Approval. Also, I will be closing your pr.

**Comment by SAUMILDHANKAR** [comment]
@riddle015 Thanks for picking up this issue. Please move it to In progress column. Also, please share your progress update. Thank you.

**Comment by riddle015** [comment]
ETA: 5/30/2022
Availability: 3 hours

**Comment by JessicaLucindaCheng** [comment]
@riddle015 Please move this issue to the "In Progress" column.

Edit: I have gone ahead and moved it to the In Progress column this time. However, in the future, please remember to move the issue to the In Progress column at the time you self-assign an issue. Thanks.

**Comment by riddle015** [comment]
Pull request has been submitted. Please let me know if there is anything else I need to do for this issue. 

Thanks for you patience
Hiram
