### ISSUE TITLE
Remove font-size and font-weight from .getting-started-step-title-faq class

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2961]
### Overview
As a developer, I want to remove font-size and font-weight from [.getting-started-step-title-faq](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L371-L374) class because it is redundant code 

### Details
We want to remove font-size and font-weight from [.getting-started-step-title-faq](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L371-L374) class because these should now be dependent on title4 class. Note: If we have two classes with same specificity, the class that is later in the aggregated [main.scss](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/main.scss) file will be used, which may not be the title4 class.

### Action Items
- [x] Review [.getting-started-step-title-faq](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L371-L374) class  in the [Getting Started page](https://www.hackforla.org/getting-started)
- [x] Remove lines 372-373 from [Getting Started page scss file](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss):https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L372-L373
- [x] Please search our codebase (using VS code or GitHub search functionalities) to ensure  [.getting-started-step-title-faq](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L371-L374) class isn't being reused at other places in our website
- [x] If [.getting-started-step-title-faq](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L371-L374) class is being used at multiple places, make sure existing functionalities are not impacted by this change 
- [x] Make sure [Getting Started page](https://www.hackforla.org/getting-started) looks fine for smaller viewport screens as well, such as tablet, mobile (responsiveness)

### Resources/Instructions
- [Getting Started page](https://www.hackforla.org/getting-started)
- [Getting Started html file](https://github.com/hackforla/website/blob/b8d2700a5f95538b9ddbc83b9ecd6e010b307fc1/pages/getting-started.html)
- [Getting Started page scss file](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss)
- [.getting-started-step-title-faq](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L371-L374) class

**Comment by 1anya1** [comment]
Availability: 2 hours
Review ETA: Friday, March 25, 2022

**Comment by SAUMILDHANKAR** [comment]
@1anya1 This issue is not ready to be worked upon yet. Please pick issues from the Prioritized Backlog column only. Requesting you to unassign yourself from this issue. Further, please work on one issue at a time, I see you are currently working on issue #2173. Thank you.

**Comment by kathrynsilvaconway** [comment]
ETA: Bythe end of the day on 4/19
Availability: 4 Hours

**Comment by JessicaLucindaCheng** [comment]
@kathrynsilvaconway This is issue isn't ready to be worked on as it is still in "New Issue Approval" column.

- [ ] Please unassign yourself from this issue. 
- [ ] Then, look for an issue to work on in the Prioritized Backlog. (Detailed instructions below if needed.)

**How to find issues to work on:**
1) In the "Onboarding info/links" column on the far left of the Project Board, scroll down the column until you see the cards that say "Sort by Front-end Issues" and "Sort by Back-end Issues".
<img width="202" alt="front-end-back-end-filters" src="https://user-images.githubusercontent.com/31293603/163284446-66cc2ad6-fd4a-427a-835d-afabcc640957.png">

2) Then, you can filter by role and complexity by clicking on the links in those cards. For example, if I was looking for a front-end medium issue, click on the "Medium" link on the "Sort by Front-end Issues" card.

3) After applying the filters, pick the top issue from the "Prioritized Backlog" column to work on because that issue has been prioritized with the highest priority compared to the other filtered issues.

**Comment by clayton1111** [comment]
ETA: by end of day 7/14
Availability: 4 Hours
