### ISSUE TITLE
Update Project Profile: GreenEarthOS

### ISSUE THREAD

**Issue by sanya301** [hackforla/website#3059]
### Overview
As Admin team I want the Green Earth project's details to be up to date on the HackforLA website so that people don't try to join it.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [green-earth-os.md](https://github.com/hackforla/website/blob/gh-pages/_projects/green-earth-os.md) file and find the `leadership` variable.
- [x] Remove everyone from the `leadership` variable
- [x] Add the following `technology` variable (syntax and spacing are important)
```
technologies: 
  - mkdocs
```
- [x] Add the following `tools` variable and value
```
tools: Google sheets, Google forms, Figma, FigJam
```
- [x] Update the project `status` from `Active` to `On Hold`

### Resources
- https://github.com/hackforla/website/blob/gh-pages/_projects/green-earth-os.md
- [HFLA wiki on project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by sanya301** [comment]
The following need to be updated:

## Remove: 
- leadership 
  - [x]  Akila Sankaran
  - [x] Samay Nathani
  - [x] Jessica Forrest-Baldini
  - [x] María-Inés Montes

## Add:
- Leadership
  - [x] Name: Sanya Nijhawan
    - GitHub handle: sanya301
    - Role: Product Manager
    - SLACK ID: U031FLYS561
  - [x] Name: Raji Pradheap
     - GitHub handle: rpradheap
     - Role: Product Manager
     - SLACK ID: U02R9MKA6KH
- [ ] technologies
   -  [ ] mkdocs
- [ ] tools
  - [ ] Google sheets
  - [ ] Google forms
  - [ ] Figma
  - [ ] FigJam

**Comment by JessicaLucindaCheng** [comment]
@sanya301 There is an unchecked Action Item that says, "Open an issue on VRMS to update the meeting times and provide the link to the new issue in the comment below". Did you need your meeting times updated too? If yes, you will need to fill out [VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

Edit: In order to clarify the Action Item in the original post, I changed the Action Item to now say, "If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in the comment below."

**Comment by sanya301** [comment]
@JessicaLucindaCheng I must have missed that, but no we do not need to update the meeting times

**Comment by frankstepanski** [comment]
Question: Just for clarification, am I just updating the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/green-earth-os.md)?

Availability for this week: Monday and Tuesday
My estimated ETA for completing this issue: Monday or Tuesday

**Comment by JessicaLucindaCheng** [comment]
@frankstepanski
- > Question: Just for clarification, am I just updating the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/green-earth-os.md)?

Answer: Yes
- In the future, if you have questions, a blocker, or need help, please post them in the hfla-site Slack channel or ask them during meeting time; otherwise, we may miss it.
- You have already completed a Small issue and you only need to do one Small issue during your whole time as part of the Website Team (though there are exceptions). I will allow you to work on this issue since it is time-sensitive and the issue is getting kind of old. However, after you finish this issue, please work on a Medium issue. Thanks.

**Comment by frankstepanski** [comment]
Sorry, broke my ankle Sunday night. I will get to this on Friday.
ETA: Friday

**Comment by SAUMILDHANKAR** [comment]
@frankstepanski Sorry to hear about your accident. Hope you get well soon.

**Comment by kathrynsilvaconway** [comment]
@ExperimentsInHonesty  @sanya301  This issue was unassigned because it was abandoned by a dev who left the team without notice. It was written back in April. Before I put it back into the prioritized backlog, I wanted to verify that the info is still accurate. What changes, if any, do we need to make?

**Comment by blulady** [comment]
Changes are no longer accurate. Send to product to decide what to do.

**Comment by ExperimentsInHonesty** [comment]
### Leadership
Remove all the leadership

### technologies
Add the following
- mkdocs

### Tools
Add the following
-Google sheets
-Google forms
-Figma
-FigJam

### Status
Change status to on hold

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge This is ready for dev formatting so that we can prioritize it (I verify all the info is correct).

**Comment by Thinking-Panda** [comment]
i. Availability: Weekdays 10 AM - 3 PM
ii. ETA: EOD 2/16/23
