### ISSUE TITLE
Bump node-fetch from 2.6.1 to 2.6.7 to resolve a security vulnerability

### ISSUE THREAD

**Issue by Sparky-code** [hackforla/website#3082]
### Overview

As a developer, I would like website team repo to be free of security vulnerabilities. For this issue, we will address the security vulnerability alert related to node-fetch. 

### Details

This issue addresses a security issue in node-fetch version < 2.6.7 that was automatically prompted by GitHub's [dependabot](https://github.com/dependabot).

Note: Node-fetch is vulnerable to exposure of sensitive information to an unauthorized actor.

### Action Items

- [x] Enable alerts and updates in your own fork of the Hack for LA website so that they match those in the Hack for LA repository. These settings can be found in the settings tab in your own repo under code security and analysis and is referenced in _image 1_ below.
- [x] After enabling the above, you should see an autogenerated PR in your own repository which references the node-fetch vulnerability, _images 2 and 3_ below.
- [x] Review [package-lock.json file](https://github.com/hackforla/website/blob/gh-pages/github-actions/github-data/package-lock.json) where changes need to be made.
- [x] Double-check if this update has caused issues and/or unintended changes in repositories that were updated.
- [x] Include the results of your check as a comment in this issue.
- [x] Address this PR **in your own repository** in order to test if the update causes any issues for the Hack for LA website.
- [x] Pending successful research and testing of the update, create a PR to merge the changes in node-fetch to gh-pages (main).

### Resources/Instructions

>>   [A page about dependabot and enabling alerts/updates](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates)   
>> [Package-lock.json file](https://github.com/hackforla/website/blob/gh-pages/github-actions/github-data/package-lock.json)

<details>
    <summary>Image 1</summary>

![alerts_and_updates_github](https://user-images.githubusercontent.com/95888938/165132576-2c654508-c468-4779-8bff-d885ac70dfd7.png)

</details>

<details>
    <summary>Image 2</summary>

![image](https://user-images.githubusercontent.com/95888938/165017123-9bdf4c7c-4ccc-4c35-a952-414518e916fc.png)

</details>

<details>
    <summary>Image 3</summary>

![image](https://user-images.githubusercontent.com/95888938/165018016-c2606e4c-5fec-4377-af9e-f50eaca5d2d4.png)

</details>

### Is there a dependency?

No

### If Yes, please explain

N/A

**Comment by blulady** [comment]
ETA: Thursday (5/26)
Availability: Thursday - Saturday (5/26 - 5/28)

**Comment by JessicaLucindaCheng** [comment]
@blulady Please move this issue into the "In Progress" column

Edit: I have gone ahead and moved it to the In Progress column this time. However, in the future, please remember to move the issue to the In Progress column at the time you self-assign an issue. Thanks.

**Comment by blulady** [comment]
Progress: I have completed the first few check marks. I need to read: A page about dependabot and enabling alerts/updates and the 
Blockers: As of right now, just need to read the instructions
Availability: 4 hours to work on it this weekend
ETA: Uncertain how many hours it will take
Pictures (optional): Currently no visual changes

**Comment by blulady** [comment]
<details>
    <summary>Step 1: Enable Dependency Graph, Dependabot Alerts, Dependabot Security Updates</summary>

![Screenshot (158)](https://user-images.githubusercontent.com/67162265/173699678-e2c1d232-6958-4fb0-94f4-35594fc18412.png)


</details> 

<details>
    <summary>Step 2: Make sure that I am seeing the alert in my repository</summary>

![Screenshot (159)](https://user-images.githubusercontent.com/67162265/173699829-1ac495e5-9763-48b5-890b-1c9b948b2f52.png)

and that I am able to review the security update
![Screenshot (160)](https://user-images.githubusercontent.com/67162265/173700034-c9da6416-b2a4-4b07-9a57-3bb5b5689c74.png)

</details> 


<details>
    <summary>Step 3: Review [package-lock.json file](https://github.com/hackforla/website/blob/gh-pages/github-actions/github-data/package-lock.json) where changes need to be made.
This is a bit more challenging because Hack For LA’s package-lock.json file doesn’t look like my package-lock.json file: </summary>

Hack for LA's
![Screenshot (162)](https://user-images.githubusercontent.com/67162265/173700842-30176815-89a4-4589-b3d2-4adfe79d166a.png)

Mine
![Screenshot (163)](https://user-images.githubusercontent.com/67162265/173701011-30e8eafd-94a7-439a-849f-bd0f624bdb79.png)

</details> 

<details>
    <summary>Step 4: Review package-lock where changes need to be made</summary>

![Screenshot (164)](https://user-images.githubusercontent.com/67162265/173701473-946d0223-6b0a-415a-87ab-1562803aa9d6.png)



</details> 

<details>
    <summary>Step 5: Research if this update has caused issues and/or unintended changes in repositories that were updated. </summary>
Unclear as to what steps should be taken here. Google search?
</details>


<details>
    <summary>Step 6: Address this PR in your own repository in order to test if the update causes any issues for the Hack for LA website.</summary>

![Screenshot (165)](https://user-images.githubusercontent.com/67162265/173701534-3d9dfb2b-f1b9-442a-93a4-2afd9599aaee.png)


![Screenshot (166)](https://user-images.githubusercontent.com/67162265/173703001-d05dcb52-8666-4256-b005-80eb8b4ea4f3.png)

![Screenshot (167)](https://user-images.githubusercontent.com/67162265/173703665-1eb6965c-31a2-4d07-93e9-400ae5e7be98.png)

![Screenshot (168)](https://user-images.githubusercontent.com/67162265/173703681-b7ebf935-2457-4588-bbeb-21cc4d1c885a.png)

![Screenshot (169)](https://user-images.githubusercontent.com/67162265/173703707-3c22923a-367c-432f-ab8f-621648863e4b.png)

![Screenshot (170)](https://user-images.githubusercontent.com/67162265/173703730-a81ba8a9-ea6a-4564-a98d-4534a1822240.png)

![Screenshot (171)](https://user-images.githubusercontent.com/67162265/173703746-e7d7fbe2-9b68-43dc-ab2f-982d02a1aa25.png)

![Screenshot (172)](https://user-images.githubusercontent.com/67162265/173703766-87464f69-8d79-4f0c-9805-f5d72d94d2d8.png)

![Screenshot (173)](https://user-images.githubusercontent.com/67162265/173703784-66d1713d-8feb-42d3-85bd-a7bba548870f.png)

![Screenshot (174)](https://user-images.githubusercontent.com/67162265/173703801-24470a39-4580-462a-a530-c7db0c82291e.png)

![Screenshot (175)](https://user-images.githubusercontent.com/67162265/173703825-b885c15d-1392-4b77-9f64-823832ca0518.png)


</details>

<details>
    <summary>Step 7: Pending successful research and testing of the update, create a PR to merge the changes in node-fetch to gh-pages </summary>
Will attend meeting tonight and ask about moving forward with a PR
</details>
