### ISSUE TITLE
Redesign Citizen's Engagement's SDG sizes and related padding

### ISSUE THREAD

**Issue by phuonguvan** [hackforla/website#3117]
### Overview
We need to make sure that all text on the site is minimum 16pt, including text on the SDG icons, which will also require padding changes  to accommodate.

### Details
We need to make sure that the Website and the Figma design match for the Citizen Engagement page, so that the current website has the most up-to-date design decisions and that the Figma file is ready for future iterations.

### Action Items
- [x] Review the screenshots in the Resources section
- [x] Make a copy of the 16pt version in Figma (has a red line), add a blue line around it, and start working on the new copy
- [x] Figure out what size the SDG needs to be in order for the text, that is part of the image, to be a minimum of 16pt.  See note in resources about how to determine this.
- [x] Make the SDG icon the new proper size in your Figma draft (in blue)
- [x] Redesign the padding 
- [x] Review the draft with the design lead

### Resources/Instructions
- [HfLA - Citizen Engagement Page](https://www.hackforla.org/citizen-engagement)
- [Gold's Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=22485%3A129377)
- [Figma - Citizen Engagement](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15901%3A100458)
- [Figma, Design Systems](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24474%3A284697)
- The image has text embeded in it.  We did not create the image so you can't decompose it into its parts to see what size the text is.  What you can do, is try Roboto (bold and black) or Oswald (medium and semibold) in all caps to try to match the existing size and then once you have determined the size and weight of the font used, you can figure out how big you need to make the SDG Icon Image in order for the font to equal 16pt.  Here is a link to the styleguide for the SDGs https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf

#### Website
SDG text box width: 280
SDG image is 120x120 
<details>
<summary>Website Screenshot</summary>

![image](https://user-images.githubusercontent.com/100561599/167723661-cd3bb936-bc97-491c-b5e1-adf25a44ec49.png)
![unknown (1)](https://user-images.githubusercontent.com/100561599/167619259-6605f408-ffa4-49ed-b105-2956e581d363.png)
</details>

#### Figma
SDG text box width: 318
SDG image is 88x88
<details>
<summary>Figma</summary>

![image](https://user-images.githubusercontent.com/100561599/167724052-82743bea-7f8f-4faf-aef5-4abb0ba4f158.png)
![image](https://user-images.githubusercontent.com/100561599/167723983-19f5c787-867a-4fa5-b037-ecca71633f70.png)
</details>

**Comment by EmilyTat** [comment]
Availability for this week: 6 hrs
My estimated ETA for completing this issue: EOD 06/10/22

**Comment by EmilyTat** [comment]
Provide Update
1. Progress - I have completed steps 1 & 2, reviewing screenshots and making a working copy of the 16pt version with a blue line around it in Figma File. 
2. Blockers - All text on website and Figma file is 16 pt - unsure what needs changing - is it the text on the actual image? Unsure how to edit this in Figma. 
3. Availability - 6 hrs
4. ETA - EOD 06/10/22

**Comment by EmilyTat** [comment]
Want to discuss and work together on this in next Design Team Meeting, thank you!

**Comment by gold-o** [comment]
Progress: I have redesigned the SDG section and padding for the citizen engagement cards on the website page. I still have to redesign the SDG section for the mobile page, but I have a few questions.
Blockers: N/A
Availability: 4-5 hours
ETA: By the end of this week (by 07/23)
Pictures (optional): "Add any pictures of the visual changes made to the site so far."
![Screen Shot 2022-07-17 at 3 15 41 PM](https://user-images.githubusercontent.com/38343775/179426891-8cbeec1c-68b3-48c8-b3cf-c136d351a1c2.png)

**Comment by gold-o** [comment]
Progress: I have completed the desktop design for the issue
Blockers: For the mobile version, when the font is changed to 16pt and the image is resized, it changes the design. It would be good to explore the best way we can design the mobile version of this page with the new SDG sizing.
Availability: N/A
ETA: The issue is completed

![Screen Shot 2022-09-12 at 3 35 58 PM](https://user-images.githubusercontent.com/38343775/189770882-88d43a6a-5aea-491b-b26e-74fb810f4f9d.png)

**Comment by gold-o** [comment]
The issue is completed. For the mobile version, developers will use the original SDG image with the 90 pixels sizing.

**Comment by ExperimentsInHonesty** [comment]
Hi Dev leads.

The latest version is on [this figma frame labeled final version](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24474%3A284697)

If you are unclear what needs to be done, please bring this to the sunday or monday meeting.

**Comment by JessicaLucindaCheng** [comment]
> Hi Dev leads.
> 
> The latest version is on [this figma frame labeled final version](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24474%3A284697)
> 
> If you are unclear what needs to be done, please bring this to the sunday or monday meeting.

- This is the dev issue to implement the new design: #3738

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty I just want to confirm a couple of notes:

- Gold O. wrote:
  > The issue is completed. For the mobile version, developers will use the original SDG image with the 90 pixels sizing.
 
  - Does this mean changes only need to be made for the desktop view of the Citizen Engagement page?
    - Ans from Bonnie: Yes, only changes for desktop
 
- You wrote:
  > The latest version is on [this figma frame labeled final version](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24474%3A284697)
  
  - I don't see a frame labeled final version. Do you mean the frame labeled "Newest Version"?
    - Ans from Bonnie: Yes, newest version

**Comment by JessicaLucindaCheng** [comment]
- This is the dev issue to implement the new desktop design: #3738

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 
I know the mobile design is staying the same. However, the current [Citizen Engagement webpage](https://www.hackforla.org/citizen-engagement) SDG image size, SDG paragraph text size, and the SDG header text size do not match the [Current Page Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0&t=BCFRDyeyl3bouj0A-0).
- Note: I couldn't inspect the mobile view in the [updated Figma design in the red frame labeled Newest Version](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24474%3A284697&t=TbIeVN7XfDgCWNbZ-0). Thus, I referred to the Current Pages Figma design. Let me know if there is a different design I should be referring to.
- Question: Do you want the mobile design to match the Current Pages in Figma?
  - If yes, do you want me to write a separate Medium size issue to update the mobile Citizen Engagement to match the Figma design?

Ans: 
- From 2023-01-16 Dev/PM meeting, Bonnie said the mobile view of the webpage is fine as is. The mobile design should match the page. So, write an ER issue so that the mobile design is updated to match the page.

**Comment by JessicaLucindaCheng** [comment]
> Hi Dev leads.
> 
> The latest version is on [this figma frame labeled final version](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24474%3A284697)
> 
> If you are unclear what needs to be done, please bring this to the sunday or monday meeting.

- This is the dev issue to implement the new desktop design: #3738


> ...
> * From 2023-01-16 Dev/PM meeting, Bonnie said the mobile view of the webpage is fine as is. The mobile design should match the page. So, write an ER issue so that the mobile design is updated to match the page.

- I wrote the #3766 for a design lead to follow up on.
