### ISSUE TITLE
Update Project Profile: Open Community Survey

### ISSUE THREAD

**Issue by kalyaniraman** [hackforla/website#3217]
### Overview
As a product manager of Open Community Survey I want my project's details to be up to date on the HackForLA website

### Project card
URL: https://github.com/hackforla/website/tree/gh-pages/_projects/open-community-survey.md

### Action Items

- [ ] Open Community Survey Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new comment below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub handle
         - [ ] Role
         - [ ] SLACK ID
      - [x] links 
         - [x] Github
         - [x] Slack
         - [x] Test Site (Don't exist)
         - [x] Demo Site (Don't exist)
         - [x] Site (Don't exist)
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status
 - [x] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

### Resources

- HackforLA.org, Open Community Survey page: https://www.hackforla.org/projects/open-community-survey
- [OCS Roster](https://docs.google.com/spreadsheets/d/1b97Np96EimkxicW83pwnYkn7uDd7fCD5H_6F21nOkg4/edit?usp=sharing)

### Prior Closed Issues

- 2021-10-11 https://github.com/hackforla/website/issues/2364#issue-1023261996
- 2022-01-22 https://github.com/hackforla/website/issues/2711

**Comment by kalyaniraman** [comment]
Add the Following People

Name: Ambareen Sultana
GitHub handle: ambersu123
Role: Product Manager
SLACK ID: U03FQ1BBGP4

**Comment by matt-arofin** [comment]
`Availability`: 3 hours, Friday and Saturday
`ETA`: 06/15/2022

**Comment by JessicaLucindaCheng** [comment]
@matt-arofin This issue isn't ready to be worked on yet because it was still in the New Issue Approval column when you picked it. I am unassigning you from this issue and moving this back to New Issue Approval.

For how to find issues to work on, please read [Part 2: How the Website team works with GitHub issues](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues), especially section 2.3 Where can I find GitHub issues to work on?

**Comment by JessicaLucindaCheng** [comment]
@kalyaniraman I saw you wanted to add Ambareen to leadership, so I unchecked leadership (including Name, GitHub handle, Role, SLACK ID) above since a person needs to be added. Did you need any changes to any of the following:
  - links
     - Github
     - Slack
     - Test Site
     - Demo Site
     - Site
  - technologies
  - partner
  - tools
  - status

If changes are needed, please let us know in a comment below. If no changes are needed and the item is okay as is, please check off the item in https://github.com/hackforla/website/issues/3217#issue-1260261742 above. Thank you.

**Comment by kalyaniraman** [comment]
@ExperimentsInHonesty Can you please let me know what the below items are?

- links
  - Test Site
  - Demo Site
  - Site

**Comment by RyanCahela** [comment]
Availability: Sunday 10AM - 5PM
ETA: 2 Hours
