### ISSUE TITLE
GitHub Actions: Bot adding and removing "Status: Updated" and "To Update!" label

### ISSUE THREAD

**Issue by Zak234** [hackforla/website#3341]
### Overview
There is a bug with the Github bot in which it both adds and removes the "Status: Updated" label. This should be fixed to avoid confusion and to make sure that the proper labels are being applied.

### Action Items
- [x] Please go through the wiki article on [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
- [x] Review the [add-label.js](https://github.com/hackforla/website/blob/2fe355b396ed7f785d382505b8c2ecafe09cb486/github-actions/add-update-label-weekly/add-label.js#L226) file, to understand how the bot adds and removes labels from the issue.
- [x] Understand why the Github action bot adds and removes the "Status: Updated" and the "To Update!" label.
- [x] Change the code logic to fix this error

### Checks
- [x] Test in your local environment that it works

### Resources/Instructions
Relevant files:
- https://github.com/hackforla/website/blob/2fe355b396ed7f785d382505b8c2ecafe09cb486/github-actions/add-update-label-weekly/add-label.js
- https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml

Relevant Issues:
Status: Updated Bug:
- #2497 
- #2561 
- #2397 
- #3059 

To Update! Bug:
- #2462 
- #2317

Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
- [GitHub RESTAPI](https://docs.github.com/en/rest)

#### Architecture Notes

The idea behind the refactor is to organize our GitHub Actions so that developers can easily maintain and understand them. Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by ExperimentsInHonesty** [comment]
This issue had not been added to the project board.  It got added on Sept 11, but no additional action since then.  Please review.  

Extra details
- This issue was created from: https://github.com/hackforla/website/issues/2650

**Comment by jdingeman** [comment]
Initially thought that there was going to be a conflict between this and the other issue related to added and removed labels, but it looks like they work in different files. Adjusted bullet points for readability. Sending this back to add to the board.

**Comment by bzzz-coding** [comment]
i. Availability: Tuesday and Thursday evenings
ii. ETA: 1/28/23

**Comment by bzzz-coding** [comment]
**Progress:** 
I've been trying to understand the logic of adding/removing labels. Judging from the documentation, 
- if there has been a comment by the asignee or if the issue has been crosse-referenced within 3 days, use the 'Status: Updated' label; 
- else if there has been a comment by the asignee or if the issue has been crosse-referenced within 7 days, use the 'To Update!' label;
- else if there has not been a comment by the asignee or if the issue has been crosse-referenced within 14 days, use the '2 weeks inactive' label;

**Blockers:**
However, the code seems to have more 'inner logic' that was not mentioned in the documentation, so I would like to get a corner case clarified:
- if the issue was created within three days, but no comment by asignee or cross-referencing since then, what label should it have? 

Lastly,I need help understanding what getTimeline() returns. 
In add-label.js, there is a getTimeline() function that I assume is using the GitHub API https://docs.github.com/en/rest/issues/timeline?apiVersion=2022-11-28 and if so, should return an array of objects. However, in function isTimelineOutdated(), I see a for loop like this: 
`for await (let [index, moment] of timeline.entries())`, 
which makes me question what timeline's structure is like and how objects are nested and what properties they have.  

**Availability:** Tuesday and Thursday evenings.
**ETA:** mid to late March, as I also need to figure out the best way to test GHA in my forked repo.

**Comment by jdingeman** [comment]
Hey @bzzz-coding, to answer your corner case, I don't think the github bot will post anything within three days of assignment and there's not really a label that is needed for it. If someone has self-assigned and they're actively working on it, then we don't necessarily need the issue to have a label on it. The github bot already reminds the assignee to put their ETA and availability after they've assigned it to themselves. If they didn't, I don't think it even checks it. But this might be a good thing to bring up if there is not already a GHA that checks this. 

For the question regarding the getTimeline() function, it looks to me like they might be [issue events](https://docs.github.com/en/webhooks-and-events/events/issue-event-types). My guess is that `index` refers to, evidently, the index of the issue event, and the `moment` I imagine is the contents of the issue event. The use of `.created_at` is pointing me to the Response Schema of an HTTP status code 200 shown on that page.

**Comment by bzzz-coding** [comment]
Progress: Refactored isTimelineOutdated function and fixed some other inconsistent conditions. 
Blockers: Had to infer what GitHub API returns -- need more testing.
Availability: Tuesday and Thursday evening, Saturday 3/4, and Sunday 3/5 in the morning.
ETA: Saturday 3/4/23
