### ISSUE TITLE
Preference Testing options for Toolkit page

### ISSUE THREAD

**Issue by vaisali89** [hackforla/website#3448]
### Overview
Conduct Preference testing of options provided by the design team for the Toolkits page. Four variations of design have been provided for testing.

### Action Items
- [x] Have Bonnie add you to the 1password vault so that you can get access to our email address website-research@hackforla.org
- [x] Read [this article](https://usabilityhub.com/guides/preference-testing) in order to get a refresher/primer/good overview of how best to utilize preference testing.
- [x]  [Sign up](https://usabilityhub.com/pricing) for a free account on Usability Hub using the project email
- [x] Set up a preference test that asks participants to compare the four versions, which are :
             - Applied filer tags on the side vs on the top
             - The look of the filters
             -  Light background vs dark background
             -  How results show on the page: 3 columns vs 1 column of Figma file
- [x] Recruit participants through Hack for LA Slack channels
- [x] Present findings to Product and Design to decide on which version should be developed.

### Resources/Instructions

[Usability Hub: An introduction to preference testing](https://usabilityhub.com/guides/preference-testing)
[Usability Hub: Sign Up](https://usabilityhub.com/pricing)
[Figma file](https://www.figma.com/file/MVRUNtLFjuamihX8PQg2Ic/Hack-for-LA-about%2Faccomplishment-and-Toolkit-page?node-id=307%3A388197)

**Comment by ExperimentsInHonesty** [comment]
Hi @nehasyed97 After meeting with Sija today, I setup this Figma page in our Figma account, so that we could do testing internally (with team on Sunday) before we go to external users via usability hub

 https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=19750%3A127094

I also created the following items in the slack channel so we can do voting https://hackforla.slack.com/archives/C018FMQTWMT/p1660170421953849

**Comment by nehasyed97** [comment]
1. Progress: Completed issue today (14/08/2022) via live preference test. Out of 17 voters, 14 displayed a preference towards Toolkit Dark bg - option 3. While the issue is complete, I will be reaching out to individuals with civic tech jobs to understand the way in which they conduct preference tests. This will help uncover if there are any ways to improve our current method.
2. Blockers: I am not entirely sure how to locate members with civic tech jobs but will explore different Slack channels and send out a message if I need help. I am also not entirely sure on how to create a Figjam file but will have more clarity regarding this once I am able to connect with somebody within civic tech.
3. Availability: 6 hours.
4. ETA: 1/1.5 weeks.
4. Pictures: Attached is the selected Toolkit Dark bg - option 3.

<img width="359" alt="Screen Shot 2022-08-14 at 6 24 10 PM" src="https://user-images.githubusercontent.com/109565476/184557233-e6fd5910-d637-4cb4-865d-d76d0f548727.png">

**Comment by nehasyed97** [comment]
Progress: I have spent the last few days playing around with Figjam to come up with a model that could (potentially) be used for preference testing moving forward. Currently, I have come up with 3 different models and will use our team call on Sunday to decide on the most efficient one.
Blockers: As I am very new to Figjam and teaching myself how to navigate it, the models I am coming up with are relatively simple. 
Availability: 6 hours.
ETA: August 28, 2022.
Pictures: N/A

**Comment by 7kram** [comment]
@ExperimentsInHonesty Because it involves toolkit, lets add the **Homepage Launch** milestone

**Comment by ExperimentsInHonesty** [comment]
@nehasyed97 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ExperimentsInHonesty** [comment]
@nehasyed97 You closed the issue but there are no details of what the final determination was

**Comment by ExperimentsInHonesty** [comment]
- [ ] Ready for design lead to copy the contents out of this figma file into one owned by our project.
- [x] Ready for development lead to create an issue to start laying out this page.  It will eventually replace the toolkit page, but we could develop it with a different name and then replace the toolkit page when its done.
- [ ] Ready for research lead to make sure the research is properly recorded in the wiki

**Comment by jdingeman** [comment]
> * [ ]  Ready for design lead to copy the contents out of this figma file into one owned by our project.
> * [x]  Ready for development lead to create an issue to start laying out this page.  It will eventually replace the toolkit page, but we could develop it with a different name and then replace the toolkit page when its done.
> * [ ]  Ready for research lead to make sure the research is properly recorded in the wiki

Dev issue made here:
- #3959
