### ISSUE TITLE
Update docker-compose to remove the previously generated site and Jekyll metadata before building

### ISSUE THREAD

**Issue by aricforrest** [hackforla/website#3587]
### Overview

Jekyll does not always rebuild every file in the _site directory every build. This can cause old versions of files to be served.

### Action Items

- [x] Update the `docker-compose.yml` file to run the `jekyll clean` command before the existing `jekyll serve` command.
- [x] Test updating a file in `_projects` to ensure the update reflects immediately when running `docker-compose up`.

### Resources/Instructions

- https://github.com/hackforla/website/blob/gh-pages/docker-compose.yml
- https://jekyllrb.com/docs/usage/

**Comment by bishrfaisal** [comment]
@aricforrest @kathrynsilvaconway good work creating this issue, there are just a few minor items remaining before we can approve this.

This issue is missing the following:
- It does not have a [size points label](https://github.com/hackforla/website/labels?q=size) - we need points labels in addition to t-shirt sizes.
- If there is no dependency on this issue, please remove 

> Is there a dependency?
> No
> 
> If Yes, please explain
> No response

**Comment by aricforrest** [comment]
@bishrfaisal I've added a size points label and removed the dependency section.

**Comment by Adastros** [comment]
Availability: 2 - 8 PM 20NOV22, 9 - 11PM 21NOV22, 22NOV22
ETA: 11PM 22NOV22
