### ISSUE TITLE
Add rebase instructions to wiki

### ISSUE THREAD

**Issue by zempo** [hackforla/website#361]
### Overview
I think we need instructions in the wiki on how to rebase

### Action Items

- [ ] Decide where rebase instructions should go in the wiki
- [x] Write the new text
- [ ] Review with Bonnie 

### Resources/Instructions
[Instructions](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a)

**Comment by cnk** [comment]
General rebase instructions? I think the main thing most folks need is a link to the GitHub docs on working with forks - especially how to keep your fork in sync with the main project repository - https://help.github.com/en/enterprise/2.20/user/github/collaborating-with-issues-and-pull-requests/working-with-forks

**Comment by cnk** [comment]
I started looking for where to put this in the wiki and found we had some git instructions in the project README.md. They are fine up to the point where you have made some changes and need to create a pull request. 

After step 4 we need to tell contributors how to push their branch to their own fork and then create a pull request. In the ideal situation, before doing that push, the contributor would update their fork to the latest code from the hackforla/website repository and then rebase their topic branch onto that updated gh-pages branch in their fork. 

I started adding instructions on how to keep your fork up to date with the main project. (The existing section on incorporating upstream changes is problematic because it uses `git reset --hard` which may cause people to lose work.) But I decided I didn't like the order in which I tried to explain keeping your fork up to date with the main `hackforla/website` repo vs how to rebase before pushing a topic branch to your own fork. @zempo if you would like to take over and figure out a better order for explaining that process, I would be grateful. 

My (unfinished) updates are available in the readme-changes branch of my fork: https://github.com/cnk/website/commit/17321e281369442a23ab7785d6e6fde5a184960f

**Comment by zempo** [comment]
Thank you for writing the text, @cnk 

I think a solution to the tricky order of the process of forking/cloning would be a mini index of the steps covered in this process. This way, readers can quickly navigate to the approach they want to take.

### Forking and Cloning
---
1. Become a member
2. Fork
3. Clone ...
---
^It would look like this, but with a better explanation for each step and that we have clickable links to go to each section. As demonstrated [here](https://stackoverflow.com/questions/2822089/how-to-link-to-part-of-the-same-document-in-markdown).

Unless anyone is opposed, I think I'll add that index today (along with the @cnk 's updates).

**Comment by zempo** [comment]
@ExperimentsInHonesty and @cnk , I've got the changes ready to go [here](https://github.com/zempo/website/commit/6ef994e00b93a40d5efa1077ad0cf9b68604c8d4#diff-04c6e90faac2675aa89e2176d2eec7d8).

If everything looks fine with both of you, I'll go ahead and submit a pull request

**Comment by zempo** [comment]
I've checked with everyone and it seems we're good to go.
I'm closing this issue for now.
