### ISSUE TITLE
Communities of Practice information updates: UI/UX

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/website#3691]
### Overview
We want to update the information in the UI/UX CoP card so that the information is accurate.

### Action Item
- [x] In _data/internal/communities/ui-ux.yml, update the file to reflect the information written below:

  ### remove person(s)
  
  Name: Felicia Swafford
  Name: Kevin Wang
  
  ### Add person(s) 
  
  Name: Aparna Gopal 
  Title: Co-Lead
  GitHub Handle: Aparna1Gopal
  Slack Member ID: U0245UJP868
  
  Name: Julia Gab
  Title: Co-Lead
  GitHub Handle: juliagab56
  Slack Member ID: U03AS9FBAAU
  
### Resources
- Communities of Practice webpage: https://www.hackforla.org/communities-of-practice
- Link to UI/UX CoP card source card: https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/ui-ux.yml

**Comment by ExperimentsInHonesty** [comment]
I approve these proposed changes

**Comment by ExperimentsInHonesty** [comment]
### Overview
We want to update the information in the UI/UX CoP card so that the information is accurate.

### Action Item
- [ ] In _data/internal/communities/ui-ux.yml, update the file to reflect the information written below:

  ### remove person(s)
  
  Name: Felicia Swafford
  Name: Kevin Wang
  
  ### Add person(s) 
  
  Name: Aparna Gopal 
  Title: Co-Lead
  GitHub Handle: Aparna1Gopal
  Slack Member ID: U0245UJP868
  
  Name: Julia Gab
  Title: Co-Lead
  GitHub Handle: juliagab56
  Slack Member ID: U03AS9FBAAU
  
### Resources
- Communities of Practice webpage: https://www.hackforla.org/communities-of-practice
- Link to UI/UX CoP card source card: https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/ui-ux.yml

**Comment by ExperimentsInHonesty** [comment]
Original cleaned up version (from form)
---
### Overview
We want to update the information in the UI/UX CoP card so that the information is accurate.

### Action Item
- [ ] In _data/internal/communities/ui-ux.yml, update the file to reflect the information written below:

  ### Remove person(s) and info from CoP file?
  
  YES
  
  ### If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:
  
  Name: Felicia Swafford
  Name: Kevin Wang
  
  ### Add person(s) and info to CoP file?
  
  YES
  
  ### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:
  
  Name: Aparna Gopal 
  Title: Co-Lead
  GitHub Handle: Aparna1Gopal
  Slack Member ID: U0245UJP868
  
  Name: Julia Gab
  Title: Co-Lead
  GitHub Handle: juliagab56
  Slack Member ID: U03AS9FBAAU
  
  ### Meeting time
  Check that meeting time is Wednesdays 6pm PT

### Resources
- Communities of Practice webpage: https://www.hackforla.org/communities-of-practice
- Link to UI/UX CoP card source card: https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/ui-ux.yml

**Comment by angelenelm** [comment]
**Availability**: 9AM - 3PM PST M-F
**ETA**: End of day November, 21 or 22, 2022
