### ISSUE TITLE
Fix the dropdown menu design for projects page

### ISSUE THREAD

**Issue by blulady** [hackforla/website#3744]
### Dependency
- #3256 

### Overview
During recent audits, the team realized that the drop-down menu design is not uniform. In an attempt to unify all drop-down menus the design team has redesigned the drop-down menu. This issue is to implement the new uniform design specifically on the projects page.

### Action Items
- [x] Update the drop-down menu on the projects page to reflect the design in Figma
- [x] The goal is to make this component reusable on multiple pages with different filters specified
- [x] Take into account accessibility of navigating the filters with keyboard -see resources below
- [x] Make the appropriate changes to the CSS, HTML, and JS as you need to
- [x] Note: The final design shows a "Search by keword" function, but you can ignore this for now, as this will be worked on in a different issue.

### Resources/Instructions
- for reference a link to related design issue: #3277 
- in the [elements folder](https://github.com/hackforla/website/tree/gh-pages/_sass/elements) you should find  `_dropdown_filters.scss` and that is where you will want to make the changes to the CSS
- in the [_includes](https://github.com/hackforla/website/blob/gh-pages/_includes/) page you should find the [current-projects.html](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects.html)
- in the [assets/js](https://github.com/hackforla/website/blob/gh-pages/assets/js) folder you should find [project.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js)
- [Final design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24096%3A281035)

[Design Systems](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
[Accessibility Resources](https://github.com/hackforla/website/issues/2173#issuecomment-1279768721)
[Standardized Components Wiki](https://github.com/hackforla/website/wiki/Standardized-Components) specifically:
   - [Keyboard Accessible - sufficient techniques](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=211#principle2)
   - [Using CSS when component receives focus](https://www.w3.org/WAI/WCAG21/Techniques/css/C15.html) - [Focus visible](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible)
   - [Navigable Guideline 2.4](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/)
   - [Focus Not Obscured](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/#2412-focus-not-obscured-minimum-aa)

**Comment by chrismenke45** [comment]
Availability: Tues, Wed 8am-12pm. Thurs 12pm-6pm. 
ETA: 3/24

**Comment by chrismenke45** [comment]
Progress: I've set up the general layout and the functionality of the filters works
Blockers: I will need to learn more about keyboard accessibility to finish
Availability: Mon-Fri 8am-12pm
ETA: 3/24

**Comment by chrismenke45** [comment]
3/24 Update:
PR Created
Available: 3/25 8am-12pm

**Comment by ExperimentsInHonesty** [comment]
@chrismenke45 Please change your pr to a draft and fix the following issue then take off the draft label

The current mockup shows the filter on the side being higher.  And even without the search bar, its still to low.

### Current mockup from Figma
![image](https://user-images.githubusercontent.com/37763229/227653220-784b6531-11d4-42af-8ece-336dd986c374.png)

### Your screenshots from your dev
<img src="https://user-images.githubusercontent.com/86500980/227623832-c6624c74-7f37-4e29-a333-d0cc9e0517ad.png" width="" length="" />

**Comment by chrismenke45** [comment]
@ExperimentsInHonesty  Will do! Thank you for looking over it so quickly!

**Comment by ExperimentsInHonesty** [comment]
@chrismenke45 While you are waiting for your PR to get reviewed.  Can you add a write up of what files go into the filter component and any other details that a person adding the same component to another page (e.g., toolkit page) will need to know.  You can leave that write up here in this issue as a comment.

**Comment by chrismenke45** [comment]
# How to Implement Dropdown Filters on Another Page
## Files to reference
- [_dropdown_filters.scss:](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_dropdown_filters.scss) This contains the styling for the filters you will be using. It is responsive and the classes are used to reflect changes in the UI due to user input
- [current-projects.js:](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) This is an example of how the js should be pulling information from our files and using it to build/filter items. It adds all the required classes  to the filter elements to allow them to be responsive and react to user input.
- [current-projects.html:](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects.html) This is an example of the base html required for the js file to build and add elements as needed
## Recommended workflow
- Begin with reviewing [current-projects.js:](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) and understand workflow
- Import data to be displayed and assign to a variable (see retrieveProjectDataFromCollection and projectDataSorter functions in current-projects.js
- Build data cards (see projectCardComponent function in current-projects.js)
- Specify which attributes of the data the filter should work on (see createFilter function in current-projects.js)
- Specify filter titles (many will just be the attribute that is being filter on, see main function  in current-projects.js)
- Add event listeners
## Functions that will need to be changes to reflect you page's needs:
- retrieveProjectDataFromCollection and  projectDataSorter will need to be changed to whatever data is being displayed
- createFilter will need to get new keys with values pulled from data
- projectCardComponent will need to be changed to whatever data is being displayed
- updateProjectCardDisplayState will need to be updated to whatever data is being displayed
- main will need to specify what filter titles will be used on new data
- updateFilterFrequency will need to query select from different class assuming data cards class is no longer '.project-card'
- updateUI & noUrlParameterUpdate will need to be updated to reflect name changes of the functions listed above
- All other functions regarding the filters should be good to go as is once the above functions have been changed
