### ISSUE TITLE
Remove duplicate `alt` field in youthjusticenav.md

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#3746]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
There is a duplicate alt field for [youth justice nav](https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/youthjusticenav.md). This breaks some yaml interpreters, and is non-standard for yaml.

### Action Items
- [ ] For the file `_projects/youthjusticenac.md`, delete line 6
```
alt: "All capital letters spelling out title of project - YOUTH JUSTICE NAV"
```

### Resources/Instructions
**File and code links you will need to work on this issue**

- Directory to find the page once you have it in your IDE: `_projects/youthjusticenav.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/e5361f8ab2a6537ee941e90f1d4e38ea83015276/_projects/youthjusticenav.md?plain=1#L6

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

**Comment by annierm18** [comment]
Availability: 4/1 and 4/2
ETA: 4/2

**Comment by annierm18** [comment]
@Aveline-art or @ExperimentsInHonesty line 8 now looks different than what is documented in this ticket. It now says "alt: 'Youth Justice Nav'" because of this change I believe: https://github.com/hackforla/website/pull/4140. Should the action item in this issue be updated before I work on it? Thanks in advance for your help on this.

**Comment by roslynwythe** [comment]
Hi @annierm18 - Thank you for taking up this issue and correctly pointing out that line 8 has been modified by PR #4140.  The file now contains duplicate alt text on lines 6 and 8 and I have modified the Action Items so that line 6 is deleted.  For the future, please note that questions of this nature are best presented to the dev lead team for a quicker response: https://github.com/hackforla/website/wiki/Meet-the-Team
