### ISSUE TITLE
Bug: Project meeting data from VRMS is not updating

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#3890]
### Overview
We need to find and fix the data on the project's page for events not updating , so that people who are looking to join teams have accurate meeting data.

#### Details
The meeting time is showing up on the [Events page](https://www.hackforla.org/events/) but not on the project page.   Which means the API is working, but somehow we are not updating the data used on the projects page.

### Action Items
- [x] Identify and document how to replicate problem
- [x] Identify and document source files
- [x] Identify and document what it should be doing
- [x] Figure out what is broken

### Resources/Instructions
- [GHA: vrms data](https://github.com/hackforla/website/wiki/GHA:-vrms-data)
   - https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json
- in the text under [Hack for LA's Site Architecture, page section, project-meetings.html](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#pages) there is info about how the API is used on the Events page.
  - This file is referenced but gets 404 [project-meetings-from-vrms.json](https://github.com/hackforla/website/blob/gh-pages/_data/project-meetings-from-vrms.json) in the _data folder
- in the text under [Hack for LA's Site Architecture, API Endpoints section](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#api-endpoints) there is info about how its used
- [_layouts/project.html line 65](https://github.com/hackforla/website/blob/c4677fd902310b59710c0b76f1d2a5ab1f64a0cb/_layouts/project.html#L65) page where the meeting time info is displayed
- [JS file that gets the data](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js)

#### Replicating problem

1. Logging into VRMS
2. Seeing the meeting data it provides
<details>
<summary>VRMS team page in VRMS.io application</summary>

<img width="513" alt="Screen Shot 2023-01-24 at 9 05 28 AM" src="https://user-images.githubusercontent.com/39230947/214362559-0588a7c1-4177-454c-a6b3-df3503099a1c.png">
</details> 

4. Checking the meetings against what appears on the website for the project page
<details>
<summary>VRMS page on hackforla.org website</summary>

<img width="899" alt="Screen Shot 2023-01-24 at 9 05 33 AM" src="https://user-images.githubusercontent.com/39230947/214362540-c8fd5aa2-7a06-434d-9060-3abb2bc6d1ec.png">
</details>

5. Checking the meetings against what appears on the hackforla.org Events page
<details>
<summary>Sunday meetings list</summary>

![image](https://user-images.githubusercontent.com/37763229/215351272-c12485a1-3809-4ccc-97bc-d94071fb1ad2.png)

</details>

**Comment by ExperimentsInHonesty** [comment]
Double check that the Events page is using the same api as the project page via is js file.

https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js#L125
 - const API_URL = 'https://www.vrms.io/api/recurringevents';

Its using the same api, but it might be calling the data seperately instead of using the file https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json that is created by the 2am pst chron job (GHA: https://github.com/hackforla/website/blob/gh-pages/.github/workflows/vrms-data.yml)

**Comment by MattPereira** [comment]
**Availability:** 7 - 9 PM Sunday - Thursday
**ETA:** asap

**Comment by MattPereira** [comment]
@ExperimentsInHonesty 

There is a meeting object in the `vrms_data.json` array that looks like this

![image](https://user-images.githubusercontent.com/73561520/216847600-a6b93439-da5f-4a7f-ac62-8205ae44fa92.png)

Since the `project` key of this meeting object has a `null` value, an error is thrown on the 56th iteration of the for loop that appends the meetings to the project page

https://github.com/hackforla/website/blob/40fe386562da5eefb48537a035a5f10d789111f7/assets/js/project.js#L131

https://github.com/hackforla/website/blob/40fe386562da5eefb48537a035a5f10d789111f7/assets/js/project.js#L134

The unhandled error results in the for loop exiting before the final 57th iteration runs, which is the iteration that would append the infamous "Sun 7:00 pm - 8:00 pm testing" that is currently missing from the VRMS project page.

You can see this error on the live site if you visit https://www.hackforla.org/projects/vrms and open the browser console.
![image](https://user-images.githubusercontent.com/73561520/216848212-bfe80ee3-ed0a-41ee-9c1c-80336fa4545b.png)

**Comment by MattPereira** [comment]
Let me know if I should merge my own PR since this fix is needed ASAP or if you'd prefer I wait for reviews

**Comment by MattPereira** [comment]
I also just noticed that the `projectTitle` "Access The Data" does not match casing with the VRMS data for `project.name` so I am adding a `.toLowerCase()` method to both the `projectTitle` and `projectName` to fix it.

You can see Access the Data meeting times are currently broken on the live site: https://www.hackforla.org/projects/access-the-data
