### ISSUE TITLE
Add Code Spell Checker VS Code extension installation instructions

### ISSUE THREAD

**Issue by christinaor** [hackforla/website#4101]
### Dependency
- [x] https://github.com/hackforla/website/issues/4349 is ready for implementation

### Overview
As developers of the Hack for LA website, we want to align on the tools we're using to keep the codebase as free as possible of misspellings so our reputation and the quality of our code is maintained. For this issue, we will add installation instructions for the VS Code extension, Code Spell Checker, so our developers will be aligned on the local spellchecker used.

### Action Items
- [x] In `CONTRIBUTING.md`, update the Table of Contents to include linkage to the Code Spell Checker installation process with the following: 
```
    - [**1.7 Dev setup (7): Install local codebase spell checker**](#17-dev-setup-7-install-local-codebase-spell-checker)
```

- [x] In the same file, add the following instructions for the installation process:
```
### **1.7 Dev setup (7): Install local codebase spell checker**

You must use VS Code as your local text editor to install the VS Code extension for spell checking your codebase, Code Spell Checker.

The recommended installation method is to install Code Spell Checker directly from the VS Code text editor, and those instructions can be found [here](https://code.visualstudio.com/learn/get-started/extensions). The extension can also be installed via the VS Code Marketplace website [here](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker). <strong><em>Feel free to reach out in the [Hack for LA Slack channel](https://hackforla.slack.com/messages/hfla-site/) if you have trouble installing the extension in VS Code.</em></strong>
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Ensure that the linkage from the first action item links correctly to the second action item's instructions.
- [x] Create a pull request in the usual manner, but after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)

### Merge Team
- [x] After this issue is completed, change the instructions in the pre-work checklist from 
```
Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md]
``` 
to 
```
Complete steps 1.1 - 1.7 in [Part 1: Setting up the development environment within Contributing.md]
```

### Resources/Instructions

- [Code Spell Checker VS Code extension](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
- [Installing VS Code extensions](https://code.visualstudio.com/learn/get-started/extensions)
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)

### Related Issues
- This issue follows up on: https://github.com/hackforla/website/issues/3546
- This issue is part of an epic https://github.com/hackforla/website/issues/4349

**Comment by ExperimentsInHonesty** [comment]
We should do this on a feature branch (add info for how to do that)
also in the roll-out plan, it should cover
- messaging in people's dev issues
  - message should have a checkbox with an acknowledgement that the change has been made to requirements and that they have read the new instructions in the contributing.
- messaging in their preworks 
  - message should have a checkbox with an acknowledgement that the change has been made to contributing and that they have read the new instructions.
- team meeting messaging
- pr review messaging
- slack channel
- any edits to PR review & making PR guidance (given that it's possible that the commits people will do, we exceed the scope of their issue because the linter will catch spelling mistakes, and they will fix them.)

Issue
- Create Roll out plan
  - define where messages need to go
  - if one time or permanent code changes (make new issues after messaging wording is decided, if it requires code changes)
  - what generally they cover
  - when they will get added or sent
- Update Contributing #4101 (this issue)
  - Update PR Guidance (add to this issue)
- Create messaging for issues (dev & prework), meetings & github actions message on new pr
  - example: github new pr: add this text (or something like it)
     > We added a spelling linter on X date, 
     >     - If the PR contains spelling changes, those are included in the scope of this issue.
     >     - if the PR has not passed the linter because spelling changes are suggested, please see the contributing X section for installing the VS code plugin.

**Comment by jdingeman** [comment]
New issue made here:
- https://github.com/hackforla/website/issues/4349
@ExperimentsInHonesty - I tried my best in figuring out roughly how we would roll this out but I want to make sure I'm on the same page as you.

**Comment by DevRishiJain** [comment]
8/7/23
16:00-18:00
