### ISSUE TITLE
Lucky Parking Unique Transportation Related Neighborhoods Contact Information

### ISSUE THREAD

**Issue by chriskong217** [hackforla/website#4151]
### Overview
We need to receive a list of names from Lucky Parking regarding which organizations they have been in contact with, so that we can add the logos to the citizen engagement page.

### Action Items
- [x] Contact Yuting to find out what NCs on Resource 1. have been contacted by Lucky Parking
- [x] Copy the names that have been contacted to Resource 2.
- [ ] Create a new issue to gather logos and create issues to add them to the repo

### Resources/Instructions
1. [Transportation Related Committee Members spreadsheet](https://docs.google.com/spreadsheets/d/1dME7V4iMni9V-LGr4KBsp9HfONLsRWeTqlgcu0mqYqI)
2. HackForLA [Partner logo to project matrix, Copy of Unique Transportation Related Neighborhoods tab](https://docs.google.com/spreadsheets/d/1B4qN_eGqWuqqeY_oazw7TLJ49ubHkAb6AESPmDb5Z4E/edit#gid=383882409)
3. Citizen Engagement Page: https://www.hackforla.org/citizen-engagement

**Comment by chriskong217** [comment]
Progress: Lucky Parking has been contacted for the names, am still awaiting a response. 
Blockers: Lucky Parking has been non-responsive, and the names are needed to continue with the task.
Availability: Monday 7pm - 9pm, Wednesday 7pm - 9pm
ETA: Dependent on Lucky Parking contact

**Comment by ExperimentsInHonesty** [comment]
@ychu196 I am happy to help you with a recommendation.   Could you help @Josiah-O, get in touch with whoever is the new pm there, to sort out this issue?  We just need know what Neighborhood councils that the lucky parking team has actually worked with, so we can add their logos to the hackforla website.

**Comment by ychu196** [comment]
Thank you so much @ExperimentsInHonesty ! I will slack dm you for additional deets
@Josiah-O Happy to help, just join the lucky parking slack group and dm me. you can I can setup a 5 min meeting.

**Comment by Josiah-O** [comment]
@ychu196 Thanks for your feedback and willingness to help. I have sent you a message on Slack.

**Comment by ychu196** [comment]
Just a heads up @ExperimentsInHonesty I gave them your hack for la email address as I figure that was your most preferred way of being contacted.

**Comment by ychu196** [comment]
I have met with @Josiah-O and directed him to 2 contacts in Lucky Parking

**Comment by Josiah-O** [comment]
Note to self: I will ask @gregpawin to update the lucky parking current project team by opening an issue on the website team's repo using this [template](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2Crole%3A+back+end%2FdevOps%2Crole%3A+front+end%2CComplexity%3A+Small%2Csize%3A+0.5pt%2Ctime+sensitive&projects=&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D)


So that we can update this page to reflect current team members info https://www.hackforla.org/projects/lucky-parking

**Comment by Josiah-O** [comment]
@gregpawin mentioned Seymour Liao is responsible to provide the information on Neighborhood councils that the lucky Parking Team has actually worked with, since the Lucky Parking team have mostly been talking to his contacts. 

I have reached out to Seymour Liao on Lucky Parking Slack channel, waiting for his feedback.

**Comment by Josiah-O** [comment]
Seymour Liao have given the Neighbourhood Community as Atwater Village only

**Comment by ExperimentsInHonesty** [comment]
- Please reach out to Seymour and Danny Pham in the team channel pointing out that they currently have an open issue to update the Lucky Parking teams info on the website and it does not reference Atwater Village as a partner.  Do you want that added? https://github.com/hackforla/website/issues/4909

**Comment by ExperimentsInHonesty** [comment]
![ALWATER VILLAGE 1](https://github.com/hackforla/website/assets/37763229/4ff4ecb3-99ad-450f-8c53-e8ef52818414)

**Comment by Josiah-O** [comment]
I have reached out to Seymour and Danny Pham to ask them if they want to reference Atwater Village in the Lucky Parking team's update issue.

**Comment by ExperimentsInHonesty** [comment]
- I created an ER https://github.com/hackforla/website/issues/5098.  This issue is ready to close

**Comment by ExperimentsInHonesty** [comment]
@Josiah-O - I created an ER https://github.com/hackforla/website/issues/5098.  This issue is ready to close
