### ISSUE TITLE
ER: Add info to the wiki for when someone accidentally creates an issue from a checkbox 

### ISSUE THREAD

**Issue by qngyn** [hackforla/website#4167]
### Emergent Requirement - Problem
This issue originally was called Add yourself to the #hfla-site and #hfla-site-pr Slack channels and its was blank.  Which we think is because the author accidentally clicked on the circle next to the checkbox in their prework, which creates an issue.

### Issue you discovered this emergent requirement in
- this one

### Date discovered 
2023-03-16

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty qngyn (not at messaging them, so they don't keep getting notices about this)

### What happens if this is not addressed
We have to explain it manually instead of being able to close with comment and the comment links to a wiki page which explains it.

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]

Instructions for developer who has created an issue accidentally:
- create a comment in the new issue stating that the issue was created accidentally
- close the issue as "not planned"

WIKI is not accepting new contribs. See https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki for instructions.

**Comment by ExperimentsInHonesty** [comment]
@qngyn I assume this issue got created when you accidentally clicked on the circle that appeared to the right of the checkbox item.  Congratulations! Now you know how a new issue can be made out of a task item. This comes in really handy if you are trying to make a lot of issues at once.  

An example of that would be if I wanted to do an accessibility check on each page of the site. In my epic issue, I could create a list (of each page and the issue title)
- [ ] Accessibility check: Projects page
- [ ] Accessibility check: Join Us page
- [ ] ...
Then I could hover over the item and click the circle and voilà, a new issue with the correct title, and it's linked to my epic.

Since I know you don't need this issue, I am going to close it.  But I won't delete it because I want to have it available as an example and explanation.  We will be demoing this in the Sunday meeting, so everyone can be familiar with this "secret" feature.

**Comment by ExperimentsInHonesty** [comment]
Did this get added to the wiki yet?

**Comment by ExperimentsInHonesty** [comment]
We need to write the wiki page is something I can send to someone when they create one of these issues accidentally.

WIKI is not accepting new contribs.  See https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki for instructions.

**Comment by roslynwythe** [comment]
- new issue #5678
