### ISSUE TITLE
Create a new Code of Conduct Page

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4249]
### Overview
Since HfLA is no longer bound by Code for America's Code of Conduct, we need to update HfLA's Code of Conduct. For this issue, you will need to create a new Code of Conduct page so that developers will read the Code that pertains to HfLA specifically.

### Action Items
- [x] In [website/pages](https://github.com/hackforla/website/tree/gh-pages/pages), create a new html file named code-of-conduct.html
  - [x] Add the Jekyll [front matter](https://jekyllrb.com/docs/front-matter/) block for this new page
  - [x] Use `layout: default`
  - [x] Make the permalink to the page with `permalink: code-of-conduct` so Jekyll can build the page
  - [ ] ~~Include the file in index.html~~
- [x] Using the [GitHub REST API](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28), use the [hackforla/codeofconduct](https://github.com/hackforla/codeofconduct/blob/master/README.md) README.md file to populate the website's current [CODEOFCONDUCT.md](https://github.com/hackforla/website/blob/gh-pages/CODEOFCONDUCT.md) dynamically
  - [x] The idea here is that the content of the Code of Conduct only gets edited in one place and can be applied across all projects
  - [x] This will then be rendered onto the new code-of-conduct.html file using Liquid
  - [x] Be sure to separate the content as appropriate into 
    - Header
    - Content Body
    - Footer

### For PM/Tech Lead/Merge Team
- [x] When this PR associated with this issue is merged, add a "ready for design lead" label on this issue #4249, and place it into the New Issue Approval Column so that design can review the layout and redesign as necessary. 
  

### Resources/Instructions
- Associated ER for this issue: https://github.com/hackforla/website/issues/4243
- Using [Liquid](https://jekyllrb.com/docs/liquid/) in Jekyll
- [GitHub REST API](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28)
- REST API [Media Types](https://docs.github.com/en/rest/overview/media-types?apiVersion=2022-11-28)

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - I am testing out ways to do this. I looked at your Diff analysis and I was confused. Do you want the [CODEOFCONDUCT.md](https://github.com/hackforla/website/blob/gh-pages/CODEOFCONDUCT.md) file that currently exists in the website repo to just be a hard copy of the [CODEOFCONDUCT.md](https://github.com/hackforla/codeofconduct/blob/master/README.md) in hackforla/codeofconduct? Or do you want the page to dynamically render _from_ hackforla/codeofconduct without holding a hard copy inside the repo?

I was also not sure what the Feature label should be.

**Comment by ExperimentsInHonesty** [comment]
@jdingeman Use the same feature labels as the ones I put on this issue

Yes, I want to dynamically render from hackforla/codeofconduct without holding a hard copy inside the repo if possible.  That way we are always only updating it in one place and that place is appropriate for all teams to link to.

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - I think it's possible using the GitHub API, but I think this will be considered a large issue. Please see DRAFT NOTES for potential roadblocks/questions.

**Comment by ExperimentsInHonesty** [comment]
@jdingeman I think that if we do this

> The Code of Conduct should be placed onto a card, similar to the [HackforLA Platform](https://www.hackforla.org/about/#platform) card or the [HackforLA Sustainability](https://www.hackforla.org/about/#sustainability) card

Then it's going to look weird because there is no header image and text. For now, let's just have it be 
header | content directly on page | footer.  
We will call that MVP.  Then later we can always send it to design to decide how it should be different.

**Comment by bootcamp-brian** [comment]
Availability for this week: Weekdays before 5pm
ETA: By end of next week (4/16)

**Comment by bootcamp-brian** [comment]
Provide Update
1. Progress: Currently researching ways to get the code of conduct to render dynamically from the readme file in the hackforla/codeofconduct repo.
2. Blockers: Haven't been able to figure out a way to access the necessary info from a live browser environment yet.
3. Availability: Tues-Fri next week
4. ETA: Hopefully by the end of next week.

**Comment by bootcamp-brian** [comment]
@ExperimentsInHonesty - From my research into this issue, using the GitHub REST API to get the info from the README.md file in the [hackforla/codeofconduct](https://github.com/hackforla/codeofconduct/blob/master/README.md) repo doesn't seem like a great solution because it would require a lot more work in terms of parsing the data and doing a lot of DOM manipulation.

I think I've come up with a good alternative, though. If we use a GitHub action created in the [hackforla/codeofconduct](https://github.com/hackforla/codeofconduct/blob/master/README.md) repo that triggers whenever the README.md file gets updated and uses GitHub REST API to copy that file's contents and create or update a corresponding .md file in the _includes directory of the website repo, we can then easily include that file on the code of conduct page while maintaining the markdown formatting from the original file. This would technically have a hard copy in the website repo, but its maintenance would be automated. I believe I've worked out the code to do this for the most part, but only someone who has write access to the [hackforla/codeofconduct](https://github.com/hackforla/codeofconduct/blob/master/README.md) repo would be able to implement it.

Does this suggestion accomplish what you wanted and sound like a good option to you, Bonnie? Let me know how you want me to move forward with this issue.

**Comment by bootcamp-brian** [comment]
Provide Update
1. Progress: Researched potential solutions for achieving the desired functionality but need input from leadership before proceeding any further.
2. Blockers: No other blockers.
3. Availability: Weekdays this week after 6pm.
4. ETA: Hopefully within the next week if we can decide how to proceed at Sunday's meeting.

**Comment by bootcamp-brian** [comment]
Provide Update
1. Progress: Discussed solution and got approval to implement, however it turns out I still need extra permissions to implement. Will be inquiring about this at tomorrow's meeting.
2. Blockers: Just what I mentioned in the progress report.
3. Availability: Weekdays this week after 6pm.
4. ETA: Within the next week.
