### ISSUE TITLE
Decision Record for HfLA's Code of Conduct branch

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4250]
### Overview
We need to have documentation of [HfLA Code of Conduct](https://github.com/hackforla/codeofconduct) being behind the master branch. For this issue, you will create a [Decision Record](https://github.com/hackforla/website/wiki/Decision-Records) for this so that we have transparency for our choice to keep the branch behind the master branch.

### Action Items
HfLA is no longer bound by Code for America's [Code of Conduct](https://github.com/codeforamerica/codeofconduct), so we are able to keep our own Code of Conduct without needing to update it to the latest CfA Code of Conduct. 

- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)

### Action Items to be completed when new wiki is ready
- [ ] Create a new Decision Record in [Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted)
- [ ] Follow the template to document this choice
- [ ] See [comment](https://github.com/hackforla/website/issues/4244#issuecomment-1480112022) on https://github.com/hackforla/website/issues/4244 for relevant analysis of the difference between CfA's and HfLA's Code of Conduct that should be documented
- [ ] Add a link to the DR in [Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted) 
- [ ] Update the main [Decision Records](https://github.com/hackforla/website/wiki/Decision-Records) page with a link to the new DR preceded by a ✅

### Resources/Instructions
- Associated ER for this issue: https://github.com/hackforla/website/issues/4243
- [HfLA Decision Records](https://github.com/hackforla/website/wiki/Decision-Records)
- [HfLA Code of Conduct](https://github.com/hackforla/codeofconduct)
- [Code for America Code of Conduct](https://github.com/codeforamerica/codeofconduct)

**Comment by ExperimentsInHonesty** [comment]
@jdingeman figure out where in this issue to add the notes that I put in this comment about the differences between CfA and HfLA Code of Conduct.  https://github.com/hackforla/website/issues/4244#issuecomment-1480112022  that analysis of the specific differences noted should be part of the DR.

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - added that as an action item

**Comment by vincentdang** [comment]
i. Availability: This Friday and weeknights next week.
ii. ETA: TBD (I still have questions haha).

**Comment by jdingeman** [comment]
Hi @vincentdang - please see update to contributing to the wiki.

**Comment by vincentdang** [comment]
(In progress)
This is a record in the [Decision Records on Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted).

Issue 

- HfLA is no longer bound by Code for America's [Code of Conduct](https://github.com/codeforamerica/codeofconduct), so we are able to keep our own Code of Conduct without needing to update it to the latest CfA Code of Conduct.

Problem Statement

- Need a new code of conduct specific only to HFLA and separate from Code for America.

Potential Solution

A new code of conduct needs to be drafted to stand as the main source of rules and regulation for HFLA members to adhere to.  

Thus, several issues were created in order to organize the development of a new Code of Conduct (coc).  They were as follows: differential analysis in order to identify key changes that will distinguish HFLA’s code of conduct from COA, create a new HTML page for it, create a decision record (this), and finally to make it go live.


When finished we should follow https://github.com/hackforla/codeofconduct instead of https://github.com/codeforamerica/codeofconduct

There are still some issues (including front end) causing the coc branch to be behind the masters.  See below.

Issue Summary:

- The New Code of Conduct page is planning on having a top nav and footer.

- There may be additional policy changes needed by June 1st, 2023.

- A dependency between coc pages exist (.md and non- .md) and needs to be redirected.

Notes:
 - A Spanish translation may come later.

Feasibility Determination

- The HFLA code of conduct has been implemented partially but still has issues and needs to be worked on.

**Comment by jdingeman** [comment]
Hi @vincentdang - sorry for the delayed response. This looks good! I'll go ahead and close this issue.
