### ISSUE TITLE
Create Donation Circle Component and Integrate with Donate Page 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4263]
### Dependency
- [x] #3983 

### Overview
Re implement the donation circles as HTML/CSS (without the use of a graphic file) to replace the current images that are being used, so that we can achieve higher WCAG compliance.

### Details
The display of functional text within an image is not WCAG compliant.  In this issue, the newly designed donation circles image  will be implemented using HTML/CSS (without the use of a graphic file), and the resulting component will replace the existing donation graphic found on the Donate page, in both mobile and desktop views. 

### Action Items
- [x] View the new donation circles graphic design in the Resources section below.  Also note the text for each circle is displayed in the Requirements section below.  If possible, fit in the few additional words displayed under Requirements
- [x] Create a new html file `_includes/donation/donation-circles.html` and add the html to render the donation circles component.  No img or svg tags should be used.  
- [x] In `pages/donate.html` replace the `<img>` tag with a liquid tag `{% include 'filename' %}` where `'filename'` references the new html file.  Note that 'filename' is relative to the `_includes` folder. 
- [x] Existing SCSS for the Donate page can be found at `_sass/components/_donate.scss`.  The SCSS for styling the new component should be placed in `_sass/components/_donate-components.scss`.  If this file does not exist, create it and add an import statement in `_sass/main.scss`.  Create SCSS classes that are unique and independent of the target pages, so that the component could be used on a variety of pages.  Update SCSS and HTML as needed so that the appearance of the modified Donate page matches the appearance of the current pages, for both mobile and desktop screen sizes. 
- [x] In `_sass/components/_donate.scss` delete any styles that are no longer used.   
 
#### Merge Team
- [x] Release dependency on #4544  
- [x] In Epic #4492, check off the dependency under "Creating/Integrating New Issues".  If all of the dependencies under that heading have been merged, then release dependencies on all the issues listed under "Clean Up". 

### Requirements
The circle above Monthly will have the words: Hosting, Mailing List services, Zoom, Meetup
The circle above Annual will have the words: Domain Names, Insurance
The circle above Occasional will have the words: Stickers, T-shirts

### Resources/Instructions
<details>
<summary> View the design to implement in the new component - however please try to fit in the additional text as specified in the Requirements section above</summary>

![image](https://user-images.githubusercontent.com/5314153/230799702-356590af-3a19-43fe-8dbc-fa2d6238ade0.png)
</details>

- HfLA Donate Page: [webpage](https://hackforla.org/donate) and [html](https://github.com/hackforla/website/blob/gh-pages/pages/donate.html)
- HfLA Join Us Page: [webpage](https://hackforla.org/join) and [html](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html)
- wiki page [Standardized Components](https://github.com/hackforla/website/wiki/Standardized-Components)
- [Donate Page Figma Design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24579-285100&t=BxoSIHc3NPIJKbZy-0)
- This issue is part of the Epic #4492
- For a discussion of WCAG SC 1.4.9 see https://www.w3.org/WAI/WCAG21/Understanding/images-of-text-no-exception.html
- [Liquid](https://jekyllrb.com/docs/liquid/) in Jekyll

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe There needs to be a mention in here that desktop and mobile are different layouts and they need to do both.  Also, please define the size label

**Comment by roslynwythe** [comment]
- @ExperimentsInHonesty  -  The donation image will change as part of the Donate page redesign implementation which is in progress in issue #3983 so perhaps this issue should have a dependency on that implementation.  Or, in this issue, should I reference the Figma design instead of the current Donate page?  Also, is it correct to assume that the new donation image will also be used on the Join Us page?

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge 

Please revise the title and the instructions for this issue so that it reflects this
 - The current image is https://github.com/hackforla/website/blob/gh-pages/assets/images/donate/donation-chart.svg
 - The image will be replaced with CSS/html that gets put into an include
 - Go to any page that currently uses it (Join and donation), and wherever the image is specified, change it out for the include.  Pages should look exactly the same when done.

- I have made an ER that summarizes the problems, see it for details https://github.com/hackforla/website/issues/4407

**Comment by JessicaLucindaCheng** [comment]
Overall, good job with writing this issue! Please change the following:
- [ ] Rewrite the Overview to be in a modified user format of ` We need to do X for Y reason` and you can move what you currently have into a Details section.
- [ ] For the first action item 
  > View the new donation circles graphic design in the Resources section below.

  I'm a little confused because the words in the image you provided and the words in the Requirement section don't match. Please clarify.
- [ ] It looks like for the 4th action item, you are adding `_sass/components/_donate-components.scss`. If a new SCSS file is added, it needs to imported into [_sass/main.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/main.scss). I'm not sure if you want the developer to figure that out on there own or want to mention that in the issue.
- [ ] In the Resources section, the [Donate Page Figma Design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?t=GNPDyHkt3KQSW7j0-0) links to the title page of the Figma design. It would be more helpful to link it directly to the design you want the developer to refer to.

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe Overall, good job writing this issue! Please change the following:
- [x] Rewrite the Overview to be in a modified user format of ` We need to do X for Y reason` and you can move what you currently have into a Details section.
- [ ] For the first action item 
  > View the new donation circles graphic design in the Resources section below.

  I'm a little confused because the words in the image you provided and the words in the Requirement section don't match. Please clarify.
- [x] It looks like for the 4th action item, you are adding `_sass/components/_donate-components.scss`. If a new SCSS file is added, it needs to be imported into [_sass/main.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/main.scss). I'm not sure if you wanted the developer to figure that out on their own or if you want to mention that in the issue.
- [x] In the Resources section, the [Donate Page Figma Design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?t=GNPDyHkt3KQSW7j0-0) links to the title page of the Figma design. It would be more helpful to link it directly to the design you want the developer to refer to.

**Comment by roslynwythe** [comment]
Thank you @JessicaLucindaCheng you raised excellent points.  My comments are below in bold.  To summarize, I created a comment to ask Bonnie about the second point, and I would appreciate your advice regarding the last point.  

> @roslynwythe Overall, good job writing this issue! Please change the following:
> 
> * [x]  Rewrite the Overview to be in a modified user format of ` We need to do X for Y reason` and you can move what you currently have into a Details section.
**Done**
> * [ ]  For the first action item
>   > View the new donation circles graphic design in the Resources section below.
>   
>   
>   I'm a little confused because the words in the image you provided and the words in the Requirement section don't match. Please clarify.
**Bonnie had created the Requirements section and I need to ask her about the discrepancy.**  
> * [x]  It looks like for the 4th action item, you are adding `_sass/components/_donate-components.scss`. If a new SCSS file is added, it needs to be imported into [_sass/main.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/main.scss). I'm not sure if you wanted the developer to figure that out on their own or if you want to mention that in the issue.
**Absolutely, I added that instruction to the Action Item**
> * [ ]  In the Resources section, the [Donate Page Figma Design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?t=GNPDyHkt3KQSW7j0-0) links to the title page of the Figma design. It would be more helpful to link it directly to the design you want the developer to refer to.
**That's a good point but I wonder if it is even useful to refer to the Figma design, since it is not 100% current and the dev could just refer to the live site for comparison.  Would it be ok if I delete the reference to Figma?**

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty In the Requirements section you had listed the text that should appear in each circle.  Jessica noticed that you included a few lines of text that do not appear on the Figma design.  In particular, in the Monthly circle you list Meetup and in Annual circle you list Insurance, neither of which appear on the Figma design.  Should we ask the dev to try to fit in the additional text?

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe 
> In the Resources section, the [Donate Page Figma Design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?t=GNPDyHkt3KQSW7j0-0) links to the title page of the Figma design. It would be more helpful to link it directly to the design you want the developer to refer to.
>> That's a good point but I wonder if it is even useful to refer to the Figma design, since it is not 100% current and the dev could just refer to the live site for comparison. Would it be ok if I delete the reference to Figma?

- I need clarification first to answer your question because I am a little bit confused. By the time a developer starts on this issue, are the circles's html and css suppose to be already implemented in #3983 - meaning the circles will exist in the stacked/vertical format? If yes, is this issue just to move around code to componentize it?

**Comment by roslynwythe** [comment]
> @roslynwythe
> 
> > In the Resources section, the [Donate Page Figma Design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?t=GNPDyHkt3KQSW7j0-0) links to the title page of the Figma design. It would be more helpful to link it directly to the design you want the developer to refer to.
> > > That's a good point but I wonder if it is even useful to refer to the Figma design, since it is not 100% current and the dev could just refer to the live site for comparison. Would it be ok if I delete the reference to Figma?
> 
> * I need clarification first to answer your question because I am a little bit confused. By the time a developer starts on this issue, are the circles's html and css suppose to be already implemented in [Implement Redesigned Donate Page (mobile and desktop) #3983](https://github.com/hackforla/website/issues/3983) - meaning the circles will exist in the stacked/vertical format? If yes, is this issue just to move around code to componentize it?

- Issue #3983 was just completed and the new circle stacked/vertical design appears on the Donate page as an svg.  In this issue it will be implemented with only html/css and componentized.  Please advise, what is the best way to have Bonnie look at the comment above about the extra text in the circles?  Would it be confusing to add "Ready for Product" to the issue?

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe 

> That's a good point but I wonder if it is even useful to refer to the Figma design, since it is not 100% current and the dev could just refer to the live site for comparison. Would it be ok if I delete the reference to Figma?

Since this issue is to implement the circles with HTML and SCSS, a developer may want to refer to the Figma design to help with styling/SCSS the circles. Thus, I think it would be better for the Figma design link to remain but be updated to go directly to the page with the design.

@JessicaLucindaCheng Ok I've updated the Figma link to go directly to the Donate page design.  

> Please advise, what is the best way to have Bonnie look at the comment above about the extra text in the circles? Would it be confusing to add "Ready for Product" to the issue?

You can add "Ready for Product" label. You may also want to copy and paste your question in a new comment below so it is the last comment in this issue. Also, you may want to hide any resolved or outdated comments too.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty 
- In your comment above you mention this design: https://github.com/hackforla/website/blob/gh-pages/assets/images/donate/donation-chart.svg but I have written this issue to implement the newer more vertical "stacked" circle design which is now displayed on the Donate page and is more accessible since it accommodates 16 pt text.  Please let me know if that needs to be changed.
<details>
<summary> View the design to implement in the new component</summary>

![image](https://user-images.githubusercontent.com/5314153/230799702-356590af-3a19-43fe-8dbc-fa2d6238ade0.png)
</details>

-  In the Requirements section you had listed the text that should appear in each circle.  Jessica noticed that you included a few lines of text that do not appear on the Figma design.  In particular, in the Monthly circle you list **Meetup** and in the Annual circle you list **Insurance**, neither of which appear on the Figma design.  Should we ask the dev to try to fit in the additional text?

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe 
> In the Requirements section you had listed the text that should appear in each circle. Jessica noticed that you included a few lines of text that do not appear on the Figma design. In particular, in the Monthly circle you list Meetup and in the Annual circle you list Insurance, neither of which appear on the Figma design. Should we ask the dev to try to fit in the additional text?

YES, and after you make that change to the issue, go ahead and move this to the top of the prioritized backlog (prioritized within other issues that are time sensitive)

**Comment by agosmou** [comment]
i. Availability: 4/25/23
ii. ETA: 4/27/23

**Comment by agosmou** [comment]
Created pull request. Awaiting review.
