### ISSUE TITLE
ER: what is the difference between 2 milestones that both deal with onboarding issues

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4369]
### Emergent Requirement - Problem
We need a note that explains to people who will prioritize issues what the difference is between Onboarding Flow and Team Workflow  milestones

### Issue you discovered this emergent requirement in
- #4350

### Date discovered 
2023-04-02

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@jdingeman @bonniewolfe 

### What happens if this is not addressed
Hard to prioritize

### Resources

- [Milestone page, sorted Alphabetically](https://github.com/hackforla/website/milestones?direction=asc&sort=title&state=open) see the descriptions for each milestone
- https://github.com/hackforla/website/issues/2607
- https://github.com/hackforla/website/issues/2316 -- issue that should resolve this ER

### Recommended Action Items
- [ ] Make a new issue to add a page to the wiki that explains how we use the milestones and what they mean.
- [ ] Add item to Discuss with DEV Lead /PM team to the agenda

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - this issue should take care of this ER 
- https://github.com/hackforla/website/issues/2316
Currently the wiki has unfinished pages for the Milestones and only links to the milestones for People Depot. Once the wiki is open for contributions, #2316 can be moved so that we can add the wiki explaining the milestones.

**Comment by ExperimentsInHonesty** [comment]
Closed because an issue already exists.
