### ISSUE TITLE
Add a Tools filter to the projects check page

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4427]
### Dependency

- [x] #4525
- [x] #4776
- [x] #4798
- [x] #4799
- [x] #4800
- [x] #4801
- [x] #4802
- [x] #4803
- [x] #4804
- [x] #4805 
- [x] #4806
- [x] #4807
- [x] #4808
- [x] #4809
- [x] #4810
- [x] #4811
- [x] #4812
- [x] #4813
- [x] #4814
- [x] #4913 

### Overview
We need to revise the filter dropdown menu to include a dropdown for Tools, so that we can use this page to see where we might need to moved projects values from tools to technologies, and vice versa

### Action Items
- [x] View the current filters dropdown menus on the [projects-check page](https://www.hackforla.org/projects-check/) 
- [x] Make appropriate changes to the following files to create a functional Tools filter dropdown menu
  -  [/_includes/current-projects-check.html](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects-check.html)
  - [/assets/js/current-projects-check.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js)
- [x] The style of the dropdown menu should mimic the existing dropdown menus for Technologies and Languages

#### Current Filters on projects-check page
![image](https://user-images.githubusercontent.com/88953806/230258281-d0cc8963-4206-4961-8327-2be733b83860.png)

#### Example of Tools vs. Languages and Technologies
![image](https://user-images.githubusercontent.com/88953806/230259139-6508966e-7d70-4966-b9d8-6a5896a1fff3.png)

#### For Merge Team/Tech Leads/PMs
- [x] When the PR linked to this issue has been merged, release the dependency on 
   - [x] #3487 
   - [x]  ~#4262~  
   Note: 4262 has dependency on 3487 
   - [x] #4960 

### Resources/Instructions
- [projects-check page](https://www.hackforla.org/projects-check/)
- This issue is part of an epic: #4434

**Comment by ExperimentsInHonesty** [comment]
@jdingeman I removed this text because I felt it was needed a more direct overview.  friendly reminder that an overview should be We need to do X for Y reason.

> When PMs update their project information, they are adding items to technologies instead of tools. If a team adds something to tools, it's not showing up in technologies, and renders the filters on the [projects-check page](https://www.hackforla.org/projects-check/) less useful.

- I reopened the ER 4261 because I see some steps missing
  - Once the epic is made, this issue should have a link to it.

**Comment by Sebster3** [comment]
**Availability**: M, T, Th 5:30PM-9:00PM
**ETA**: Friday 4/14

**Comment by Sebster3** [comment]
Hi @bonniewolfe, I need to get your input on how to proceed with a blocker I'm having with issue #4427. I've run the problem by Justin and he suggested that I ping you to help sort out next steps.

**The Problem**
During the process of adding the filter for **Tools** onto the projects check page, I've been unable to produce functional parity with the two existing filters (**Technologies** and **Languages**). I've discovered that the data for the two existing filters are saved as YAML lists in each project's markdown file, however the data for the new **Tools** filter is saved as a string of comma-separated values.
My Goal was to use the current implementation of the existing two filters onto the new filter in order to avoid rewriting the same functionality, but the implementation breaks when the string-based data is passed in.

**Some Possible Solutions**
1. The **Tools** data is restructured from a string into a list. This approach adapts the data to utilize the current filters' implementation, but would require editing files outside the scope of the issue—located within `/_projects`.
2. Write additional code that produces the same results and accepts the data as a single string.
3. Adapt the current implementation to accept both a list and a single string containing comma-separated values.

**The Suggested Solution**
We go with option 1, and restructure the data to be a list since this is what the current implementation accepts and is a relatively minor change that should be easy to bug test. There is the chance that some other part of the website, that neither myself or Justin are aware of, that relies on that specific data being contained in a single string.

The branch [add-projects-check-tools-filter-4427](https://github.com/Sebster3/hfla-website/tree/add-projects-check-tools-filter-4427) on my fork adds the new filter onto the page as per this issue. The additions are currently page-breaking, pending next steps.

The branch [fixes-for-breaking-changes-in-4427](https://github.com/Sebster3/hfla-website/tree/fixes-for-breaking-changes-in-4427) on my fork includes the additions of the previously mentioned branch as well as the proposed out-of-scope fixes for this problem.

**Comment by Sebster3** [comment]
Option 1 was selected as the plan moving forward. An emergent request has been made with a roadmap for identifying and addressing the impact of the proposed changes.

The emergent request: #4523

**Comment by pdimaano** [comment]
Availability: Weekday evenings
ETA: 9/5/23
