### ISSUE TITLE
Change logic to know which repositories to pull from if project has own GithHub org.

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#458]
### Overview
Some projects have multiple repositories (usually on their github org) vs the projects that are inside of hackforla's own github org which usually only have a mono repo.  Because of this we cannot pull the contributors or Languages in the same way.  

### Action Items
Define a logic that will allow us to indicate if a project has multiple repos
e.g., multiple-repo: true
and if it has its own org and multiple repo then it would run a different process for scraping the GitHub contributors and languages to instead scrape all the repos in their org.

### Resources/Instructions
affects: HelloGov, PublicTreeMap, Engage

**Comment by KianBadie** [comment]
I have a [repo](https://github.com/KianBadie/github-api-test/tree/orgs) where I code work for the github api. The branch I linked, thanks to some help from StackOverflow, get's contributors from multiple repos if the repo we have registered is part of a different org other than hfla. It combines the users contributions and sorts the contributors by how many contributions they made across the repos under their org. 

The next step is to create a branch on my fork of hfla and integrate the code from my testing repo into the context of the actuall hfla site. ETA as soon as possible. I will try to do it on Monday but might need a day or 2 extra.

**Comment by KianBadie** [comment]
Add requirement to fetch github projects that don't have the hack-for-la tag but we have the id. Example is work for la.

**Comment by KianBadie** [comment]
@ExperimentsInHonesty 
So I have the implementation of getting repos from orgs that are not hfla pretty much ready. I integrated it into a branch on my own fork and it works as expected. 

In regards to adding the implementation for getting repos that are not tagged "hack-for-la", it seems that we need to use an undocumented API endpoint. It works, but I just wanted to give a heads up with that. Here is an issue talking about it from 2014: https://github.com/octokit/rest.js/issues/163.

Here is an example of when using it with the Work for LA repo: https://api.github.com/repositories/79977929
Here are the docs the Repository api calls on GitHub: https://developer.github.com/v3/repos/ (no documentation on this endpoint).

I'll go ahead and work on it still. ETA on pull request is tomorrow, sorry for the lag.

**Comment by KianBadie** [comment]
@ExperimentsInHonesty 
So I think there is an unforeseen challenge. I don't think we are able to use Liquid/Jekyll in the github actions script because it is not being processed by Jekyll. It is being ran straight from github rather than being built by Jekyll. I have code that works that hardcodes a list of repos that are not tagged. So far the list has only one repo to account for Hack For LA. 

```
untaggedRepos = [79977929];
await github.getAllTaggedRepos();
await github.getUntaggedRepos(untaggedRepos);
```

I was thinking of maybe trying to do some work around with the fs module that we already import to write the github file in order to read the project card files and try to extract the id from them. It will just take some more time to figure out. And I was wondering if you wanted the solution I currently have to be implemented and work on that more this week.

**Comment by cnk** [comment]
Keeping a list of repos that do not have the 'hack-for-la' tag but that we want to track works. I might want to keep the id + the project name or github url because it will make it easier for humans to see which repos we are adding in. 

But my question for the multi-repo orgs is how we are going to aggregate the contributions from multiple repos and then attached them to one project page. The current method assumes a 1:1 relationship with the project card and the identification number in the github_date.json file. (You may have already solved that and I don't see it because I didn't run the code in your test repo.)

**Comment by KianBadie** [comment]
@cnk Are you saying to keep the something like the id + project name in the list of untracked repos for readability? My current plan/what I was working on was to parse each of the files in _projects and then use string manipulation to get the id. Doesn't seem impossible. It doesn't feel completely like the best practice though

And I'm sorry, I didn't understand the second point. I'll explain what I'm currently doing and hopefully that answers the question you brought up. I'm getting the contributors links from each project under an org that is separate from ours. Then I parse all that contributor data, combining contributions from the same users. And then it ends in one final list on contributors. Does that answer the question? Or are you asking how conceptually we are getting contributors from different repos and putting them as contributors on the repo we are displaying in a project home page?

**Comment by KianBadie** [comment]
Also, another thing to fiddle with. Trying to access files in our repo through Github actions isn't proving as straightforward as I thought it would be. Looks like it's executing in some external environment where it doesn't have access to other project files. I am confident there is a way to make it happen. But just wanted to give another heads up. Like I said earlier, I have code that works for both requirements, but the untaggedrepo ids are hardcoded. I can make a pull request and fix it in the near future

**Comment by cnk** [comment]
> Are you saying to keep the something like the id + project name in the list of untracked repos for readability?

Yes that is what I was suggesting. 

> Or are you asking how conceptually we are getting contributors from different repos and putting them as contributors on the repo we are displaying in a project home page?

Yes. Even if you combine all the contributors from all the projects from some other org (which might or might not be a safe assumption to make), how are you going to associate the whole org contributions with a Hack for LA project card?

**Comment by KianBadie** [comment]
***Update***
I made a pull request for this issue a couple days ago just in case the desire was there for it to be integrated. Here are some notes I added to that pull request, but I will add here as well: 

- Right now, the script is hardcoding the project id that is not tagged under "hack-for-la". In the future, we can parse the _projects directory using javascript to get the project ids we need.
- Getting the untagged repos by id is using an endpoint that has no documentation on the GitHub API docs. I made some comments about it here. Is that something that we want to discuss? Are we ok with that?
- The way I tried to test that it was indeed getting all the contributors was by manually adding the contributors from the Public Tree Map org and seeing if it matched up with the results from the script. It did, but I didn't test it with others. Not sure how to validate the data. I was thinking of making a script that added up the contributors and then I would compare that scripts results to this scripts results. But then I thought "isn't this current script doing what that validator script is going to do?" But I guess the validation script would have less going on in terms of code/functionality and if we get the same results it would provide some more confidence that the results from this script are correct.. If it would be better to make that, please let me know.

In response to what you brought up @cnk, yeah we could do that. I could edit my pull request on Monday for the script to work like that. Do you think getting all the project ids through the project cards using javascript and then checking which ids we did not fetch data for yet is a worthwhile functionality to have? And I see the point your making on the combining contributors. I was thinking of it like the Hack For LA project card represent the whole project itself rather than just the repo they decide to display, which could be their main repo. However, I am fine with the additions not going through. If it doesn't work out conceptually I'm fine with not having the pull request go through, so don't sweat about that :)

**Comment by ExperimentsInHonesty** [comment]
@cnk is going to review the PR that Kian has submitted today.  Kian and Bonnie to talk about administrative workflow for adding new projects that don't have mono repos (inside and outside hfla github org)
