### ISSUE TITLE
Add Donate button to HFLA website

### ISSUE THREAD

**Issue by wesrowe** [hackforla/website#472]
### Overview
Visitors to the site might want to donate to HfLA. We need to enable that.

### Action Items

- research placement of donation links on similar websites; hypothesis: main nav
- UX design

### Resources/Instructions
Link may be [Donate to a Brigade](https://www.codeforamerica.org/donate-to-a-brigade), or it may be the (currently broken) [Donate to Hack for LA](https://secure.codeforamerica.org/page/contribute/donate-to-a-brigade-today?source_codes=Brigade-page&brigade=Hack%20for%20LA%20Brigade) page.

https://www.codeforamerica.org/donate

**Comment by ExperimentsInHonesty** [comment]
@wesrowe The only link that ever worked was https://www.codeforamerica.org/donate 

It is my understanding that the url https://secure.codeforamerica.org/page/contribute/donate-to-a-brigade-today?source_codes=Brigade-page&brigade=Hack%20for%20LA%20Brigade is based off other brigades that have that, but those were setup individually for brigades, and one was never setup for Hack for LA.  CfA has said that they won't make that url work for us, so we will have to go with the https://www.codeforamerica.org/donate url.

@harishlingam  - Action item on this issue is for the two design team members to look at the existing website nav and decide where the donate button should be for the time being.  When we do the redesign we can spend more time researching where other websites put the button.

**Comment by ashlingam** [comment]
@yuikomajima @leestella748 Following on the above, we want to decide where a Donate should be located on the home page, as well as any other locations on the website. We can discuss this on Sunday's call.

**Comment by leestella748** [comment]
@ExperimentsInHonesty I found this link https://donorbox.org/hackforla through a Github branch, though clicking on the logo in the corner leads to https://www.hacker.fund rather than our website.

**Comment by ExperimentsInHonesty** [comment]
hackforla.org/donor route needs to be redirected to https://www.codeforamerica.org/donate
add donor button to top right of page (replacing social media icons) (in black, turns red on hover)
add donor button on bottom to the right of Follow us (in pink)

**Comment by yulia-kh** [comment]
progress:
Button added to nav bar and footer. When clicked it redirects you https://www.codeforamerica.org/donate
<img width="797" alt="Screen Shot 2020-05-24 at 8 21 19 AM" src="https://user-images.githubusercontent.com/13112628/82757954-6e56e600-9d98-11ea-8a69-412d0d8e9f1c.png">

    blocks:
Can't figure out css for mobile. Need help with passing conditional style to {% include %}

    availability:
Tuesday 7:00-8:00pm
Saturday 9:00-12:00pm

    ETA:
Next week

**Comment by yulia-kh** [comment]
That's what I've got on mobile

<img width="361" alt="Screen Shot 2020-05-24 at 10 07 15 AM" src="https://user-images.githubusercontent.com/13112628/82760145-90effb80-9da6-11ea-879a-be6e04c371f9.png">
<img width="361" alt="Screen Shot 2020-05-24 at 10 07 32 AM" src="https://user-images.githubusercontent.com/13112628/82760151-96e5dc80-9da6-11ea-8404-699daea355e0.png">

And on desktop

<img width="944" alt="Screen Shot 2020-05-24 at 10 07 56 AM" src="https://user-images.githubusercontent.com/13112628/82760154-9b11fa00-9da6-11ea-88ab-a60f232ead1e.png">

**Comment by ExperimentsInHonesty** [comment]
@yulia-kh move donate button up to align with text, @KianBadie will review.
