### ISSUE TITLE
Create wiki page to document test procedure for issues that modify issue templates

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4786]
### Overview
We need to document the process for testing issues that modify issue templates.  

### Action Items
- [x] Write a wiki page describing the process for testing issues that modify issue templates, based on  https://github.com/hackforla/website/issues/4307#issuecomment-1549888931
- [x] Do not include the last item "Copy these sections from the Issue into the PR" and the subitems
- [x] As described in the Resources below, a draft wiki page will be created in a comment within this issue.  When the draft wiki page is ready for review, move this issue into the `Questions/In Review` column.  

### Resources/Instructions
- We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Follow the instructions give in  [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)

**Comment by Ris345** [comment]
Availability: 08/08/23
ETA: 09/08/23

**Comment by Ris345** [comment]
### Testing issue templates


- Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example:  `git push --set-upstream origin test-update-labels-1234`  
- The response from the push command will include the URL for creating a pull request. Copy/Paste the URL for creating the Pull Request for later.  
- Browse to your fork of the website repository and click Settings 
  <details><summary>Screenshot of Repository Settings</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/8ecf2e55-2187-4ab9-acf1-2fd7548291a1)

  </details> 
- Change the default branch to the new issue branch
  <details><summary>Screenshot of Default Branch Setting</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/945fe02e-035f-4215-9c25-1d46c209d8c0)

  </details> 
- Further down on the settings page under Features, check the Issues checkbox
  <details>
  <summary>Screenshot of Issues Checkbox</summary>

  <img width="1465" height="823" alt="Image" src="https://github.com/user-attachments/assets/301dc157-f9bf-4cea-b46d-1f4241c70387" />

  </details>

- Browse to the Issues page, then click Labels
  <details><summary>Screenshot - creating labels in the test Repo</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/208e1b07-2478-4ed3-98a1-207de58d25c5)

  </details> 
- Create labels corresponding to each label that was listed in the updated issue template. The color of the labels don't have to match those on the `hackforla/website` repository, but the text of the labels must match exactly.  
- From the Issues page, click "New Issue" then locate the template updated by your issue, and click "Get Started" to open the issue template. 
- Copy/Paste the URL of the updated issue template and save for later use.  
- Verify the appearance of the issue template.
- Complete the PR process by visiting the URL saved from the push command.
- In the PR copy/paste this text immediately before the section "Screenshots of Proposed Changes Of The Website"
 ```
 ### For Reviewers
- Use this URL to check the updated issue template: [URL OF ISSUE TEMPLATE]
```
- Replace the text in the square brackets (as well as the square brackets) with the URL of the updated issue template

**Comment by LRenDO** [comment]
Hi @Ris345!

I am assuming this is ready for review even though the last check box was unchecked since it looks pretty close complete and there is no question in the comments.

This looks good overall!  You copied the correct parts of the instructions and created a draft in a comment in this issue.

I only have a few changes to request.
- [ ] change the checkboxes to bullet points as this is more consistent with our wiki
- [ ] change the title to something like "Testing updated issue templates" to be more consistent with how our wiki is written
- [ ] add a link to the comment with the draft in it to the [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) page

You can tag me in a separate comment once you make the changes.

Thanks for contributing to the wiki!

**Comment by Ris345** [comment]
@LRenDO Thanks for the feedback I made the suggested change,  but not certain if the link I added is suppose to be that way?

**Comment by LRenDO** [comment]
Hi @Ris345! 

Thanks for updating! The bullet points look great! 

Let me clarify what you need to do for the title and link. 

The title you had before was good. There is no need to mention the wiki in the title because the instructions you’re creating don’t modify the wiki. I just mentioned the wiki to explain why I requested the changed. 

The change itself was only to adjust the title to something like “Testing updated issue templates"

For the link, please read the [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) page, in particular the `Creating a new wiki page` section. 

On that same page you will see links at the bottom. You need to add a link to the bottom of that list of links by editing the wiki page. The URL should go to the comment that contains your draft above. 

You can get the URL for the comment by clicking the `…` in the top right corner of your comment with the draft. 

For the link, there does not need to be a link added in the comment/draft you wrote. You can delete the link you added and change it back to the original "REPLACE THIS TEXT WITH URL OF THE ISSUE TEMPLATE ON THE TEST REPO"

Please let me know if you have any questions. Happy to clarify.

Edit: Apologies, writing this on my phone and it got a little funky. Tried to clean it up.

**Comment by Ris345** [comment]
@LRenDO Thanks for the comments still confused about what I should do with the link and how to create a draft the three dots only show copy link or reference in new issue.

**Comment by LRenDO** [comment]
Hi @Ris345! Title update looks great! Below is a step by step instruction for adding the link to the [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) page. If you're still having trouble, let me know and we can connect on Slack. I'm available on and off today.

- [x] Copy the URL of the comment that contains your draft. You can do this by:
  - [ ] Clicking the `. . .` button in the upper right hand corner of the comment that contains the draft as pictured below
  - [x] Clicking `Copy Link` on the drop down menu as pictured below
![Image of menu](https://github.com/hackforla/website/assets/59513509/98e1c27c-ec09-489e-bdfc-10ffc470bc5f)

- [x] Go to the [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) page
- [x] Click the edit button pictured below
![Image of edit button](https://github.com/hackforla/website/assets/59513509/2019e902-3a70-4266-b7d9-aaa19a2d78a2)
- [x] At the very bottom of the page add your link in the markdown link format that uses brackets and parentheses  `[REPLACE THIS TEXT WITH TITLE OF YOUR DRAFT](REPLACE THIS TEXT BY PASTING COPIED URL HERE)`.
- [x] Click `Save`
- [x] Confirm that it has been added at the end and it is displaying and linking properly

It should be all set after that!

**Comment by Ris345** [comment]
@LRenDO Thank you for these extremely clear instructions, I think I completed all the necessary steps. Let me know if I am missing anything.

**Comment by LRenDO** [comment]
@Ris345 Awesome! Glad we got there! Looks great. The draft is now correctly linked on the How to contribute to the Wiki page. Thanks for making the changes!

**Comment by mocodesss** [comment]
In this comment: https://github.com/hackforla/website/issues/4786#issuecomment-1670584024, the screenshot associated to "Further down on the settings page under Features, check the Issues checkbox" > "Screenshot of Issues Checkbox" does not show a screenshot of the Issues Checkbox. Instead, it is the same screenshot from the step above it showing the Default Branch Setting. 

Here are screenshot of the Issue Checkbox:
<details>
<summary>Dark mode</summary>

<img width="1655" height="907" alt="Image" src="https://github.com/user-attachments/assets/a9366a5c-1ddb-4ce1-a361-5c4b6003b88f" />

</details>
<details>
<summary>Light mode</summary>

<img width="1465" height="823" alt="Image" src="https://github.com/user-attachments/assets/301dc157-f9bf-4cea-b46d-1f4241c70387" />

</details>


I am happy to change this but will first ask about it in Slack in case there is a process for doing so that I should be following.

**Comment by daras-cu** [comment]
@mocodesss thanks for flagging this, you can go ahead and change the screen shot
