### ISSUE TITLE
Update wiki page for GitHub Action: "add update label weekly" 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4856]
### Overview
We need to review and update the wiki page for the GitHub Action `add update label weekly`.   In particular we need to create three new sections that have recently been added to the GHA wiki page template:  "Labels", "Dependencies" and "Test Procedure".  

### Action Items
- [x] Become familiar with [HfLA's GitHub Actions main wiki page](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) and [HfLA GitHub Actions wiki page](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions).
- [x] Become familiar with [add update label weekly wiki page](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly).  Follow links to the `yml` and `js` files and understand the logic of the GHA.  
- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki).  Following the process given in [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) when completing the remaining Action Items.  
- [x] On [HfLA GitHub Actions wiki page](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions) make any necessary updates to the summary of `add update label weekly`, then review/update the [GHA: add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly) page for accuracy and completeness, and add the new sections
  - [x]  "Labels" - List those labels on which the GHA depends or affects.  
  - [x]  "Test Procedure" - Detail the process for testing the GHA in case there is a code change or a change in a dependent label, resource or package.  

### Resources/Instructions
- This issue was create as a result of #6403
- [HfLA's GitHub Actions main wiki page](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) 
- [HfLA GitHub Actions wiki page - with index to GHAs ](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)
- [add update label weekly wiki page](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly).
- [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)

- Additional notes that may be helpful are here: [Issue 6355 comments](https://github.com/hackforla/website/issues/6355#issuecomment-1958771755)

**Comment by kiran98118** [comment]
1. I just started working on this project. Understood the description and read the steps to do.
2. No difficulties yet
3. I have 6-8 hrs to work on this project this week
4. By the end of this week

**Comment by w1ld-r** [comment]
Availability: Weekdays 9AM - 8PM CST
ETA: Sunday 3/3 10PM CST

**Comment by w1ld-r** [comment]
Friday 3/1 Update: I've updated my ETA from EOD today to Sunday 3/3 because my schedule changed unexpectedly.

**Comment by w1ld-r** [comment]
# Schedule Friday 0700<br><sub>(aka "Add Update Label Weekly")</sub><br><sub>Workflow</sub>
## Summary
The `add update label weekly` GitHub Action checks the in-progress column from the project board and goes through each issue. If there is an assignee, it checks the timeline for the issue. If the issue is inactive for 7 days, it posts a comment to update the issue and ensures the label is changed to `To Update !`. If it inactive for 2 weeks, it adds the `2 weeks inactive` label. Otherwise, it add the `Status: Updated` label. It removes all related labels if the ticket is updated between 3 and 7 days, the ticket was recently assigned, or a PR was submitted for the issue.

### Trigger
- Scheduled to run every Friday at 0700 UTC / 1200 am PDT 

### Labels:
- `Status: Updated`
- `To Update !`
- `2 weeks inactive`

### Workflow Files 
- [schedule-fri-0700.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-fri-0700.yml)
  - [add-label.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/add-label.js)
  - [update-instructions-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/update-instructions-template.md)

#### Supporting Files/Folder  
- [add-update-label-weekly folder](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule/add-update-label-weekly)
    * In the above folder, the [add-label.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/add-label.js) file references the following files:
      * [update-instructions-template.md ](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/update-instructions-template.md) (in add-label-weekly folder)
      * [find-linked-issue.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/utils/find-linked-issue.js) (in utils folder)
      * [get-timeline.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/utils/get-timeline.js) (in utils folder)

### Process
Every Friday at 7:00 AM, the `add update label weekly` GitHub Action checks the in-progress column from the project board and goes through each issue. If there is an assignee, it checks the timeline for the following:
- If there is an update within **3 days**, it adds the `Status: Updated` label
- If the ticket inactive for **7 days**, it posts a comment requesting the assignee to update the issue and changes the label to `To Update !`
- If the ticket is inactive for **14 days**, it adds the `2 weeks inactive` label
- **It removes all related labels if:** (a) the ticket is updated between 3 and 7 days, (b) the ticket was recently assigned, or (c) a PR was submitted for the issue

## Test Procedure

### Getting Started:

1. Become familiar with the GHA testing process by reading the resources in the "Testing Resources" section below, as well as this GHA's files in the "Supporting Files/Folder" section.
2. Copy the HfLA project board in your forked repo if you don't already have it.
3. Add any test issues to `In Progress (actively working)` column.
4. Create any PRs needed to check the open and closed PR conditions.
5. Create an action secret `TEST_COLUMN_ID` where value is the `In Progress (actively working)` column ID on your forked board.

### Modify Files:

6. In [schedule-fri-0700.yml](https://github.com/hackforla/website/blob/9913ae68a679067f006dfcd4055e23cd009b5474/.github/workflows/schedule-fri-0700.yml) file:
      - Change `secrets.IN_PROGRESS_COLUMN_ID` to `secrets.TEST_COLUMN_ID` in `schedule-fri-0700.yml` file to avoid unexpected behavior.  (OUTDATED & Needs Revision)
      - Set schedule for manual testing.
    <details><summary>adding `workflow-dispatch` to enable manual trigger</summary>

    ![image](https://github.com/hackforla/website/assets/5314153/1e6e8bb3-aeac-4f1a-969f-200dc61eedc4)

    </details> 

7. Adjust cut-off times for status labels in [add-label.js](github/github-actions/trigger-schedule/add-update-label-weekly/add-label.js) as needed:
    <details>
    <summary>To test the "Status: Updated" label condition</summary>
    <br />

    **Replace this:**

    ```
    threeDayCutoffTime.setDate(threeDayCutoffTime.getDate() - updatedByDays)
    ```
    
    **With this:**
    ```
    threeDayCutoffTime.setDate(threeDayCutoffTime.getDate() - updatedByDays + 3)
    ```
    
    **NOTE:** This retains the label so the issue must already be labeled `Status: Updated` to begin with. It also requires a comment from the assignee.
      </details>
      
      <details>
      <summary>To test the "To Update !" label condition</summary>
      <br />

      **Replace this:**

      ```
      threeDayCutoffTime.setDate(threeDayCutoffTime.getDate() - updatedByDays)
      const sevenDayCutoffTime = new Date()
      sevenDayCutoffTime.setDate(sevenDayCutoffTime.getDate() - commentByDays)
      ```
      
      **With this:**

      ```
      threeDayCutoffTime.setDate(threeDayCutoffTime.getDate() - updatedByDays + 5)
      const sevenDayCutoffTime = new Date()
      sevenDayCutoffTime.setDate(sevenDayCutoffTime.getDate() - commentByDays + 7)
      ```
      </details>
      
      <details>
      <summary>To test the "2 weeks inactive" label condition</summary>
      
      <br />

      **Replace this:**
      ```
      threeDayCutoffTime.setDate(threeDayCutoffTime.getDate() - updatedByDays)
      const sevenDayCutoffTime = new Date()
      sevenDayCutoffTime.setDate(sevenDayCutoffTime.getDate() - commentByDays)
      const fourteenDayCutoffTime = new Date()
      fourteenDayCutoffTime.setDate(fourteenDayCutoffTime.getDate() - inactiveUpdatedByDays)
      ```
      
      **With this:**
      ```
      threeDayCutoffTime.setDate(threeDayCutoffTime.getDate() - updatedByDays + 7)
      const sevenDayCutoffTime = new Date()
      sevenDayCutoffTime.setDate(sevenDayCutoffTime.getDate() - commentByDays + 9)
      const fourteenDayCutoffTime = new Date()
      fourteenDayCutoffTime.setDate(fourteenDayCutoffTime.getDate() - inactiveUpdatedByDays + 14)
      ```
      </details>

### Run Tests:

8. Push changes.
9. Set default branch to feature branch.
10. Run workflow manually and check results.

## Testing Resources
- [How to Review GitHub Actions Pull Requests](https://github.com/hackforla/website/issues/4867#issuecomment-1732198461)
- [Hack for LA's GitHub Actions tip section](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tips)
- [Adding an action secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)

**Comment by w1ld-r** [comment]
Added link to the comment above to [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki/_edit)

**Comment by LRenDO** [comment]
Hi @gaylem! 

Great work on this so far! 
- Links are working correctly
- The link to the draft was added correctly to the "How to Contribute to the Wiki" page
- The summary of changes was very helpful

I do have a couple changes to request.
- It looks like this action also adds the `2 weeks inactive` label. 
  - add it to the description in your draft for the GHA: add update label weekly.
  - use the same process to add as you did with the comment above for the  [HfLA GitHub Actions wiki page](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions). 
- In the action items, it said to add two sections. I might have missed it, but it looks like they are not included. 
  - "Labels" - List those labels on which the GHA depends or affects.
  - "Test Procedure" - Detail the process for testing the GHA in case there is a code change or a change in a dependent label, resource or package.

In addition to the links provided in the issue, you may find [this tips section](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tips), [this wiki draft](https://github.com/hackforla/website/issues/4867#issuecomment-1732198461) and [this old PR](https://github.com/hackforla/website/pull/4908) helpful for writing up testing instructions.

When you're finished with the changes you can move the issue back to the `Questions / In Review` column and add the `ready for dev lead` label. Feel free to ping me here or on Slack for any help or clarification! Thanks again for taking on this issue!

**Comment by w1ld-r** [comment]
Hey @LRenDO, thanks for your feedback. I was honestly a little confused about this ticket. Here's what isn't making sense to me:

1. Are you saying I should add all the labels from [add-label.js](https://github.com/hackforla/website/blob/9913ae68a679067f006dfcd4055e23cd009b5474/github-actions/trigger-schedule/add-update-label-weekly/add-label.js) to my updated instructions like this? Is there anything else I need to do?

> ### Labels 
> - statusUpdatedLabel = 'Status: Updated'
> - toUpdateLabel = 'To Update !'
> - inactiveLabel = '2 weeks inactive'

2. I'm not sure what you mean by "use the same process to add as you did with the comment above for the HfLA GitHub Actions wiki page." Can you clarify?

3. Sorry about missing the testing part, I think I thought the process section sort of covered that but now I see it's more complex. I'm going to have to dig into that a bit but I'll work on it today.

Thanks!

UPDATE: I made some changes to my updated instructions, let me know if they're on the right track!

**Comment by LRenDO** [comment]
Hi @gaylem!

Let me see if I can clarify those areas. 

1. I believe what you have is pretty much what they are looking for in terms of labels. You probably don't need to add the variable name - just a list of the labels (i.e. only the Status: Updated part of the first one). I haven't taken a deep dive into this GHA in a while but I believe it might also use 'Status: Updated'. If you haven't already, I would just double check the code and make sure there  aren't any other labels in there.

2. Ah yes, let me clarify. I just meant to use the process outlined in the "How to Contribute to the Wiki" page to update the description on the [HfLA GitHub Actions](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions) wiki page. The way you did for the "GHA: Update Label Weekly" page. 

3. All good! I had to read through the issue a few times to get a good handle on all the things it was asking for. 

Again, feel free to reach out for help or clarification!

**Comment by w1ld-r** [comment]
Thanks for your quick response, @LRenDO! 

1. I reviewed the add-label.js file and I'm only seeing the three I listed there. I've updated my instructions per your recommendations. 

2. I'm still a little confused, so let me know if this is correct: I thought this ticket was to update the add update label weekly section (see image below) and provide updated instructions for the [GHA:-add-update-label-weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly) page, which I did in the comments of this PR. Is there another page I'm supposed to edit? Or are you saying I need to to update the description below? I didn't make any changes because it seemed fine as is but let me know if I'm just misunderstanding.

> <img width="926" alt="Screenshot 2024-03-07 at 8 55 26 AM" src="https://github.com/hackforla/website/assets/76500899/0e2c1aa7-7d1c-47f2-9777-eab91d48e643">

3. As for testing, I don't think I know enough about testing GH Actions to do this part effectively. I've copy/pasted what you wrote [here](https://github.com/hackforla/website/pull/4908). Let me know if that is sufficient, or if maybe I should hand this back to someone else to finish?

**Comment by w1ld-r** [comment]
@LRenDO Ope I'm dumb, I just re-read the add update label weekly description and realized it's missing the other labels. Please disregard my previous question in #2 above, I'll make the changes.

**Comment by w1ld-r** [comment]
Hey again @LRenDO -- I think I've made some progress. Let me know if this is sufficient: https://github.com/hackforla/website/issues/4856#issuecomment-1974826346

Some more questions:

1. Should I put the summary updates in a separate comment?
2. Do I need to add a link for the summary to this page? https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki

Thanks again for your patience and help with this!

**Comment by LRenDO** [comment]
Hi @gaylem! Looks like it's coming together! The Labels section looks great!

- Great questions! Yes, on both 1 & 2:
   - The "Updated summary for add update label weekly in [HfLA GitHub Actions](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)" should be in a separate comment and should also include the entire page so that it can be completely replaced by the comment text.
   - The link to that comment should also be included in the "How to Contribute to the Wiki" page.
  - For both drafts you can remove the "Updated ... " line so that the only text in the comments is what will be moved to the new wiki.

- I have a few requests for the testing section
  - Change title to "Test Procedure" (to be consistent since the issue uses that term, it's likely we want this to be consistent across the GHA Wikis)
  - Include an overview of the process something like:
    - Become familiar with the GHA testing process by reading the resources in the Testing Resources section and this GHAs files in the "Supporting Files/Folder" section.
    - Copy the HfLA project board in your forked repo if you don't already have it.
    - Add any test issues to `In Progress (actively working)` column 
    - Create any PRs needed to check the open and closed PR conditions
    - In YAML file
      - Change `secrets.IN_PROGRESS_COLUMN_ID` to `secrets.TEST_COLUMN_ID` in YAML file so as not to avoid unexpected behavior
      - Set schedule for manual testing
    - Create an action secret `TEST_COLUMN_ID` where value is the `In Progress (actively working)` column ID on your forked board
    - Adjust cut off times for status labels as needed (This a summary section and include what you have in the testing section so the code blocks can be toggled)
    - Push changes
    - Set default branch to feature branch
    - Run workflow manually and check results

  - Add a section for testing resources that includes:
    - [How to Review GitHub Actions Pull Requests](https://github.com/hackforla/website/issues/4867#issuecomment-1732198461)
    - [Hack for LA's GitHub Actions tip section](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tips)
    - [Adding an action secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)

Again, feel free to ping me!

**Comment by w1ld-r** [comment]
#### Workflows are yaml files
#### Supporting files can be
* js
* json
* md
* gitkeep

### Template for GHA documentation
```
## Summary
### Scheduled
-
### Workflow
-
### Supporting Files/Folders
-
---
Back to [HfLA GitHub Actions](HfLA-GitHub-Actions)

```

### Hack for LA's GHAs
#### [add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly)
- Checks the in-progress column from the project board and goes through each issue. If there is an assignee, it checks the timeline for the issue. If the issue is inactive for 7 days, it posts a comment to update the issue and ensures the label is changed to `To Update !`. If it inactive for 2 weeks, it adds the `2 weeks inactive` label. Otherwise, it add the `Status: Updated` label. It removes all related labels if the ticket is updated between 3 and 7 days, the ticket was recently assigned, or a PR was submitted for the issue.

#### [github data](https://github.com/hackforla/website/wiki/GHA:-github-data)
- Generates a new github-data.json and commits that to the repository

#### [issue trigger](https://github.com/hackforla/website/wiki/GHA:-issue-trigger)
- Check if an issue has the three required labels. If not, add the 'missing' labels and post a comment about adding missing labels. If the issue has all, post a comment that congratulates and gives more details about the project board

#### [lint-scss](https://github.com/hackforla/website/wiki/GHA:-lint-scss)
- Checks and lints modified scss files in PRs

#### [move closed issues](https://github.com/hackforla/website/wiki/GHA:-move-closed-issues)
- Moves a closed issue into either the QA or Done column of the project board. If the issue has a “hard” label (Feature: Refactor CSS, Feature: Refactor HTML, Feature: Refactor JS / Liquid, Feature: Refactor GH), the issue is moved to the Done column. If the issue has no “hard” labels but does have an “override” label (role: front end), the issue is moved to the QA column. If the issue has no “hard” or “override” labels and does have a “soft” label (role: back end/devOps, Feature: Analytics), it is moved to Done. All other issues are moved to QA

#### [pr instructions](https://github.com/hackforla/website/wiki/GHA:-pr-instructions)
- Creates an instruction on how to get a copy of a PR branch for review, then uploads the results into an artifact

#### [pull request trigger](https://github.com/hackforla/website/wiki/GHA:-pull-request-trigger)
- An open script that could be triggered when a pull request is closed on the following branches 'gh-pages', 'feature-homepage-launch', 'feature-tech-dropdown'

#### [set pr labels](https://github.com/hackforla/website/wiki/GHA:-set-pr-labels)
- RegEx takes the issue number on the body of the PR, and uploads the results (including labels on the issue) into an artifact

#### [update team members](https://github.com/hackforla/website/wiki/GHA:-update-team-members)
- Trim inactive members from the write team

#### [vrms data](https://github.com/hackforla/website/wiki/GHA:-vrms-data)
- Generates a new vrms_data.json and commits that to the repository

#### [wr pr instructions](https://github.com/hackforla/website/wiki/GHA:-wr-pr-instructions)
- Leaves a comment on new PRs with a link to the relevant documentation for reviewing PRs and the command line instructions for pulling down a new branch for review.

#### [wr pull request trigger](https://github.com/hackforla/website/wiki/GHA:-wr-pull-request-trigger)
- An open script that should house all the other scripts (workflows) that should be triggered when a pull request is closed.

#### [wr set pr labels](https://github.com/hackforla/website/wiki/GHA:-wr-set-pr-labels)
- This workflow is triggered when workflow [Set PR labels] is completed. Downloads artifact for the completed workflow. Then, gets the PR and issue number from the downloaded artifact and uses an API request to get the labels. Lastly, puts the same labels into the PR.

### Deprecated GHAs

#### [no-labels-template.md](https://github.com/hackforla/website/issues/2898)
- Removed the no-labels-template.md file so that the total number of bot comments are reduced, and developers would have less notifications. Edited lines 47-55 in post-labels-comment.js so that no comment object was created when all the correct labels were added, and therefore no comment is posted. 

---


### extra folders or files with unknown workflows
* Supporting Files Folder: [trigger-schedule](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule) - folder has one file ```.gitkeep``` and its empty - The .gitkeep was likely added as a way of forcing git to track the new empty directory when the person who created the GHA began working on it. This is not a supported feature of git and now that there is content in the directory, there is no real need for the .gitkeep file
The commit message for the .gitkeep file is just “Create directory for gha refactor”

**Comment by LRenDO** [comment]
Hi @gayle! Great work! Both of the drafts look great and they are both linked correctly on the "How to contribute to the wiki" page.  Thanks again for taking the time to work on this issue and contribute to our wiki!
