### ISSUE TITLE
Update GHA wiki page with new section "How to review GHA Pull Requests"

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4867]
### Overview
We need to add a section to the HfLA GitHub Actions wiki page to guide developers in the process of reviewing GitHub Action issues.  

### Action Items
- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)
- [x] Using the process outlined above, draft a new section of the [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) page, titled "How to Review GitHub Actions Pull Requests".  Include these subsections:
   - [x] Creating a test branch on your fork
   - [x] Modifying Repository Settings and Labels 
   - [x] Creating your own Project Board (link to Tip 6)
   - [x] Using Personal Access Tokens to test in your own Project Board (link to Tip 7)

### Resources/Instructions
[Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) 
[HfLA GitHub Actions - detail](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)

**Comment by nnr-nnr** [comment]
i. Availability: Sunday 9am–12pm PT, Monday 3pm–6pm PT
ii. ETA: Tues 8/1

**Comment by nnr-nnr** [comment]
1. Progress: have familiarized self with pre-reads
2. Blockers: N/A
3. Availability: Sunday 8/6 11-1PM ET
4. ETA: Sunday 8/6
5. Pictures: N/A

**Comment by meru-a** [comment]
i. Availability: In the evenings & weekends
ii. ETA: 09/23/2023 at the latest

**Comment by meru-a** [comment]
# How to Review GitHub Actions Pull Requests
## Step 1: Creating a test branch on your fork 
### 1.1. Create a new branch for testing
First, make sure your `gh-pages` branch in your fork is synced to the original HfLA repository. 

Then, create a new branch in your updated local repository where you will apply the changes from the pull request. You can name the branch something descriptive that includes the original branch name, for example:
```
git checkout -b test-gha-{INSERT_NAME_OF_BRANCH} gh-pages
```
### 1.2.  Pull the suggested changes:
Get the changes from the pull request into your test branch. Replace {INSERT_NAME_OF_BRANCH} with the author's branch name you want to test:
```
git pull https://github.com/{INSERT_NAME_OF_OWNER}/website.git {INSERT_NAME_OF_BRANCH}
```
### 1.3 Push the test branch:
Once you apply any other the issue-specific edits in `.yml` files necessary to trigger the GitHub Actions, push the test branch with the applied changes to your forked repository on GitHub:
```
git push origin test-gha-{INSERT_NAME_OF_BRANCH}
```
## Step 2: Modifying Repository Settings and Labels
In the "Settings" of your forked repository, make sure to change your "Default branch", and select the button with the arrows to switch you default branch to the newly created branch `test-gha-{INSERT_NAME_OF_BRANCH}` and update to it.

**Important:** when you are done testing make sure to repeat these steps to re-select "gh-pages" as your default branch.
<details>
<summary>Settings page of the repository.</summary> 

![Settings page](https://github-production-user-asset-6210df.s3.amazonaws.com/20477610/270084494-9bd8ed9d-42f4-4f17-9c7e-1ce74202c003.png)
</details>

There are also few other settings and configurations you may need to adjust depending on the action in review:

- Security policies 
- Branch protection rules
- Issues
- Pull request (PR) templates
- Creating necessary labels

Modifying these settings will make sure that your forked repository is aligned with the `hackforla/website` repository and you can properly test the changes made by the GitHub Actions. You may need to consult with the [HfLA-GitHub-Actions](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions) page, because understanding action can help decide what modifications will be needed to test it.

## Step 3: Creating your own Project Board
Follow the steps to [create your own Project Board copy](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board) for testing.

## Step 4: Using Personal Access Tokens to test in your own Project Board
You will need to [create your own Personal Access Tokens](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-7-using-personal-access-tokens-to-test-in-your-own-project-board) in your forked repository to ensure that the workflow can access it. It is also a best practice to give your secret an expiration date.

**Important:** when you are creating your own token, do not give your token the same name that you see in the yaml file, otherwise unexpected behavior may result. Any other name is OK (for example, TEST_TOKEN).

<details>
<summary> Monitor the workflow runs in the "Actions" tab of your forked repository to ensure that it works as expected.</summary>

![Actions tab](https://github-production-user-asset-6210df.s3.amazonaws.com/20477610/270083797-d568e7d9-b856-415e-9848-aaa6b6aca116.png)
</details>

**Comment by LRenDO** [comment]
Hi @pearlescence-m ! Great job with this issue! I'm assuming it's ready for review since you have completed all the steps. Adding the `ready for dev lead` label and adding it to the `Questions / In Reveiew` column as you did will notify us it's ready to be reviewed. If I got this wrong though, please let me know if there is something specific you would like help with.

- Formatting and wording aligns well with current Wiki Docs
- 4 topics on the issue are covered
- Descriptions are very clear
- Comment is linked in the `How to Contribute to the Wiki` page
- The issue was moved to the correct column for review

I have a couple relatively minor requests.
- [x] Update the images. They are not working properly.
- [x] This may be a little nit-picky but, in `Step 2` change `you might consider adjusting depending on the action in review:` to something like `you may need to adjust depending on the action in review:` to make it sound less optional. Most actions require creating some kind of changes to one or more of these areas to effectively test them.
- [x] Also in `Step 2` adding something about how understanding the action can help decide what modifications will be needed to test a particular action and adding a link to the [description of our GHAs](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)

When you've made the changes you can ping me here in a comment and add the `ready for dev lead` label.  Also, please let me know if you have any questions!

Thanks for working on this issue!

**Comment by meru-a** [comment]
@LRenDO Yes, I did finish the issue at the time, but wasn't sure if I needed to use any label at all to indicate that since it wasn't mentioned in the issue -- thanks for clarifying this and for your feedback!

I made the changes concerning points 2 and 3. However, I am not sure how to add the images here. I added direct links to the images but they are still not displaying properly. Do you know if I need to upload them to the repo's assets folder (to use in relative paths)?

**Comment by LRenDO** [comment]
Hi @pearlescence-m! Thanks for making the updates! They look great!

It looks like the images not working because there needs to be a blank line before the images.  Like this:

```
<summary>Settings page of the repository.</summary> 

![Image](https://github-production-user-asset-6210df.s3.amazonaws.com/20477610/270084494-9bd8ed9d-42f4-4f17-9c7e-1ce74202c003.png)
```
You can also replace the word `image` with alt text to describe the image.

Ping me when it's all set and I will go ahead and approve it!

**Comment by meru-a** [comment]
@LRenDO thanks a lot, that worked! The issue is now ready for the review.

**Comment by LRenDO** [comment]
Hi @pearlescence-m! This looks great. Thanks for making the updates and contributing to the wiki! Nice work!
