### ISSUE TITLE
Update Zoom Link on Meetings and Agendas Wiki Page

### ISSUE THREAD

**Issue by LRenDO** [hackforla/website#4931]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to remove the Zoom links on the [Meetings and Agendas](https://github.com/hackforla/website/wiki/Meetings-and-Agendas) page, so that we can better manage meeting attendance through invitations and Slack.

We are currently moving the wiki to a new repo and we will not be updating the old wiki. Please refer to the instructions for [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/)

### Action Items
- [x] Copy the entire [Meetings and Agendas](https://github.com/hackforla/website/wiki/Meetings-and-Agendas) page
- [x] Paste the page into a comment below (on this issue)
- [ ] In the `Meeting Times` table delete the following
  - [ ] the last column of the header row: `**Meeting Link** |`
  - [ ] the last column of the row below the header: `--------------|`
  - [ ] all of the zoom links listed in that column including the vertical bar at the end of the column. For example, the first link to delete would be ` [Zoom](https://us02web.zoom.us/j/81834211409?pwd=eHFwWHo1UU1PZVQ0OEhuRktGUnFWQT09)           |` 
- [ ] Delete all of the lines with Zoom links, including the associated bullet point, on the rest of the page. For example, the first one would be to delete `- [Zoom](https://us02web.zoom.us/j/4451450308?pwd=U0JobzZqN0xGSXBUUkRsNlB5YzJiQT09)`
- [ ] Post the comment
- [ ] Add a link to the comment just posted to the `Content to be Added/Edited in New website-wiki Repo` section of the [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki#content-to-be-addededited-in-the-new-website-wiki-repo).
- [ ] Change the project board column for this issue to the `Questions / In Review` column
- [ ] Add `ready for dev lead` label to this issue

### Resources/Instructions
- [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/)
- Created from ER #4918

**Comment by ExperimentsInHonesty** [comment]
The meeting  zoom links should come off the wiki.  Revise this issue accordingly

**Comment by LRenDO** [comment]
@ExperimentsInHonesty and @roslynwythe, happy to revise this issue and can do it on 7/25/23. Just want to confirm and clarify a couple items before I rewrite it.

- Confirming that on the [Meetings and Agendas](https://github.com/hackforla/website/wiki/Meetings-and-Agendas#website-team-meeting-all-roles) page the entire `Meeting Link` column in the table should be removed along with the bullets points in the sections below the table that contain Zoom links.

- I believe we are in need of good first issues. This looks to me like it is more like a small complexity issue now.  If I give very specific instructions about what to replace, can it stay a good first issue or should I just go ahead and bump up the complexity? 

Thanks!

**Comment by roslynwythe** [comment]
Hi @LRenDO I'm sorry I didn't realize earlier that the zoom links should come off the wiki page.  Please see my comments below.  

> @ExperimentsInHonesty and @roslynwythe, happy to revise this issue and can do it on 7/25/23. Just want to confirm and clarify a couple items before I rewrite it.
> 
> * Confirming that on the [Meetings and Agendas](https://github.com/hackforla/website/wiki/Meetings-and-Agendas#website-team-meeting-all-roles) page the entire `Meeting Link` column in the table should be removed along with the bullets points in the sections below the table that contain Zoom links.

Yes.

> * I believe we are in need of good first issues. This looks to me like it is more like a small complexity issue now.  If I give very specific instructions about what to replace, can it stay a good first issue or should I just go ahead and bump up the complexity?

IMO it is too complex for a good first issue so I would bump up the complexity to Small.  
> 
> Thanks!

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I am not sure what is needed by product on this issue now.  Can you let me know, or lets remove the ready for product label.

**Comment by LRenDO** [comment]
@ExperimentsInHonesty and @roslynwythe I can remove the label.  It sounds like I may have misunderstood the process. I thought it needed to be reviewed by product again since you requested changes. Should I have done ready for dev lead? or ready for prioritization instead? Thanks!

**Comment by ExperimentsInHonesty** [comment]
- [x] remove everyone from tuesday meeting with message
- [x] readd the merge team and leads who are not pms
- [x] review all the other meetings (lead and planning week to see if any of those need updates).
    - [ ] update the sunday meeting to have the same instructions for starting the meeting as appear on Tuesday and Thursday, don't send update when it asks
- [ ] Cancel meetings in December

**Comment by roslynwythe** [comment]
This is the "note" that was sent to invitees of the Thursday dev office hours meeting, after removing them from the calendar invite.  This message can be reused after changing the day, name of meeting, and zoom link.  

The meeting time is the same, we have moved the invitation management to Zoom registration instead of Google Calendar.  Please follow the next steps if you want to attend the Thursday dev office hours meeting.

1. Register for the recurring meeting:
https://us02web.zoom.us/meeting/register/tZApduuurDoiGtPEzAMeUuO2lBhjtTMzbWMK

2. After registering, you will receive a confirmation email containing information about joining the meeting.  In that email, there is a link to add this meeting to your calendar, please do so.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty would you like to review this draft message for posting to Slack: 
### In hfla-site:
- From now on, Google Calendar events for meetings will be generated using Zoom meeting registration.  
- Each developer meeting series (Sunday, Tuesday and Thursday) has a Zoom registration link; following the one-time submission of the registration form, developers will be registered for every recurring meeting in the series, and they will receive a confirmation email containing the actual zoom meeting link for that series of meetings, as well as a link for adding the events to their Google Calendar.  
- Don't worry, registration does not imply a committment to attend the meetings; it simply provides developers with the option of receiving Google Calendar events with a new Zoom meeting link.  
- To attend a meeting, developers will have to login using the same email address they used for registration.      
- Developers have been removed from the existing Google Calendar meeting events, and removed members will be receiving email notices with the subject line "Canceled event with note..".  As explained in the note, no meetings were cancelled, but to recreate the Google Calendar events, developers must submit the registration form linked in the instructions.   
- If you did not receive a cancellation notice, you can still submit the registration form.  Just use the link(s) below:
  - Sunday 10 am:
  - Tuesday 7 pm:
  - Thursday 7 pm: 

### In hfla-site-merge:
- Due to limitations in Google Calendar guest lists, we are moving to a new system using Zoom meeting registration.  If developers have questions about calendar invites, please refer them to this message in hfla-site: [INSERT LINK TO ABOVE POST].  If you receive requests to add developers to the Google Calendar invite lists, inform them that our system has changed and refer them to the instructions in hfla-site.  
- Merge team members have been added to the Google Calendar guest lists.  If you want to attend meetings using your email, you should register using the Zoom registration link found in the Google Calendar event.  You would then have the option of adding Google Calendar events with the new Zoom meeting link and removing the existing Google Calendar events.

**Comment by roslynwythe** [comment]
- Deleted Tues and Thurs meetings days 1-7 until the end of the series
- Tues series ends in May 2024, Thurs series ends in Oct 2024
- Also deleted all meetings in December.

**Comment by ExperimentsInHonesty** [comment]
@LRenDO The instructions are missing deleting the last ------| in the seperater row (between the header and the content).

**Comment by LRenDO** [comment]
@ExperimentsInHonesty, good catch! It has been updated.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I edited [Meetings and Agendas](https://github.com/hackforla/website/wiki/Meetings-and-Agendas) by replacing the zoom link in the table, with a link to the agenda.  At this point, the content beneath the table seems redundant; please advise.  

These agenda links have not been updated in over a year, are there current issues? 
[PM/ORG/UX Meeting Agenda of 2022](https://github.com/hackforla/website/issues/1797)
[UXR Meeting Agenda](https://github.com/hackforla/website/issues/2498)
[PM/Design Meeting Agenda 2022](https://github.com/hackforla/website/issues/3040)

**Comment by tonyvang** [comment]
Availability: Satuday evening, Sunday afternoon
ETA: EOD Sunday

**Comment by tonyvang** [comment]
I'm not sure the Action Items of this issue reflect the present state of the page to be edited. The present [Meetings and Agendas ](https://github.com/hackforla/website/wiki/Meetings-and-Agendas) looks like the table below, and does not include a "Meeting Link" column or Zoom links. I self-assigned this issue outside of a meeting, so my apologies if this wasn't meant to be worked on yet.

<html>
<body>
<google-sheets-html-origin>

Meeting | Agenda | Time
-- | -- | --
Developers Team Meeting | [Agenda](https://github.com/hackforla/website/issues/2010) | See [website project page](https://www.hackforla.org/projects/website)
Developers Office Hours |   | See [website project page](https://www.hackforla.org/projects/website)
All Team Meeting | [Agenda](https://github.com/hackforla/website/issues/2027) | See [website project page](https://www.hackforla.org/projects/website)
Dev Leads/PM | [Agenda](https://github.com/hackforla/website/issues/2607) | See [website project page](https://www.hackforla.org/projects/website)


</body>
</html>

**Comment by ExperimentsInHonesty** [comment]
This has been resolved already
