### ISSUE TITLE
ER: emojis on labels

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4932]
### Emergent Requirement - Problem
Some teams at HfLA want to use emojis on their labels, and we want to let them if possible.  We now know it is possible, but there are some things we need to do first

### Issue you discovered this emergent requirement in
- #4050

### Date discovered 
2023-07-10

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@rdhmdhl 

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
write up a Decision record about why emjois on labels are good, and then make another issue to get consensus on what labels to use and ...

**Comment by ExperimentsInHonesty** [comment]
Does anyone have experience creating GitHub Actions for labels when the label has an emoji?

I want the emoji to appear in front of the name of the label 
e.g. `😴 2 weeks inactive`

**Comment by t-will-gillis** [comment]
Decision Record has been added to [Decision Records on Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted) 
- [DR: Adding emojis to labels, updating Github Actions](https://github.com/hackforla/website/issues/4050#issuecomment-1646282976)  

Issue/plan for implementing the JSON file of Key:Value pairs to replace hard-coded label values (Still in process as of 4/29/24)
- Issue #5205  


Closing this ER because of the DR and issue 5205 listed above.
