### ISSUE TITLE
Build initial list of recruiting categories to use for filtering

### ISSUE THREAD

**Issue by cnk** [hackforla/website#494]
### Overview

Do some market research about an appropriate list of recruiting categories for the filtering feature 

### Dependency
#254 

### Action Items
- [x] Review current on boarding survey for categories
- [x] Ask Slack channel for feedback
- [x] Make a spreadsheet of the current wording used in recruiting with Drop down
   - [x] Populate spreadsheet with current needs pulled from website
   - [x] Ask all the pms to choose the job category from the available dropdown.

### Resources
[Project Recruiting Current Needs](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
Go to the getting started page.  There is a link to an onboarding survey that had the categories we are standardizing on

**Comment by cnk** [comment]
- Front-End Development
- Back-End Development
- Full Stack Development
- UI/UX Design
- Graphic Design
- Data Science
- Product Management
- Project Management
- Business Analysis
- Research (user research, usability testing)

**Comment by ExperimentsInHonesty** [comment]
@cnk after taking a closer look at the list, we have decided to edit it slightly.  See below.  What are the next steps for this issue?
- PM
- UI/UX
- Development
- Data

**Comment by ExperimentsInHonesty** [comment]
Added a question to slack to see if we are missing anything
https://hackforla.slack.com/archives/C04502L0P/p1589129918277600
- PM
- UI/UX
- Development
- Data
- SEO/Marketing
- Content

**Comment by ExperimentsInHonesty** [comment]
snipit from slack https://hackforla.slack.com/archives/C04502L0P/p1589129918277600
The HackforLA.org website team #hfla-site is working on a general role categories list.  Have we left anything out?
PM
UI/UX
Development
Data
SEO/Marketing
Content

Dean 
Visual Designer

Bonnie
the UI/UX category encompasses graphic design too.   -  the descriptive role recruiting text on the project cards, will dive into the specifics of what they are looking for.  We are just looking for the large buckets for filtering, which reduce the amount of project cards they have to read.

Joelparkerhenderson 
Ones to consider… CX (customer experience), DX (developer experience), GX (grantor experience), BA (business analyst), QA (quality assurance).

David Fridley
Instead of PM what about saying Project Manager or Product Manager - or ProjM and ProdM

**Comment by ExperimentsInHonesty** [comment]
These are the categories we are going live with
- Business Analyst 
- PM
- Content
- UI/UX
- Development
- Ops
- Data
- QA
- SEO/Marketing

**Comment by ExperimentsInHonesty** [comment]
talk to team about how we are going about this https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/311-data.md

**Comment by ExperimentsInHonesty** [comment]
make a spreadsheet of all of the current looking for and what its new category is going to be.

**Comment by cicyhou** [comment]
Just a reminder that the hack for LA website open roles should match with the confirmed selection to minimize any confusion

**Comment by ExperimentsInHonesty** [comment]
Notes

CNK Comment: What is the appropriate level of granularity for this list? and can we make this list comprehensive enough that any projects "looking for" description will map to one or two categories?
Bonnie Comment: we settled on the 9 categories below.

**Comment by ExperimentsInHonesty** [comment]
Current roles: 

Business Analyst
PM
Content
UI/UX
Development
Ops
Data
QA
SEO/Marketing

**Comment by ExperimentsInHonesty** [comment]
List has been passed off to Civic Opportunity Team and is in use on the current needs spreadsheet https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0
