### ISSUE TITLE
Create Wiki page to fill in missing GHA documentation: Issue Trigger

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5166]
### Overview
We need to separate the wiki content for the issue trigger workflow[^1],[^2],[^3] into two parts corresponding to the two jobs within the workflow: `Add Missing Labels to Issues` and `Ask for Preliminary Update` 

### Action Items
- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)
- [x] In a comment in this issue, create a draft of a new wiki page"GHA: Add Missing Labels to Issues" using the template below.  Much of the content can come from the page GHA: Issue Trigger[^1]
- [x] In a comment in this issue, create a draft of a new wiki page "GHA: Ask for Preliminary Update" using the template below
- [x] Copy the contents of the page HfLA GitHub Actions[^2] to a comment in this issue then edit the section under "issue trigger".  The new content should consist of two bullet points:
   - [x] The first bullet should summarize the function of the job `Add Missing Labels to Issues` and will link to the corresponding new page
   - [x] The second bullet should summarize the function of the job `Ask for Preliminary Update` and will link to the corresponding new page
- [x] Copy the contents of the page GHA: Issue Trigger[^3] to a comment in this issue then edit it to reference the content in the two newly created wiki pages.   

#### Template for GHA documentation
```
## Summary
-
### Scheduled
-
### Workflow
-
### Supporting Files/Folders
-
### Labels
-
### Test Procedure
```
[^1]: https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml
[^2]:[HfLA GitHub Actions](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)
[^3]:[GHA: Issue Trigger](https://github.com/hackforla/website/wiki/GHA:-issue-trigger)

**Comment by roslynwythe** [comment]
- @ExperimentsInHonesty I know that this should be part of #4819 which has not yet been approved, but I wrote this issue now because it addresses the largest gap in the GHA documentation and it concerns a job "Ask for Preliminary Update" that will be the subject of some work in connection with #4469

**Comment by A-Wu5** [comment]
i. Availability T-Sunday evenings
ii. ETA: I'm not exactly sure yet. I'll have a better understanding by the end of the week if I do not finish it by then.

**Comment by A-Wu5** [comment]
### GHA: Add Missing Labels to Issues
## Summary
- Check if an issue has the four required labels: a 'Feature/P-Feature' label, a 'Size' label, a 'Role' label, and a 'Complexity' label. If not, add the corresponding 'missing' labels and post a comment about adding missing labels. If the issue has all three labels, post a comment that congratulates and gives more details about the project board
### Scheduled
- Issue opened
### Workflow
- [issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)
### Supporting Files/Folders
- Supporting Files Folder: [trigger-issue/add-missing-labels-to-issues](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues)
- Support File [obtain-labels.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/utils/obtain-labels.js) located in utils folder (Check if obtain-labels.js file is still being used in this workflow)
### Labels
- [Feature Missing](https://github.com/hackforla/website/labels/Feature%20Missing), [role missing](https://github.com/hackforla/website/labels/role%20missing),  [size: missing](https://github.com/hackforla/website/labels/size%3A%20missing), [Complexity: Missing](https://github.com/hackforla/website/labels/Complexity%3A%20Missing), 
### Test Procedure
See below comment

**Comment by A-Wu5** [comment]
### GHA: Ask for Preliminary Update
## Summary
- Thanks contributer for taking up the issue. Asks contributer to comment on issue their availability and ETA to complete the issue. Additionally, reminds the contributer only work on one issue at a time.
### Scheduled
- Assign issue
### Workflow
- [issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)
### Supporting Files/Folders
- Supporting Files Folder: [trigger-issue/add-preliminary-comment](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-preliminary-comment)
### Labels
- 
### Test Procedure

**Comment by A-Wu5** [comment]
### HFLA Github Actions
#### Workflows are yaml files
#### Supporting files can be
* js
* json
* md
* gitkeep

### Template for GHA documentation
```
## Summary
### Scheduled
-
### Workflow
-
### Supporting Files/Folders
-
---
Back to [HfLA GitHub Actions](HfLA-GitHub-Actions)
```

### Hack for LA's GHAs
#### [add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly)
- Checks the in-progress column from the project board. Goes through each issue, and if there is an assignee, checks the timeline for the issue. If it is outdated, posts a comment to update the issue and ensures the label is changed to 'to update.' Else, change the label so it is 'updated'

#### [github data](https://github.com/hackforla/website/wiki/GHA:-github-data)
- Generates a new github-data.json and commits that to the repository

#### [issue trigger](https://github.com/hackforla/website/wiki/GHA:-issue-trigger)
- ##### [Add Missing Labels to Issues](url)
  Check if an issue has the four required labels: a 'Feature/P-Feature' label, a 'Size' label, a 'Role' label, and a 'Complexity' label. If not, add the corresponding 'missing' labels and post a comment about adding missing labels. If the issue has all three labels, post a comment that congratulates and gives more details about the project board
- ##### [Ask for Preliminary Update](url)
  Thanks contributer for taking up the issue. Asks contributer to comment on issue their availability and ETA to complete the issue. Additionally, reminds the contributer only work on one issue at a time.

#### [lint-scss](https://github.com/hackforla/website/wiki/GHA:-lint-scss)
- Checks and lints modified scss files in PRs

#### [move closed issues](https://github.com/hackforla/website/wiki/GHA:-move-closed-issues)
- Moves a closed issue into either the QA or Done column of the project board. If the issue has a “hard” label (Feature: Refactor CSS, Feature: Refactor HTML, Feature: Refactor JS / Liquid, Feature: Refactor GH), the issue is moved to the Done column. If the issue has no “hard” labels but does have an “override” label (role: front end), the issue is moved to the QA column. If the issue has no “hard” or “override” labels and does have a “soft” label (role: back end/devOps, Feature: Analytics), it is moved to Done. All other issues are moved to QA

#### [pr instructions](https://github.com/hackforla/website/wiki/GHA:-pr-instructions)
- Creates an instruction on how to get a copy of a PR branch for review, then uploads the results into an artifact

#### [pull request trigger](https://github.com/hackforla/website/wiki/GHA:-pull-request-trigger)
- An open script that could be triggered when a pull request is closed on the following branches 'gh-pages', 'feature-homepage-launch', 'feature-tech-dropdown'

#### [set pr labels](https://github.com/hackforla/website/wiki/GHA:-set-pr-labels)
- RegEx takes the issue number on the body of the PR, and uploads the results (including labels on the issue) into an artifact

#### [update team members](https://github.com/hackforla/website/wiki/GHA:-update-team-members)
- Trim inactive members from the write team

#### [vrms data](https://github.com/hackforla/website/wiki/GHA:-vrms-data)
- Generates a new vrms_data.json and commits that to the repository

#### [wr pr instructions](https://github.com/hackforla/website/wiki/GHA:-wr-pr-instructions)
- Leaves a comment on new PRs with a link to the relevant documentation for reviewing PRs and the command line instructions for pulling down a new branch for review.

#### [wr pull request trigger](https://github.com/hackforla/website/wiki/GHA:-wr-pull-request-trigger)
- An open script that should house all the other scripts (workflows) that should be triggered when a pull request is closed.

#### [wr set pr labels](https://github.com/hackforla/website/wiki/GHA:-wr-set-pr-labels)
- This workflow is triggered when workflow [Set PR labels] is completed. Downloads artifact for the completed workflow. Then, gets the PR and issue number from the downloaded artifact and uses an API request to get the labels. Lastly, puts the same labels into the PR.

### Deprecated GHAs

#### [no-labels-template.md](https://github.com/hackforla/website/issues/2898)
- Removed the no-labels-template.md file so that the total number of bot comments are reduced, and developers would have less notifications. Edited lines 47-55 in post-labels-comment.js so that no comment object was created when all the correct labels were added, and therefore no comment is posted. 

---


### extra folders or files with unknown workflows
* Supporting Files Folder: [trigger-schedule](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule) - folder has one file ```.gitkeep``` and its empty - The .gitkeep was likely added as a way of forcing git to track the new empty directory when the person who created the GHA began working on it. This is not a supported feature of git and now that there is content in the directory, there is no real need for the .gitkeep file
The commit message for the .gitkeep file is just “Create directory for gha refactor”

**Comment by A-Wu5** [comment]
### GHA: Issue Trigger
## Summary
- [Adds 'Missing' labels to newly created issues](url) to notify issue creator to add required labels. 
- [Asks contributer for a preliminary update](url) when assigned an issue to gauge the time it might take to complete the issue.
### Scheduled
- Issue opened and issue assigned
### Workflow
- [issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)
### Supporting Files/Folders
- Supporting Files Folder: [trigger-issue/add-missing-labels-to-issues](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues)
- Supporting Files Folder: [trigger-issue/add-preliminary-comment](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-preliminary-comment)
- Support File [obtain-labels.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/utils/obtain-labels.js) located in utils folder (Check if obtain-labels.js file is still being used in this workflow)
---
Back to [HfLA GitHub Actions](HfLA-GitHub-Actions)

**Comment by A-Wu5** [comment]
Blocker: I am confused on these steps: 
- The first bullet should summarize the function of the job Add Missing Labels to Issues and will link to the corresponding new page
 - The second bullet should summarize the function of the job Ask for Preliminary Update and will link to the corresponding new page.

It says to link the bullet to the corresponding new page, but the page has not been created/approved for creating. Currently in my comments, the URLS linked don't go anywhere. This also applies to the step for editing the HFLA Github actions page and GHA: Issue trigger page 

Edit: Spacing

**Comment by A-Wu5** [comment]
Blocker: For the two steps where I am using the template given to create new pages, I am unsure what to put for Labels and Test Procedure.

**Comment by roslynwythe** [comment]
Hi @A-Wu5 great job so far.  Don't worry about creating the links between the pages; that can be done later when the pages are incorporated into the new wiki.  The "Links" section are fine but the "Test Procedure" sections need to be filled in and these are actually the most involved part of this issue.  Below I've created a draft "Test Procedure" for "Add Missing Labels to Issues".  Please review that, confirm the steps (doing an actual test if possible) and clean up the formatting as required.  Then create something similar for the "Ask for Preliminary update", but that will be simpler because it does not require a secret token.   

Also under "Supporting Files/Folders", please detail each individual file, noting for instance the general purpose of the `.js` and `.md` files.  It doesn't look like `obtain-labels.js` is used but please confirm that.  

Also in "GHA: Issue Trigger" please mention the logic that connects the steps, for instance the logic that checks if the assignee is on the website-write team, and the logic that checks if the issue has the appropriate 'role' labels.  From glancing at the code now it appears that if the assignee is not on the website-write team or if the issue does not have an appropriate role label, the "missing" labels are added but no "added labels" or "missing labels" comments are posted.  Please confirm and add that information.  Thanks

**Comment by roslynwythe** [comment]
### Draft - Test Procedure for "Add Missing Labels to Issues"

#### Step 1: Issue Branch
- Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example:  `git push --set-upstream origin update-missing-labels-1234`  

#### Step 2: Repository Settings and Labels
- Browse to your fork of the website repository and click Settings 
  <details><summary>Screenshot of Repository Settings</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/8ecf2e55-2187-4ab9-acf1-2fd7548291a1)

  </details> 
- Change the default branch to the new issue branch
  <details><summary>Screenshot of Default Branch Setting</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/945fe02e-035f-4215-9c25-1d46c209d8c0)

  </details> 
- Further down on the settings page under Features, check the Issues checkbox
  <details><summary>Screenshot of Issues Checkbox</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/945fe02e-035f-4215-9c25-1d46c209d8c0)

  </details> 
- Browse to the Issues page, then click Labels
  <details><summary>Screenshot - creating labels in the test Repo</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/208e1b07-2478-4ed3-98a1-207de58d25c5)

  </details> 
- Create labels from the "Complexity", "size", "role" and "Feature" series. The color of the labels don't have to match those on the `hackforla/website` repository, but the text of the labels must match exactly.  

#### Step 3: Create Personal Access Token
The workflow file `issue-trigger.yml` requires a repository secret and so you will need to create your own personal access token (PAT) in your forked repository for testing in your repository.  

<details>
<summary>1. Go to your "Settings"</summary>

![image](https://user-images.githubusercontent.com/88953806/227071674-104ed00b-9663-40f1-9127-c685e51b4e65.png)

</details>

<details>
<summary>2. Click on "Developer settings"</summary>

![image](https://user-images.githubusercontent.com/88953806/227072126-c2800d22-e629-403b-b9ac-2443ca4a5bd6.png)

</details>

<details>
<summary>3. Click on "Personal access tokens" and then "Tokens (classic)"</summary>

![image](https://user-images.githubusercontent.com/88953806/227072068-e68905f5-bf71-4e75-b6df-5882ccf01a2b.png)

</details>

<details>
<summary>4. Click "Generate new token" and then "Generate new token (classic)"</summary>

![image](https://user-images.githubusercontent.com/88953806/227072516-c2a9b7b0-be36-4be4-9d23-4399bca1ef0d.png)

</details>

<details>
<summary>5. Now you can create a new personal access token</summary>

![image](https://user-images.githubusercontent.com/88953806/227072745-0ee6a304-0f87-443b-9bcb-19c906f43142.png)

</details>


It is a best practice to set an expiration date for the token.  Select the scope `read: org`

When the token is generated, copy it and place it somewhere safe so you don't lose it. The token will not be available again when you leave the page!!

<details>
<summary>6. Go to your repository and click "Settings"</summary>

![image](https://user-images.githubusercontent.com/88953806/227074014-279b838a-d9d8-4a83-ad31-7908e69de1a7.png)

</details>

<details>
<summary>7. Scroll down and click the "Secrets and variables" dropdown and click on "Actions"</summary>

![image](https://user-images.githubusercontent.com/88953806/227074258-a0d8bcb1-4bae-4d9e-b835-023d4bdae3f4.png)

</details>

<details>
<summary>8. Click on "New repository secret"</summary>

![image](https://user-images.githubusercontent.com/88953806/227074389-c3f384b5-be12-43e7-815f-27afe2353492.png)

</details>

<details>
<summary>9. Name the secret `TEST_TEAMS` and paste the secret token into the textbox</summary>

![image](https://user-images.githubusercontent.com/88953806/227074662-17fcd5f8-568c-43fa-9aeb-cd6ae225b29e.png)

</details>

Now, while you are testing the GitHub Action in your repository, you will replace `secrets.TEAMS` with `secrets.TEST_TEAMS` in `issue-trigger.yml`. Once you are satisfied with the changes in your own system, change it back to `secrets.TEAMS` before making your pull request so that token for the HfLA Project Board is not pointing to a secret that doesn't exist. 

#### Step 4 Testing
- Create issues with various labels and confirm that if an issue has no labels from a required series ("Complexity", "role", "size" or "Feature"), the appropriate "missing" label is added and the appropriate comment is added.

**Comment by A-Wu5** [comment]
Thank you for the clarification! I see what I need to do now.

**Comment by A-Wu5** [comment]
Update
1. Progress - Working on draft for 'Ask for Preliminary Update'; Currently going through test procedure for 'Add Missing Labels' to reinforce understanding
3. Blockers - See above
4. Availability - M - F 12PM - 3PM
5. ETA - 11/10

**Comment by roslynwythe** [comment]
Hi @A-Wu5 I forgot to mention, when you have a draft for me to review, please send me a message on Slack or else put the issue in Questions/In Review and add the label "ready for dev lead".  Thanks very much for your work on this issue!

**Comment by A-Wu5** [comment]
### GHA: Add Missing Labels to Issues
## Summary
- Check if an issue has the four required labels: a 'Feature/P-Feature' label, a 'Size' label, a 'Role' label, and a 'Complexity' label. If not, add the corresponding 'missing' labels and post a comment about adding missing labels. If the issue has all three labels, post a comment that congratulates and gives more details about the project board
### Scheduled
- Issue opened
### Workflow
- [issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)

### Supporting Files/Folders
- Supporting Files Folder: [trigger-issue/add-missing-labels-to-issues](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues)
  - [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) - Message template for reminding user to add required labels
  - [check-labels.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/check-labels.js) - Checks labels and returns missing labels
  - [post-labels-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/post-labels-comment.js) - Formats the missing labels into the message template and posts it to the issue
### Labels
- [Feature Missing](https://github.com/hackforla/website/labels/Feature%20Missing), [role missing](https://github.com/hackforla/website/labels/role%20missing),  [size: missing](https://github.com/hackforla/website/labels/size%3A%20missing), [Complexity: Missing](https://github.com/hackforla/website/labels/Complexity%3A%20Missing), 

### Test Procedure
#### Step 1: Issue Branch
- Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example:  `git push --set-upstream origin update-missing-labels-1234`  

#### Step 2: Repository Settings and Labels
- Browse to your fork of the website repository and click Settings 
  <details><summary>Screenshot of Repository Settings</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/8ecf2e55-2187-4ab9-acf1-2fd7548291a1)

  </details> 
- Change the default branch to the new issue branch
  <details><summary>Screenshot of Default Branch Setting</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/945fe02e-035f-4215-9c25-1d46c209d8c0)

  </details> 
- Further down on the settings page under Features, check the Issues checkbox
  <details><summary>Screenshot of Issues Checkbox</summary>

  ![image](https://github.com/hackforla/website/assets/68984808/00521466-74b4-4ee4-b288-fe9422fa8729)

  </details> 
- Browse to the Issues page, then click Labels
  <details><summary>Screenshot - creating labels in the test Repo</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/208e1b07-2478-4ed3-98a1-207de58d25c5)

  </details> 
- Create labels from the "Complexity", "size", "role" and "Feature" series. The color of the labels don't have to match those on the `hackforla/website` repository, but the text of the labels must match exactly.  

#### Step 3: Create Personal Access Token
The workflow file `issue-trigger.yml` requires a repository secret and so you will need to create your own personal access token (PAT) in your forked repository for testing in your repository.  

<details>
<summary>1. Go to your "Settings"</summary>

![image](https://user-images.githubusercontent.com/88953806/227071674-104ed00b-9663-40f1-9127-c685e51b4e65.png)

</details>

<details>
<summary>2. Click on "Developer settings"</summary>

![image](https://user-images.githubusercontent.com/88953806/227072126-c2800d22-e629-403b-b9ac-2443ca4a5bd6.png)

</details>

<details>
<summary>3. Click on "Personal access tokens" and then "Tokens (classic)"</summary>

![image](https://user-images.githubusercontent.com/88953806/227072068-e68905f5-bf71-4e75-b6df-5882ccf01a2b.png)

</details>

<details>
<summary>4. Click "Generate new token" and then "Generate new token (classic)"</summary>

![image](https://user-images.githubusercontent.com/88953806/227072516-c2a9b7b0-be36-4be4-9d23-4399bca1ef0d.png)

</details>

<details>
<summary>5. Now you can create a new personal access token</summary>

![image](https://user-images.githubusercontent.com/88953806/227072745-0ee6a304-0f87-443b-9bcb-19c906f43142.png)

</details>


It is a best practice to set an expiration date for the token.  Select the scope `read: org`

When the token is generated, copy it and place it somewhere safe so you don't lose it. The token will not be available again when you leave the page!!

<details>
<summary>6. Go to your repository and click "Settings"</summary>

![image](https://user-images.githubusercontent.com/88953806/227074014-279b838a-d9d8-4a83-ad31-7908e69de1a7.png)

</details>

<details>
<summary>7. Scroll down and click the "Secrets and variables" dropdown and click on "Actions"</summary>

![image](https://user-images.githubusercontent.com/88953806/227074258-a0d8bcb1-4bae-4d9e-b835-023d4bdae3f4.png)

</details>

<details>
<summary>8. Click on "New repository secret"</summary>

![image](https://user-images.githubusercontent.com/88953806/227074389-c3f384b5-be12-43e7-815f-27afe2353492.png)

</details>

<details>
<summary>9. Name the secret `TEST_TEAMS` and paste the secret token into the textbox</summary>

![image](https://user-images.githubusercontent.com/88953806/227074662-17fcd5f8-568c-43fa-9aeb-cd6ae225b29e.png)

</details>

Now, while you are testing the GitHub Action in your repository, you will replace `secrets.TEAMS` with `secrets.TEST_TEAMS` in `issue-trigger.yml`. Once you are satisfied with the changes in your own system, change it back to `secrets.TEAMS` before making your pull request so that token for the HfLA Project Board is not pointing to a secret that doesn't exist. 

#### Step 4 Testing
- Create issues with various labels and confirm that if an issue has no labels from a required series ("Complexity", "role", "size" or "Feature"), the appropriate "missing" label is added and the appropriate comment is added.

**Comment by A-Wu5** [comment]
### GHA: Ask for Preliminary Update

## Summary
- Thanks contributor for taking up the issue. Asks contributor to comment on issue their availability and ETA to complete the issue. Additionally, reminds the contributor only work on one issue at a time.

### Scheduled
- Assign issue

### Workflow
- [issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)

### Supporting Files/Folders
- Supporting Files Folder: [trigger-issue/add-preliminary-comment](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-preliminary-comment)
  - [check-label-preliminary-update.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-preliminary-comment/check-label-preliminary-update.js) - Checks if preliminary update comment needs to be posted
  - [preliminary-update-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js) - Formats the preliminary update comment and posts it depending if needed
  - [preliminary-update.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-preliminary-comment/preliminary-update.md) - Template for preliminary update comment

### Labels
- None

### Test Procedure

#### Step 1: Issue Branch
- Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example:  `git push --set-upstream origin update-missing-labels-1234`  

#### Step 2: Repository Settings and Labels
- Browse to your fork of the website repository and click Settings 
  <details><summary>Screenshot of Repository Settings</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/8ecf2e55-2187-4ab9-acf1-2fd7548291a1)

  </details> 
- Change the default branch to the new issue branch
  <details><summary>Screenshot of Default Branch Setting</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/945fe02e-035f-4215-9c25-1d46c209d8c0)

  </details> 
- Further down on the settings page under Features, check the Issues checkbox
  <details><summary>Screenshot of Issues Checkbox</summary>

  ![image](https://github.com/hackforla/website/assets/68984808/00521466-74b4-4ee4-b288-fe9422fa8729)

  </details> 
- Browse to the Issues page, then click Labels
  <details><summary>Screenshot - creating labels in the test Repo</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/208e1b07-2478-4ed3-98a1-207de58d25c5)

  </details> 
- Create labels from the "Complexity", "size", "role" and "Feature" series. The color of the labels don't have to match those on the `hackforla/website` repository, but the text of the labels must match exactly.  

#### Step 4: Testing
- Create new test issues that include a 'role: back end/devOps', 'role: front end', or 'role: design' label and assign self to issues to confirm preliminary comment is posted.

**Comment by A-Wu5** [comment]
# Issue Trigger<br><sub>Workflow</sub>

## Summary
- [Adds 'Missing' labels to newly created issues](url) to notify issue creator to add required labels. 
- [Asks contributor for a preliminary update](url) when assigned an issue to gauge the time it might take to complete the issue.
### Scheduled
- Issue opened and issue assigned
### Workflow
- [issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)
- When a new issue is created, this file checks if the required labels are present and adds corresponding `Missing` labels to the issue. If the user is apart of the website-write team, then a comment is posted to remind the user to add missing labels if needed.
- When a user is newly assigned to an issue, the file checks if the issue contains any of the labels: `role: back end/devOps`, `role: front end`, `role: design`, `role: user research` and posts a comment to ask user for their preliminary update.
### Supporting Files/Folders
- Supporting Files Folder: [trigger-issue/add-missing-labels-to-issues](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues)
- Supporting Files Folder: [trigger-issue/add-preliminary-comment](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-preliminary-comment)
---
Back to [HfLA GitHub Actions](HfLA-GitHub-Actions)

**Comment by A-Wu5** [comment]
Hi @roslynwythe. I've fixed my draft in the 3 comments above. I've followed your test procedure for 'Add Missing Labels to Issues' and the steps were very clear, so I added that to my drafts in the comment above with only a change to one of the screenshots. 
I've noted the general purposes for each file under "Supporting Files/Folders" and I've confirmed that `obtain-labels.js` is not used in these files.

I've also described some of the logic for 'GHA: Issue Trigger' under the 'workflow' section. Please let me know if it is done correctly.

Thank you!

**Comment by roslynwythe** [comment]
Hi @A-Wu5 this looks great!  There are just a few tiny things required to complete the issue.  
- [x]  correct the misspelling of "contributor"
- [x]  write "none" under "Labels" for "GHA: Ask for Preliminary Update"
- [x] go to the page  [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) and update the links for all three wiki pages.

**Comment by A-Wu5** [comment]
@roslynwythe I completed the tasks you mentioned above!

**Comment by roslynwythe** [comment]
Great job @A-Wu5 on completing this issue.
