### ISSUE TITLE
Implement mobile hamburger nav

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#526]
### Overview
Create mockups for mobile hamburger nav

### Action Items
- [x] Create mockups for mobile hamburger nav in Figma
- [x] Share and discuss mockups and decide on style change

**Comment by leestella748** [comment]
@ExperimentsInHonesty
<img width="539" alt="image" src="https://user-images.githubusercontent.com/61727650/84102066-513f2b80-a9c4-11ea-95ff-d4886a452390.png">
Figma:https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1001%3A1263

Let me know what you think!  I didn't see a reason to change the navigation item names unless we still wanted to switch up the order of "Press", "About", and "Contact Us" on desktop.

**Comment by ExperimentsInHonesty** [comment]
@leestella748 Can we see a mockup with the hamburger menu style where all the lines are the same length.  I think that is more common than the graduated menu currently depicted.

Re the menu order.  I think we need to add some other links anyway, So the new menu items (unless I missed something) should be Getting Started, Projects, Press, Connect. 

- in the future there will be new menu items for Toolkit and Meetings and the order and naming could be Getting Started, Meetings/Workshops, Projects, Toolkit, Press, Connect.

**Comment by ExperimentsInHonesty** [comment]
for Latest actionable update see [comment above](https://github.com/hackforla/website/issues/526#issuecomment-643789867) Once the new PM starts and Stella has finished the mock ups, we will move this with a note about tasks to the development prioritized backlog.

**Comment by leestella748** [comment]
@ExperimentsInHonesty 
<img width="459" alt="image" src="https://user-images.githubusercontent.com/61727650/84600839-2b38e180-ae31-11ea-843b-e833d7f66fe4.png">

**Comment by ExperimentsInHonesty** [comment]
@leestella748 Hi Stella, Sorry for the delay. 

 I am a little confused by the recent mockups, they don't seem to echo the new menu items I asked for in the comment referenced https://github.com/hackforla/website/issues/526#issuecomment-643789867

Specifically the new menu needs to be "Getting Started, Projects, Press, Connect"

**Comment by leestella748** [comment]
@ExperimentsInHonesty My bad!  I don't know how I missed it 
<img width="764" alt="image" src="https://user-images.githubusercontent.com/61727650/85230395-92601400-b3a4-11ea-934b-e48ae26addd0.png">


Figma: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1136%3A1159
Prototype view: https://www.figma.com/proto/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1136%3A1159&viewport=137%2C13%2C0.25107648968696594&scaling=scale-down

**Comment by ruben1s** [comment]
Update:
    Currently working on issue. Having trouble with some of the scss.

**Comment by ExperimentsInHonesty** [comment]
@leestella748 back to the drawing board.

**Comment by leestella748** [comment]
@ExperimentsInHonesty 
I discussed with the dev team today about having the nav bar disappear when users scroll down and then have it reappear if the users scrolled back up.  It seemed unnecessarily confusing and difficult to prototype, while the clickable prototype from last week seemed pretty understandable.  

I expanded on the prototype (try dragging down/up on the screens as if you're scrolling on your phone) https://www.figma.com/proto/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1461%3A2360&viewport=287%2C-1252%2C0.3910782039165497&scaling=scale-down
<img width="733" alt="image" src="https://user-images.githubusercontent.com/61727650/86203931-163f9c00-bb1b-11ea-9319-36638b6e2a1e.png">

**Comment by ExperimentsInHonesty** [comment]
@drubgrubby please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by drubgrubby** [comment]
- Progress
Made good progress in sorting out the site structure and figuring out where to put/insert/include files and images for this. (This is my first real coding task, so I spend more time just sleuthing than I would have liked).

- Blockers
The main challenge is that I don't know how things are put together well enough, so it takes extra time to figure out where to include things, how the CSS is structured, etc. 

- Availability
Don't have a ton of availability in the early part of this week.  Will do my best to make it up in the later part. 

-  ETA
Let's say by Sunday the 23rd

**Comment by drubgrubby** [comment]
**Progress**
The javascript/css for toggling the menu and images is done and seems to be working as it should. 
Sadly, at the moment this is at the expense of menu styling and...well, things aren't where they're supposed to be anymore.  
The next (and hopefully final) phase is to bend the CSS to my will so that everything appears according to spec. 

**Blockers**
1) My CSS is kind of rusty.

**Availability**
I should have lots of time to work on this in the coming week. 

**ETA**
Sunday the 23rd

**Comment by drubgrubby** [comment]
Progress
Apologies to all.  Between the evacuation, refreshing my Twitter feed to see if my house had burned, and other fire related things, I didn't get very much done this week.  Doing some flexbox study (thanks Josh), and understanding the website CSS better (thanks Ruben) was about all the progress I made.   

Blockers
Only the unexpected. 

Availability
Depending on wind direction, I should have plenty of time this week. 

ETA
Looking to next Sunday.

**Comment by drubgrubby** [comment]
**Progress**
This is complete, with the exception of the following three things (which is to say, it's not quite complete):

1) In order to use the smaller HFLA logo for the mobile site, I used the smaller, mobile logo and then scaled it up for the main site.  Because of that, it sits on the page in a slightly different way than it does currently. It seems acceptable to me, but I'd like the designers (or someone else) to sign off on this.

The way it will look: 
<img width="511" alt="Screen Shot 2020-08-30 at 8 41 15 AM" src="https://user-images.githubusercontent.com/68244054/91663267-aeff8300-ea9c-11ea-971e-ec3453293972.png">

The way it looks now: 
<img width="546" alt="Screen Shot 2020-08-30 at 8 41 02 AM" src="https://user-images.githubusercontent.com/68244054/91663274-b6269100-ea9c-11ea-9cd2-42b5585d592d.png">

2) I'm having an issue with the whitespace on the nav menu for phones in landscape mode.  Hopefully someone in the dev breakout can help me sort this out.  (I just noticed this and I don't think it's a difficult fix)

Portrait:
<img width="529" alt="Screen Shot 2020-08-30 at 8 47 08 AM" src="https://user-images.githubusercontent.com/68244054/91663405-7ca25580-ea9d-11ea-9207-5ac6d25067af.png">

Landscape: 
<img width="724" alt="Screen Shot 2020-08-30 at 8 47 20 AM" src="https://user-images.githubusercontent.com/68244054/91663421-90e65280-ea9d-11ea-8c89-67a3fa0ea4aa.png">

3) There's a bug that I just noticed (that I should have noticed sooner) that makes the not mobile menu disappear sometimes when I don't want it to.  Ooops.

Additionally, as I got phase one of the mobile nav working I realized that it should not only close the menu when clicking on the "X", but it should close the menu when you touch anywhere on the screen outside the menu.  I'm working on adding this feature, but I'm getting stumped by where to put the stopPropagation function.  Hopefully someone in the dev meeting can help with that.  

Should we launch the mobile nav without this feature, or wait until I get it working? (Which could take anywhere from 5 minutes to forever, I suppose). 

**Blockers**
My ability to fix the bug.

**ETA**
Hopefully Tuesday...or maybe Wednesday

**Comment by drubgrubby** [comment]
**Progress:**
I believe that this is complete according to spec

**Blockers:**
The bugs that I haven't noticed yet, and the never-ending horror-show of browser incompatibility. 

**ETA**
Two days ago (as you read this)

**Comment by ExperimentsInHonesty** [comment]
we are going to test the bold vs not bold after pr approved and merged.

**Comment by ExperimentsInHonesty** [comment]
David will continue to make changes as per kian's direction on the PR

**Comment by alexandrastubbs** [comment]
https://github.com/hackforla/website/pull/716#issuecomment-694511325

**Comment by KianBadie** [comment]
Merging the pull request as @cnk reminded me of the conversation we had at the last dev meeting. See my newest comment [here](https://github.com/hackforla/website/pull/716#issuecomment-695364816). It says this: 

@cnk Reminded me of the conversation we had during the dev meeting regarding this pull request where we decided it would be a good idea to merge this and test live. I personally think it is a good idea as well as we can see if the bugs (which are not breaking bugs) are consistent for other people, as they would be able to test on their own phones. I think we can work on bugs as they are shown to be consistent.
