### ISSUE TITLE
Refactor code using the deprecated Window: Event Property

### ISSUE THREAD

**Issue by StephenTheDev1001** [hackforla/website#5289]
### Overview

We want to refactor code that uses the deprecated Window: Event Property to avoid JS errors/bugs.

### Action Items

- [x] In your local IDE, navigate to [_assets/js/current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- [x] Refactor using the following code from:
```
if ((event.key === "Enter" || event.key === "Spacebar" || event.key === " ") && document.activeElement.getAttribute("aria-label")) {
```
to
```
if ((e.key === "Enter" || e.key === "Spacebar" || e.key === " ") && document.activeElement.getAttribute("aria-label")) {
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website. On https://www.hackforla.org/projects and locally on docker (ie https://localhost:4000/projects)  make sure to to test tab index using "Enter" and "Space" to ensure it is working as intended.

### Resources/Instructions

1. Resulted from this  #5264 (example of a refactor on the ER)
2. Documentation on [Window: Event Property](https://developer.mozilla.org/en-US/docs/Web/API/Window/event)

**Comment by StephenTheDev1001** [comment]
Availability - M - F 10am -12pm
ETA - Sept 1st

**Comment by roslynwythe** [comment]
@StephenTheDev1001 thank you for writing this issue.  It looks great.  I have a few minor suggestions:
-  consider increasing the size to 1 pt, since that is the typical size for a medium complexity issue.  
- when specifying the file to open in the IDE, it might be helpful to provide a file path relative to the website folder, i,e., `_assets/js/current-projects.js`
- when specifying a webpage for testing, it might be helpful provide a webpage (i.e, https://www.hackforla.org/projects) or a permalink (ie /projects/)
- add the label `P-Feature: Projects Page`

**Comment by StephenTheDev1001** [comment]
@roslynwythe I changed it to complexity: small, I don't think it should take more than 3 hrs. I made all the other changes/additions you've suggested. You've helped so much with my creating my first few issues. Thank you so much!

**Comment by ExperimentsInHonesty** [comment]
@StephenTheDev1001 It seems like you are using e but where is the e parameter defined?

**Comment by Maarimar** [comment]
Availability: I am available Wednesday and Thursday afternoon
 ETA: I expect to finish this issue by end of day tomorrow
