### ISSUE TITLE
remove mention of CfA from Ballot Nav project partners

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5410]
### Overview
We need to remove mention of CfA from the list of partners on the Ballot Nav project

### Action Items
- [x] In your local IDE, navigate to `_projects/ballot-nav.md`
- [x] replace the line

```
partner: Code for America, Other Brigades
```
with
```
partner: Code for San Jose, Code for Atlanta, Open Oakland
```
- [x] Using Docker, confirm that the change is reflected on the Ballot Nav project webpage, and the surrounding elements are unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/ballot-nav.md
2. Ballot Nav project webpage(s): https://www.hackforla.org/projects/ballot-nav

**Comment by krushn-a** [comment]
Hey @roslynwythe, Can I Work on this issue.

**Comment by ExperimentsInHonesty** [comment]
@krushn-a we would love to have you work on an issue.  We have an extensive onboarding process, please join us at onboarding https://meetup.com/hackforla/events then join a team at hack for LA.  If you join this one (the website team), when you join we will instruct you where to find issues that are ready to be worked on and our contributing guidelines.  Our org is free   We just do this process, so that we don't end up repeating the same thing to hundreds of people 1 by 1.  If you are already on the team, please review the Prioritized Backlog.

**Comment by danielmshawn** [comment]
Availability for this week: Thu Sep 14 9a-11a, 4-6p
My estimated ETA for completing this issue: Thu 6p
