### ISSUE TITLE
Remove mention of CfA from the Privacy Policy

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5429]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to remove mention of CfA from the Privacy Policy

### Action Items
- [ ] In your local IDE, navigate to `_data/internal/privacy-policy.yml`
- [ ] Replace:
 ```
  Code for America\
  Ref: Hack for LA, HackforLA.org\
  155 9th Street\
  San Francisco, CA 94103
``` 
with
```
Civic Tech Structure, Inc.\
Ref: Hack for LA, HackforLA.org\
13428 Maxella Ave, Unit 821\
Marina Del Rey, CA 90292
```
- [ ] Using Docker, confirm that the change has been made on the Privacy Policy page, and the rest of the page is unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_data/internal/privacy-policy.yml
2. Privacy Policy webpage: https://www.hackforla.org/program-areas

**Comment by sakibian** [comment]
Hi @roslynwythe Can I work on this?

**Comment by ExperimentsInHonesty** [comment]
Hello @@sakibian Thank you for your interest! Please note that in order to work on an issue with Hack for LA, you must first become a member. See below for instructions on how to join.

### Prerequisites
You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe 
I think the lines need a break character, which is what I think the "\" is in the prior text.  Please check and revise or update issue to explicitly state that it does not need that character under the resources section.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty Yes you are correct.  Thanks for catching that!

**Comment by benpinhassi** [comment]
Hey,
Availability: Afternoon and evenings (PT).
ETA: Two days.
