### ISSUE TITLE
Run VSCode Spell Checker on _includes/about-page/about-card-sustainability.html

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5527]
### Overview
We need to audit HfLA codebase files for spelling errors using the VSCode Code Spell Checker extension in order to ensure site quality.  Results will be categorized as misspellings, false positives in the HfLA spelling audit spreadsheet[^1] and will be resolved in later issues.  

### Action Items
- [x] You must use VS Code as your local text editor and install the `Code Spell Checker` VS Code extension[^2]  
- [x] Do not change any configuration settings or make any spell corrections
- [x] Open the file '_includes/about-page/about-card-sustainability.html' and note any Code Spell Checker errors
- [x] Locate the file in column A ("File") of the "Page Audit" sheet.  In the column labelled "Result Summary", select the appropriate option:  `No errors` or `At least one error`.  
- [x] If at least one error was reported, copy/paste each cSpell message into a separate row in the `Results` sheet
- [x] In each new row, select the appropriate value: `misspelling` or `false positive` from the "Result type" column.  A false positive is a term that is not a misspelling, but it is not recognized by the spell checker because it is a technical term, abbreviation, acronym, URL or proper noun (name of a person, place or organization).  
- [x] Move this issue to the Questions/In Review column and apply the label 'ready for dev lead`

### Merge Team
- [x] After this issue is closed, release the dependency on this issue in #5248
- [ ] After the last dependency has been released, close that issue. 

### Resources/Instructions
- This issue is part of #5248
[^1]: [HfLA spelling audit spreadsheet - Results](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=69989048)
[^2]:The recommended installation method is to install Code Spell Checker directly from the VS Code text editor, and those instructions can be found [here](https://code.visualstudio.com/learn/get-started/extensions). The extension can also be installed via the VS Code Marketplace website [here](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

**Comment by locb65** [comment]
Availability: Everyday after 6pm EST.
ETA: 1-2 hours after starting. Planning to start and finish 9/16/2023

**Comment by locb65** [comment]
@roslynwythe 
Hi Roslyn. I have a question. 

 Locate the file in column A ("File") of the "Page Audit" sheet. In the column labelled "Result Summary", select the appropriate option: No errors or At least one error.
 
 Where exactly is the file above?
 
 I have been looking for it for quite some time. Any direction helps. Thank You!

**Comment by LRenDO** [comment]
Hi @locb65! Great job with this issue! It looks like there were false positive errors on this page on my end too! You did a great job adding them to the sheet correctly. You also did a great job with moving the issue to the right column and adding the correct label. 

Strangely, "Collabathon" didn't show up as an error on my end which theoretically it should have. Let's go ahead and leave it on there in case it's something with my version, but I do have a request for it.
- [x] On the `Results` sheet of the spreadsheet in the `Result type` column, please change the type to `False Positive` because it is the correct word we want to use on the site (it's the name of an event, I believe). 

Once it's completed, you can ping me here in a comment to let me know and add the `ready for dev lead` tag back to the issue. Thanks for working on this issue!

**Comment by locb65** [comment]
Hi @LRenDO. The have implemented the changes to the spreadsheet that you asked for. I assumed that Collabathon could be an event name as it does sound like one, but I was not too sure. I am placing the `ready for dev lead` tag back on.

**Comment by LRenDO** [comment]
Hi @locb65! Looks great! Thanks for making the update!
