### ISSUE TITLE
Create Toolkit page

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#555]
### Overview
Create Toolkit landing page. This page will house all learning resources, including internal guides and external resources.

### Action Items
- [x] UX Research
   - [x] Review existing guides and learning materials 
   - [x] Organize the wording and define elements that should be on page
   - [x] Get sign off 
- [x] UI Mockup
   - [x] Design mockup
   - [x] Get sign off
   - [x] Check dependency status. If dependency is not cleared, move to Icebox.
- [ ] Development
   - [ ] Implement final mockup
   - [ ] Obtain code review

### Resources/Instructions
Anatomy of a Good GitHub Issue Page: #514 

Guide Page: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=695%3A0

**Comment by alexandrastubbs** [comment]
Two different designs: 

1. More immediate page - header + links below (separated by type of resource - internal and external)
2. Long-term, more modular page w/ filtering

**Comment by yuikomajima** [comment]
Here are some initial mockups (all images are concept.) The left one is MVP, and right one is more long term.

figma link: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967

**Comment by alexandrastubbs** [comment]
Bonnie to provide paragraph for the top of the page.

**Comment by ExperimentsInHonesty** [comment]
@ruben1s Here is my paragraph for the top of the page:

### There is no Toolkit
Toolkit implies that there is one set of tools that is perfect for the job you are tackling!
What you will find here are tools we have found to be effective.  Think of this as the most awesome collective tool shed!
Here you can find, share, and suggest tools that are of use to the open source civic tech software community.

**Comment by ruben1s** [comment]
Update: Here are the screenshots of my progress.

1. Progress:
   Completed all the html.  
   Stored all assets svgs/images.
   Need to work on scss. 

2. Blocks: None

3. Availability: Mon - Fri 5 pm - 7 pm

4. ETA: Friday Aug 28.

![Screenshot from 2020-07-25 19-36-29](https://user-images.githubusercontent.com/33906590/88470195-7ae9de80-ceae-11ea-9f51-c990af3662ab.png)
![Screenshot from 2020-07-25 19-36-34](https://user-images.githubusercontent.com/33906590/88470202-7fae9280-ceae-11ea-90e3-178c9e63457a.png)

I still need to work on the mobile view of the page and touch up on the scss.

**Comment by alexandrastubbs** [comment]
@ruben1s please provide an update on your progress with: 

1. Progress
2. Blocks 
3. Availability 
4. ETA

**Comment by ruben1s** [comment]
Update: 
![screencapture-0-0-0-0-4000-toolkit-2020-08-02-09_42_28](https://user-images.githubusercontent.com/33906590/89127715-a3706a80-d4a4-11ea-9ace-bdf163b16695.png)

Still working on:
    -Getting good images
    -Cleaning up the svgs
    -Mobile view
    -Dead Links

**Comment by alexandrastubbs** [comment]
@yuikomajima to provide images

**Comment by yuikomajima** [comment]
hi @ruben1s - figma doc is updated with images of the figma, zoom and github logo. Attached pngs for your reference. These have been taken from Worldvectorlogo which said it was free downloads. 
![zoom-communications-logo 1](https://user-images.githubusercontent.com/56898767/89128959-18946d80-d4ae-11ea-9a97-193778aeaee0.png)
![figma-1 1](https://user-images.githubusercontent.com/56898767/89128960-19c59a80-d4ae-11ea-9be0-5fd8ba8a8a3b.png)
![GitHub-Mark-120px-plus 1](https://user-images.githubusercontent.com/56898767/89128961-19c59a80-d4ae-11ea-84bc-575c08074973.png)

**Comment by alexandrastubbs** [comment]
Can we add the current Toolkit page to the HfLA website menu? When you submit pull request for this, do not include the word 'fixes' and it should not close this issue. Mention the issue number.

**Comment by ruben1s** [comment]
Update:

    I am still working on the mobile versions of the toolkit page. 

Desktop:
![screencapture-0-0-0-0-4000-toolkit-2020-08-22-22_17_22](https://user-images.githubusercontent.com/33906590/90971462-660c6500-e4c5-11ea-81bd-b3170b2f1dc2.png)

Ipad:
![screencapture-0-0-0-0-4000-toolkit-2020-08-22-22_17_45](https://user-images.githubusercontent.com/33906590/90971465-6ad11900-e4c5-11ea-85aa-0391a14293cf.png)

Iphone:
![screencapture-0-0-0-0-4000-toolkit-2020-08-22-22_18_01](https://user-images.githubusercontent.com/33906590/90971467-6efd3680-e4c5-11ea-98dd-862d1a49c9be.png)

**Comment by alexandrastubbs** [comment]
@ruben1s to finish by EOD. @alexandrastubbs to visually review and @jbubar to do first pass review, @KianBadie to review as well.

**Comment by ExperimentsInHonesty** [comment]
@ruben1s sorry to hear you are feeling badly.  Get better soon, and give us a progress report 🤣

**Comment by ruben1s** [comment]
Update:
1. Progress: Pull request pending

2. Blocks: None

3. Availability: Mon - Fri 5pm - 7pm && Sat Sun 11am - 8pm

4. ETA: TBD

Desktop View:
![screencapture-0-0-0-0-4000-toolkit-2020-09-05-21_54_02](https://user-images.githubusercontent.com/33906590/92318535-77c03300-efc2-11ea-9f6d-b4c792cdce64.png)

Mobile View:
![screencapture-0-0-0-0-4000-toolkit-2020-09-05-21_54_30](https://user-images.githubusercontent.com/33906590/92318536-7989f680-efc2-11ea-8c2b-4f98bffe96b5.png)

Tablet View:
![screencapture-0-0-0-0-4000-toolkit-2020-09-05-21_54_50](https://user-images.githubusercontent.com/33906590/92318538-7d1d7d80-efc2-11ea-8c73-27ffbda5993c.png)

**Comment by ruben1s** [comment]
I made the necessary changes to the column issue on mobile view. Here are the snapshots.
![screencapture-0-0-0-0-4000-toolkit-2020-09-06-11_19_32](https://user-images.githubusercontent.com/33906590/92332479-12585a80-f033-11ea-8a97-15f0f141ee6e.png)
![screencapture-0-0-0-0-4000-toolkit-2020-09-06-11_19_59](https://user-images.githubusercontent.com/33906590/92332482-14bab480-f033-11ea-9f42-4c66f8b93e1e.png)
![screencapture-0-0-0-0-4000-toolkit-2020-09-06-11_20_22](https://user-images.githubusercontent.com/33906590/92332485-197f6880-f033-11ea-95ac-4f7c1da1eb33.png)

**Comment by alexandrastubbs** [comment]
@KianBadie to connect with @ruben1s to help him understand how to refactor into a collections unit.

**Comment by ruben1s** [comment]
Update:

Progress: 
    I refactored the code to use liquid. I made two collection folders 1 for the toolkit pages and 1 for the resource card pages. 
    There is a pr in the pipeline. Screenshots are below.

Blocks: None

Availability: Mon - Fri 5pm - 7pm && Sat Sun 11am - 8pm

ETA: TBD

![screencapture-0-0-0-0-4000-toolkit-2020-09-12-21_48_26](https://user-images.githubusercontent.com/33906590/93010477-db59db80-f541-11ea-9a0b-ce893e073a40.png)

![screencapture-0-0-0-0-4000-toolkit-2020-09-12-21_47_48](https://user-images.githubusercontent.com/33906590/93010482-e01e8f80-f541-11ea-906b-5798da20758e.png)

![screencapture-0-0-0-0-4000-toolkit-2020-09-12-21_45_29](https://user-images.githubusercontent.com/33906590/93010484-e3198000-f541-11ea-86ee-e293f79eb69a.png)

**Comment by KianBadie** [comment]
Putting this here just for documentation purposes. This is in regards to the collections refactoring (and should have been posted before @ruben1s above update about the collections).

Resources/guides should be collection items. The toolkit page should loop through the collection items in order to display them. Original request structure was to have one collection with a variable denoting if an item was a resource or a guide. See @ruben1s above comment for an update on the structure of the collection.

**Comment by ruben1s** [comment]
Need a field in .md file for
image url 
alt text
title
title-link
description
cardType (resource / guide)
status (coming soon / live )
category

**Comment by ExperimentsInHonesty** [comment]
Not creating unique collection for guides (one already exists) just add this info to the top matter
![Screen Shot 2020-09-13 at 11 03 11 AM](https://user-images.githubusercontent.com/37763229/93025191-c23c4380-f5b0-11ea-94d3-59b81a82d6c1.png)

there will need to be a collection for resources which should match (or mostly match) the fields.

**Comment by ruben1s** [comment]
Quick - Update: I made the changes requested above. Removed the toolkitGuidePages collection and migrated extra fields to the guidepages collection.

here are the snapshots of the page
![screencapture-0-0-0-0-4000-toolkit-html-2020-09-13-18_53_17](https://user-images.githubusercontent.com/33906590/93035654-73af9900-f5f2-11ea-83b9-98f44592c695.png)
![screencapture-0-0-0-0-4000-toolkit-html-2020-09-13-18_53_01](https://user-images.githubusercontent.com/33906590/93035655-74e0c600-f5f2-11ea-80ec-f928c9ff05f4.png)
![screencapture-0-0-0-0-4000-toolkit-html-2020-09-13-18_52_39](https://user-images.githubusercontent.com/33906590/93035657-75795c80-f5f2-11ea-8df9-29ddea8cefb1.png)

**Comment by alexandrastubbs** [comment]
@ruben1s some notes below on these mocks. 

Mobile:

- everything should be left justified 
- Image below toolkit description should be larger (fill in the white space)
- Add more padding above the Development, Design, Project Management 
- Add a space between Guides and (We Made These!)
- In box for 2FA guide, there is too much space between picture and title, title and copy block (if you are trying to make them all the same, we would prefer they were all unique and fit their content, specifically for mobile)
- Text in the guide boxes should be consistent and the size in the 2FA box 
- For any guides that are 'coming soon' the title should not be underlined, because it is not clickable
- For external resources, need to include the arrow in bottom right corner that signifies the ability to link out externally 
- The large blue space at the end of the page should not be there 

Tablet: 

- everything should be left justified 
- Decrease white space below the image at the top of the page 
- Add more padding above the Development, Design, Project Management 
- Add a space between Guides and (We Made These!)
- In box for 2FA guide, we need the box size to match the content (goes for all guides)
- Font size for the whole page should be what is found in the mobile 2FA guide 
- For any guides that are 'coming soon' the title should not be underlined, because it is not clickable
- For external resources, the icons/images are too small and should fill the space more (font also needs to be bigger per the above note)
- For external resources, need to include the arrow in bottom right corner that signifies the ability to link out externally 
- The large blue space at the end of the page should not be there 

Desktop: 

- everything should be left justified 
- The image is too big and the copy is too small, and the copy stretches too wide across the page
- Add a space between Guides and (We Made These!) - also font should be bigger, match Figma 
- The images in the guide boxes are not filling the box 
- For the guides, if there are less than 3 items, keep the cards left justified (match figma)
- Text is too small, match Figma (should be the same size for the title and the coming soon and different from the copy) 
- For any guides that are 'coming soon' the title should not be underlined, because it is not clickable
- External resources should be bigger too match Figma and be consistent with the Guides title

**Comment by KianBadie** [comment]
Me and @ruben1s are working on the last visual touch ups today and tomorrow morning. I intend on having this merged before tomorrow's meeting based purely on matching the figma visually. I think there are some structural changes that should happen to the code, but I think it is more important to get this page out.

**Comment by KianBadie** [comment]
I've attached screenshots to the point that me and @ruben1s have reached at this point

I will upload the screenshots in this comment. There are places where it is still wonky (specifically landscape on mobile as you will see in my screenshots). Structurally, I think it needs changes. But I was shooting purely on visual requirements (as I assumed those were the more important ones in getting this page out). Also, on larger phones, the header/introduction text get's a bit wonky (which you will also see in the screenshots).

I think it is almost there. Needs some fixes on mobile landscape.

![Screenshot from 2020-09-20 09-38-35](https://user-images.githubusercontent.com/18221058/93716735-3c774580-fb26-11ea-8057-3ecd382fa0da.png)
![Screenshot from 2020-09-20 09-38-46](https://user-images.githubusercontent.com/18221058/93716736-3d0fdc00-fb26-11ea-83ce-f06fa5f065e7.png)
![Screenshot from 2020-09-20 09-38-56](https://user-images.githubusercontent.com/18221058/93716737-3d0fdc00-fb26-11ea-85e4-c65326750b4f.png)
![Screenshot from 2020-09-20 09-39-05](https://user-images.githubusercontent.com/18221058/93716738-3da87280-fb26-11ea-932a-7e5c6dc2fb81.png)
![Screenshot from 2020-09-20 09-39-19](https://user-images.githubusercontent.com/18221058/93716739-3e410900-fb26-11ea-871e-565d51b6c1f7.png)
![Screenshot from 2020-09-20 09-39-26](https://user-images.githubusercontent.com/18221058/93716740-3e410900-fb26-11ea-8f93-b3ac8128b0ef.png)
![Screenshot from 2020-09-20 09-39-48](https://user-images.githubusercontent.com/18221058/93716741-3ed99f80-fb26-11ea-8db9-7b608825d4b3.png)
![Screenshot from 2020-09-20 09-40-00](https://user-images.githubusercontent.com/18221058/93716742-3ed99f80-fb26-11ea-9b08-fe5e44e5da95.png)
![Screenshot from 2020-09-20 09-40-10](https://user-images.githubusercontent.com/18221058/93716743-3ed99f80-fb26-11ea-9be3-74d8e75e165b.png)
![Screenshot from 2020-09-20 09-40-18](https://user-images.githubusercontent.com/18221058/93716744-3f723600-fb26-11ea-9443-7e9b55d22b99.png)
![Screenshot from 2020-09-20 09-40-28](https://user-images.githubusercontent.com/18221058/93716745-3f723600-fb26-11ea-912b-23ee9e8b34ff.png)
![Screenshot from 2020-09-20 09-40-35](https://user-images.githubusercontent.com/18221058/93716746-400acc80-fb26-11ea-9169-e0d913381783.png)
![Screenshot from 2020-09-20 09-40-42](https://user-images.githubusercontent.com/18221058/93716747-400acc80-fb26-11ea-8970-4afb4f4d04b2.png)
![Screenshot from 2020-09-20 09-40-48](https://user-images.githubusercontent.com/18221058/93716748-40a36300-fb26-11ea-8430-6abec36bc7b1.png)
![Screenshot from 2020-09-20 09-40-54](https://user-images.githubusercontent.com/18221058/93716749-40a36300-fb26-11ea-9319-e47f0c848280.png)
![Screenshot from 2020-09-20 09-41-09](https://user-images.githubusercontent.com/18221058/93716750-413bf980-fb26-11ea-9d51-78d8003acc93.png)
![Screenshot from 2020-09-20 09-41-34](https://user-images.githubusercontent.com/18221058/93716751-413bf980-fb26-11ea-9c90-3c422eb1c343.png)
![Screenshot from 2020-09-20 09-41-43](https://user-images.githubusercontent.com/18221058/93716752-413bf980-fb26-11ea-85cf-bc4759f69edc.png)
![Screenshot from 2020-09-20 09-41-59](https://user-images.githubusercontent.com/18221058/93716753-41d49000-fb26-11ea-8015-bd9bcc8a86a7.png)
![Screenshot from 2020-09-20 09-42-08](https://user-images.githubusercontent.com/18221058/93716754-41d49000-fb26-11ea-9397-44d469aaaff0.png)
![Screenshot from 2020-09-20 09-42-23](https://user-images.githubusercontent.com/18221058/93716756-426d2680-fb26-11ea-8377-1f4ee094a5ba.png)
![Screenshot from 2020-09-20 09-42-30](https://user-images.githubusercontent.com/18221058/93716757-426d2680-fb26-11ea-80f3-350eb0a5546f.png)
![Screenshot from 2020-09-20 09-42-35](https://user-images.githubusercontent.com/18221058/93716758-426d2680-fb26-11ea-8bcb-ed7e109ff32d.png)
![Screenshot from 2020-09-20 09-42-45](https://user-images.githubusercontent.com/18221058/93716759-4305bd00-fb26-11ea-9483-7fdcd0c47852.png)
![Screenshot from 2020-09-20 09-42-53](https://user-images.githubusercontent.com/18221058/93716761-4305bd00-fb26-11ea-894c-60459b11a765.png)
![Screenshot from 2020-09-20 09-42-59](https://user-images.githubusercontent.com/18221058/93716762-439e5380-fb26-11ea-8b66-1a16bfb8bb35.png)

**Comment by KianBadie** [comment]
Action items since 9/20 meeting:
- [ ] Continue to fix visual bugs and move styling towards figma
- [x] Make "coming soon" guide cards have black titles, so that it is clear they are not clickable
- [x] Add dynamic padding to with for text within resource/guide cards
- [x] Increase size of svg's so that they scale better on desktop
- [x] Fix comingsoon text so that it displays properly (responsive)
- [x] Make sure font sizes of recourse and guide pages are same

An action item that I personally think should be checked
- [ ] Verify that resource/guide cards do display dynamically (as screen size changes, more or less cards will appear in a given row)

**Comment by KianBadie** [comment]
From new pr #750 :

The reason why this is in a new pr is because I accidentally shared my changes with Ruben on the wrong branch, resulting in the changes being unable to merge cleanly into the toolkit branch that the old pr #728. My apologies. I added Ruben as a co-author, so credit will still be given to him for this page.

Visually, I think the desktop halfscreen and Pixel 2XL landscape can be better. The reason why it is like that now is that it is still trying to left justify things. The styling rules that center the cards for mobile don't kick in until smaller screen sizes. I really want to move things forward in terms of getting this page out and closing the issue, and I would like to improve this change as time goes on.

# Desktop
![Desktop](https://user-images.githubusercontent.com/18221058/94368332-671e4c80-0098-11eb-9183-d46558827292.png)
# Desktop At Half Screen
![half-screen](https://user-images.githubusercontent.com/18221058/94368337-6ab1d380-0098-11eb-9d1c-72d2b7f64114.png)
# iPhone 6
![iPhone6](https://user-images.githubusercontent.com/18221058/94368348-730a0e80-0098-11eb-8bce-de330ee6dec1.png)
# iPhone 6 Landscape
![iPhone6_landscape](https://user-images.githubusercontent.com/18221058/94368368-83ba8480-0098-11eb-9b1b-fc2ae77c6074.png)
# Pixel 2XL
![pixel2XL](https://user-images.githubusercontent.com/18221058/94368374-887f3880-0098-11eb-8bb6-0818dd65ab07.png)
# Pixel 2XL Landscape
![pixel2XL_landscape](https://user-images.githubusercontent.com/18221058/94368380-8ddc8300-0098-11eb-8d02-da80615b0f92.png)
