### ISSUE TITLE
img tag refactor in CONTRIBUTING.md Section 3.1.b v

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5621]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md`
- [x] Replace
```
<img src="https://user-images.githubusercontent.com/81049661/161181526-23ae511c-e991-4cc6-a0a4-d8db19dd69ca.png"/>
```
with
```
<img src="https://user-images.githubusercontent.com/81049661/161181526-23ae511c-e991-4cc6-a0a4-d8db19dd69ca.png">
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), and #5040

**Comment by naveenmallemala5** [comment]
i. Availability: Wednesday (10/04/2023)-Tuesday (10/10/2023). Please contact me anytime on Slack if there are questions on this issue. I should respond quickly.
ii. ETA: Tuesday(10/10/2023) - EOD.

**Comment by LRenDO** [comment]
Hi @naveenmallemala5! It looks like there is a pull request for this issue and I don't see an question here.  It looks like maybe you moved it in the column because it is in review.  Issues that have pull requests associated with them don't need to be moved to this column unless you have a question. There are sometimes issues that don't have pull requests associated with them and those will need to be moved to this column. This is a little unclear in the workflow.  Until the pull request is merged, this issue stays in the `In progress (actively working)` column and should automatically close once the pull request is merged.  If I have assumed incorrectly and you had a question, please feel free to move it back to the `Questions / In Review` column and add a question in the comments here. If you have any questions, feel free to ping me! Thanks for working on the issue!
