### ISSUE TITLE
add "ignoreWords" array to cspell.json

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5676]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to update the Code Spell Checker configuration file with the "ignoreWords" array which will contain individuals' names or other false positive terms that should be ignored by the spell checker. 

### Action Items
- [x] You must use VS Code as your local text editor to install the VS Code extension for spell checking your codebase,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] Do not change any configuration settings or make any spell corrections
- [x] Open the file `cspell.json`
- [x] After the "words" array, add the array
```
   "ignoreWords": [
      "Harish"
   ]
```
- [x] Save `cspell.json` and then test the change by opening `_guide-pages/survey-reporting-dashboard-guide.html` and confirming that the name 'Harish' is not marked as an unknown word.  
- [x] No docker testing is required.  Create a Pull Request in the usual manner, with changes only to `cspell.json`.   

### Resources
[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by doppedheart** [comment]
please assign me this issue please

**Comment by ChrisKildunne** [comment]
i. Availability: Weekdays
ii. ETA: End of day

**Comment by kwangric** [comment]
Hey @ChrisKildunne! Since you already have a previous issue that hasn't been completed yet (#5716), we will have to unassign you from this issue. You can pick up a new issue once your previous one has been merged.

Also, it looks like you have already worked on two "Good First Issues" and one "Small Issue". We encourage developers to pick up a Medium complexity issue as the next step. Thanks!

**Comment by ChrisKildunne** [comment]
Hi Richard,
I was told to work my way up on both front end and back end issues. In
other words, work on a good first issue for backend and then also work on a
good first issue for front end. Since my pull request was merged for issue
#5716 I figured I could get started on a new issue, my apologies.
Thanks!

**Comment by kwangric** [comment]
@ChrisKildunne gotcha. Didn't realize you were doing both.

The pull request for #5716 is still active. There is one approval so far and I plan on reviewing and merging it later today. Once that happens, feel free to assign yourself to this issue again!

**Comment by elliot-d-kim** [comment]
Availability: Mon-Thu outside of 2-7pm, Fri before 2pm, Sat all day
ETA: EOD today (2/2/24)
