### ISSUE TITLE
Add info to the wiki for when someone accidentally creates an issue from a checkbox

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5678]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need a wiki page to provide instructions to a developer who has accidentally created an issue from a checkbox (task list) item.  

### Action Items
- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)
- [x] In a comment in this issue, create a draft wiki page "How to close an accidentally created issue"
- [x] Instruct the developer to enter a comment in the new issue stating that the issue was created accidentally, then to select "not planned" from the drop down next to "Close issue", then click Close issue.  
- [x] Move this issue to Questions/In Review and add the label "ready for dev lead"
- [x] After the draft is approved, record the link to the draft wiki as described in [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) so that it will be included in the new wiki.  

### Resources/Instructions
[How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)
- This issue was created as a result of #4167

**Comment by heejung-hong** [comment]
## How to close an accidentally created issue
### If an issue is created accidentally by clicking on the "Convert to issue" circle at the end of an Action Item, 

<details>
<summary>Image of "Convert to issue"</summary>

![ConvertToIssue](https://github.com/hackforla/website/assets/133067265/7233b01c-af3d-4d03-bb3b-2488dae7d13d)

</details>
<details>
<summary>Image of "Issue created accidentally"</summary>

![IssueCreatedAccidentally](https://github.com/hackforla/website/assets/133067265/ba2185ff-2eab-49cb-953f-65364bdfae3b)

</details>

### Please close the issue with the following:

1. In the "Add a comment" section of the issue,
   - write a comment in the issue stating that the issue was created accidentally.
2. Click on the drop down arrow next to the "Close with Comment" button,
   - select "Close as not planned,"
   - click on "Close with comment" to close the issue.

<details>
<summary>Image of "Close with Comment" button with "Close as not planned"</summary>

![CloseAsNotPlanned](https://github.com/hackforla/website/assets/133067265/41fa3892-e1b4-44af-aeae-32c9340addcf)

</details>
<details>
<summary>Image of "Close with Comment" button after selecting "Close as not planned" option</summary>

![CloseWithComment](https://github.com/hackforla/website/assets/133067265/b35b0ab4-ed5d-452f-a686-063868037c78)

</details>

### If you are at the submit an issue section, you can click on the back arrow to exit.

<details>
<summary>Image of "back arrow"</summary>

![BackArrow](https://github.com/hackforla/website/assets/133067265/e93e8530-ef44-46f3-8e5a-f7b64c8760e2)

</details>

**Comment by roslynwythe** [comment]
Hi @heejung-hong this looks very good, but I'm a bit unclear about the last section "If you are at the submit an issue section..".   Please describe that situation to me.  Thanks

**Comment by heejung-hong** [comment]
Hi @roslynwythe, 
I tried to recreate the back arrow button when I clicked on "Convert to issue" circle.  Clicking on the circle just created an issue.  At this time, I can't recall what I did to open a completely black issue.
If it is okay with you, I think it is okay to delete the last section "If you are at the submit an issue section..".
Thank you

**Comment by ExperimentsInHonesty** [comment]
@heejung-hong 

In your instructions, you have put

> 1. In the "Add a comment" section of the issue,
>     - write a comment in the issue stating that the issue was created accidentally.

Change the  text to say
1. In the "Add a comment" section of the issue,
 - add the following comment to the issue
   ```
   This issue was created accidentially by clicking on a checkbox in another issue.  It can be closed.
   ```

I agree that you can take of this part

> "If you are at the submit an issue section..".

**Comment by heejung-hong** [comment]
## How to close an accidentally created issue
### If an issue is created accidentally by clicking on the "Convert to issue" circle at the end of an Action Item, 

<details>
<summary>Image of "Convert to issue"</summary>

![ConvertToIssue](https://github.com/hackforla/website/assets/133067265/7233b01c-af3d-4d03-bb3b-2488dae7d13d)

</details>
<details>
<summary>Image of "Issue created accidentally"</summary>

![IssueCreatedAccidentally](https://github.com/hackforla/website/assets/133067265/ba2185ff-2eab-49cb-953f-65364bdfae3b)

</details>

### Please close the issue with the following:
1. Add the label: `Ignore: Accidentally clicked circle next to a box`
2. In the "Add a comment" section of the issue,
    - add the following comment to the issue.
   ```
   This issue was created accidentially by clicking on a checkbox in another issue.  It can be closed.
   ```
3. Click on the drop down arrow next to the "Close with Comment" button,
   - select "Close as not planned."
   - click on "Close with comment" to close the issue.

<details>
<summary>Image of "Close with Comment" button with "Close as not planned"</summary>

![CloseAsNotPlanned](https://github.com/hackforla/website/assets/133067265/41fa3892-e1b4-44af-aeae-32c9340addcf)

</details>
<details>
<summary>Image of "Close with Comment" button after selecting "Close as not planned" option</summary>

![CloseWithComment](https://github.com/hackforla/website/assets/133067265/b35b0ab4-ed5d-452f-a686-063868037c78)

</details>

**Comment by heejung-hong** [comment]
Hello @ExperimentsInHonesty,
I have made the requested changes in a new comment.
Thank you

**Comment by LRenDO** [comment]
Hi @heejung-hong! Great work on the wiki page draft and update! You also did a great job with moving the issue to the right column and adding the correct label. You can go ahead and add the link to the table on the [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) page. Once you've done that you can ping me here and re-add the  `read for dev lead` label and I will close it out! Thanks!

**Comment by roslynwythe** [comment]
Thank you @heejung-hong

**Comment by heejung-hong** [comment]
Hi @LRenDO,
I have added the link to the table on How to [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) and ready for your review.
Thank you

**Comment by LRenDO** [comment]
@heejung-hong Looks great! Thank you!
