### ISSUE TITLE
Change Clickable Area for Filter Section from Arrow to Filter Section Heading

### ISSUE THREAD

**Issue by Adastros** [hackforla/website#5770]
### Overview

We need to change the clickable area for a filter section from the arrow to the filter section heading. 

### Details
The arrows used on the filters are rotated HTML symbols. As result, the clickable area of the symbols are angled and changes position each time it is clicked on. To keep the clickable area consistent without the use of images/svgs, it will be better to make the entire filter section heading clickable. 

The user should be able to expand and collapse a filter section when clicking anywhere along the section heading. 

<details>
<summary>Current implementation - highlighted clickable area for arrows</summary>

![image](https://github.com/hackforla/website/assets/48114590/29cbf5ce-83df-44f4-9a9b-c5555ac93234)

</details>

<details>
<summary>Desired Functionality - Events Page when viewed on Mobile</summary>

![2023-10-30 23-08-16](https://github.com/hackforla/website/assets/48114590/77bea8f8-3b03-49ab-bbbd-65819e133c0f)

</details>

### Action Items

- [ ] Update the function(s)/ event listener(s) within `current-projects.js` to change the clickable area from the arrow to each list tag with class "filter-item".
- [ ] Update the function(s)/ event listener(s) within `toolkit.js` to change the clickable area from the arrow to each list tag with class "filter-item".
- [ ] Verify that clicking anywhere along a list tag opens and closes its associated filter section

### Resources/Instructions

- This issue was created per #5233 
- [Home Page](https://www.hackforla.org/#)
- [Projects Page](https://www.hackforla.org/projects/)
- [Toolkit Page](https://www.hackforla.org/toolkit/?)
- [Events Page - View on mobile/small viewport width (<= 768px) to see desired functionality](https://www.hackforla.org/events/)
- [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- [toolkit.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/toolkit.js)

**Comment by raviteja4117** [comment]
Availability for the Week: Tuesday, Thursday
My estimated ETA for completing this issue: Hopefully by Sunday 12th Nov

**Comment by LRenDO** [comment]
Hi @raviteja4117!

Thanks for taking on this issue! I moved this issue back to the `In Progress (actively working)` column on the project board and removed the `Ready for Dev Lead` label since there is an associated pull request waiting for review and there doesn't appear to be a question about the issue. The `Questions / In Review` column is generally for issues that don't have an associated pull requests or for questions about an issue. Generally, the issue will explicitly say to move it to the `Questions / In Review` column and to add the label `Ready for Dev Lead` in the instructions. If there is an associated PR, the issue stays in `In Progress (actively working)` until the pull request is merged.

If I've misinterpreted the status and you have a question, please feel free to move it back and be sure to post a comment with your question. If any of this needs clarifying, please feel free to ping me! Thanks!
