### ISSUE TITLE
Add "_config.yml" to "ignorePaths" array in cspell.json

### ISSUE THREAD

**Issue by freaky4wrld** [hackforla/website#5850]
### Overview
We need to populate the spell check configuration file with file paths that should be excluded from spell checking, 

### Action Items
- [x] You must use VS Code as your local text editor and use the `Code Spell Checker` Extension for this issue,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] In VSCode, navigate to 'cspell.json`
- [x] Add the path "_config.yml" to the end of the array "ignorePaths"
- [x] Save 'cspell.json` and test the update by confirming that files in the specified path are not spell checked.  

### Merge Team
- [ ] Release the dependency on this item in #5450
- [ ] When the last dependency is released, close #5450 as completed.  

### Resources/Instructions
[Introduction to JSON](https://www.json.org/json-en.html)
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)
This issue is part of #5450

[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe
1) I saw this in the Prioritized Backlog but also saw a `ready for dev lead` label on it, so I moved it back to New Issue Approval.
2) I saw the github-actions bot added and removed some labels on Nov 29, 2023, after you manually changed the labels on Nov 16, 2023. I'm not sure if this was intentional by an automation I am not currently aware of or something else. Here is a screenshot of the activity:

<img width="650" alt="github-action bot changing labels" src="https://github.com/hackforla/website/assets/31293603/ffb06212-062b-45ab-9edb-c5498376b93e">


Please figure out what to do with this issue. Thank you.

**Comment by aqandrew** [comment]
Availability for this week: 1 hour today, 3-4 hours Wednesday and Thursday
My estimated ETA for completing this issue: 15 minutes
