### ISSUE TITLE
Investigate use of Daniel Ridge bot its repo 'check-ghpages-versions' 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5897]
### Overview
We need to understand the purpose and status of the Daniel Ridge bot and its repo  'check-ghpages-versions', to determine if the Website team should take responsibility for maintaining it.

### Details
Daniel Ridge Bot repo  'check-ghpages-versions' is intended to automatically check the dependencies for the Docker image created from [ghpages-docker](https://github.com/hackforla/ghpages-docker), and when necessary, to update the ghphages-docker Dockerfile, build a new image and push it to Docker Hub.  

### Action Items
- [x] Read <a href="https://github.com/hackforla/ops/wiki/%40danielridgebot-Ops-Wiki#danielridgebot" target="_blank">DanielRidge Bot Wiki</a>
- [x] Determine if the workflows are still needed, and if so, check the status and effectiveness of the workflows and whether any maintenance is required.  
- [x] The possibility of a stale Dockerfile has been raised in connection with several issues including #5644 and #5647.  Determine if the Daniel Ridge bot could play a role in solutions to these issues.
- [x] Record findings in a comment in this issue
- [x] Move this issue to "Questions/In Review" and add the label "ready for dev lead"

### Resources/Instructions
- <a href="https://github.com/hackforla/ops/wiki/%40danielridgebot-Ops-Wiki#danielridgebot" target="_blank">DanielRidge Bot Wiki</a>
- <a href="https://github.com/danielridgebot" target="_blank">@danielridgebot</a>
- <a href="https://github.com/danielridgebot/check-ghpages-versions" target="_blank">`check-ghpages-versions`</a>
- <a href="https://github.com/hackforla/ghpages-docker" target="_blank">`ghpages-docker`</a>
- <a href="https://github.com/hackforla/ghpages-docker#readme" target="_blank">`ghpages-docker`'s README</a>
- <a href="https://github.com/hackforla/ghpages-docker/wiki" target="_blank">`ghpages-docker`'s Wiki</a>
- Follow the steps here, [How do you update ghpages-docker](https://github.com/hackforla/ghpages-docker/wiki#how-do-you-update-ghpages-docker), for more details on to resolve issues opened by Daniel.

**Comment by roychan1** [comment]
i. Availability: 9am-5pm
ii. ETA: 11/27 at the earliest

**Comment by roslynwythe** [comment]
Hi @roychan1 I wanted to bring these comments to your attention:  https://github.com/hackforla/website/issues/5644#issuecomment-1818840871 and https://github.com/hackforla/website/issues/5644#issuecomment-1826101141

**Comment by roychan1** [comment]
1. Progress: I have done research on the DanielRidge Bot, ghpages-docker, check-ghpages-versions repositories.
2. Blockers: I have difficulty figuring out a solution, I will communicate with someone on slack channels.
3. Availability: I will work on it this weekend (12/9 - 12/10).
4. ETA: 4 days.

**Comment by roslynwythe** [comment]
Hi @roychan1, please advise, was the "Keep-Alive Workflow" a viable solution?

**Comment by roychan1** [comment]
> Hi @roychan1, please advise, was the "Keep-Alive Workflow" a viable solution?

Hi @roslynwythe , I verified that the [check-ghpages-versions](https://github.com/danielridgebot/check-ghpages-versions) workflow did pause due to inactivity for 60 days, as shown in this screenshot: 
![Screenshot 2023-12-15 233956](https://github.com/hackforla/website/assets/52181651/07e54f9a-3b70-4fef-88fa-ca036c9d4496)

The "Keep-Alive Workflow" should be a viable solution, as it is intended for cron based triggers, like [Check Github Pages Gem Version and Open New Issue on Change](https://github.com/danielridgebot/check-ghpages-versions/blob/main/.github/workflows/check-gh-pages-version.yml) from the check-ghpages-versions repo. 

As specified in the [How To Use](https://github.com/marketplace/actions/keepalive-workflow#how-to-use) section of the Keep-Alive Workflow documentation, its workflow name will just needed to be specified as the last step in [Check Github Pages Gem Version and Open New Issue on Change](https://github.com/danielridgebot/check-ghpages-versions/blob/main/.github/workflows/check-gh-pages-version.yml) workflow from check-ghpages-versions, and read/ write permissions has to be enabled on the check-ghpages-versions repo.

I believe the workflow is still needed because I verified that the version of the GitHub page ruby gem has fallen out of date. [github-pages-gem.txt](https://github.com/danielridgebot/check-ghpages-versions/blob/main/release-versions/github-pages-gem.txt) shows version 227 (newest version detected, not necessarily updated), while [Official GitHub Pages Versions](https://pages.github.com/versions.json) shows version 228. 

The [check-ghpages-versions](https://github.com/danielridgebot/check-ghpages-versions) repo's GitHub actions should have opened an issue in hackforla/ops notifying about version update, and when version in the dockerfile is updated, [ghpages-docker](https://github.com/hackforla/ghpages-docker) repo's GitHub actions would rebuild the image and push it to DockerHub. The Dockerfile was stale most likely because no issues were opened to notify about version updates due to the stopping of the bot, and consequently the Docker image was not rebuilt and pushed to DockerHub. Fixing of the bot should prevent a stale dockerfile moving forward.

I have not tested the "Keep-Alive Workflow" myself so I cannot say that it functions as intended. Should I test it as part of this issue? Is there any more information I should provide or subjects I should look into for this issue? Please let me know if clarifications are needed. Thank you.

**Comment by roychan1** [comment]
1. Progress: I have included findings in this comment: https://github.com/hackforla/website/issues/5897#issuecomment-1858763484 and added "ready for dev lead" label. I am awaiting on a response regarding the issue.
2. Blockers: N/A
3. Availability: day time during the week of 12/31 - 1/6
4. ETA: less than a week, depending on the status of review

**Comment by roslynwythe** [comment]
@roychan1 thank you for the analysis and recommendation.  This issue will be closed as completed and a new issue created for implementing the "Keep-Alive Workflow".  If you are interested in writing the new issue, please message me on Slack.
