### ISSUE TITLE
Template for Issue Using SDLC Process

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#602]
### Overview
The 'ideal' development workflow cycle differs from the operating model for the HFLA site team. We are working to document the process the HFLA site team uses, but before we codify the model, we'd like to test the 'ideal' SDLC in practice first. This issue will be the first test of that process. 

### Action Items

SDLC Test: feature = Citizen Engagement Projects 

Description of the Citizen Engagement Projects: We at Hack for LA are volunteers that believe in building technology and analyzing data to make it easier to participate effectively in your community. Here, you'll find a series of products that we have built or are building to make that happen.

Research/Planning
- [ ] Identify user stories for the specific issue (product)
   - [ ] Review each user story on the personas and user stories board to identify which ones apply to the feature 
   - [ ] Add user story to comment below 
- [ ] Perform Customer Research (product)
- [ ] Revise user stories (product)
- [ ] Evaluate user story data requirements (software development)
- [ ] Prioritize user stories (product)
- [ ] Define feature(s) (product)
- [ ] Define acceptance criteria (product)
- [ ] Refine product backlog (product)

Development
- [ ] Create feature wireframes (UI/UX)
- [ ] Develop feature (software development)
- [ ] QA (UI/UX)
- [ ] Usability standards testing (UI/UX)
- [ ] Launch feature (software development)

Measurement
- [ ] Analytics measurement (product)

### Resources/Instructions
[SDLC Diagram](https://drive.google.com/file/d/1emxhYv9N6KuCVrG-gnqkqHdGnjhm_Qvb/view)
[Citizen Engagement Figma Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625%3A0)

**Comment by alexandrastubbs** [comment]
Test this on project pages. Bring up during PM meeting. 

To do: 
- [ ] Set up user stories board on the product repo
- [ ] Write sample user stories 
- [ ] Put on PM agenda closer to event time

**Comment by alexandrastubbs** [comment]
Need @ExperimentsInHonesty to create user story board on product management repo, or to provide me permissions to create the board.

**Comment by IAgbaje** [comment]
### Personas 

- [ ] Product Managers
- [ ] New volunteers
- [ ] Sponsors/Donors
- [ ] Local Community


### User Stories for a Product manager

- [ ] As a product manager, i want to give a brief introduction about HackforLA.
- [ ] As a product manager, i want to be able to encourage people to join my project.
- [ ] As a product manager, i want to advertise the specific skill sets required in my project.
- [ ] As a product manager, i want to tell people about my project without having to repeat myself.
- [ ] As a product manager, **i want to tell people the tools we use.**
- [ ] As a product manager, i want to tell people about the value my product/project offers 
- [ ] As a product manager, i want to tell people about the value my application serve . 
- [ ] As a product manager, i want to encourage people to make use of my application.
- [ ] As a product manager, i want to solicit for financial supports from sponsors/donors.

### User Stories for a new volunteer
- [ ] As a new volunteer, i want to have an understanding of what HackforLA is about.
- [ ] As a new volunteer, i want to know where my skillset fits into.
- [ ] As a new volunteer, **i want to how much of my time would be required.**
- [ ] As a new volunteer, i want to know what value proposition HackforLA offers.
- [ ] As a new volunteer, i want to know how my responsibility serves the community as a whole. 

### User Stories for a Sponsors/Donors

- [ ] As a Sponsor/Donor, i want to know HackforLA's mission and vision.
- [ ] As a Sponsor/Donor, i want to know HackforLA serves the community.
- [ ] As a Sponsor/Donor, i want to know who i can reach out to for more information.
- [ ] As a Sponsor/Donor, i want to know where i can make my donation.


### User Stories for a local community

- [ ] As a local community, i want to have an understanding of how HackforLA serves my community.
- [ ] As a local community, i want to have an understanding of what values HackforLA serve.
- [ ] ~~As a local community i want to know what these projects/services would cost for.~~

**Comment by ahdithebomb** [comment]
User Stories that definitely apply

### Prospective Member
- [x] As a user, I want to get a quick snapshot of the organization's activity without too much time or effort, so that I can determine right away whether or not I want to get involved.
- [x] As a prospective member, I would like to know how I can get involved in a project for the city.

### Project Leader
- [x] As a project leader, I want to find potential volunteers outside of my existing brigade network.
- [x] As a project leader, I want a sufficient number of interested team members to have a sustainable base of developers/UI/UX, etc. who maintain the project.

### Stakeholders
- [x] As a potential stakeholder, who is a non-profit organization, I want to know that you have worked successfully with organizations like mine, since I have limited resources and cannot afford to invest in projects that will not benefit my organization in the long run.
- [x] As a potential stakeholder, who is a government agency, I want to know if you have worked with my organization before, or that you are approved to work with my organization.
- [x] As a potential stakeholder, I want to see that Hack for LA has a good rate of success.

### Friends of Hack For LA
- [x] As a friend of Hack for LA, I want to connect volunteers with Hack for LA projects.

**Comment by ahdithebomb** [comment]
List of user stories that might be related to the feature 
- https://github.com/hackforla/website/projects/6#card-28481493
- https://github.com/hackforla/website/projects/6#card-29010005

**Comment by ExperimentsInHonesty** [comment]
Will not be worked on here.  Have created a new issue on Product Management repo
