### ISSUE TITLE
Add Tools to the Languages/Technologies filter group on the projects page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6196]
### Overview
We need to add Tools into `Languages/Technologies` filter on the projects page, revising it to `Languages/Technologies/Tools`, in order to provide users with the ability to filter projects based on Tools.  

### Details
The [projects](https://www.hackforla.org/projects) and [projects-check](https://www.hackforla.org/projects-check) pages share the same js file `/assets/js/current-projects.js` ; based on the value of `window.location.pathname`, the code implements different filters between the pages.   Note that in this issue we do not want to alter the projects-check in any way.  

### Action Items
- [x] Open the file `assets/js/current-projects.js` in your IDE
- [x] Update the code to add `Tools` to the `Languages/Technologies` filter
- [x] Rename the filter `Languages/Technologies/Tools`
- [x] Using docker, confirm the operation of the filters on the `/project` page
- [x] Using docker, confirm that the appearance and behavior of the `/projects-check` page is unchanged.  

### Resources/Instructions
- Projects page: [webpage](https://hackforla.org/projects) | [HTML include](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects.html) | [JavaScript](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- Projects Check page: [webpage](https://hackforla.org/projects-check) | [HTML include](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects-check.html) | [JavaScript](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- This issue was created from #6150

**Comment by LRenDO** [comment]
Hi @sornekian!

Thanks for taking on this issue! I moved this issue back to the `In Progress (actively working)` column on the project board and removed the `Ready for Dev Lead` label since there is an associated pull request waiting for review and there doesn't appear to be a question about the issue. The `Questions / In Review` column is generally for issues that don't have an associated pull requests or for questions about an issue. Generally, the issue will explicitly say in the instructions to move it to the `Questions / In Review` column and to add the label `Ready for Dev Lead`. If there is an associated PR, the issue stays in `In Progress (actively working)` until the pull request is merged.  If you do have a question, please feel free to add it and move it back to the `Questions / In Review` column.

Thanks for taking on this issue!

**Comment by partapparam** [comment]
i. Availability: 6-9pm, Sunday, Monday, Thursday
ii. ETA: EOD Thursday

**Comment by partapparam** [comment]
Made good progress but will take longer to complete this issue due to some bugs.
i. Availability: 6-9pm, Sunday, Monday
ii. ETA: EOD Monday
