### ISSUE TITLE
Update message when no results from filter selections, Projects and Projects-Check page

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6299]
### Overview
We need the 0 results search message on the Projects and Project-check pages to deliver a message that makes sense
#### Details
On the Projects and Projects-Check pages, when no results are found after filters have been selected, the message displayed is:
<details><summary>Screenshot</summary>
<p>
<img width="755" alt="Screenshot 2024-02-14 205443" src="https://github.com/hackforla/website/assets/40799239/b270eb0f-9cd6-4f76-86e0-73e40c4e2d81">
</details> 

Each category in the message should be shown in a singular forms and not the plural.

### Action Items
- [x] Explore both [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) and
 [current-projects-check.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js) to understand how the search filter feature works and what triggers the "We couldn't find results for: " message.
- [x] Change "Technologies", "Languages", "Tools", and "Programs" so that "Technology", "Language", "Tool", and "Program" are displayed as appropriate when the filter selection return no results.
- [x] Using Docker, confirm that the [Projects](https://www.hackforla.org/projects/) and [Projects-Check](https://www.hackforla.org/projects-check/) pages display the updated message.
- [x] Note that this issue is only for messages under the search bar, and not for the filter tags shown under "Applied Filters".

### Resources/Instructions
- Related issues for the filter tags
  - #4647 
  - #6298 
- This issue initiated by #6297

**Comment by raviteja4117** [comment]
i. Availability: Monday - Friday 
ii. ETA: EOD 25 Feb

**Comment by raviteja4117** [comment]
Sorry,  got busy with some work will finish it by Friday EOD this week

**Comment by LRenDO** [comment]
Hi @raviteja4117! 

Thanks for taking on this issue! I moved this issue back to the `In Progress (actively working)` column on the project board and removed the `Ready for Dev Lead` label since there is an associated pull request waiting for review and there doesn't appear to be a question about the issue. The `Questions / In Review` column is generally for issues that don't have an associated pull requests or for questions about an issue. Generally, the issue will explicitly say in the instructions to move it to the `Questions / In Review` column and to add the label `Ready for Dev Lead`. If there is an associated PR, the issue stays in `In Progress (actively working)` until the pull request is merged.  If you do have a question, please feel free to add it and move it back to the `Questions / In Review` column.

**Comment by raviteja4117** [comment]
Hi @LRenDO 

Got it, thanks for the heads up! I'll keep that in mind and ensure to follow the correct workflow in the future.
