### ISSUE TITLE
Getting Started Page Accordion and Whitespace

### ISSUE THREAD

**Issue by efrenmarin45** [hackforla/website#651]
### Overview
The bottom of the 'Getting Started' page has a white stripe above the footer that shouldn't be there. The accordion resizes to a bigger width once the user clicks on the chevron when it should remain the same. 
### Action Items
Review previous commits and find out what caused the changes on the 'Getting Started' page.
### Screenshots of Issue
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/51544521/88613001-5e31e000-d041-11ea-9726-3e17cf917708.png">
<img width="1439" alt="2" src="https://user-images.githubusercontent.com/51544521/88613026-6b4ecf00-d041-11ea-8373-25319f51db22.png">

**Comment by efrenmarin45** [comment]
**Progress:** I traced back the changes associated with the 'Getting Started' page and found what was changed. Reverted back to fix the issue.
**Blocks:** No
**Availability:** All week
**ETA:** Done

**Comment by alexandrastubbs** [comment]
@efrenmarin45 the space is still not visible on the Getting Started page. Please share an update on your progress

**Comment by efrenmarin45** [comment]
**Progress:** I went back through the previous commits to see if anything was changed to cause the negative margin but found no changes to the class 'header-container'. Fixed missing space and made sure no other files were using the class.
**Blocks:** No
**ETA:** Done

**Comment by efrenmarin45** [comment]
Before:
<img width="1439" alt="Before" src="https://user-images.githubusercontent.com/51544521/89591296-afd72900-d7fe-11ea-87b5-a843cfd70a9a.png">

After:
<img width="1440" alt="After" src="https://user-images.githubusercontent.com/51544521/89591306-b5347380-d7fe-11ea-9922-9cd119790ba9.png">

**Comment by efrenmarin45** [comment]
**Progress:** Working on implementing changes asked by @KianBadie. Changes include removing the grey portion on the page, squashing commits, and removing any fragments of code. 
**Blocks:** No
**Availability:** Friday night
**ETA:** EOD Saturday

**Comment by efrenmarin45** [comment]
Grey bars removed:
<img width="1438" alt="Screen Shot 2020-08-16 at 5 53 32 AM" src="https://user-images.githubusercontent.com/51544521/90334776-dc204180-df84-11ea-9d5a-0b38c43984a0.png">

**Comment by ExperimentsInHonesty** [comment]
Turns out that there is a little more to do on this.  @kian will writeup instructions.

**Comment by KianBadie** [comment]
@efrenmarin45 I'm sorry for not catching this earlier, the last things to get done are:
- [ ] Fix the gray bar showing up on mobile (the cause of this is the "margin-top" property that is defined in the @media query in the .header-container class).
- [ ] ~~Add padding to the bottom of the header container class so that it can be the same size as before (I think the amount of pixels is 29px that needs to be added to the bottom. It is currently at 40px. The 29px is from how much margin was taken from the container below it).~~ 

I was going to add this action item: Use padding instead of margins in .header-container to lower the container below the nav bar. That way if the nav bar becomes smaller for some reason, there still won't be a grey bar. The situation I described is valuable, but I feel like it is fixing the wrong problem. There is something about the way the nav bar, the .main class, and the containers inside the main class are mixing that makes this margin situation a little weird. So I don't believe it is just a padding issue. I feel like this action doesn't really have a clear thing it's fixing. So I am going to just leave it to the 2 above action items for now. 

Edit: acutally @efrenmarin45, before you do the second action item I want to ask @ExperimentsInHonesty which looks better between the first and second image? The only difference is how much white space there is before the blue content section below.
![Screenshot from 2020-08-24 16-39-11](https://user-images.githubusercontent.com/18221058/91106776-68d39b00-e628-11ea-80f1-27bb359db0cb.png)
![Screenshot from 2020-08-24 16-39-21](https://user-images.githubusercontent.com/18221058/91106777-696c3180-e628-11ea-9831-25e1955b73cb.png)

Edit 2: You can ignore the second action item as @ExperimentsInHonesty chose the option that currently exists. That leaves the only fix to be the mobile fix.

**Comment by ExperimentsInHonesty** [comment]
@KianBadie and @efrenmarin45  it doesn't seem like there is a standard amount across the pages I looked at.  But I think the second one is what I would use now.  Please also mention [this](https://github.com/hackforla/website/issues/651#issuecomment-679416519) to @daniellen00 for her site audit.

**Comment by daniellen00** [comment]
Got it!

**Comment by efrenmarin45** [comment]
**Progress:** Looked at the styling and addressed the issues brought up by @KianBadie. Fixed the margin and padding for the mobile view. Please see attached images for reference.
**Blocks:** No
**Availability:** Due to illness, availability is limited.
**ETA:** Done, submitting for review.

**Comment by efrenmarin45** [comment]
**Before:** 

<img width="383" alt="Old" src="https://user-images.githubusercontent.com/51544521/91630217-618ff280-e984-11ea-8317-a262a1ad5d1d.png">



**After:**

<img width="381" alt="New" src="https://user-images.githubusercontent.com/51544521/91630220-72406880-e984-11ea-9b4d-ca602de78705.png">

**Comment by efrenmarin45** [comment]
**Progress:** Reached out to @KianBadie for further clarification and assistance on git workflow. 
**Blocks:** Needed to have an up to date local repo but this has been fixed on my end. 
**Availability:** Due to illness, availability is limited.
**ETA:** Sunday Evening

**Comment by efrenmarin45** [comment]
Providing screenshots for reference to the grey bar.

**New:** 
<img width="378" alt="Screen Shot 2020-08-30 at 5 43 16 AM" src="https://user-images.githubusercontent.com/51544521/91659241-b9615300-ea83-11ea-8ee1-29b6a21ea3e3.png">

**Comment by efrenmarin45** [comment]
Noticed the chevron was misaligned on the Getting Started page accordion under certain mobile versions. Fixed in this issue as well. Images for reference below.

**Old:**
<img width="378" alt="Old" src="https://user-images.githubusercontent.com/51544521/91659367-ef9ed280-ea83-11ea-8e35-f597f4d9992d.png">


**New:**
<img width="375" alt="New" src="https://user-images.githubusercontent.com/51544521/91659375-f9283a80-ea83-11ea-8439-a799e70a97fd.png">
