### ISSUE TITLE
ER: create shared utility function for inserting event schedule after DOM content has loaded

### ISSUE THREAD

**Issue by aqandrew** [hackforla/website#6544]
### Emergent Requirement - Problem
Following #6543 and #6536, code is duplicated between project-meetings.js:

https://github.com/hackforla/website/blob/bc1d295b748facda2f0a4b8e48a0e7ec48c2f0a7/assets/js/project-meetings.js#L7-L19

and right-col-content.js:

https://github.com/hackforla/website/blob/cda844b97e33775ec1ad15f655743c8913c5f62c/assets/js/right-col-content.js#L8-L19

### Issue you discovered this emergent requirement in
- #5473
- #6479

### Date discovered 
March 28, 2024

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
- @ajb176 
- @gaylem 

### What happens if this is not addressed
If this implementation needs updating in the future, the same updates will need to take place in two different files. This negatively impacts the site's maintainability.

### Resources
Pages to test:
- `/events`
- `/project-meetings`

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions

Factoring this code fragment out into a shared utility function, to be imported by those JS files, will keep the implementation of this code consistent across pages.

Note: This ER should be addressed after both PRs mentioned above are merged. Alternatively, we can close them both and open a new PR that includes a shared utility function and will close the two originating issues.

**Comment by roslynwythe** [comment]
- @aqandrew @gaylem thank you for work on this.  It turns out that we have been working on writing an issue #6023 that will revise the code behind the Events page, so that it retrieves event data from a JSON file, which is the method used to display meetings on the projects pages.  So I have added an item to that issue, to refactor project-meetings.js as well and will see if that approach is approved.  

By the way, just a note about our ER process.  When creating an ER, it is worthwhile to apply the label `ready for dev lead` so that it comes to the attention of a dev lead promptly; otherwise things can get lost in the New Approval Column.  Thanks!

**Comment by roslynwythe** [comment]
Thank you again @aqandrew for taking note of the duplicated code.  We already had an issue in the pipeline, #6023, to address the situation, and so this ER will be closed.
