### ISSUE TITLE
Change footer position from "sticky" to "absolute" on feature-homepage-launch branch

### ISSUE THREAD

**Issue by w1ld-r** [hackforla/website#6637]
### Overview

The footer is sticking above the fold on the `feature-homepage-launch` branch.   This is a problem because it covers a substantial amount of content, especially on mobile devices, where it covers all of the content on smaller devices. If deployed, this will create an undesirable user experience.

### Details

It looks like the `position attribute` is `absolute` on the `gh-pages` branch and `sticky` on the `feature-homepage-launch` branch.

**`gh-pages` branch:**
https://github.com/hackforla/website/blob/86167464b9d5d4677e3161659f0a72d1da33a1ae/_sass/components/_footer.scss#L1-L2

**`feature-homepage-launch` branch:**
https://github.com/hackforla/website/blob/572801dcf5f6afed19fb6d334f086e0690022db5/_sass/components/_footer.scss#L1-L2

![screenshot_2024-02-28_at_4 59 01___pm](https://github.com/hackforla/website/assets/76500899/ae4f7209-f391-4a9c-9838-5dac93c947df)

### Action Items
- [x] Read the instructions for [how to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch). 
- [x] Before you make changes, make sure the issue is still visible locally in your browser. Compare with the screenshot above.
- [x] If the problem persists, change the `position` attribute from `sticky` to `absolute`. If that doesn't work, you can try removing the position attribute all together. If you find a better alternative solution, leave a comment explaining why you took a different approach.
- [x] View your changes locally in multiple browsers (Chrome, Firefox, Safari, etc.) and multiple screen sizes (desktop, mobile and tablet) on several pages to prevent regressions ([instructions](https://github.com/hackforla/website/wiki/How-to-review-Pull-Requests#Step3))

### Resources/Instructions

- This describes the desired behavior, but the solution likely won't work in this case: https://www.freecodecamp.org/news/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c/
- https://github.com/hackforla/website/issues/6397

**Comment by roslynwythe** [comment]
@gaylem looks great, I would just add to test at mobile, tablet and desktop screen sizes.  Also please hide the bottom comment above

**Comment by roslynwythe** [comment]
@gaylem this looks great.  Please add the label `Feature: Feature Branch` and in Resources, reference the ER.

**Comment by moazDev1** [comment]
Availability: Wed (6PM - 10PM)
ETA: EOD 5/1

**Comment by moazDev1** [comment]
Hey @gaylem,

I just made a [PR](https://github.com/hackforla/website/pull/6806) solving this issue. The solution you suggested by replacing/removing the position doesn't fix the issue so I had to go for another solution.

The approach I took was using **[Flexbox](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox)**:
   1. In `_main.scss` I converted the `#app` element (footer's parent element) to a flex container using `display: flex;` `flex-direction: column;`. This establishes a stack (vertical layout) for its child elements and the footer will be pushed to the bottom since it's the last element.
   2. In `_footer.scss` I removed the previously used `position: sticky` and `margin-top` styles on the `.main-footer` element. With the flexbox layout in place, these styles are no longer necessary for positioning the footer.
