### ISSUE TITLE
Update wiki page for GitHub Action: github-data

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6643]
### Overview
We need to review and update the wiki page for the GitHub Action `github-data`.   In particular we need to create two new sections that have recently been added to the GHA wiki page template:  "Labels" and "Test Procedure".  

### Action Items
- [x] Become familiar with [HfLA's GitHub Actions main wiki page](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) and [HfLA GitHub Actions wiki page](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions).
- [x] Become familiar with GHA: github-data[](https://github.com/hackforla/website/wiki/GHA:-github-data).  Follow links to the `yml` and `js` files and understand the logic of the GHA.  
- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki).  Following the process given in [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) when completing the remaining Action Items.  
- [x] As outlined in [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki), copy the (raw) page [GHA: github-data](https://github.com/hackforla/website/wiki/GHA:-github-data) into a comment in this issue, then review/correct the content for accuracy and completeness, and add the new sections:
  - [x]  "Labels" - List those labels on which the GHA depends or affects.  
  - [x]  "Test Procedure" - Detail the process for testing the GHA in case there is a code change or a change in a dependent label, resource or package.  (see the Test Procedure example in this issue comment https://github.com/hackforla/website/issues/4856#issuecomment-1974826346)

### Merge Team/Dev Lead 
- [ ] When this issue is closed, remove the `Dependency` label from #6786 then move it from the Ice Box and insert the link to the draft wiki page from this issue, into the Resources section of #6786

### Resources/Instructions
- This issue was create as a result of #6403
- [HfLA's GitHub Actions main wiki page](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) 
- [HfLA GitHub Actions wiki page - with index to GHAs ](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)
- [add update label weekly wiki page](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly).
- [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)

- Additional notes that may be helpful are here: [Issue 6355 comments](https://github.com/hackforla/website/issues/6355#issuecomment-1958771755)

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe 
- I think this issue needs some more clarity. Since this issue is part of an epic, I have added a note to the Epic here with my questions https://github.com/hackforla/website/issues/6403#issuecomment-2059505858.

**Comment by ExperimentsInHonesty** [comment]
Also, I don't really understand what the value of the inclusion of this is 
- Additional notes that may be helpful are here: https://github.com/hackforla/website/issues/6355#issuecomment-1958771755

I read it, but it was not clear what that was in reference to.  We generally don't want to link to a comment that then requires us to scroll up to prior comments to understand what it's related to, because that can lead someone down a rabbit hole.  If we could summarize that or give context before they view the link, that would work.

**Comment by roslynwythe** [comment]
> @roslynwythe
> 
> * I think this issue needs some more clarity. Since this issue is part of an epic, I have added a note to the Epic here with my questions [Epic: Create GitHub Action Wiki pages #6403 (comment)](https://github.com/hackforla/website/issues/6403#issuecomment-2059505858).

Please see my response https://github.com/hackforla/website/issues/6403#issuecomment-2067931770

**Comment by roslynwythe** [comment]
> Also, I don't really understand what the value of the inclusion of this is
> 
> * Additional notes that may be helpful are here: [Update documentation: fix broken links #6355 (comment)](https://github.com/hackforla/website/issues/6355#issuecomment-1958771755)
> 
> I read it, but it was not clear what that was in reference to. We generally don't want to link to a comment that then requires us to scroll up to prior comments to understand what it's related to, because that can lead someone down a rabbit hole. If we could summarize that or give context before they view the link, that would work.

You are corret, it is not relevant.  I had copied the Resources/Instructions section from a different issue and included that one by mistake.

**Comment by YolandaHaynes** [comment]
Availability: Wed - Thur 8:30-10:30pm, Sun 1-4pm
ETA: EOD 4/28/24

**Comment by YolandaHaynes** [comment]
Udpating my timeframe due to time conflicts last week. 
Roadblocks: trying to understand the GHA and not finding/understanding what 'labels' to add for the new section. Continuing reading and understanding the concepts.
Availability: Tue/Thur 8:30-11:30pm pst
ETA: 05/03/24

**Comment by roslynwythe** [comment]
Hi @YolandaHaynes It appears that there aren't any labels relevant to this GHA, so you can just write "none".

**Comment by YolandaHaynes** [comment]
## Summary

The [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml) GitHub Action retrieves Hack for LA's project repository information using the [get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/github-data/get-project-data.js) script. It then overwrites the [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json) file with the current repository data and commits it to the website repository. The new data will then display in each project's page. This action is triggered daily by a cron job. 

### Scheduled
- Scheduled to run everyday at 11:00am GMT (3am PST) via the [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml) workflow file

### Labels
- None

### Workflow
1. Retrieve old [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json)
2. Retrieve all tagged and untagged repos
3. For each repo:
    1. Retrieve:
      - id
      - name
      - languages
      - url
      - Issue Contributors
      - Issue Comment Contributors
      - Project Contributors
    2. Append data in format below:
```
  {
        id: repo.id,
        name: repo.name,
        languages: Object.keys(repoLanguages.data),
        repoEndpoint: repo.url,
        commitContributors: {
          data: commitContributors
        },
        issueComments: {
          data: issueCommentContributors
        },
        contributorsComplete: {
          data: projectContributors
        },
  }
```

### Supporting Files/Folders
* Supporting Files Folder 1: [github-data directory](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule/github-data)
* Data: [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json)
* Workflow File: [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml)

### Test Procedure

1. In order to start testing, you will need to create the `HACKFORLA_PA_BOT_TOKEN` in your personal repo. Review the GitHub documentation for [creating a personal access token ](https://docs.github.com/en/enterprise-server@3.9/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token). When creating the token, select the following scopes:
    * public_repo (under 'repo')
    * admin:org_hook 
    
2. Then you can add the token to your personal repo using [these instructions](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository). 

3. Update the `schedule-daily-1100.yml` workflow file by adding the `workflow_dispatch` command below. This will allow you to trigger the GHA manually on your working branch so that you can test it.

4. Change the `github.repository` from `hackforla/website` to `your-github-handle/your-repo-name`.

``` 
on:
  schedule:
    - cron:  '0 11 * * *'
  workflow_dispatch:

jobs:
  github_data:
    runs-on: ubuntu-latest
    if: github.repository == 'your-github-handle/your-repo-name' # Usually the repo name is `website` unless you changed it while forking the main Hack for LA repo
```
5. Change your default repo to your working branch using [these instructions](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch).

6. Since this GitHub Action updates data about Hack for LA's many projects/repos, you will need to replicate the Hack for LA organization to test this workflow. 
     a. Create a new organization. [GitHub official docs](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/creating-a-new-organization-from-scratch)
     b. Transfer your repo to the newly created organization. [GitHub Doc on how to transfer](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository)
     c. Create a couple of test project repositories with contributors, code, url, language etc as if it's a real project repo. An easy way to do this may be to fork some of Hack for LA's existing projects. 

7. After you have created a mock scenario, trigger the GHA by pushing to your repo.

8. Make sure to test both happy and unhappy paths and consider possible edge cases. 

9. The expected result is that the workflow will overwrite the existing `github-data.json` file with the new data. You should see the data you created reflected there. Given your personal repo may not possess all of the projects that exist on Hack for LA, keep that in mind as you test. Check to see if the new changes made it to the `github-data.json` file.  

> [!CAUTION]
> Before you submit a PR, do the following:
> 1. Remove the `workflow_dispatch` command
> 2. Change `github.repository` back to `hackforla/website`
> 3. Change your default repo back to `gh-pages`
> 4. Revert any changes you made to the `github-data.json` file for testing on your branch 


*** Still work in progress***

Questions: 

1. Am on the right path with the testing procedure instructions for the GHA?

2. I'm not entirely sure if I am understanding this GHA. I added my summary at the top from what I gathered reading through the resources. So when this GHA gets triggered, it updates the github-data.json file with new data. Does that mean when this json file gets updated, then in the Hack for LA's project section, each Project's page will have the most up-to-date information? Is this the reason behind this GHA?

3. How is the data in `github-data.json` used? Will it automatically display on the projects page?

**Comment by YolandaHaynes** [comment]
Hi @roslynwythe , I'm unsure about the testing procedure for this GHA. Please let me know if I'm on the right path with what I have written above.

**Comment by t-will-gillis** [comment]
Hey @YolandaHaynes Thanks for working on this! I have some comments:
- Regarding the section "Workflow":
   - If this is a description about what the workflow does, it does not retrieve the old data per se. For me, the summary would be that for each project in HfLA, the automation is adding up the contributions to that project for each member 
- Regarding the section "Test Procedure":
  - This is a comment for ALL of the eventual Wiki entries for the workflows: I think that eventually, the first part of "Test Procedure" should be a link to another Wiki that describes in general the steps for [setting up the testing environment](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335), and then each separate workflow might have specifics.  
  - 1: It might be good to add a note saying to the effect that the `GITHUB_TOKEN` is automatic and that you don't need to add it explicitly.
  - 3: I think that we can/should leave `workflow-dispatch:` permanently.
  - 5: I think this should be the first thing done before changing anything... 
  - 6: The person testing changes to this workflow _**does not need**_ to create an organization. When this is run from a branch in one's own repo, the workflow will query data from HfLA and then write that data to the `github-data.json` file on that person's own repo.
  - 7: This will be triggered by going to "Actions", selecting "Schedule Daily 1100" on the left, and then selecting "Run workflow" to the right. (I.e. not by pushing)
  - 8: Not sure what this means; the test run on Item 7 is the test.
  - 9: A successful test will **_most likely_** update the data in `github-data.json` but this is not guaranteed- the action `stefanzweifel/git-auto-commit-action@v5.0.1` checks the existing data file and only updates when and if it detects changes. If you were to run simultaneous tests of "Schedule Daily 1100", there likely would be no changes to the data, so nothing new would be written, but this is ok. The successful test is to check whether the test run is 'all green' and whether the auto-commit step either determined that the data was already up-to-date (thus did not update anything) or the auto-commit updated the data.
  
 Regarding your questions:
  - 1: I would say that the testing procedure is roughly to make whatever changes need to be made, then triggering the workflow.
  - 2: This workflow is adding up the contributions for each team member for each team across HfLA. This data is used on the project pages to update the "All-Time Contributors". (The data might be used for other reasons as well). So on the screenshot below (snippet from `github-data.json`), this is saying that for the "Home Unite Us" project, Erik Guntner has made 447 all-time contributions to the project, Tyler Home has 164, etc. Then on the [Home Unite Us](https://www.hackforla.org/projects/home-unite-us) page, Eric's profile is shown, then Tyler's, then the person with the next highest contributions, etc.
  <details>
 

![Screenshot 2024-05-16 122627](https://github.com/hackforla/website/assets/40799239/de52466a-37c9-4cb3-ae9a-2dbbd1e6c796)
  </details>  
 
   - 3: yes - see above
  
  Thanks for starting this write up and working to understand what is happening! I will try to add more, and let me know if I can help with anything...

**Comment by t-will-gillis** [comment]
PS I would recommend adding the quotes around `'hackforla/website'` instead of just `hackforla/website` -  I am saying this because if the quotes aren't included, the workflow will crash.

**Comment by YolandaHaynes** [comment]
1. Progress: "Received some feedback and will finish up the task"
2. Blockers: None at the moment. 
3. Availability: Sunday 11-1pm, Tues/Thur 9-11pm
4. ETA: If no other roadblock surfaces, EOD Tue

**Comment by YolandaHaynes** [comment]
Hi @t-will-gillis Thank you so much for your feedback. Below I have updated with your input. Please let me know if I misunderstood something or missed anything else. 

For the workflow section you made the comment about, I just took the information from https://github.com/hackforla/website/wiki/GHA:-github-data. I thought that information was already updated and verified since it was last edited in 2023. I slightly updated the workflow section from your input. 


Updated version below:

## Summary

The [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml) GitHub Action retrieves Hack for LA's project repository information using the [get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/github-data/get-project-data.js) script. It then overwrites the [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json) file with the current repository data and commits it to the website repository. The new data will then display in each project's page. This action is triggered daily by a cron job. 

### Scheduled
- Scheduled to run everyday at 11:00am GMT (3am PST) via the [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml) workflow file

### Labels
- None

### Workflow
1. Retrieves each project in HFLA contributions [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json)
2. Retrieve all tagged and untagged repos
3. For each repo:
    1. Retrieve:
      - id
      - name
      - languages
      - url
      - Issue Contributors
      - Issue Comment Contributors
      - Project Contributors
    2. Append data in format below:
```
  {
        id: repo.id,
        name: repo.name,
        languages: Object.keys(repoLanguages.data),
        repoEndpoint: repo.url,
        commitContributors: {
          data: commitContributors
        },
        issueComments: {
          data: issueCommentContributors
        },
        contributorsComplete: {
          data: projectContributors
        },
  }
```

### Supporting Files/Folders
* Supporting Files Folder 1: [github-data directory](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule/github-data)
* Data: [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json)
* Workflow File: [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml)

### Test Procedure

1. Change your default repo to your working branch using [these instructions](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch).

2. To set up your testing environment, please follow the steps here: [Set-Up Environment](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335)

3. In order to start testing, your `GITHUB_TOKEN` is automatically added, and you don't need to add it explicitly. You can read the GitHub official doc under [secretes in workflow]( https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow). You will need to create the `HACKFORLA_PA_BOT_TOKEN` in your personal repo. Review the GitHub documentation for [creating a personal access token ](https://docs.github.com/en/enterprise-server@3.9/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token).  When creating the token, select the following scopes:
    * public_repo (under 'repo')
    * admin:org_hook 
    
4. Then you can add the token to your personal repo using [these instructions](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository). 

5. Update the `schedule-daily-1100.yml` workflow file by adding the `workflow_dispatch` command below. This will allow you to trigger the GHA manually on your working branch so that you can test it.

6. Change the `github.repository` from `'hackforla/website'` to `'your-github-handle/your-repo-name'`. Also remember to update your token from `HACKFORLA_PA_BOT_TOKEN` to your newly created token `${{ secrets.Your_New_Token }}`

``` 
on:
  schedule:
    - cron:  '0 11 * * *'
  workflow_dispatch:

jobs:
  github_data:
    runs-on: ubuntu-latest
    if: github.repository == 'your-github-handle/your-repo-name' # Usually the repo name is `website` unless you changed it while forking the main Hack for LA repo
```
7. To trigger the GHA, go to the "Actions" tab, select "Schedule Daily 1100" on the left, and then selecting "Run workflow" button to the right. 

8. A successful test will most likely update the data in github-data.json, but this is not guaranteed. The action `stefanzweifel/git-auto-commit-action@v5.0.1` checks the existing data file and only updates when and if it detects changes. If you were to run simultaneous tests of "Schedule Daily 1100", there likely would be no changes to the data, so nothing new would be written, but this is ok. The successful test is to check whether the test run is 'all green' and whether the auto-commit step either determined that the data was already up-to-date (thus did not update anything) or the auto-commit updated the data.

> [!CAUTION]
> Before you submit a PR, do the following:
> 1. Change `github.repository` back to `hackforla/website`
> 2. Change the token back to `${{ secrets.HACKFORLA_BOT_PA_TOKEN }}`
> 3. Change your default repo back to `gh-pages`

************
Thank you again @t-will-gillis for your guidance. I wasn't able to test before because I wasn't sure if I was on the right path with how to test this GHA initially.  I am now able to test it on my end and I had a successful test with a green check. Please let me know if some of the instructions are not clear enough, or I put in too much information.

**Comment by t-will-gillis** [comment]
Hi @YolandaHaynes - The instructions before you worked on this were pretty sparse, so this is a great improvement! It is looking very good and I think you are giving the right amount of information.

Here are a couple more suggestions, if you agree. (I did not copy the links to the snippets below). For the Summary, this might be clearer:
> The [schedule-daily-1100.yml]() GitHub Action retrieves Hack for LA's team member contributions from each project’s repository using the [get-project-data.js]() script. It then updates the [github-data.json]() file …

And for the Workflow:
> 1. Retrieves member contribution data from each HFLA project's repo and saves it to [github-data.json]()

Thanks again for working on this!

**Comment by YolandaHaynes** [comment]
# Schedule Daily 1100<br><sub>(aka "Update GitHub Data")</sub><br><sub>Workflow</sub>
## Summary

The [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml) GitHub Action retrieves Hack for LA’s team member contribution from each project’s repository using the project [get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/github-data/get-project-data.js) script. It then updates the [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json) file with the current repository data and commits it to the website repository. The new data will then display in each project's page. This action is triggered daily by a cron job. 

### Scheduled
- Scheduled to run everyday at 11:00am GMT (3am PST) via the [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml) workflow file

### Labels
- None

### Workflow
1. Retrieves member contribution data from each HFLA project’s repo and saves it to [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json)
2. Retrieve all tagged and untagged repos
3. For each repo:
    1. Retrieve:
      - id
      - name
      - languages
      - url
      - Issue Contributors
      - Issue Comment Contributors
      - Project Contributors
    2. Append data in format below:
```
  {
        id: repo.id,
        name: repo.name,
        languages: Object.keys(repoLanguages.data),
        repoEndpoint: repo.url,
        commitContributors: {
          data: commitContributors
        },
        issueComments: {
          data: issueCommentContributors
        },
        contributorsComplete: {
          data: projectContributors
        },
  }
```

### Supporting Files/Folders
* Supporting Files Folder 1: [github-data directory](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule/github-data)
* Data: [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json)
* Workflow File: [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml)

### Test Procedure

1. Change your default repo to your working branch using [these instructions](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch).

2. To set up your testing environment, please follow the steps here: [Set-Up Environment](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335)

3. In order to start testing, your `GITHUB_TOKEN` is automatically added, and you don't need to add it explicitly. You can read the GitHub official doc under [secretes in workflow]( https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow). You will need to create the `HACKFORLA_PA_BOT_TOKEN` in your personal repo. Review the GitHub documentation for [creating a personal access token ](https://docs.github.com/en/enterprise-server@3.9/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token).  When creating the token, select the following scopes:
    * public_repo (under 'repo')
    * admin:org_hook 
    
4. Then you can add the token to your personal repo using [these instructions](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository). 

5. Update the `schedule-daily-1100.yml` workflow file by adding the `workflow_dispatch` command below. This will allow you to trigger the GHA manually on your working branch so that you can test it.

6. Change the `github.repository` from `'hackforla/website'` to `'your-github-handle/your-repo-name'`. Also remember to update your token from `HACKFORLA_PA_BOT_TOKEN` to your newly created token `${{ secrets.Your_New_Token }}`

``` 
on:
  schedule:
    - cron:  '0 11 * * *'
  workflow_dispatch:

jobs:
  github_data:
    runs-on: ubuntu-latest
    if: github.repository == 'your-github-handle/your-repo-name' # Usually the repo name is `website` unless you changed it while forking the main Hack for LA repo
```
7. To trigger the GHA, go to the "Actions" tab, select "Schedule Daily 1100" on the left, and then selecting "Run workflow" button to the right. 

8. A successful test will most likely update the data in github-data.json, but this is not guaranteed. The action `stefanzweifel/git-auto-commit-action@v5.0.1` checks the existing data file and only updates when and if it detects changes. If you were to run simultaneous tests of "Schedule Daily 1100", there likely would be no changes to the data, so nothing new would be written, but this is ok. The successful test is to check whether the test run is 'all green' and whether the auto-commit step either determined that the data was already up-to-date (thus did not update anything) or the auto-commit updated the data.

> [!CAUTION]
> Before you submit a PR, do the following:
> 1. Change `github.repository` back to `hackforla/website`
> 2. Change the token back to `${{ secrets.HACKFORLA_BOT_PA_TOKEN }}`
> 3. Change your default repo back to `gh-pages`

**Comment by YolandaHaynes** [comment]
Attached above comment into the [How to Contribute Wiki Page](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) under the `GHA: github data` section. 


@t-will-gillis I’m a little bit confused as to how to have this peer reviewed. Please let me know what steps I need to do next to start that process. Thank you.

**Comment by t-will-gillis** [comment]
Hey @YolandaHaynes - Looks great and thanks so much for all of your work! (And thanks for putting up with the review.) In retrospect, I think this was much more than a `Complexity: Medium`...

You added the link to the Wiki, and what we've been doing counts as peer review, so I will 'Close as Completed' and you can move on to your next issue.
