### ISSUE TITLE
Communities of Practice Page

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#678]
### Overview
We need a homepage for communities of practice which explains what they are and details how to get involved in order to grow our community.

### Action Items
Requirements gathering
- [x] Paragraph about what CoPs are about
- [ ] Instructions for joining the team meetings (join their slack channel and look for the meeting info (usually pinned or in description))
- [x] For each community of practice
   - [x] Name
   - [x] Paragraph that describes them 
   - [x] Meeting times 
   - [x] Leadership Type
     - [ ] Community-led 
     - [x] Specific leader(s)
         - [ ] List leaders - slack member ID, Github picture 
     - [x] Seeking leadership
   - [x] Slack Channel (where they can find the zoom link for the meetings)

UI/UX 
- [ ] [Mockup of the page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25627)

Development 
- [ ] Submit collection architecture for approval
   - [ ] Create the cards
   - [ ] Build the page

### Resources/Instructions
See _projects collection
[Working Figma of the page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25627)

**Comment by yuikomajima** [comment]
Created desktop version for this. If it looks alright we would need the copy and also all of the 5 groups of practice so we can get imagery for all. https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25943

**Comment by ExperimentsInHonesty** [comment]
@yuikomajima 

I updated the figma page to have the names of the groups.  Here is all the other details

Communities of Practice started at Hack for LA in 2020, post covid.  These communities have been a vital connection point in our fully remote organization, that has enabled us to connect people across projects in ways that are both meaningful for the individuals and have helped the organization build professional infrastructure to support our community, nonprofit and government project partnerships.  These communities have also enabled Hack for LA to provide rapid response to the evolving crises of 2020.

If you would like to join one of the Communities of Practice that has a regular meeting time, join their slack channel and look for the meeting info, usually pinned or in description.  Otherwise see the "How to get started" section below.

Data Science
- time: Thursdays 8:00-9:00 pm PDT (every week)
- slack channel #data-science
- leadership: 
   - Sophia Alice, Co-Lead
   - Ryan Swan, Co-Lead
- description: This group  is a space where data science professionals from different projects can come together to share effective practices, give and get mentorship.  The members also sometimes workshop group projects.

Project/Product Management
- time: Tuesdays 6:00-7:00 pm PDT (every other week)
- slack channel #product-management
- leadership: Community Led
- description: The members from different projects come together to share effective practices, give and get mentorship, set development standards and create guides and templates for new projects.

Programming 
- time: 
- leadership: seeking
- description: This group is needed to create a space where developers from different projects can come together to share effective practices, give and get mentorship, set development standards and create guides for new projects.
- How to get started:  If you have been working on a Hack for LA project for a month or more and are interested in helping to setup this group, join us at the Project/Product Management Community of Practice meeting and we can talk about how we can help you get this off the ground (the project leads will be able to get the word out to their project team).

Ops
- time: Tuesdays 8:00-9:00 pm PDT (every week)
- slack channel: #ops
- leadership: Community Led
- description: This group covers all areas of dev-ops and has been the spot for coordination on infrastructure improvements such as AWS hosting, password vaults, multi-tenant product architecture, etc.

UI/UX
- time: Thursdays (every other week - forming now)
- slack channel: #ui-ux
- leadership: seeking
- description: This group is needed to create a space where both UI and UX professionals from different projects can come together to share effective practices, give and get mentorship, set standards and create guides for new projects.
- How to get started:  If you have been working on a Hack for LA project for a month or more and are interested in helping to setup this group, join us at the Project/Product Management Community of Practice meeting and we can talk about how we can help you get this off the ground (the project leads will be able to get the word out to their project team).

**Comment by alexandrastubbs** [comment]
@yuikomajima any updates on this?

**Comment by yuikomajima** [comment]
updated with above changes. I just put in some images from unsplash but please lmk if there are any specific ones we'd like to use.  https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25943

**Comment by yuikomajima** [comment]
Updated photo and button size: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25943

**Comment by ExperimentsInHonesty** [comment]
@yuikomajima looks good.  I'll send this to development

**Comment by pawan92** [comment]
@dmcneary Could you update please:
Progress:
Blockers:
Availability:
ETA:

**Comment by dmcneary** [comment]
1/24 update:
Progress: boilerplate
Blockers: mostly time, should be more free going forward
Availability: open
ETA: 1/31

**Comment by tarang100** [comment]
@dmcneary please share the update

**Comment by dmcneary** [comment]
2/1 update:
Progress: HTML marked up, still working on CSS
Blockers: schoolwork, and puppies
Availability: mornings
ETA: hopefully 2/7, if not 2/9

**Comment by dmcneary** [comment]
2/6 update:
Progress: still working on CSS
Blockers: entering winter term finals, plus job training (yay!)
Availability: pretty blocked up this week, will try to make some progress mon 2/8 - wed 2/10
ETA: hopefully 2/21

**Comment by drubgrubby** [comment]
@dmcneary - You mentioned that you wouldn't be at the meeting.  Can you please give us an issue update?  Thanks.

**Comment by dmcneary** [comment]
2/16 update:
Progress: still working on CSS, "Slack invite notice" banner and leader label-cards pending
Blockers: school
Availability: mid-day and evenings
ETA: hopefully 2/21

Progress screenshots:
![image](https://user-images.githubusercontent.com/43227293/108150253-3cee1b00-7089-11eb-9edb-fc980d62eb76.png)
![image](https://user-images.githubusercontent.com/43227293/108150276-51321800-7089-11eb-8afb-e6882d81bd84.png)

**Comment by dmcneary** [comment]
2/20 update:
Progress: still working on  desktop CSS, "Slack invite notice" banner and leader label-cards pending design
Blockers: school
Availability: mid-day and evenings
ETA: hopefully 2/23

**Comment by pawan92** [comment]
@dmcneary Could you please add the labels we talked about?
Please refer to https://github.com/hackforla/website/wiki/Instructions-for-adding-Status-Labels-to-issues for understanding on how to add the status labels

**Comment by dmcneary** [comment]
As per today's meeting, @ruqpyL2 will be taking charge on this completing issue going forward and I will be available for questions.

**Comment by csseu** [comment]
**Status update 3/6:** 
_Progress:_ reviewed figma and codebase to try to understand project and how things are set up. Converting the CoP content cards into a collection (_communities/) so we can iterate with Liquid. 
_Blockers:_ work.
_Availability:_ will put in a few nights this week, barring work
_ETA:_ Not sure yet but shooting for two weeks.

**Status update 3/14:**  (happy pi day)
_Progress:_ It's mostly there, except that:
- I need to add the "self-invite" thing to the header (easy enough)
- Figma mentions wanting to move away from the 454 and 494px card heights to allow variable card heights and asks to find a way to do this. It seems that the variations in the card image dimensions make this more difficult. I tested dynamically setting the images heights using JS, but I don't like this because it breaks when you resize the window and applies to mobile when it shouldn't. Probably try another solution using liquid, and if that doesn't work I might just standardize those image dimensions (the way we have on the events page etc.)

_Blockers:_ work.
_Availability:_ will put in a few nights this week, barring work
_ETA:_ probably push an update for testing next weekend, understood if y'all want someone else to jump in though.

**Comment by Lol-Whut** [comment]
Please add an update with:

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#step-8-status-updates

Thanks so much!!

**Comment by csseu** [comment]
3/16:
_Progress:_ The community cards are marked up using Liquid so future updates can be easily done by editing .md files. Content updates were added and I think complete. A little polishing of the css layout is still needed for smooth responsiveness.
Blockers: work.
Availability: will put in a few nights this week
ETA: probably push an update for QA this Saturday

Pictures to be attached.

**Comment by csseu** [comment]
<details>
<summary>desktop</summary>
<br>
<img src="https://user-images.githubusercontent.com/23020878/111413247-21cbf680-869b-11eb-89a6-b321768296b9.png">
</details>
<details>
<summary>mobile</summary>
<br>
<img src="https://user-images.githubusercontent.com/23020878/111413257-27294100-869b-11eb-9d04-9dd5c51579bd.png">
</details>
<details>
<summary>tablet</summary>
<br>
<img src="https://user-images.githubusercontent.com/23020878/111501891-95edb500-8702-11eb-9144-f37a6abf67af.png">
</details>
