### ISSUE TITLE
Standardize Slack channels using ID and archives: CONTRIBUTING.md Section 1.5

### ISSUE THREAD

**Issue by marioantonini** [hackforla/website#6848]
### Overview

We need to fix our reference to the hfla-site Slack channel in Section 1.5 of the CONTRIBUTING.md file to use the channel ID instead of the channel name, so that if the name gets changed, the link will still work. We are also changing the link to use archives instead of messages

### Action Items

- [x] In your IDE open the file `CONTRIBUTING.md`
- [x] In Section 1.5, look for the line that references the slack channel `hfla-site` by name `https://hackforla.slack.com/messages/hfla-site`
  - [x] This needs to be changed ONLY in Section 1.5, do not change other lines with the same references.
  - [x] Change the following:
  **From:**
  ```
  ...<strong><em>Feel free to reach out in the [Hack for LA Slack channel](https://hackforla.slack.com/messages/hfla-site/) if you have trouble installing ...
  ```
  **To:**
  ```
  ...<strong><em>Feel free to reach out in the [Hack for LA Slack channel](https://hackforla.slack.com/archives/C4UM52W93/) if you have trouble installing ...
  ```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository. 
  - [x] Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.
  - [x] Verify that the link still opens the `hfla-site` channel in Slack
  - [x] Also store the test URL for use in a later step:
  ```
  https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
  ```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions

- https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
- On the Slack desktop app, you can right click on a channel name, select `View channel details` and find the Channel ID in the bottom of the details pane. The `hfla-site` channel ID is: `C4UM52W93`
- This issue resulted from #6224 and aligns with #4535

**Comment by roslynwythe** [comment]
@marioantonini Since CONTRIBUTING.md cannot be previewed locally in the typical manner (ie using Docker), we typically preview it on GitHub.  Please incorporate these instructions into the testing guidance for this issue:
````
- [ ] With CONTRIBUTING.md still open, make a note of the section in which the replaced content appears, so that you will know where to look in the document to preview the change.
- [ ] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [ ] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```
````
Also this is optional but for issues that update CONTRIBUTING.md I usually provide the Section # that contains the edit, to make it easier to test/review.  If you do that, you can remove the first action item in this comment.  

When working on new issues, we typically assign ourselves and apply the label `Draft`.  When you are finished editing this issue please remove your assignment and the `Draft` label and add the label 'ready for product` label

**Comment by dcotelessa** [comment]
Availability: 10-5pm
W, F
