### ISSUE TITLE
Change the `Feature: Administrative` label to `feature: spelling` in spell check issue template

### ISSUE THREAD

**Issue by urvishp13** [hackforla/website#6857]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to change the `Feature: Administrative` label to the `feature: spelling` label in the spell check issue template. We're doing this, so the issues generated from this template are properly labeled.

### Action Items
- [x] Open the file `.github/ISSUE_TEMPLATE/spell-check-audit.md ` in your code editor.
- [x] In the `labels` property, replace 
   ```
   Feature: Administrative
   ```
   with 
   ```
   feature: spelling
   ```
- [x] Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example: `git push --set-upstream origin test-update-label-1234`
- [x] The response from the push command will include the URL for creating a pull request. Copy/Paste the URL for creating the Pull Request for later.
- [x] Browse to your fork of the website repository and click Settings
  <details><summary>Screenshot of Repository Settings</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/8ecf2e55-2187-4ab9-acf1-2fd7548291a1)

  </details> 
- [x] Change the default branch to the new issue branch
  <details><summary>Screenshot of Default Branch Setting</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/945fe02e-035f-4215-9c25-1d46c209d8c0)

  </details>
- [x] Further down on the settings page under Features, check the Issues checkbox
  <details><summary>Screenshot of Issues Checkbox</summary>

  ![image](https://github.com/hackforla/website/assets/16524851/563fc427-ba07-4e47-9440-2580bbfcad52)

  </details> 
- [x] Browse to the Issues page, then click Labels
  <details><summary>Screenshot - creating labels in the test Repo</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/208e1b07-2478-4ed3-98a1-207de58d25c5)

  </details>
- [x] Create labels corresponding to each label that was listed in the updated issue template. The color of the labels don't have to match those on the `hackforla/website` repository, but the text of the labels must match exactly.
- [x] From the Issues page, click "New Issue" then locate the template updated by your issue, and click "Get Started" to open the issue template.
- [x] Copy the URL of the issue creation page as [URL OF ISSUE TEMPLATE] and save for later use.
- [x] Verify the changes of the issue template.
- [x] Complete the Pull Request process by visiting the URL saved from the push command.
- [x] In the PR copy/paste this text immediately before the section "Screenshots of Proposed Changes Of The Website"
   ```
   ### For Reviewers
   - Use this URL to check the updated issue template: [URL OF ISSUE TEMPLATE]
   ```
- [x] Replace the text in the square brackets (as well as the square brackets) with the URL of the updated issue template.
- [x] Submit your pull request with your changes for review.
- [x] After PR is merged, be sure to follow the steps above to change your default branch back to `gh-pages` and to disable the Issues feature.

### Resources/Instructions
- This issue is made for ER #6615

**Comment by roslynwythe** [comment]
Hi @urvishp13 great job writing this issue.  Since this issue involves labels, there are a few steps I would like to add to the test procedure.  Please refer to https://github.com/hackforla/website/issues/4786#issuecomment-1670584024 and you will find two "bullet points" that describe how the developer should go about creating labels in their repository so that the labels will appear in the test issue. 

Also, thank you for referencing the ER from this issue under  "Additional Resources".  There is a GitHub "hack" that we like to use when referencing issues; that is, if a line of text begins with a hypen ("-"), then any references to issues in that line will be expanded with the issue title.  

Just one other tiny thing - we like to hide any comments that are not going to be useful to the developer picking up the issue.  So please hide the comment above that the bot created.  

When you have made those changes, please move the issue back to "Questions/In Review" and apply "ready for dev lead" label.  Thanks!

**Comment by santiseccovidal** [comment]
I have a question. I want to confirm that I understood correctly.
"Create labels corresponding to each label that was listed in the **updated issue template**".
By "**updated issue template**" is this the file _github/ISSUE_TEMPLATE/spell-check-audit.md_ after my changes?

Then by "The color of the labels don't have to match those on the hackforla/website repository"  are these the labels from_https://github.com/hackforla/website/labels_?

Perhaps my question is obvious since by the issue's heading which says "spell check issue template" I can infer that refers to the file _github/ISSUE_TEMPLATE/spell-check-audit.md_

Finally by "then locate the template updated by your issue, and click "Get Started" to open the issue template." is this the file **spell-check-audit.md** in my fork?

**Comment by santiseccovidal** [comment]
@urvishp13 Hi Urvish perhaps you can help me out with this doubt

**Comment by santiseccovidal** [comment]
Also I noticed that in the file "spell-check-audit.md" there's seems to be "back end/devOps" with two extra spaces being "back   end/devOps", it's at the start of a new line so I don't know which of the two texts I must use in the label creation.

**Comment by santiseccovidal** [comment]
I have a blocker:
After reading again `CONTRIBUTIG.md` I'll be clearer in expressing my difficulties.
I do not clearly understand if the issue is refering to the file `spell-check-audit.md` by the term "template".
I also don't know if I am supposed to add the label "role: back
  end/devOps" as it appears in the file or instead "role: back end/devOps"

Here's what I've done so far
1- Assumed that by template we mean the `spell-check-audit.md`
2- As the issue states "but the text of the labels must match exactly." when creating the labels I just copy/paste the text from the file. Starting from the first character in the word to the last. This made the label creation in Github have a few more spaces but the visual was not affected [image attached- note difference between "back end" and "front end"]

I want to know if that is correct before moving on with the rest.
The branch I'm working on is "**change-label-spellcheck-6857**"

![Screenshot 2024-06-14 123203](https://github.com/hackforla/website/assets/53095957/e7c43c0c-1891-41b4-9ae9-79719c7c78ea)

**Comment by t-will-gillis** [comment]
Hi @santisecco 
- I agree that 'template' refers to `spell-check-audit.md`
- For consistency, the label should have a single space, i.e. `role: back end/devOps`. I see what you are saying about how the existing template has two spaces. As a test, I added many extra spaces on all of the labels and it seems that the correct label gets selected still, but I would remove the extra space anyway. 
Thanks!

I am removing the `Status: Help Wanted` label, but if you still have questions feel free to ask and/or add the label back to this issue.
