### ISSUE TITLE
Audit of key/value pairs in working files vs template 

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#689]
### Dependency
https://github.com/hackforla/website/issues/386#issuecomment-785427876

### Overview
We need to ensure that the 'template of a project.md file' has the most accurate information so that developers building out markdown files can have a strong reference point. 

### Background
When Josh was recently working on the 100 Automations code, he noted that 'Readme' vs 'ReadMe' was causing issues with his script. This is a recurring problem, and is not specific to 'Readme'. We would like to do an audit to ensure that all terms are accurately represented in the 'template of a project.md file'. 

### Action Items

Development 
- [ ] Do an audit of the 100 Automations working file and cross-check with the 'template of a project.md file' for any terms not represented

### Resources/Instructions
100 automations project card /_projects/100automations.md
[Template of Project.md File](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)
[List of all Data Types](https://docs.google.com/spreadsheets/d/1w59UfwbGiEAoBXjAxl4uwQe3xk5j6yFd3NxBMOm510Y/edit#gid=1937603924)

**Comment by alexandrastubbs** [comment]
@rblaz001 hey, do you have a copy that lists all of the different fields that should exist that would be useful to updating the template in the wiki?

https://github.com/hackforla/website/wiki/Template-of-a-project.md-file

**Comment by rblaz001** [comment]
> @rblaz001 hey, do you have a copy that lists all of the different fields that should exist that would be useful to updating the template in the wiki?
> 
> https://github.com/hackforla/website/wiki/Template-of-a-project.md-file

Sure, I'm not home at the moment but I'll try to get you the information later tonight.

**Comment by aahvocado** [comment]
Not completely certain of the task but I just did a quick comparison between the template and the current `100-automations.md` file. The only thing that the template has over the file is the `tools` field.

The `partner` field also has a `#` symbol in front of it, making it a header in the markdown but I don't know if that's an issue. 

Let me know if there are other requirements for this issue, @alexandrastubbs , thanks!

**Comment by rblaz001** [comment]
The All Data Types sheet has all the datatypes currently used for the project cards. @alexandrastubbs 

https://docs.google.com/spreadsheets/d/1i-lFTd5ysOpYHeXFPgyTfg4b4rhy3XfVQ3VmEua5au0/edit#gid=2000472151

Reminder that the entries that are comma delimited are nested entries. For example leadership,links,github corresponds to
```
leadership:
    - links:
          github:
```

Sorry for the delay

**Comment by ExperimentsInHonesty** [comment]
@aahvocado please see Raudel's comment above https://github.com/hackforla/website/issues/689#issuecomment-715903712

**Comment by alexandrastubbs** [comment]
@aahvocado are you still intending to work on this? Can you share an update?

**Comment by aahvocado** [comment]
Wow, thanks for the ping @alexandrastubbs! It's been hard wading through the noise of github emails. 

I made yet another comparison with the sheet that @rblaz001 linked and here are the fields that `100-automations.md` is missing:
- `completed-contact`
- `hide`
- `leadership,links,linkedin`
- `tools`

And as mentioned earlier, there's a `#` symbol in front of the `partner` field.


I think I'm mostly lost on what I should be doing? I can imagine some of these fields being optional so perhaps its not necessary. I don't know what changes I can contribute here but please let me know.

**Comment by ExperimentsInHonesty** [comment]
**Why do files in the project.md template file have hashtags?**
The fields in the project.md files that can be ignored are marked with a hashtag `#` because the files are actually yaml files, so the hashtag is being treated as ignore not a header.  

**Should I leave in the # tags when I am making a file for a new project?**
If the field is available in the project.md template file then a person could use it in the actual project files (e.g., 100automations.md) but if they don't need it they can leave it out.  But no harm is caused by them leaving it in, it's just not prefered.

**What to do next on this issue**
This issue's goal is to compare the all the current data types that are being pulled from the project files with the template to see if the files have something the template does not.  

### Action Items
- [ ] Review the script for the feasibility making changes. https://github.com/hackforla/website/issues/386#issuecomment-785427876
- [ ] If script can be revised then use the spreadsheet that results from that to do the following
- [ ] Review with the team the results
- [ ] If the template is missing key/value pairs, then we need to update the template.  
- [ ] If the project files are missing key/value pairs we need to get that info from the project.  New issues will be made from the results of the script.

Template: https://github.com/hackforla/website/wiki/Template-of-a-project.md-file

Old version of the All Data Types sheet: https://docs.google.com/spreadsheets/d/1i-lFTd5ysOpYHeXFPgyTfg4b4rhy3XfVQ3VmEua5au0/edit#gid=2000472151
