### ISSUE TITLE
Dashboard Page Loading Time Message

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#698]
### Overview
We need to add a message that appears when the dashboard page is loading so that users know the page is in fact working and it will just take a bit longer. 

### Action steps
- [ ] Development
   - [ ] ideate solutions for how we can add a message to the page while loading 
- [ ] Product 
    - [ ] review solution and source any needed visuals 
- [ ] Development
   - [ ] implement solution

### Resources/Instructions
[Dashboard page](hackforla.org/dashboard)

**Comment by cnk** [comment]
Has anyone changed anything on the Google Sheet? Now instead of being slow, it comes back very quickly - with a broken computer icon and a message in the Javascript console: 

`Refused to display 'https://accounts.google.com/ServiceLogin?passive=1209600&osid=1&continue=https://admin.google.com/ServiceNotAllowed&followup=https://admin.google.com/ServiceNotAllowed' in a frame because it set 'X-Frame-Options' to 'deny'.`

hmmmmmm on further investigation, it works when I am anonymous but fails when I am logged into my google account - never mind, the problem was with my Caltech-associated Google account.

**Comment by ExperimentsInHonesty** [comment]
Kian and Raudel provided this info: https://stackoverflow.com/questions/3142837/capture-iframe-load-complete-event

**Comment by ExperimentsInHonesty** [comment]
@sena-ji are you still working on this issue, or should I unassign you?

**Comment by sena-ji** [comment]
> @sena-ji are you still working on this issue, or should I unassign you?

I’m still working on it. I think I’ll be done by Tuesday after I make some adjustments and ask some questions to the dev team.

**Comment by ExperimentsInHonesty** [comment]
as per discussion at last developer meeting @sena-ji will update the code to only put the loading image on the dashboard page.
