### ISSUE TITLE
Add github-handle for Adrian Inchauste in heart.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#7045]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/heart.md` in the IDE
- [x] Replace:
```
- name: Adrian Inchauste
```
with
```
- name: Adrian Inchauste
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/heart.md?plain=1
Project Webpage: https://www.hackforla.org/projects/heart

- This issue is part of #5441.

**Comment by cchrizzle** [comment]
i. Availability: 1 - 1.5hrs / day; I usually try to work on these early in the day and check back if there's any input/responses from others.
ii. ETA: E.O.D. tomorrow 6/24/24.

**Comment by cchrizzle** [comment]
i. **Progress**: Pretty much finished, just having some issues with pushing my commit.

ii. **Blockers**: there were some changes in "gh-pages" when I fetched the upstream before I pushed my commit, so I followed the steps to incorporate the changes from the upstream (git fetch upstream > git checkout -b upstream-gh-pages --track upstream/gh-pages > git pull > git checkout gh-pages > git merge upstream-gh-pages > git push). Now nothing happens when I try to add "heart.md".

I've tried changing branches to both the branch I created for this (add-github-handle-adrian-inchauste-7045) and "gh-pages", but it hasn't worked for either one.

Trying to figure out what happened, will push my changes once I get it figured out!

iii. : **Availability**: an hour to an hour and a half a day.

iv. **ETA**: As soon as I figure out and can fix what happened.
