### ISSUE TITLE
List of Github usernames for all HfLA Website contributors for license compliance

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#705]
### Overview
We need a list of everyone who has contributed code to the Hack for LA website from the start date of this repository up until today. This list will be used to tag individuals to issue number 699. 

Note - the issue is not tagged on purpose, as we do not want to this issue to be tied to that one or for any actions to pop up on that issue.

### Action Items
Development 
- [x] Leverage Github API to identify all users who have contributed code to HfLA site since this repo was started 
- [x] Export list of individuals (with their Github handles) into a 
   - [x] CSV file
example

> @ExperimentsInHonesty 
> @ruben1s 
> @KianBadie 

- [x] text file
example
> @ExperimentsInHonesty @ruben1s @KianBadie 

- [x] upload both files to this issue

**Comment by KianBadie** [comment]
I'm not sure on the other ways this will be implemented, but I think using GitHub's API would be the quickest/easiest way to gather this data. Here are some potentially useful resources about the GitHub API that can be useful for gathering this data. I'll be listing resources about the API/API client ([octokit/rest.js](https://octokit.github.io/rest.js/v18/)) as well as relevant endpoint in the API/API client form:
- [octokit/rest.js](https://octokit.github.io/rest.js/v18/): GitHub's API client for JavaScript. You could use a request library to access the GitHub API, but the API client has convenient methods for dealing with pagination and prevents you from having to deal with a request library.
- Pagination: [What it is/how to traverse](https://developer.github.com/v3/guides/traversing-with-pagination/#basics-of-pagination) and [octokit/rest.js](https://octokit.github.io/rest.js/v18#pagination)'s convenient solution for it.
- Contributors endpoint: Endpoint in [GitHub API](https://developer.github.com/v3/repos/#list-repository-contributors) and endpoint in [octokit/rest.js](https://octokit.github.io/rest.js/v18#repos-list-contributors).
- Commits: I don't know if the commits endpoint would return an amount of users who contributed that is different to the contributors endpoint listed above. I think it should be researched to see if it should be used instead of the contributors endpoint. Here is the endpoint in [GitHub API](https://developer.github.com/v3/repos/commits/#list-commits) and [octokit/rest.js](https://octokit.github.io/rest.js/v18#repos-list-commits)
- User: to get user info (email, username, etc.). Endpoint in [GitHub API](https://developer.github.com/v3/users/#get-a-user) and [octokit/rest.js](https://octokit.github.io/rest.js/v18#users-get-by-username)

These are the endpoints that I think are relevant, but feel free to explore the API a bit more to see if there is a better way to implement w/o using these endpoints. I think looking at the data the endpoints return will be really helpful, as the data often returns links to other endpoints that are useful. (Ex: a commit data object contains a user object that has a link to api call needed to get more info on that user).

**Comment by ruben1s** [comment]
Here are the files:
[contributorsTXT.txt](https://github.com/hackforla/website/files/5357001/contributorsTXT.txt)

**Comment by ruben1s** [comment]
Unfortunately, I cant upload the csv file because github doesnt support it.

**Comment by ExperimentsInHonesty** [comment]
Excellent job
