### ISSUE TITLE
Use VRMS data to update the meeting times on the CoP page

### ISSUE THREAD

**Issue by del9ra** [hackforla/website#7072]
### Overview
We need to automate the update of meeting times on the Communities of Practice page [^1] in a similar way as we do on the Events [^2] and individual project pages using VRMS data. Currently each CoP project is manually updated in the yml files under `_data/internal/communities` [^3].

### Action Items
- [x] Create `communities-of-practice.js` file in `assets/js/` directory
- [x] Remove the meeting-times key from `_data/internal/communities` [^3]
- [x] Pull the meeting times from the VRMS data similar to how the project's pages [^4] using the VRMS data from `_data/external/vrms_data.json` [^5].
- [x] Take a look at `assets/js/project.js`[^6] and see how it utilizes `assets/js/utility/vrms-events.js`. Pay special attention to the following code:  ```{% assign vrmsData = site.data.external.vrms_data %}
const vrmsData = JSON.parse(decodeURIComponent("{{ vrmsData | jsonify | uri_escape }}"))```
- [x] Modify the HTML structure of `communities-of-practice.html` to accommodate the display of meeting times fetched from VRMS data.
- [x] Include `communities-of-practice.js` into the `communities-of-practice.html` file

### Resources/Instructions
[^1]: [Communities of Practice (CoP) page](https://www.hackforla.org/communities-of-practice)
[^2]: [Events page](https://www.hackforla.org/events/)
[^3]: [_data/internal/communities](https://github.com/hackforla/website/tree/gh-pages/_data/internal/communities)
[^4]: https://www.hackforla.org/projects/311-data
[^5]: https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json
[^6]: https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js
- #5328

**Comment by t-will-gillis** [comment]
Hi @del9ra - looks good! 

Here are some things you might consider:  

In most locations, you are using backticks around files and directories (e.g., `communities-of-practice.js`). I think this looks good and it would be good to continue doing that for `_data/internal/communities` in “Overview” and `assets/js/utility/vrms-events.js` and `communities-of-practice.html` in “Actions Items”. For the bullet “Take a look at this code…”, for consistency you could reference `assets/js/project.js[^6]` and then footnote the link. For consistency, in places where a full path link is shown it might be better to show the shortened path- for example you could display Footnote 5 in the same way as Footnote 3.   

In the “Overview”, the way the that the CoP meeting times need to be updated won’t match exactly the “Events” page, and in the “Action Items” you refer to each project’s page using VRMS data. I think it would be clearer to say that we need to automate the times “…in a similar way as we do on the Events and individual project pages using VRMS data.” Also, on the last sentence you could say that “Currently, each CoP project is manually updated…”  

Since you mention the “Events” page in the “Overview”, for one of the “Action Items” bullets it would make sense to reference how the files for the “Events” page extract and use data from `vrms_data.json`. (maybe combined into the second bullet ?)
Finally, in “Resources/Instructions”, there should be a reference back to the `ER` or `Epic` that prompted this one.

Thanks for taking this on!

**Comment by roslynwythe** [comment]
Hi @del9ra - thank you for writing this issue.  Here are a few comments:
- Remove the label "Issue Making: Level 2" since this isssue does not create issues.  
- Remove the label "size: 0.5 pt" and add a label with a larger size.  I usually specifiy 2 pt for large issues
- under Resources/Instructions, on the line that specifies the issue number of the ER, please add a "-" at the beginning of the line; then GitHub will generate a nice link with the issue title
- In the ER, please add a reference to this issue
- @t-will-gillis @ExperimentsInHonesty    Should add an Action Item to remove the `meeting-times` key value pair from the CoP yml files to avoid redundant data?
- @t-will-gillis @ExperimentsInHonesty In terms of formatting, should we specify that the resulting CoP page should maintain the same appearance/formatting?

**Comment by del9ra** [comment]
> Hi @del9ra - thank you for writing this issue. Here are a few comments:
> 
> * Remove the label "Issue Making: Level 2" since this isssue does not create issues.
> * Remove the label "size: 0.5 pt" and add a label with a larger size.  I usually specifiy 2 pt for large issues
> * under Resources/Instructions, on the line that specifies the issue number of the ER, please add a "-" at the beginning of the line; then GitHub will generate a nice link with the issue title
> * In the ER, please add a reference to this issue
> * @t-will-gillis @ExperimentsInHonesty    Should add an Action Item to remove the `meeting-times` key value pair from the CoP yml files to avoid redundant data?
> * @t-will-gillis @ExperimentsInHonesty In terms of formatting, should we specify that the resulting CoP page should maintain the same appearance/formatting?

Thank you for your feedback and thorough review! I’ve implemented the changes you suggested.

**Comment by ExperimentsInHonesty** [comment]
### Current state

https://www.hackforla.org/events/
7:00 pm - 8:00 pm   [Community of Practice: Data Science](https://www.hackforla.org/communities-of-practice) All
7:00 pm - 8:00 pm   [311 Data](https://www.hackforla.org/projects/311-data) All

https://www.hackforla.org/communities-of-practice
Data Science CoP shows
**Meeting Times:** Mondays 7:00-8:00 pm PT

https://www.hackforla.org/projects/311-data
Wed 7:00 pm - 8:00 pm All


### Future state for the CoP page

**Meeting Times:** Mondays 7:00 pm - 8:00 pm PT

**Comment by roslynwythe** [comment]
@delaradaryaei please note Bonnie's comment above detailing the desired appearance for the meeting times on the CoP page.  Also please add an Action Item to remove the `meeting-times` key from the CoP yml files.

**Comment by del9ra** [comment]
> @delaradaryaei please note Bonnie's comment above detailing the desired appearance for the meeting times on the CoP page. Also please add an Action Item to remove the `meeting-times` key from the CoP yml files.

I don't see the difference between the current state and the future state for the CoP page. Could you please specify the difference? The only difference I see is the way we retrieve meeting times: either from YAML files or from VRMS data. 
I added a new Action Item as you said.
