### ISSUE TITLE
The Hack for LA website bot made a mistake!

### ISSUE THREAD

**Issue by sakibian** [hackforla/website#7155]
The Hack for LA website bot made a mistake!
I am responding to Issue #7084 because I have been active.
See my Issue #6747 #6733 #6730 #6731 #6735 #6729 #6736 etc...

## Dev Leads
This member believes that the bot has made a mistake by placing them on the "Inactive Member" list. Please see the referenced issue.

_Originally posted by @sakibian in https://github.com/hackforla/website/issues/7084#issuecomment-2257665899_

**Comment by t-will-gillis** [comment]
I left this note on 7084 also:  

Hi @sakibian The bot sees comments as activity, and your status will be considered 'active' the next time the bot runs (which will be September 1). 

FYI, the reason that the July 1st workflow listed you as inactive is because the bot is only considering comments and commits that developers have made in the last month (for the July 1st workflow, since June 1). As long as you are contributing via comments or commits every month, you will be considered active. If you are inactive for two months, the bot will removed your access automatically; however, if this happens- don't worry. We will be happy to restore your access anytime you wish, just let us know.
