### ISSUE TITLE
Standardize Toolkit Page Header CSS

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#780]
### Overview 
The Toolkit page's header is currently inconsistent with other similar page headers. Adjust CSS (padding and text) to conform with rest of HfLA site.

### Action Items 
- [ ] Follow instructions outlined in [this Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3214%3A34) to standardize Toolkit page header
     - [ ] Adjust text size, font weight, line height as noted
     - [ ] Adjust padding as noted

### Resources/Instructions  

[Toolkit Page Edits Instructions on Figma
](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3214%3A34)[Current Toolkit Page
](https://www.hackforla.org/toolkit)[Current Getting Started Page (for Comparison)](https://www.hackforla.org/getting-started)

**Comment by KianBadie** [comment]
**From PR** #788: 

I'll be specific in what I did to match/respond to the specificity of the directions.
- Made title of page exact same as getting started by removing toolkit page specific class (now it just takes styling rules from h1 tag just like getting started page).
- Made font size, max width, padding, and margin of header paragraph the same exact values as the getting started header paragraph. Only tangible difference between the two pages for this part is the text align (I kept it left for the toolkit as that was the original request). I didn't make a generic class for partly that reason and partly that I did not have the time for it today. And I also didn't know if I should start that process.
- Reduced the space on the top and bottom of the header. Not the same values as recommended in the figma, but it is the same as the getting started page (which I felt like was the goal of the issue). They are both computed to 40px away from the nav bar and the following section (content for the getting started page, category banner for toolkit page).
- "Guides We Made These!" and "External Resources" font size changed to 1.75rem (which equates to the request 28px). I kept this in rem because the toolkit used much more `rem` units than `px` units, and I wanted to keep that theme as much as possible. I kept the `px` units in the header paragraph so it can match the getting started class definition more closely, and the componentization/genericizing of the 2 classes more apparent.
- Made Category banner 1.5rem as requested (which equates to 24px)

On iPhone 6/7/8 landscape (and other width lengths around that), it looks like the title of the page is the same font as the paragraph. However, it is the same behavior on the getting started. I posted a screenshot in it just in case it was considered an important thing to consider.

I did not post many screenshots and finished this issue in a bit of a hurry. So if you wanted to have an in depth look please clone the branch to local and self test. If more screenshots or changes are desired, I can add those tomorrow. I opened this pr just in case this issue was urgent and needed at least something.

# Screenshots
## Desktop
![desktop](https://user-images.githubusercontent.com/18221058/96324416-a6c0c000-0fd6-11eb-9ee2-9a15dcde5ada.png)
## iPhone 6/7/8 Vertical
![iphone678top](https://user-images.githubusercontent.com/18221058/96324429-b8a26300-0fd6-11eb-9c79-1d9c04be195c.png)
![iphone678bottom](https://user-images.githubusercontent.com/18221058/96324433-bb04bd00-0fd6-11eb-9bc8-aa168643a0e4.png)
## iPhone 6/7/8 Landscape
![iphone678landscapetop](https://user-images.githubusercontent.com/18221058/96324464-dc65a900-0fd6-11eb-819b-e2de00745994.png)
![iphone678landscapemiddle](https://user-images.githubusercontent.com/18221058/96324468-e091c680-0fd6-11eb-8a55-5f47a7ad5a09.png)
![iphone678landscapebottom](https://user-images.githubusercontent.com/18221058/96324471-e25b8a00-0fd6-11eb-8bf1-d12c13c98ca5.png)

**Comment by daniellex0** [comment]
Sorry, just saw this! @KianBadie this all sounds great, I think these edits are good to go! And agreed about rem measurments.

There is a chance the header paragraph will look pretty big with the same font size as the Getting Started page one because there is a lot more text, but we can get to that when these styles are fully standardized. If it does look absurdly big though, feel free to make it a little smaller at 24px (1.5rem).

Thank you for doing this so quickly!

**Comment by KianBadie** [comment]
@daniellex0 No worries! And sweet! 

For sure, I'll wait for the meeting today to see if we'll just keep it as is or if I should add that quick fix. I also realized that I didn't make the computed px distance between the header paragraph and the page title/page image 70px as requested. However, again, it is the same as the getting started page. Also, a difference between the getting started page is that on mobile the font of the paragraph does get smaller. So there is at least one difference in behavior.

**Comment by alexandrastubbs** [comment]
@ExperimentsInHonesty let us know if visual review is OK here - https://github.com/hackforla/website/pull/788

**Comment by KianBadie** [comment]
@ExperimentsInHonesty I added some more small updates to try to make this more identical to the getting started page. So things are a bit different from the early screenshots I put. I have not done a thorough comparison on mobile, but I did add a gif below trying to show how the page looks at different widths (I did not show the difference in the "Guides (We Made These!)/External Resources" headers, but it does stay at the requested font size on all widths).

I think the landscape issue that I mentioned in the [comment above](https://github.com/hackforla/website/issues/780#issuecomment-710714932) (see screenshots for iPhone 6/7/8 on ladnscape) still stands. But like I said, I think it is the same for the getting started page. So I'm not sure if matching the behavior and fixing it later is the desired route.

![desktop](https://user-images.githubusercontent.com/18221058/96374176-f19d1d80-1125-11eb-8bd5-212f50bf6e24.png)
![widthdemo](https://user-images.githubusercontent.com/18221058/96374177-f366e100-1125-11eb-854e-c156ff180c0e.gif)

**Comment by ExperimentsInHonesty** [comment]
@KianBadie Yes, please merge the improvements along the way!  The top looks much better.

**Comment by ExperimentsInHonesty** [comment]
@yuikomajima this is perfect!  I am moving this to development.

**Comment by KianBadie** [comment]
@ExperimentsInHonesty will do! I'm going to add one suggestion @drubgrubby mentioned in the review and then I will merge it very soon today!

**Edit**: Merged!
