### ISSUE TITLE
Update ballotnav project

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#804]
### Overview
We need to update the ballotnav project card to reflect the current status of the project

### Action items
- [ ] update looking for to say: See comment below
- [ ] update project card to say: See comment below

### Resources/Instructions
https://github.com/hackforla/website/blob/gh-pages/_projects/ballot-nav.md

**Comment by kcoronel** [comment]
**Project Card Edits:** 
This project came to exist during the 2020 presidential election. In the midst of voters having to decide voting at the polls which carried the possibility of covid-19 infection, while at the same time, the USPS unreliability. Although the presidential election has passed, we believe voters will continue to utilize mail-in-ballots for future elections due to accessibility and safety. While it is possible to drop off your mail-in ballot in person, the rules for doing so are not clearly outlined in one single location. Information is scattered across state and county websites, each of which may individually fail to provide one or more elements of crucial information, such as available ballot drop-off times. The BallotNav project will collect this data through a network of brigade partnerships and update it accordingly leading up to November’s election.

BallotNav’s overall goal is to provide information that helps voters cast their ballots safely and correctly, and avoid accidental disenfranchisement.

**Looking for Edits:** 
Business Analyst, UX Researcher, Marketing, PR & Partnerships, Fundraising, Software Developers, Data Scientists, Translators (Spanish especially), Community Data Monitors: We need an army of people to collect information about drop-off sites for 3,000 counties, and remain on-call to update it when changes occur.

**Comment by ahdithebomb** [comment]
@ExperimentsInHonesty just sent it to Randall.

**Comment by ahdithebomb** [comment]
This needs a rewrite.

**Comment by Arjayellis** [comment]
DRAFT: BallotNav is a tool that aims to help prevent disenfranchisement by providing reliable and up to date information on ballot drop off locations across the US. By partnering with organizations across the country, we hope to become a trusted resource for voters in upcoming elections. Due to distrust in the postal service, misguided information from the media, an inconsistent pool of resources provided by the government, and societal shifts from COVID-19, it is now more important than ever to have useful resources for those hoping to have their voices heard.

**Comment by Arjayellis** [comment]
For open roles, in terms of urgency and that we have actual work for: UX Researcher, Marketing and PR, External partners, Fundraisers

**Comment by ExperimentsInHonesty** [comment]
@Arjayellis are we partnering with orgs?  If so which ones

**Comment by Arjayellis** [comment]
No luck yet.

**Comment by ExperimentsInHonesty** [comment]
@Arjayellis then please leave that part out, because it brings up a question about if the partners are non partisan, so its better to remove it

**Comment by ExperimentsInHonesty** [comment]
BallotNav is a tool that aims to help prevent disenfranchisement by providing reliable and up to date information on ballot drop off locations across the US.   While some states have detailed information about ballot drop off locations, others leave it up to the local jurisdiction to publish that information.  In some states, Counties, Towns, Parishes, etc, do not have websites, so there is no reliable online source for ballot drop off information.  BallotNav was created to provide a reliable online resource about where to drop your ballot, hours, accessibility, etc.   We do this by calling each Jurisdictional office provided by the secretary of state and confirming locations details.

Looking for: UX Researcher, Marketing and PR, External partners, Fundraisers

**Comment by drubgrubby** [comment]
@ExperimentsInHonesty - I don't see any changes to the "looking for".  Are we just making sure that the "Looking for" in the above comment (https://github.com/hackforla/website/issues/804#issuecomment-749112577) are included in the list, or are we supposed to remove everything that's not on that list, so only the things on that list (UX Researcher, Marketing and PR, External partners, Fundraisers) are shown?
