### ISSUE TITLE
content under "Guides (We Made These!)" in Toolkit should be in the middle.

### ISSUE THREAD

**Issue by kmlhsn** [hackforla/website#806]
### Overview 
content under "Guides (We Made These!)" in Toolkit should be in the middle.

### Details 
content under "Guides (We Made These!)" in Toolkit is on the left side. It should be in the middle
### Resources  
(Any documents, links, etc. that would be helpful)
![image](https://user-images.githubusercontent.com/32615215/98469232-7dc3d180-2208-11eb-98a1-a7e22fcbce42.png)

**Comment by alexandrastubbs** [comment]
Thank you for the suggestion! We chose this layout after testing it with the content center and left-justified. People prefer the left-justified because some of the sentences span multiple lines and when we centered the text below, it looked off.

**Comment by t-will-gillis** [comment]
You must be a member of the HFLA website team in order to create pull requests. Please see our page on how to join us as a member at HFLA: https://www.hackforla.org/getting-started. If you have been though onboarding, and feel you have received this message in error, please message us in the #hfla-site team slack channel with the link to this PR.
