### ISSUE TITLE
About us page - Letter from the Executive Director

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/website#860]
### Overview
The about us page needs the text for the Letter From the Executive Directory for the first section of the page. 

### Action Items

- [ ] Write the Letter From the Executive Director

### Resources/Instructions
https://www.hackforla.org/about-us
 [draft](https://docs.google.com/document/d/1jS-ljYnk4B9O00JDyQQd1SD1IRQC5nM4bc5-FXiiS2Y/edit)

https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-executive-letter.html
https://github.com/hackforla/website/blob/gh-pages/pages/about.html

**Comment by mcspach** [comment]
Update from Bonnie at team meeting -
I have put a pause of writing the letter because the About page is not ready to launch and the content of the letter will change based on the publish date.

**Comment by drubgrubby** [comment]
@ExperimentsInHonesty - Dependencies have been resolved. We're a hair's breadth away from launching this, so whenever you want to send over the letter we can display it proudly on the about page.

**Comment by ExperimentsInHonesty** [comment]
Format

executive_letter: |
  # Terram haustis currere praemia

  ## Et iuvenis quem

  Lorem markdownum [formidabilis hospite purasque](http://utiletirynthius.io/)!
  Voluptas certe; non est iamque speculatur **aures** Ammon, fertur, medium,
  quoque ora Vulcanum audes, totumque.

      gigabit_ocr += 3 + fullBotnetIcmp;
      if (3) {
          plain(hertz);
          on_dashboard *= 2;
      }
      if (pum_bar(icq, 5) != -5) {
          exbibyte = partition;
          mediaAix.software += mamp * dawData + memory;
          file(input(archive_node, iosKilohertzModem), menu(5, 26,
                  virtual_cable_box), verticalIpBios.bridge(5, terahertz));
      }

  ## Dedit pactaeque oscula vince erat nec hic

  Inlatum dum serius, ad non **quarum cantusque fratrem** volucrem me priscis
  coloribus, cana ordine iubet pernocte namque. Quoque inploravere sic non tam
  vultumque imagine geminique pendere [vagantem tibi](http://cadensve.io/)!

  ## Teneros labores Aiax Procris demens faciebat faxo

  Priscum terga cum armis in induruit est humum texit cum illud Corythi interea
  recessu. Eget saevit *inreprehensa magis hastam* aut sequeretur volatu per
  querellas!

  1. Adest primum belua
  2. Sua nostro sub fugacia novandi cognoverat donec
  3. Celebrabant mora et ipsa quae adverso
  4. Fore genuere albas mei
  5. Aliquid erat violem

  ## Parentum par

  **Diu te rerum**! Ceres noctis concurrit. Videndum ut umbra plura ego pede
  crura! Sanguine est ripis, ignis solo at inpune semihomines advena corpora ante
  novat?

  1. Habebant Psamathen genetrice exul suo genis curas
  2. Iunonis operi alae cecidere
  3. Sit pallentemque flector corpore
  4. Non vena umbrae nec Hippomene orbem sine
  5. Dic iuvenis Troiae quibus montes iuvencos cani
  6. Cernit tectaque ingens nuribus

  ## Maligno luctuque

  Cum *magna nomen* iunguntur modo bellum annos, ille quidem adspicit nascentia
  puniceo, cum artem quercum arator. Antra iactatis dolores, votique placebant
  iuncturas creatus, afuit. Quam sit morientibus nexu est relinquit egredior
  Italis haererem imagine [pulchrosque iam Atlantiades](http://fertur.com/)
  benefacta. Copia geminis illo, ventis calido.

  Non cucurri feros, relictum freta [inquit
  Prospicientis](http://litusumente.net/atquenulla.aspx) ipse auditurum erres! Ab
  cum misit creberrima, solita [tibi consumptis](http://nisi-procne.net/) canoro?
  Deorum cum debes modo, illo demptos, per inscius fuit, vetustas. Insignia qui
  Capitolia, deae tristis consulit Mutinae es vota diu laqueo palus; tristis, cum.
  Opus haec divus, fortunam [es tellure](http://in.io/laesum-et) plumas.

**Comment by ExperimentsInHonesty** [comment]
what to cover:
The pandemic
The move to zoom
The growth of hack for LA
continue to be radically inclusive
Communities of Practice
Workforce development
Success of our organization is dependent on the success of our volunteers
Ages 8-70
embracing changes and cycles
help us achieve sustainability by clicking on the join page and contributing in the way that fits best for you.

I have wanted to write you for a while.  First it was the pandemic, and then well everything else.  Every time I was about to write, there was something new that needed all hands on deck at Hack for LA.  And while we have accomplished so much, there is still so much left to do.  So I could put off this letter again, but I want to connect with you, to tell you about the last year and a half.  Because the transformation of this civic tech organization is nothing short of astounding and is an important part of the seismic shifts we are seeing in the world around us.

For those of you who don't know our history, Hack for LA started  in 20XX as a Hack-a-Thon, and transitioned into a Hack night, that grew into three hacknights.  And in the first months of 2019 we had started the process to turn the organization into a hybrid in person/remote organization.  What drove us to start going remote before anyone was talking about the pandemic? Blame it on our long Los Angeles commutes, or the desire for our volunteers to work with their project teams more than once a week, or the need to accommodate alternate meeting times.  But when the pandemic came we already had a model and knew what the challenges were.

We moved all teams on active projects to remote only, and encouraged the teams to spread out their meetings to every night of the week, so that senior members could help many projects instead of just one.  This worked to help us expand and now we have 20+ projects and initiatives.  The website can't even keep up with publishing and promoting them.  We now have 150 team meetings a month!

We built Communities of Practice to connect people across projects and

**Comment by njackman-2344** [comment]
Availability: Sunday 3-7pm, Monday 9/18 10am-12pm, Friday 9/22 12pm-5pm PST, Tuesday 9/26 3pm -8pm PST

ETA: Friday 9/29 EOD

**Comment by njackman-2344** [comment]
Please feel free to give me a ton of notes for the letter. I tried to incorporate the above. I can add any current topics as well as the desired formatting. @ExperimentsInHonesty 

Here's the first draft: 

Dear Friends and Supporters,

We hope this message finds you in good health and high spirits. 

We wanted to take a moment to reflect on our journey, our accomplishments, and the path forward for Hack for LA.
I have wanted to write you for a while. First it was the pandemic, and then well everything else. Every time I was about to write, there was something new that needed all hands on deck at Hack for LA. While we have accomplished so much, there is still so much left to do. So I could put off this letter again, but I want to connect with you, to tell you about the last couple years.  The transformation of this civic tech organization is nothing short of astounding.

For those of you who don't know our history, Hack for LA started in 20XX as a Hack-a-Thon, and transitioned into a Hack night, that grew into three hack-nights. (code for America?) And in the first months of 2019 we had started the process to turn the organization into a hybrid in person/remote organization. 

 The Pandemic:
 It was a stressful time but we were ready for the logistical challenges. What drove us to start going remote before anyone was talking about the pandemic? Blame it on our long Los Angeles commutes, or the desire for our volunteers to work with their project teams more than once a week, or the need to accommodate alternate meeting times.  We already had a model and knew what the challenges were. We moved all teams on active projects to remote only, and encouraged the teams to spread out their meetings to every night of the week, so that senior members could help many projects instead of just one.

Growth:
The growth of Hack for LA has been nothing short of remarkable.  Our community of tech enthusiasts, data scientists, and problem solvers has expanded exponentially. Together, we've tackled some of LAs most pressing issues and created solutions that make a real difference. We're committed to nurturing this growth and continuing to empower change-makers from all walks of life.

Radical Inclusivity:
Our commitment to radical inclusivity remains unwavering. We firmly believe that innovation thrives when diverse voices come together. Whether you're 8 or 70, a seasoned expert or a curious beginner, there's a place for you here. Our doors are open to all who share our passion for positive change.

Communities of Practice:
Our communities of practice have become hubs of creativity and collaboration. These groups have allowed us to delve deeper into specific areas of interest, fostering expertise and innovation. This worked to help us expand and now we have 20+ projects and initiatives including 311Data, Food Oasis, and so many more. The website can't even keep up with publishing and promoting them. We now have 150 team meetings a month!

Workforce Development:
One of our core goals is to support workforce development. We believe that investing in the skills and talents of our community members is essential for a brighter future. Together, we can provide opportunities for growth, mentorship, and skill-building that benefit individuals and society as a whole.

Volunteer-Powered Success:
At the heart of our organization are our incredible volunteers. The success of our agency is intricately tied to the dedication and passion of those who generously give their time and expertise. Your contributions have been invaluable, and we remain humbled and grateful.

Embracing Change and Cycles:
Change is constant, and we've learned to embrace it. We recognize that cycles of growth and transformation are part of our journey. With your continued support, we'll adapt to new challenges and seize opportunities for positive impact.

Achieving Sustainability Together:
Our sustainability depends on your support. We invite you to join us on our journey by visiting our "Join" page and contributing in a way that aligns with your strengths and interests. Every contribution, big or small, helps us further our mission.
As we look to the future, we're excited about the possibilities that lie ahead. Together, we can continue to harness the power of technology and innovation to create positive change in our communities and beyond.

Thank you for being a part of our journey and for your unwavering support. 

With gratitude and hope,
Bonnie Wolfe
Executive Director

**Comment by ExperimentsInHonesty** [comment]
@njackman-2344 This draft is awesome.  I look forward to us using this when we are ready for the homepage launch.  I am going to go ahead and close this issue.  And make a new issue for adding it right before the launch.

Thanks again for the excellent draft.
