### ISSUE TITLE
Set up Miro account for HackforLA website team

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#915]
### Overview
We need to setup a Miro Account so that the HackforLa website team so that we can begin to use Miro for relevant projects.

### Action Items
- [x] Follow the instructions in the Create a Miro Account guide
   - [x]  Check to see if there is an email hackforla@gmail.com 
      - [x] If no, create one 
      - [ ] If yes, recover password for it 

### Resources/Instructions
[Create a Miro Account Guide](https://github.com/hackforla/product-managment/issues/33)

**Comment by tarang100** [comment]
**Update**

The Miro account for HfLA website has been created with hflawebsite@gmail.com; the details has been added to the 1Password Vault named "website-hackforla.org"

Till now 6 members from the website have been invited to work on the Miro Board
- Bonnie (bonnie@hackforla.org)
- Tarang (taranggupta100@gmail.com)
- Ahdi (ahdiuthayakumar@gmail.com)
- Pawan (pawanmurthy92@gmail.com)
- Danielle (daniellenedivi@gmail.com)
- Oskar (oskar.adam.zloch@gmail.com)

_**Question**_ - Should I paste the invite link for the Miro board here, so that anyone from the website team can join?

**Comment by ExperimentsInHonesty** [comment]
@tarang100 How about putting the self invite link into a google doc and then putting a link to that on the board.  That way anyone who has access to our google drive can access but anyone who does not, can't.

**Comment by tarang100** [comment]
**Update**

@ExperimentsInHonesty I have added the link for the Miro Board into a Google Doc located in the Google Drive for hflawebsite@gmail.com; I am also sharing the link to the above-mentioned Google doc [here](https://docs.google.com/document/d/1rAYtNXIJrjIhEDI9ncTHukL5jdBoDTUcCg-oYuXWxnY/edit?usp=sharing) for reference.
