### ISSUE TITLE
Another css fix

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#946]
### Overview
Another Css fix needed on the main page:
![Screen Shot 2021-01-17 at 11 02 31 AM](https://user-images.githubusercontent.com/53061723/104853121-a248c380-58b3-11eb-9339-b4c471b7b4b5.png)

### Action Items
- [x] check out the _includes/forms/contact-us.html file
- [x] check out the _sass/components/_contact-us.scss file
- [x] identify the class that you need to add some stylings to
- [x] add a some css to create space between the text and the buttons with screen width is below 580

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

- This is where we add any & all available resources. Do not shy away from adding things. If you think your audience already has it or might not need it, don't let that stop you. Add it anyway! It is very time effective to have all resources available in a single place.

**Comment by dmcneary** [comment]
Would it be suitable to stuff these options into a dropdown menu with one submit button?
```
<label for="self-select">I am a:</label>
<select name="self-select" id="self-select">
  <option>I am a government agency.</option>
  <option>I am a non-profit organization.</option>
  <option>I am none of the above.</option>
</select>
<a href="#"><button class='surveybtn btn btn-primary'>Submit</button></a>
```
or something like that...I could try and tackle this between taking breaks from my current assigned issue if that works.

**Comment by jbubar** [comment]
@dmcneary that is a good idea. Lets ask @daniellex0

**Comment by jbubar** [comment]
@daniellex0 do you think it would be a good idea to have a drop down with options and one button? instead of the three buttons
[david's idea](https://github.com/hackforla/website/issues/946#issuecomment-763338967)

**Comment by daniellex0** [comment]
@jbubar @dmcneary Hmm that might be a bit of a dramatic change for the home page layout right now, but def something we can consider for the near future since work is (slowly but surely) underway on a home page redesign.

Is this a common screen size? Is it phone landscape or something like that? If it's not a common screen size then it might not be an issue. If it is, would it be possible to add an earlier breakpoint so that the buttons will shift to the mobile layout, like this?

<img width="375" alt="Screen Shot 2021-01-20 at 6 18 07 PM" src="https://user-images.githubusercontent.com/67400366/105271400-451b6f00-5b4c-11eb-827d-e2aaf3bea6ae.png">
