### ISSUE TITLE
Make the Toolkit page's category-filtering banner functional

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#959]
### Overview
We need to make the banner for filtering categories on the Toolkit page functional so that the banner will have a purpose, and so that users can filter the guides by the category the are interested in (Development, Design, Project Management, Professional Development). Keep in mind there are a few guides right now, but many more to come.

### Action Items
Research
- [x] Determine how to categorize the guides
- [x] Research how to filter by categories (can use the homepage filter list for reference)

Front-End Development
- [x] Add 'All' category to the far left on banner, which will be the default on page
- [x] Make categories on banner clickable
- [x] Implement filtering function for Toolkit page guides 

### Resources/Instructions
[Toolkit page](https://www.hackforla.org/toolkit)
[Homepage project filters ](https://www.hackforla.org/)

Filter banner:

<img width="1400" alt="Screen Shot 2021-01-24 at 3 59 10 AM" src="https://user-images.githubusercontent.com/67400366/105630012-3efeea00-5dfb-11eb-84ab-3c478a0f7f09.png">

**Comment by mcspach** [comment]
Update
 
Progress: 
-Researched embedded Ruby syntax.
-Looked over the homepage filter for an example.
-Added 'All' category tab
-Made the links clickable, (but they don't filter the results yet)

Blockers: None
(@daniellex0 Needs some css adjustments for med screen sizes after adding the 'All' tab. Am I okay to make minor css changes to banner and links?)

Availability: Later this week.
ETA: Sunday Feb 14

<img width="1251" alt="Screen Shot 2021-02-09 at 10 37 01" src="https://user-images.githubusercontent.com/38964454/107412381-384bc480-6ad5-11eb-8395-02ac6ec6f136.png">

**Comment by daniellex0** [comment]
@mcspach Sure, feel free to make CSS changes! 

I'm also realizing the banner is pretty tiny in mobile size because apparently a mobile version of this page was never actually designed, and so the devs had to figure it out on their own. Do you want me to design a quick mobile version (perhaps two rows), or would you want to try to figure something out to fix how tiny it is in mobile?

**Comment by mcspach** [comment]
@daniellex0 Okay, thanks.

I will take a look at mobile and see what I can work out.

**Comment by mcspach** [comment]
Not available Saturday 2/13.

###PBNE
Still working out the exact code, but think I can solve it in one more sitting.
No blockers, just getting comfortable with liquid.
If not complete, I'll have a better update on Tuesday dev meeting.

**Comment by mcspach** [comment]
Update 
Blockers: 
If I can get some (more) help, that would be sweet.
1. bug- A few bugs w/ image not showing up after filtering.
2. bug- Tabs with more than one word title do not filter properly.
3. I will update css once the filter is 100% functional.

Here's what it looks like now. Should be clear which parts aren't working.

https://user-images.githubusercontent.com/38964454/108151176-f8fc1580-708a-11eb-98c7-ce596ab9bc9e.mov

**Comment by ahdithebomb** [comment]
@mcspach Looks like you remove the help wanted label, what is the current status.

**Comment by ahdithebomb** [comment]
Please update your issue with one of the following labels.

For Instance, in this case the correct label is Needs Update. 

That doesn't mean you need to do an update right now, it means the next thing that will be done is an update. When you do it, you will remove that label and add Update added. 

Blockers: Needs assistance during the meeting, external factors are preventing progress.
Help Wanted: Internal assistance is required to make progress.
Update Added: No blockers and update is ready for review.
Needs Update: No update has been provided, needs to an update in order to be reviewed.
User Acceptance Testing: Ready to be tested after review.

**Comment by mcspach** [comment]
<img width="1392" alt="Screen Shot 2021-02-21 at 9 10 21 AM" src="https://user-images.githubusercontent.com/38964454/108632604-b6d52a00-7424-11eb-8e23-bf2e09636a27.png">
<img width="1395" alt="Screen Shot 2021-02-21 at 9 10 37 AM" src="https://user-images.githubusercontent.com/38964454/108632606-b76dc080-7424-11eb-878a-2dc14c78215e.png">

Progress: Working, needs review, small CSS changes will be made before final commit if these changes are approved.
Blockers: None
ETA: Ready for merge by Tuesday if it looks okay.

**Comment by ExperimentsInHonesty** [comment]
@mcspach please talk to David or Josh about Pull Request readiness and draft state.  They can help you with your next steps.  Also I added a comment to your PR
>Please make sure when you review this page that the text in the body of the cards did not get switched to bold as appears here: #959 (comment). And also that the Titles of the links match the figma.

**Comment by mcspach** [comment]
CSS has been updated to complete issue.
<img width="1317" alt="Screen Shot 2021-02-23 at 6 34 11 PM" src="https://user-images.githubusercontent.com/38964454/108940046-8b5e6500-7607-11eb-85f0-c05fcdaa0f40.png">
<img width="441" alt="Screen Shot 2021-02-23 at 6 35 35 PM" src="https://user-images.githubusercontent.com/38964454/108940052-8e595580-7607-11eb-8463-9890884579aa.png">
<img width="418" alt="Screen Shot 2021-02-23 at 6 35 55 PM" src="https://user-images.githubusercontent.com/38964454/108940055-8f8a8280-7607-11eb-89de-7d0e2057af16.png">

**Comment by mcspach** [comment]
<img width="1440" alt="Screen Shot 2021-03-01 at 3 59 09 PM" src="https://user-images.githubusercontent.com/38964454/109576081-f4caf180-7aa7-11eb-9506-f142d3350a4d.png">
[X] - added hover effect red on links
[X] - removed 'external resources' from the filter method.

**Comment by mcspach** [comment]
Need Help!

The problem is:
All the action items for this have been solved, the request has been reviewed and changed multiple times, but there is still one bug. 

- We need to find out why some images do not render when the filter is applied.
-Some filters return images for one card, while missing the render on another. 

<details>
<summary>Missing Image Example</summary>
<img width="1212" alt="Screen Shot 2021-03-09 at 11 21 24 AM" src="https://user-images.githubusercontent.com/38964454/110525697-c2358000-80c9-11eb-8369-75f82f821ed8.png">
</details>

In order to work off my in-progress branch:
('cd' into your local hackforla/website directory)
```
git remote add mcspach git@github.com:mcspach/website.git
git checkout mcspach -b toolkit-banner-links
```

There are a few more comments here is the pull request: https://github.com/hackforla/website/pull/1078

<details>
<summary>Video-CurrentStatus</summary>

https://user-images.githubusercontent.com/38964454/110534935-7cca8000-80d4-11eb-8573-509b6d5865e2.mov


</details>
