### ISSUE TITLE
Update sitemap page status and Figma

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#963]
### Overview
We need the sitemap to be up to date and a clearer way of seeing what status pages are in on our Figma

### Action Items
- [x] Add status to all pages in figma under drafts
- [x] Add the pages to the current drafts page
- [ ] review page status with Product Team
- [ ] update the site map illustration and add it to the sitemap page

### Resources/Instructions
[Figma sitemap](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1558%3A13110)

**Comment by samantha-yee11** [comment]
![Updated Sitemap](https://user-images.githubusercontent.com/55968286/106372107-3fc6dd00-6321-11eb-9206-b55ec6fb99d0.png)

**Comment by samantha-yee11** [comment]
I've updated the Sitemap and added screen shots of live pages to their drafts. I have a few notes and questions: 

- It looks like the Connect toolbar link should be renamed to "Join Us". Join us page is ready for development.
- I changed all of the guides under the Toolkit tab to the ones consistent with the guides live but not yet linked on the current Toolkit page. Please review to make sure these are correct.
- Credits board in footer marked "Ready for Development" but the link to credits is not designed on footer
- Is the Metrics Dashboard on the "About Us" page live but not linked? Can’t tell since "About Us" is in development.

**Comment by samantha-yee11** [comment]
**Ready to review with Product Team**

**Comment by tarang100** [comment]
- The metrics dashboard is hackforla/dashboard
- Credits link appearing on footer needs to be designed. Status should be changed to "Ready for Ideation"
- PMs will provide a chart with guide status https://github.com/hackforla/website/issues/982
- Connect is changing to Join Us

**Comment by samantha-yee11** [comment]
Changes updated. Waiting on guide statuses.

**Comment by ExperimentsInHonesty** [comment]
This needs to be reconciled with the menu in figma.  All the status should be reflected in the title.
