### ISSUE TITLE
Create project card: Brigade Organizers Playbook (BOP)

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#965]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image
     - [x]  Alt image text
  - [x] 1500 x 700 hero image (please do not put project title on hero image)
     - [x]  Alt image text
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [x]  Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
  - [x]  What you are looking for skills wise
  - [x]  Partner(s)
  - [x]  Location
  - [x]  Status
- [x]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by ahdithebomb** [comment]
![bop](https://user-images.githubusercontent.com/37763229/106353359-d0100e00-629e-11eb-810c-2435cd6a4aa0.png)
alt text: Brigade Organizer's Playbook Extension Project

![bop-hero](https://user-images.githubusercontent.com/37763229/106353468-97bcff80-629f-11eb-81dc-9fd3c3eef57e.png)

Each of the 80+ Code for America Brigades is an experiment which generates valuable learnings and new effective processes and practices. However, Brigades and other civic tech volunteer organizations need not start from scratch. This project aims to improve existing structures and create new ones that make it easier to share replicable processes and practices so that organizers and members can iterate on each others work, improving outcomes for the whole network.


Leadership
Should reflect this list:
   - Name: Bonnie Wolfe 
      - Role: Agile Mentor & CfA National Advisory Council BOP project Co-Lead
      - Slack: [CfA Slack](https://codeforamerica.slack.com/team/UGREE50MT)
      - Github: experimentsinhonesty
   - Name: Thad K.       
      - Role: CfA National Advisory Council BOP project Co-Lead
      - Slack: [CfA Slack](https://codeforamerica.slack.com/team/UAU40G31A)
      - Github: thadk
   - Name: Will Pfeffer      
      - Role: CfA Brigade Network team representative
      - Slack: [CfA Slack](https://codeforamerica.slack.com/team/U014MEJV6KT)
      - Github: willpfeffer
   - Name: Sam H.    
      - Role: Product Manager 
      - Slack: [CfA Slack](https://codeforamerica.slack.com/team/U019C4LERSM)
      - Github: thesamwong
   - Name: Serena Baleja       
     - Role: Product Owner 
     - Slack: [CfA Slack](https://codeforamerica.slack.com/team/U01FUJ7124S)
     - Github: Baleja
   - Name: Marianne Miranda
      - Role: UX Research Team Lead
      - Slack: [CfA Slack](https://codeforamerica.slack.com/team/U01ASEG8HK5)
      - Github: MarianneAnthonette
   - Name: Raquel Nishijima 
      - Role: Communication Designer & UX Researcher 
      - Slack: [CfA Slack](https://codeforamerica.slack.com/team/U01EJ7KMLCV)
      - Github: raquelnish
   - Name: Jon Kropko  
      - Role: Data Scientist 
   - Name: Jon Kropko 
      - Slack: [CfA Slack](https://codeforamerica.slack.com/team/UL9U380TH)
      - Github: jkropko
   - Name: Tan Zhou 
      - Role: Research Analysis Contributors 
     - Slack:  [CfA Slack](https://codeforamerica.slack.com/team/UPMSC27G8)
      - Github:  tan-zhou
   - Name: Helen Lin 
      - Role: Research Analysis Contributors 
     - Slack:  [CfA Slack](https://codeforamerica.slack.com/team/U01B79J9V9B)
      - Github:  osnickersnee
   - Name: Myranda Pierce 
      - Role: Research Analysis Contributors 
      - Slack:  [CfA Slack](https://codeforamerica.slack.com/team/U01E521NT2L)
      - Github:  myrandi   
   - Name: Reem Mehdoui 
      - Role: Research Analysis Contributors 
      - Slack:  [CfA Slack](https://codeforamerica.slack.com/team/U01DF6AE5TL)
      - Github: reemux

change technologies to tools:
tools: Zoom, Calendly, Otter.ai, Google Docs (Doc, Sheet, Slide, Forms), HackforLA.org guides
technologies: Markdown
links:
 - wiki: https://github.com/codeforamerica/brigade-playbook/wiki
 - GitHub: https://github.com/codeforamerica/brigade-playbook
 - Slack Channel: [#organizers-playbook](https://cfa.slack.com/archives/G0196272BBN)
 - Effective Practices: https://docs.google.com/spreadsheets/d/1N0VSDhYyy5WhX_z18Q0RvLlGO29JGGdMxVsD4X3nFYs/edit#gid=1425278717

partners: Code for America (CfA), CfA National Advisory Council, Code for Boston, Code for Charlottesville
location: Remote
status: Active

**Comment by matthewlee626** [comment]
Progress: All info added to brigade-organizers-playbook.md
Blockers: Not sure why, but the card is not rendering in "Projects" on my local copy of the website. Might have something to do with the error below.
Availability: ~3 hrs, but I expect much less time.
ETA: Next Sunday (14 Feb 2021)
![image](https://user-images.githubusercontent.com/19520286/107146483-85753e00-68fd-11eb-9333-43b8a500e9e3.png)

**Comment by drubgrubby** [comment]
(This has been edited from an earlier version.  Bonnie suggested a diffefent fix.)

As you stated in the issue, this page is throwing a YAML exception. 

The problem seems to be the apostrophe in line 6 - alt: 'Brigade Organizer's Playbook Extension Project'. It's trying to process the apostrophe within the string as part of the code and throwing a YAML Exception.

You can solve this by using double quotes outside the string: 
```
The sentence would look like: alt: "Brigade Organizer's Playbook Extension Project"
```

**Comment by matthewlee626** [comment]
Resolved the issue. 

I should note: I notice some overlap between this project and Civic Tech Structure. Is that intentional?
